import MagnitudeConjecture.Combinatorics.PosetSpaceRealization
import Mathlib.LinearAlgebra.Dimension.RankNullity
import Mathlib.LinearAlgebra.Dual.Lemmas

/-!
# Incidence boundary evaluations of a finite poset space

For `t` in a finite poset, the projective boundary line `P_t` is supported
on the principal filter `Set.Ici t`.  Its complementary boundary line `Q_t`
is supported on the complement of the principal ideal `Set.Iic t`.

This file proves the two concrete evaluations used in the frozen manuscript:

* maps `P_t ⟶ X` are the vectors in the distinguished subspace `X_t`;
* maps `X ⟶ Q_t` are the linear functionals on `X / X_t`.

For a one-dimensional total space these evaluations are complementary: the
first Hom space is nonzero exactly when the second Hom space vanishes.
-/

set_option autoImplicit false

noncomputable section

open CategoryTheory

namespace MagnitudeConjecture.PosetSpace

universe u

variable {k T : Type u} [Field k] [PartialOrder T]

/-- The complement of the principal ideal generated by `t`. -/
def coPrincipalSupport (t : T) : Set T :=
  {s | ¬ s ≤ t}

/-- The complement of a principal ideal is an upper set. -/
theorem coPrincipalSupport_isUpperSet (t : T) :
    IsUpperSet (coPrincipalSupport t) := by
  intro s r hsr hs hrt
  exact hs (hsr.trans hrt)

/-- The complementary one-dimensional boundary object `Q_t`. -/
abbrev coPrincipalLine (t : T) : Obj k T :=
  line k T (coPrincipalSupport t) (coPrincipalSupport_isUpperSet t)

/-- Evaluation at `1` sends a map from `P_t` to its value in `X_t`. -/
def principalLineEvaluation (t : T) (X : Obj k T) :
    (line k T (Set.Ici t) (isUpperSet_Ici t) ⟶ X) →ₗ[k]
      X.subspace t where
  toFun f := ⟨f.linear 1, f.map_subspace t 1 (by
    rw [line_subspace_of_mem k T (Set.Ici t) (isUpperSet_Ici t) t]
    · exact Submodule.mem_top
    · exact le_rfl)⟩
  map_add' f g := by
    apply Subtype.ext
    exact LinearMap.add_apply f.linear g.linear 1
  map_smul' c f := by
    apply Subtype.ext
    rfl

/-- A vector of `X_t` defines a map from the principal-filter line. -/
def principalLineMapOfVector (t : T) (X : Obj k T)
    (x : X.subspace t) :
    line k T (Set.Ici t) (isUpperSet_Ici t) ⟶ X where
  linear :=
    { toFun := fun c ↦ c • x.1
      map_add' := fun c d ↦ add_smul c d x.1
      map_smul' := fun c d ↦ by simp [smul_smul] }
  map_subspace := by
    intro s c hc
    by_cases hts : t ≤ s
    · exact (X.subspace s).smul_mem c (X.monotone_subspace hts x.2)
    · have hc0 : c = 0 := by
        rw [line_subspace_of_not_mem k T (Set.Ici t)
          (isUpperSet_Ici t) s hts] at hc
        exact hc
      subst c
      simp

/-- The projective incidence evaluation `Hom(P_t,X) ≃ X_t`. -/
def homFromPrincipalLineEquiv (t : T) (X : Obj k T) :
    (line k T (Set.Ici t) (isUpperSet_Ici t) ⟶ X) ≃ₗ[k]
      X.subspace t :=
  LinearEquiv.ofBijective (principalLineEvaluation t X) ⟨by
    intro f g hfg
    apply Hom.ext
    apply LinearMap.ext
    intro c
    have hvalue : f.linear 1 = g.linear 1 := congrArg Subtype.val hfg
    calc
      f.linear c = f.linear (c • (1 : k)) := by simp
      _ = c • f.linear 1 := f.linear.map_smul c 1
      _ = c • g.linear 1 := by rw [hvalue]
      _ = g.linear (c • (1 : k)) := (g.linear.map_smul c 1).symm
      _ = g.linear c := by simp,
    by
      intro x
      refine ⟨principalLineMapOfVector t X x, ?_⟩
      apply Subtype.ext
      simp [principalLineEvaluation, principalLineMapOfVector]⟩

/-- Every map `X ⟶ Q_t` vanishes on the distinguished subspace `X_t`. -/
theorem homToCoPrincipalLine_vanishes (t : T) (X : Obj k T)
    (f : X ⟶ coPrincipalLine (k := k) t) :
    X.subspace t ≤ LinearMap.ker f.linear := by
  intro x hx
  rw [LinearMap.mem_ker]
  have htarget := f.map_subspace t x hx
  rw [line_subspace_of_not_mem k T (coPrincipalSupport t)
    (coPrincipalSupport_isUpperSet t) t (by
      simp [coPrincipalSupport])] at htarget
  exact htarget

/-- A map to `Q_t` descends to a functional on `X / X_t`. -/
def coPrincipalQuotientEvaluation (t : T) (X : Obj k T) :
    (X ⟶ coPrincipalLine (k := k) t) →ₗ[k]
      Module.Dual k (X ⧸ X.subspace t) where
  toFun f := (X.subspace t).liftQ f.linear
    (homToCoPrincipalLine_vanishes t X f)
  map_add' f g := by
    apply LinearMap.ext
    intro q
    induction q using Submodule.Quotient.induction_on with
    | _ x => rfl
  map_smul' c f := by
    apply LinearMap.ext
    intro q
    induction q using Submodule.Quotient.induction_on with
    | _ x => rfl

/-- A functional on `X / X_t` defines a morphism `X ⟶ Q_t`. -/
def coPrincipalLineMapOfQuotientDual (t : T) (X : Obj k T)
    (f : Module.Dual k (X ⧸ X.subspace t)) :
    X ⟶ coPrincipalLine (k := k) t where
  linear := f.comp (X.subspace t).mkQ
  map_subspace := by
    intro s x hx
    by_cases hst : s ≤ t
    · rw [line_subspace_of_not_mem k T (coPrincipalSupport t)
          (coPrincipalSupport_isUpperSet t) s (by
            simpa [coPrincipalSupport] using hst)]
      change f ((X.subspace t).mkQ x) = 0
      rw [show (X.subspace t).mkQ x = 0 by
        rw [← LinearMap.mem_ker, Submodule.ker_mkQ]
        exact X.monotone_subspace hst hx]
      exact f.map_zero
    · rw [line_subspace_of_mem k T (coPrincipalSupport t)
          (coPrincipalSupport_isUpperSet t) s (by
            simpa [coPrincipalSupport])]
      exact Submodule.mem_top

/-- The quotient-dual incidence evaluation
`Hom(X,Q_t) ≃ D(X/X_t)`. -/
def homToCoPrincipalLineEquiv (t : T) (X : Obj k T) :
    (X ⟶ coPrincipalLine (k := k) t) ≃ₗ[k]
      Module.Dual k (X ⧸ X.subspace t) :=
  LinearEquiv.ofBijective (coPrincipalQuotientEvaluation t X) ⟨by
    intro f g hfg
    apply Hom.ext
    apply LinearMap.ext
    intro x
    have hvalue := LinearMap.congr_fun hfg ((X.subspace t).mkQ x)
    exact hvalue,
    by
      intro f
      refine ⟨coPrincipalLineMapOfQuotientDual t X f, ?_⟩
      apply LinearMap.ext
      intro q
      induction q using Submodule.Quotient.induction_on with
      | _ x => rfl⟩

/-- Reflexivity of finite-dimensional vector spaces turns quotient
evaluation into the dual of the `Q_t`-corepresentable. -/
def quotientEquivDualHomToCoPrincipalLine [Fintype T]
    (t : T) (X : Obj k T) :
    (X ⧸ X.subspace t) ≃ₗ[k]
      Module.Dual k (X ⟶ coPrincipalLine (k := k) t) :=
  (Module.evalEquiv k (X ⧸ X.subspace t)).trans
    (homToCoPrincipalLineEquiv t X).dualMap

/-- The pointwise boundary map in the incidence exact sequence.  It is the
quotient map `X ⟶ X/X_t`, followed by the canonical identification of the
quotient with `D Hom(X,Q_t)`. -/
def incidenceBoundaryEvaluation [Fintype T]
    (t : T) (X : Obj k T) :
    X →ₗ[k] Module.Dual k (X ⟶ coPrincipalLine (k := k) t) :=
  (quotientEquivDualHomToCoPrincipalLine t X).toLinearMap.comp
    (X.subspace t).mkQ

/-- The incidence boundary functional evaluates a map `X ⟶ Q_t` on the
chosen vector of `X`. -/
@[simp]
theorem incidenceBoundaryEvaluation_apply [Fintype T]
    (t : T) (X : Obj k T) (x : X)
    (f : X ⟶ coPrincipalLine (k := k) t) :
    incidenceBoundaryEvaluation t X x f = f.linear x := by
  rfl

/-- The kernel of the boundary evaluation is exactly the distinguished
subspace `X_t`. -/
theorem incidenceBoundaryEvaluation_ker [Fintype T]
    (t : T) (X : Obj k T) :
    LinearMap.ker (incidenceBoundaryEvaluation t X) = X.subspace t := by
  rw [incidenceBoundaryEvaluation, LinearMap.ker_comp, LinearEquiv.ker,
    Submodule.comap_bot, Submodule.ker_mkQ]

/-- The boundary evaluation is onto. -/
theorem incidenceBoundaryEvaluation_surjective [Fintype T]
    (t : T) (X : Obj k T) :
    Function.Surjective (incidenceBoundaryEvaluation t X) := by
  exact (quotientEquivDualHomToCoPrincipalLine t X).surjective.comp
    (Submodule.mkQ_surjective (X.subspace t))

/-- Precomposition on morphisms into `Q_t`. -/
def homToCoPrincipalLinePrecomposition (t : T) {X Y : Obj k T}
    (f : X ⟶ Y) :
    (Y ⟶ coPrincipalLine (k := k) t) →ₗ[k]
      (X ⟶ coPrincipalLine (k := k) t) where
  toFun g := f ≫ g
  map_add' g h := by simp
  map_smul' c g := by simp

/-- Naturality of the incidence boundary evaluation.  Postcomposition on
the total spaces agrees with the dual of precomposition into `Q_t`. -/
theorem incidenceBoundaryEvaluation_natural [Fintype T]
    (t : T) {X Y : Obj k T} (f : X ⟶ Y) (x : X) :
    incidenceBoundaryEvaluation t Y (f.linear x) =
      (homToCoPrincipalLinePrecomposition t f).dualMap
        (incidenceBoundaryEvaluation t X x) := by
  apply LinearMap.ext
  intro g
  simp [homToCoPrincipalLinePrecomposition]

/-- Pointwise exactness of the manuscript's incidence sequence

`0 → X_t → X → D Hom(X,Q_t) → 0`.

The first map is the literal subspace inclusion and the second is
`incidenceBoundaryEvaluation`. -/
theorem principalSubspace_incidenceBoundaryEvaluation_exact [Fintype T]
    (t : T) (X : Obj k T) :
    Function.Exact (X.subspace t).subtype
      (incidenceBoundaryEvaluation t X) := by
  rw [LinearMap.exact_iff]
  exact (incidenceBoundaryEvaluation_ker t X).trans
    (X.subspace t).range_subtype.symm

/-- For a one-dimensional total space, the two incidence evaluations are
complementary. -/
theorem homFromPrincipalLine_nonzero_iff_homToCoPrincipalLine_eq_zero
    [Fintype T] (t : T) (X : Obj k T)
    (hX : Module.finrank k X = 1) :
    (∃ f : line k T (Set.Ici t) (isUpperSet_Ici t) ⟶ X, f ≠ 0) ↔
      (∀ g : X ⟶ coPrincipalLine (k := k) t, g = 0) := by
  let EP := homFromPrincipalLineEquiv t X
  let EQ := homToCoPrincipalLineEquiv t X
  have hsum := (X.subspace t).finrank_quotient_add_finrank
  rw [hX] at hsum
  constructor
  · rintro ⟨f, hf⟩
    have hPpos : 0 < Module.finrank k (X.subspace t) := by
      apply Module.finrank_pos_iff_exists_ne_zero.mpr
      refine ⟨EP f, ?_⟩
      intro hzero
      apply hf
      apply EP.injective
      simpa using hzero
    have hquot : Module.finrank k (X ⧸ X.subspace t) = 0 := by
      omega
    have hdualzero : Module.finrank k
        (Module.Dual k (X ⧸ X.subspace t)) = 0 := by
      rw [Subspace.dual_finrank_eq, hquot]
    have hsubsingle : Subsingleton
        (Module.Dual k (X ⧸ X.subspace t)) :=
      Module.finrank_zero_iff.mp hdualzero
    intro g
    apply EQ.injective
    exact Subsingleton.elim (EQ g) (EQ 0)
  · intro hzero
    have hdualsubsingle : Subsingleton
        (Module.Dual k (X ⧸ X.subspace t)) := by
      constructor
      intro f g
      calc
        f = EQ (EQ.symm f) := (EQ.apply_symm_apply f).symm
        _ = EQ 0 := by rw [hzero (EQ.symm f)]
        _ = EQ (EQ.symm g) :=
          (congrArg EQ (hzero (EQ.symm g))).symm
        _ = g := EQ.apply_symm_apply g
    have hdualzero : Module.finrank k
        (Module.Dual k (X ⧸ X.subspace t)) = 0 :=
      Module.finrank_zero_iff.mpr hdualsubsingle
    have hquot : Module.finrank k (X ⧸ X.subspace t) = 0 := by
      rw [Subspace.dual_finrank_eq] at hdualzero
      exact hdualzero
    have hPpos : 0 < Module.finrank k (X.subspace t) := by
      omega
    obtain ⟨x, hx⟩ := Module.finrank_pos_iff_exists_ne_zero.mp hPpos
    refine ⟨EP.symm x, ?_⟩
    intro hzeroP
    apply hx
    have happ := congrArg EP hzeroP
    simpa using happ

end MagnitudeConjecture.PosetSpace
