import MagnitudeConjecture.Algebra.BiserialAlgebraEquiv

/-!
# Left ideals as right ideals over the opposite algebra

Restriction of scalars along `A ≃ (Aᵐᵒᵖ)ᵐᵒᵖ` identifies the principal right
ideal generated by `op e` with the literal principal left ideal `Ae`.  This
identification transports intrinsic biseriality between the two objects.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory

namespace MagnitudeConjecture.RightModule

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
variable [IsNoetherianRing A] [IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ]

private abbrev oppositeRightIdealLeftEquivalence :
    FGModuleCat.{u} (Aᵐᵒᵖ)ᵐᵒᵖ ≌ FGModuleCat.{u} A :=
  LeftModule.fgModuleEquivalenceOfAlgEquiv (AlgEquiv.opOp k A).symm

def oppositeRightIdealLeftIdealLinearEquiv (e : A) :
    (oppositeRightIdealLeftEquivalence (k := k) (A := A)).functor.obj
        (rightIdealFGObj (MulOpposite.op e)) ≃ₗ[A]
      leftIdealFGObj (k := k) e where
  toFun x := oppositeRightIdealToLeftIdeal e x
  invFun y := leftIdealToOppositeRightIdeal e y
  left_inv x := by apply Subtype.ext; rfl
  right_inv y := by apply Subtype.ext; rfl
  map_add' x y := by apply Subtype.ext; rfl
  map_smul' a x := by apply Subtype.ext; rfl

def oppositeRightIdealLeftIdealIso (e : A) :
    (oppositeRightIdealLeftEquivalence (k := k) (A := A)).functor.obj
        (rightIdealFGObj (MulOpposite.op e)) ≅
      leftIdealFGObj (k := k) e :=
  QuotientSubmoduleEquidistribution.Contragredient.fgModuleIsoOfLinearEquiv A
    (oppositeRightIdealLeftIdealLinearEquiv (k := k) e)

omit [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
    [IsNoetherianRing A] [IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ] in
/-- Uniseriality of the principal right ideal generated by `op e` over the
opposite algebra transports to uniseriality of the literal left ideal `Ae`.
The scalar conversion is the canonical double-opposite identification. -/
theorem leftIdeal_isUniserial_of_oppositeRightIdeal (e : A)
    (h : IsUniserialModule (Aᵐᵒᵖ)ᵐᵒᵖ
      (rightIdeal (MulOpposite.op e))) :
    IsUniserialModule A (leftIdeal e) := by
  apply IsUniserialModule.of_smul_comparable
  intro x y
  rcases h.smul_comparable
      (leftIdealToOppositeRightIdeal e x)
      (leftIdealToOppositeRightIdeal e y) with hxy | hyx
  · left
    obtain ⟨r, hr⟩ := hxy
    refine ⟨r.unop.unop, ?_⟩
    apply Subtype.ext
    exact congrArg (fun z : rightIdeal (MulOpposite.op e) ↦ z.1.unop) hr
  · right
    obtain ⟨r, hr⟩ := hyx
    refine ⟨r.unop.unop, ?_⟩
    apply Subtype.ext
    exact congrArg (fun z : rightIdeal (MulOpposite.op e) ↦ z.1.unop) hr

omit [IsNoetherianRing Aᵐᵒᵖ] in
theorem leftIdealFGObj_isBiserialObject_iff_oppositeRightIdeal (e : A) :
    IsBiserialObject (leftIdealFGObj (k := k) e) ↔
      IsBiserialObject (rightIdealFGObj (MulOpposite.op e)) := by
  let E := oppositeRightIdealLeftEquivalence (k := k) (A := A)
  let i := oppositeRightIdealLeftIdealIso (k := k) e
  constructor
  · intro h
    apply IsBiserialObject.of_map_equivalence E
    exact h.congr i.symm
  · intro h
    exact (h.map_equivalence E).congr i

end MagnitudeConjecture.RightModule
