import MagnitudeConjecture.Algebra.StringBoundQuiver

/-!
# Path-generated bound-quiver relations

This file supplies the generic linear-algebra step behind monomializing a
bound-quiver presentation.  If every displayed relation is itself a path,
then the generated two-sided Hom ideal is spanned, in every Hom space, by
the individual paths which it kills.  Thus the presentation is monomial in
the sense used by `StringBoundQuiver`.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open QuotientSubmoduleEquidistribution.CategoricalIdeal

namespace MagnitudeConjecture.BoundQuiver

universe u

variable {k Q : Type u} [Field k] [Fintype Q] [Quiver.{u} Q]
variable [∀ x y : Q, Fintype (x ⟶ y)]

/-- A relation family is path-valued when every one of its displayed
generators is the linearization of a single path. -/
def IsPathRelationFamily (R : RelationFamily k Q) : Prop :=
  ∀ (X Y : LinearPathCategory.Category k Q) (r : X ⟶ Y),
    r ∈ R X Y →
      ∃ p : Quiver.Path (LinearPathCategory.vertex Y)
          (LinearPathCategory.vertex X),
        r = LinearPathCategory.pathHom p

/-- Enlarge a family of linear relations by declaring every path which
occurs with nonzero coefficient in a displayed relation to be a relation on
its own.  Two-sided closure is still taken by `generatedHomSubmodule`. -/
def pathSupportHull (R : RelationFamily k Q) : RelationFamily k Q :=
  fun X Y ↦ {f | ∃ p : Quiver.Path (LinearPathCategory.vertex Y)
      (LinearPathCategory.vertex X),
    f = LinearPathCategory.pathHom p ∧
      ∃ r : X ⟶ Y, r ∈ R X Y ∧
        LinearPathCategory.homPathLinearEquiv X Y r p ≠ 0}

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- The path-support hull is visibly generated by individual paths. -/
theorem pathSupportHull_isPathRelationFamily
    (R : RelationFamily k Q) :
    IsPathRelationFamily (pathSupportHull R) := by
  intro X Y f hf
  rcases hf with ⟨p, rfl, -⟩
  exact ⟨p, rfl⟩

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- Every original relation belongs to the ideal generated by its
path-support hull. -/
theorem relation_mem_pathSupportHullIdeal
    (R : RelationFamily k Q)
    {X Y : LinearPathCategory.Category k Q} {r : X ⟶ Y}
    (hr : r ∈ R X Y) :
    r ∈ HomIdeal.generatedHomSubmodule k (pathSupportHull R) X Y := by
  let b := LinearPathCategory.homPathBasis X Y
  have hspan : r ∈ Submodule.span k (b '' (b.repr r).support) :=
    b.mem_span_repr_support r
  apply (Submodule.span_le.2 ?_) hspan
  intro f hf
  rcases hf with ⟨p, hp, rfl⟩
  rw [LinearPathCategory.homPathBasis_apply]
  change LinearPathCategory.pathHom p ∈
    (HomIdeal.linearSpan k (pathSupportHull R)).hom X Y
  apply HomIdeal.relation_mem_linearSpan
  exact ⟨p, rfl, r, hr, Finsupp.mem_support_iff.mp hp⟩

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- The ideal of the original relations is contained in the ideal of the
path-support hull. -/
theorem relationIdeal_le_pathSupportHullIdeal
    (R : RelationFamily k Q)
    {X Y : LinearPathCategory.Category k Q} :
    HomIdeal.generatedHomSubmodule k R X Y ≤
      HomIdeal.generatedHomSubmodule k (pathSupportHull R) X Y := by
  intro f hf
  change f ∈ (HomIdeal.linearSpan k R).hom X Y at hf
  change f ∈ (HomIdeal.linearSpan k (pathSupportHull R)).hom X Y
  exact HomIdeal.linearSpan_le R (HomIdeal.linearSpan k (pathSupportHull R))
    (fun hr ↦ by
      change _ ∈ HomIdeal.generatedHomSubmodule k (pathSupportHull R) _ _
      exact relation_mem_pathSupportHullIdeal R hr) hf

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- If an ideal generated by literal paths kills a basis path, then one of
the displayed relation paths occurs as an ordinary subpath. -/
theorem exists_relation_path_factor_of_pathMap_eq_zero
    {R : RelationFamily k Q} (hR : IsPathRelationFamily R)
    {x y : Q} (p : Quiver.Path x y) (hp : pathMap R p = 0) :
    ∃ (U V : LinearPathCategory.Category k Q)
      (q : Quiver.Path (LinearPathCategory.vertex V)
        (LinearPathCategory.vertex U)),
      LinearPathCategory.pathHom q ∈ R U V ∧
        ∃ (a : Quiver.Path (LinearPathCategory.vertex U) y)
          (b : Quiver.Path x (LinearPathCategory.vertex V)),
          p = (b.comp q).comp a := by
  let X := LinearPathCategory.obj k Q y
  let Y := LinearPathCategory.obj k Q x
  let B := LinearPathCategory.homPathBasis X Y
  let T : Set (Quiver.Path x y) :=
    {s | LinearPathCategory.pathHom s ∈
      LinearPathCategory.basisCompositeSet R X Y}
  have hpIdeal : LinearPathCategory.pathHom p ∈
      HomIdeal.generatedHomSubmodule k R X Y :=
    (pathMap_eq_zero_iff_mem_relationIdeal R p).1 hp
  have hpSpan : LinearPathCategory.pathHom p ∈
      Submodule.span k (LinearPathCategory.basisCompositeSet R X Y) := by
    rw [← LinearPathCategory.generatedHomSubmodule_eq_span_basisCompositeSet]
    exact hpIdeal
  have hsubset : LinearPathCategory.basisCompositeSet R X Y ⊆ B '' T := by
    intro f hf
    rcases hf with ⟨U, V, r, hr, a, b, rfl⟩
    obtain ⟨q, rfl⟩ := hR U V r hr
    let s : Quiver.Path x y := (b.comp q).comp a
    refine ⟨s, ?_, ?_⟩
    · change LinearPathCategory.pathHom s ∈
        LinearPathCategory.basisCompositeSet R X Y
      refine ⟨U, V, LinearPathCategory.pathHom q, hr, a, b, ?_⟩
      simp only [LinearPathCategory.pathHom_comp, s,
        Quiver.Path.comp_assoc]
      rfl
    · rw [LinearPathCategory.homPathBasis_apply]
      simp only [LinearPathCategory.pathHom_comp, s,
        Quiver.Path.comp_assoc]
      rfl
  have hpSpan' : B p ∈ Submodule.span k (B '' T) := by
    rw [LinearPathCategory.homPathBasis_apply]
    exact (Submodule.span_mono hsubset) hpSpan
  have hpT : p ∈ T := (B.self_mem_span_image).1 hpSpan'
  change LinearPathCategory.pathHom p ∈
    LinearPathCategory.basisCompositeSet R X Y at hpT
  rcases hpT with ⟨U, V, r, hr, a, b, hpComposite⟩
  obtain ⟨q, hrq⟩ := hR U V r hr
  subst r
  refine ⟨U, V, q, hr, a, b, ?_⟩
  have hpathHom :
      (LinearPathCategory.pathHom p : X ⟶ Y) =
        LinearPathCategory.pathHom ((b.comp q).comp a) := by
    calc
      LinearPathCategory.pathHom p =
          LinearPathCategory.pathHom a ≫
            LinearPathCategory.pathHom q ≫
              LinearPathCategory.pathHom b := hpComposite
      _ = LinearPathCategory.pathHom ((b.comp q).comp a) := by
        simp only [LinearPathCategory.pathHom_comp,
          Quiver.Path.comp_assoc]
  apply B.injective
  dsimp only [B]
  rw [LinearPathCategory.homPathBasis_apply,
    LinearPathCategory.homPathBasis_apply]
  exact hpathHom

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- A two-sided Hom ideal generated by individual paths is monomial. -/
theorem isMonomial_of_isPathRelationFamily
    {R : RelationFamily k Q} (hR : IsPathRelationFamily R) :
    IsMonomial R := by
  intro x y
  let X := LinearPathCategory.obj k Q y
  let Y := LinearPathCategory.obj k Q x
  let killed : Set (Quiver.Path x y) := {p | pathMap R p = 0}
  let M : Submodule k (X ⟶ Y) :=
    Submodule.span k
      ((fun p : Quiver.Path x y ↦ LinearPathCategory.pathHom p) '' killed)
  change HomIdeal.generatedHomSubmodule k R X Y = M
  apply le_antisymm
  · intro f hf
    induction hf using Submodule.span_induction with
    | mem f hf =>
        rcases hf with ⟨A, B, r, hr, a, b, rfl⟩
        obtain ⟨p, rfl⟩ := hR A B r hr
        have ha := (LinearPathCategory.homPathBasis X A).mem_span a
        induction ha using Submodule.span_induction with
        | mem a ha =>
            rcases ha with ⟨q, rfl⟩
            rw [LinearPathCategory.homPathBasis_apply]
            have hb := (LinearPathCategory.homPathBasis B Y).mem_span b
            induction hb using Submodule.span_induction with
            | mem b hb =>
                rcases hb with ⟨s, rfl⟩
                rw [LinearPathCategory.homPathBasis_apply]
                apply Submodule.subset_span
                refine ⟨(s.comp p).comp q, ?_, by
                  simp only [LinearPathCategory.pathHom_comp]
                  rfl⟩
                change pathMap R ((s.comp p).comp q) = 0
                apply (pathMap_eq_zero_iff_mem_relationIdeal R _).2
                change LinearPathCategory.pathHom ((s.comp p).comp q) ∈
                  HomIdeal.generatedHomSubmodule k R X Y
                have hcomp := HomIdeal.composite_mem_linearSpan (K := k) R
                    (LinearPathCategory.pathHom q) hr
                    (LinearPathCategory.pathHom s)
                change
                  LinearPathCategory.pathHom q ≫
                        LinearPathCategory.pathHom p ≫
                      LinearPathCategory.pathHom s ∈
                    HomIdeal.generatedHomSubmodule k R X Y at hcomp
                simpa only [LinearPathCategory.pathHom_comp] using hcomp
            | zero => simp
            | add b c _ _ hb hc =>
                simpa only [Preadditive.comp_add] using M.add_mem hb hc
            | smul c b _ hb =>
                simpa only [CategoryTheory.Linear.comp_smul] using
                  M.smul_mem c hb
        | zero => simp
        | add a c _ _ ha hc =>
            simpa only [Preadditive.add_comp] using M.add_mem ha hc
        | smul c a _ ha =>
            simpa only [CategoryTheory.Linear.smul_comp] using
              M.smul_mem c ha
    | zero => exact M.zero_mem
    | add f g _ _ hf hg => exact M.add_mem hf hg
    | smul c f _ hf => exact M.smul_mem c hf
  · apply Submodule.span_le.2
    rintro f ⟨p, hp, rfl⟩
    exact (pathMap_eq_zero_iff_mem_relationIdeal R p).1 hp

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- The path-support hull is a monomial relation family. -/
theorem pathSupportHull_isMonomial (R : RelationFamily k Q) :
    IsMonomial (pathSupportHull R) :=
  isMonomial_of_isPathRelationFamily (pathSupportHull_isPathRelationFamily R)

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- Taking the path-support hull preserves admissibility. -/
theorem pathSupportHull_isAdmissible
    {R : RelationFamily k Q} (hR : IsAdmissible R) :
    IsAdmissible (pathSupportHull R) := by
  constructor
  · intro X Y f hf
    induction hf using Submodule.span_induction with
    | mem f hf =>
        rcases hf with ⟨A, B, r, hr, a, b, rfl⟩
        rcases hr with ⟨p, rfl, s, hs, hp⟩
        have hsIdeal : s ∈ HomIdeal.generatedHomSubmodule k R A B := by
          change s ∈ (HomIdeal.linearSpan k R).hom A B
          exact HomIdeal.relation_mem_linearSpan R hs
        have hsTail : s ∈ LinearPathCategory.lengthTail A B 2 :=
          hR.relationIdeal_le_lengthTail_two A B hsIdeal
        have hpSupport : p ∈
            (LinearPathCategory.homPathLinearEquiv A B s).support :=
          Finsupp.mem_support_iff.mpr hp
        have hpLength : 2 ≤ p.length :=
          (LinearPathCategory.mem_lengthTail_iff A B 2 s).1
            hsTail hpSupport
        have hpTail : LinearPathCategory.pathHom p ∈
            LinearPathCategory.lengthTail A B 2 :=
          (LinearPathCategory.pathHom_mem_lengthTail_iff p 2).2 hpLength
        have haTail : a ∈ LinearPathCategory.lengthTail X A 0 := by
          rw [LinearPathCategory.mem_lengthTail_iff]
          intro q hq
          exact Nat.zero_le q.length
        have hbTail : b ∈ LinearPathCategory.lengthTail B Y 0 := by
          rw [LinearPathCategory.mem_lengthTail_iff]
          intro q hq
          exact Nat.zero_le q.length
        have hap : a ≫ LinearPathCategory.pathHom p ∈
            LinearPathCategory.lengthTail X B 2 := by
          simpa using LinearPathCategory.comp_mem_lengthTail haTail hpTail
        simpa using LinearPathCategory.comp_mem_lengthTail hap hbTail
    | zero => exact Submodule.zero_mem _
    | add f g _ _ hf hg => exact Submodule.add_mem _ hf hg
    | smul c f _ hf => exact Submodule.smul_mem _ c hf
  · obtain ⟨N, hN, hlong⟩ := hR.long_paths_mem
    refine ⟨N, hN, ?_⟩
    intro x y p hp
    exact relationIdeal_le_pathSupportHullIdeal R (hlong p hp)

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- Every path killed by the original relations is killed after passing to
the path-support hull. -/
theorem pathMap_pathSupportHull_eq_zero_of_eq_zero
    (R : RelationFamily k Q) {x y : Q} {p : Quiver.Path x y}
    (hp : pathMap R p = 0) :
    pathMap (pathSupportHull R) p = 0 := by
  apply (pathMap_eq_zero_iff_mem_relationIdeal (pathSupportHull R) p).2
  apply relationIdeal_le_pathSupportHullIdeal R
  exact (pathMap_eq_zero_iff_mem_relationIdeal R p).1 hp

variable {A : Type u} [Ring A] [Algebra k A]

namespace SpecialBiserialPresentation

/-- A special-biserial presentation has a canonical string-algebra quotient:
replace its relation family by the path-support hull.  This is the generic
presentation-theoretic half of special-biserial socle reduction; identifying
the resulting algebra quotient with a particular socle quotient is a
separate theorem. -/
def pathSupportHullStringPresentation
    (P : SpecialBiserialPresentation k A Q) :
    let hR := pathSupportHull_isAdmissible P.toPresentation.admissible
    StringPresentation k
      (CoveringHom.finiteCategoryProjectiveGenerator.algebra
        (finiteRepresentablesOfAdmissible hR)) Q := by
  let R := pathSupportHull P.toPresentation.relations
  let hR : IsAdmissible R :=
    pathSupportHull_isAdmissible P.toPresentation.admissible
  refine {
    toSpecialBiserialPresentation := {
      toPresentation := {
        relations := R
        admissible := hR
        algebraEquiv := AlgEquiv.refl }
      arrows_starting_le_two := P.arrows_starting_le_two
      arrows_ending_le_two := P.arrows_ending_le_two
      continuation_right_le_one := ?_
      continuation_left_le_one := ?_ }
    monomial := pathSupportHull_isMonomial P.toPresentation.relations }
  · intro x y a
    let source := {b : Quiver.Star y //
      arrowMap R b.2 ≫ arrowMap R a ≠ 0}
    let target := {b : Quiver.Star y //
      arrowMap P.toPresentation.relations b.2 ≫
        arrowMap P.toPresentation.relations a ≠ 0}
    let f : source → target := fun b ↦ ⟨b.1, by
      intro hzero
      apply b.2
      simp only [arrowMap, pathMap_comp] at hzero ⊢
      exact pathMap_pathSupportHull_eq_zero_of_eq_zero
        P.toPresentation.relations hzero⟩
    have hf : Function.Injective f := by
      intro b c hbc
      have hv : (f b).1 = (f c).1 :=
        congrArg (fun z : target ↦ z.1) hbc
      apply Subtype.ext
      exact hv
    exact (Nat.card_le_card_of_injective f hf).trans
      (P.continuation_right_le_one a)
  · intro x y a
    let source := {c : Quiver.Costar x //
      arrowMap R a ≫ arrowMap R c.2 ≠ 0}
    let target := {c : Quiver.Costar x //
      arrowMap P.toPresentation.relations a ≫
        arrowMap P.toPresentation.relations c.2 ≠ 0}
    let f : source → target := fun c ↦ ⟨c.1, by
      intro hzero
      apply c.2
      simp only [arrowMap, pathMap_comp] at hzero ⊢
      exact pathMap_pathSupportHull_eq_zero_of_eq_zero
        P.toPresentation.relations hzero⟩
    have hf : Function.Injective f := by
      intro b c hbc
      have hv : (f b).1 = (f c).1 :=
        congrArg (fun z : target ↦ z.1) hbc
      apply Subtype.ext
      exact hv
    exact (Nat.card_le_card_of_injective f hf).trans
      (P.continuation_left_le_one a)

end SpecialBiserialPresentation

end MagnitudeConjecture.BoundQuiver
