import Mathlib.LinearAlgebra.Quotient.Basic

/-!
# Saturation with respect to an idempotent coordinate

For a left module `M` and an idempotent coordinate `e`, the largest submodule
on which the entire left ideal generated by `e` acts trivially consists of
the elements `x` satisfying `(e * r) • x = 0` for every scalar `r`.

Applied to `M / L`, its inverse image in `M` is the source-literal maximal
enlargement of `L` that is invisible to the projective coordinate `R e`.
This is the elementary saturation operation used in Iyama's realization
argument.
-/

set_option autoImplicit false

namespace MagnitudeConjecture.IdempotentSaturation

universe u

variable {R M : Type u} [Ring R] [AddCommGroup M] [Module R M]

/-- Universal vanishing of linear maps is unchanged when the source is
replaced by a linearly equivalent module. -/
theorem forall_linearMap_eq_zero_congr
    {P Q : Type u} [AddCommGroup P] [Module R P]
    [AddCommGroup Q] [Module R Q]
    (E : P ≃ₗ[R] Q) :
    (∀ f : P →ₗ[R] M, f = 0) ↔
      ∀ g : Q →ₗ[R] M, g = 0 := by
  constructor
  · intro h g
    have hg : g.comp E.toLinearMap = 0 := h _
    apply LinearMap.ext
    intro y
    have hy := LinearMap.congr_fun hg (E.symm y)
    simpa using hy
  · intro h f
    have hf : f.comp E.symm.toLinearMap = 0 := h _
    apply LinearMap.ext
    intro x
    have hx := LinearMap.congr_fun hf (E x)
    simpa using hx

/-- Right multiplication by `e` on the left regular module. -/
def rightMultiplication (e : R) : R →ₗ[R] R where
  toFun r := r * e
  map_add' r s := add_mul r s e
  map_smul' a r := by
    change (a * r) * e = a * (r * e)
    exact mul_assoc a r e

/-- The principal left ideal `R e`, regarded as a left `R`-module. -/
def principalLeftIdeal (e : R) : Submodule R R :=
  LinearMap.range (rightMultiplication e)

/-- The canonical generator `e` of the principal left ideal `R e`. -/
def principalLeftIdealGenerator (e : R) : principalLeftIdeal e :=
  ⟨e, ⟨1, by simp [rightMultiplication]⟩⟩

/-- Every element of `R e` is fixed by right multiplication by an
idempotent `e`. -/
theorem principalLeftIdeal_fixed
    {e : R} (he : IsIdempotentElem e)
    (y : principalLeftIdeal e) :
    y.1 * e = y.1 := by
  obtain ⟨r, hr⟩ := y.2
  change r * e = y.1 at hr
  rw [← hr, mul_assoc, he.eq]

/-- Every module element defines a map `R e → M` by scalar multiplication. -/
def principalLeftIdealHomOf (e : R) (x : M) :
    principalLeftIdeal e →ₗ[R] M where
  toFun y := y.1 • x
  map_add' y z := by
    change (y.1 + z.1) • x = y.1 • x + z.1 • x
    exact add_smul y.1 z.1 x
  map_smul' a y := by
    change (a * y.1) • x = a • y.1 • x
    exact mul_smul a y.1 x

@[simp]
theorem principalLeftIdealHomOf_generator (e : R) (x : M) :
    principalLeftIdealHomOf e x (principalLeftIdealGenerator e) =
      e • x :=
  rfl

/-- If `e` annihilates a module, every map from the principal left ideal
`R e` to that module is zero. -/
theorem principalLeftIdeal_hom_eq_zero_of_smul_eq_zero
    {e : R} (he : IsIdempotentElem e)
    (hzero : ∀ x : M, e • x = 0)
    (f : principalLeftIdeal e →ₗ[R] M) :
    f = 0 := by
  have hgenerator : f (principalLeftIdealGenerator e) = 0 := by
    have hfixed :
        e • principalLeftIdealGenerator e =
          principalLeftIdealGenerator e := by
      apply Subtype.ext
      exact he.eq
    calc
      f (principalLeftIdealGenerator e) =
          f (e • principalLeftIdealGenerator e) :=
        congrArg f hfixed.symm
      _ = e • f (principalLeftIdealGenerator e) :=
        f.map_smul e _
      _ = 0 := hzero _
  apply LinearMap.ext
  intro y
  obtain ⟨r, hr⟩ := y.2
  have hy : y = r • principalLeftIdealGenerator e := by
    apply Subtype.ext
    exact hr.symm
  rw [hy, f.map_smul, hgenerator, smul_zero,
    LinearMap.zero_apply]

/-- Vanishing of all maps from `R e` is exactly annihilation by `e`. -/
theorem principalLeftIdeal_hom_eq_zero_iff
    {e : R} (he : IsIdempotentElem e) :
    (∀ f : principalLeftIdeal e →ₗ[R] M, f = 0) ↔
      ∀ x : M, e • x = 0 := by
  constructor
  · intro h x
    have happ := LinearMap.congr_fun
      (h (principalLeftIdealHomOf e x))
      (principalLeftIdealGenerator e)
    simpa using happ
  · intro h f
    exact principalLeftIdeal_hom_eq_zero_of_smul_eq_zero he h f

/-- The largest submodule whose every scalar translate is annihilated by
`e`.  Equivalently, this is the largest submodule on which the left ideal
`R e` has zero Hom coordinate. -/
def torsionSubmodule (e : R) : Submodule R M where
  carrier := {x | ∀ r : R, (e * r) • x = 0}
  zero_mem' := by simp
  add_mem' := by
    intro x y hx hy r
    rw [smul_add, hx r, hy r, add_zero]
  smul_mem' := by
    intro a x hx r
    rw [smul_smul, mul_assoc]
    exact hx (r * a)

@[simp]
theorem mem_torsionSubmodule_iff (e : R) (x : M) :
    x ∈ torsionSubmodule e ↔ ∀ r : R, (e * r) • x = 0 :=
  Iff.rfl

/-- In particular, `e` annihilates its torsion submodule. -/
theorem smul_eq_zero_of_mem_torsionSubmodule
    (e : R) {x : M} (hx : x ∈ torsionSubmodule e) :
    e • x = 0 := by
  simpa using hx 1

/-- Any submodule annihilated by `e` is contained in the torsion submodule.
Closure under all scalars supplies the stronger defining condition. -/
theorem le_torsionSubmodule
    (e : R) (N : Submodule R M)
    (hN : ∀ x : M, x ∈ N → e • x = 0) :
    N ≤ torsionSubmodule e := by
  intro x hx
  rw [mem_torsionSubmodule_iff]
  intro r
  rw [mul_smul]
  exact hN (r • x) (N.smul_mem r hx)

/-- Enlarge `L` by the full idempotent-torsion submodule of `M / L`. -/
def saturation (e : R) (L : Submodule R M) : Submodule R M :=
  (torsionSubmodule (M := M ⧸ L) e).comap L.mkQ

@[simp]
theorem mem_saturation_iff (e : R) (L : Submodule R M) (x : M) :
    x ∈ saturation e L ↔
      ∀ r : R, (e * r) • L.mkQ x = 0 :=
  Iff.rfl

/-- Saturation really enlarges the original submodule. -/
theorem le_saturation (e : R) (L : Submodule R M) :
    L ≤ saturation e L := by
  intro x hx
  rw [mem_saturation_iff]
  intro r
  have hxzero : L.mkQ x = 0 := by
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
    exact hx
  rw [hxzero, smul_zero]

/-- The quotient of the saturation by `L` is annihilated by `e`. -/
theorem smul_mkQ_eq_zero_of_mem_saturation
    (e : R) (L : Submodule R M) {x : M}
    (hx : x ∈ saturation e L) :
    e • L.mkQ x = 0 :=
  smul_eq_zero_of_mem_torsionSubmodule e hx

/-- Maximality: every enlargement of `L` whose image in `M / L` is
annihilated by `e` lies in the saturation. -/
theorem le_saturation_of_smul_mkQ_eq_zero
    (e : R) (L N : Submodule R M)
    (hN : ∀ x : M, x ∈ N → e • L.mkQ x = 0) :
    N ≤ saturation e L := by
  intro x hx
  rw [mem_saturation_iff]
  intro r
  rw [mul_smul, ← map_smul]
  exact hN (r • x) (N.smul_mem r hx)

/-- Saturating once removes all remaining idempotent torsion: the quotient
by `saturation e L` has no nonzero submodule element whose scalar translates
are all annihilated by `e`. -/
theorem torsionSubmodule_quotient_saturation_eq_bot
    {e : R} (he : IsIdempotentElem e) (L : Submodule R M) :
    torsionSubmodule (M := M ⧸ saturation e L) e = ⊥ := by
  apply le_antisymm
  · intro x hx
    obtain ⟨m, rfl⟩ := (saturation e L).mkQ_surjective x
    rw [Submodule.mem_bot, Submodule.mkQ_apply,
      Submodule.Quotient.mk_eq_zero, mem_saturation_iff]
    intro r
    have hrzero :
        (saturation e L).mkQ ((e * r) • m) = 0 := by
      simpa only [map_smul] using hx r
    have hrmem : (e * r) • m ∈ saturation e L := by
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero] at hrzero
      exact hrzero
    have hsat := (mem_saturation_iff e L ((e * r) • m)).1 hrmem 1
    have hsat' : e • L.mkQ ((e * r) • m) = 0 := by
      simpa only [mul_one] using hsat
    calc
      (e * r) • L.mkQ m = (e * e * r) • L.mkQ m := by rw [he.eq]
      _ = e • L.mkQ ((e * r) • m) := by
        simp only [map_smul, mul_smul]
      _ = 0 := hsat'
  · exact bot_le

end MagnitudeConjecture.IdempotentSaturation
