import MagnitudeConjecture.Algebra.RightModuleStableRepresentable
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# Cyclic images of restricted representables

This file extracts the finite-length radical induction used for stable
representables into a form valid for an arbitrary finite functor.  The
target-specific input is only a natural map from one indecomposable
representable; its image has that representable as a minimal projective cover,
and the image of the representable radical is its categorical radical.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits
open QuotientSubmoduleEquidistribution
open scoped ModuleCat.Algebra

attribute [local instance] FintypeCat.fintype

namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton

universe u

variable {k A : Type u} [Field k] [IsAlgClosed k]
variable [Ring A] [Algebra k A] [FiniteDimensional k A]
  [IsNoetherianRing Aᵐᵒᵖ]
variable (S : RightModule.FiniteIndecomposableSkeleton k A)

/-- The image generated by a map from one restricted indecomposable
representable into an arbitrary finite functor. -/
def finiteRepresentableImage
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) :
    CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k :=
  (imageSubobject p :
    CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k)

/-- The inclusion of a cyclic representable image into its ambient finite
functor. -/
def finiteRepresentableImageInclusion
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) :
    S.finiteRepresentableImage i p ⟶ G :=
  (imageSubobject p).arrow

instance finiteRepresentableImageInclusion_mono
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) :
    Mono (S.finiteRepresentableImageInclusion i p) := by
  change Mono (imageSubobject p).arrow
  infer_instance

/-- The canonical epimorphism from the representing projective onto its
cyclic image. -/
def finiteRepresentableImagePresentation
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) :
    S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶
      S.finiteRepresentableImage i p :=
  factorThruImageSubobject p

@[reassoc]
theorem finiteRepresentableImagePresentation_comp_inclusion
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) :
    S.finiteRepresentableImagePresentation i p ≫
        S.finiteRepresentableImageInclusion i p = p :=
  imageSubobject_arrow_comp p

instance finiteRepresentableImagePresentation_epi
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) :
    Epi (S.finiteRepresentableImagePresentation i p) := by
  change Epi (factorThruImageSubobject p)
  infer_instance

theorem finiteRepresentableImagePresentation_ne_zero
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G)
    (hp : p ≠ 0) :
    S.finiteRepresentableImagePresentation i p ≠ 0 := by
  intro hzero
  apply hp
  rw [← S.finiteRepresentableImagePresentation_comp_inclusion i p,
    hzero, zero_comp]

/-- A nonzero cyclic image has its chosen indecomposable representable as a
minimal projective cover. -/
def finiteRepresentableImageMinimalProjectivePresentation
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G)
    (hp : p ≠ 0) :
    MinimalProjectivePresentation (S.finiteRepresentableImage i p) where
  p := S.finiteRestrictedContravariantRepresentable (S.fgObj i)
  f := S.finiteRepresentableImagePresentation i p
  projective := inferInstance
  epi := inferInstance
  rightMinimal := by
    letI : IsLocalRing (End
        (S.finiteRestrictedContravariantRepresentable (S.fgObj i))) :=
      S.finiteRestrictedContravariantRepresentableFgObj_end_isLocalRing i
    exact isRightMinimal_of_localEnd_of_ne_zero _
      (S.finiteRepresentableImagePresentation_ne_zero i p hp)

/-- The pushed-forward representable radical is a radical subobject of a
cyclic image. -/
theorem finiteRepresentableImageRadical_isRadicalSubobject
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) :
    IsUniserialObject.IsRadicalSubobject
      (imageSubobject
        (S.finiteRestrictedContravariantRepresentableRadicalInclusion i ≫
          S.finiteRepresentableImagePresentation i p)) :=
  isRadicalSubobject_imageSubobject_comp_of_epi
    (S.finiteRestrictedContravariantRepresentableRadicalInclusion i)
    (S.finiteRepresentableImagePresentation i p)
    (isRadicalSubobject_mk_of_mono_rightAlmostSplit
      (S.finiteRestrictedContravariantRepresentableRadicalInclusion i)
      (S.finiteRestrictedContravariantRepresentableRadicalInclusion_isRightAlmostSplit i))

/-- For a nonzero generator, its pushed-forward representable radical is a
proper subobject of the cyclic image. -/
theorem finiteRepresentableImageRadical_ne_top
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G)
    (hp : p ≠ 0) :
    imageSubobject
        (S.finiteRestrictedContravariantRepresentableRadicalInclusion i ≫
          S.finiteRepresentableImagePresentation i p) ≠ ⊤ := by
  have hessential : IsEssentialEpi
      (S.finiteRepresentableImagePresentation i p) :=
    isEssentialEpi_of_isRightMinimal _
      (S.finiteRepresentableImageMinimalProjectivePresentation
        i p hp).rightMinimal
  exact imageSubobject_comp_ne_top_of_isEssentialEpi
    (S.finiteRestrictedContravariantRepresentableRadicalInclusion i)
    (S.finiteRepresentableImagePresentation i p) hessential
    (mk_ne_top_of_mono_rightAlmostSplit
      (S.finiteRestrictedContravariantRepresentableRadicalInclusion i)
      (S.finiteRestrictedContravariantRepresentableRadicalInclusion_isRightAlmostSplit i))

/-- If the pushed-forward radical of a cyclic image is uniserial, so is the
whole image. -/
theorem finiteRepresentableImage_isUniserial_of_radical
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G)
    (hrad : IsUniserialObject
      ((imageSubobject
          (S.finiteRestrictedContravariantRepresentableRadicalInclusion i ≫
            S.finiteRepresentableImagePresentation i p) :
        CoveringHom.FiniteDimensionalModuleCategory
          (C := S.IndecCategoryᵒᵖ) k))) :
    IsUniserialObject (S.finiteRepresentableImage i p) :=
  IsUniserialObject.of_radicalSubobject _
    (S.finiteRepresentableImageRadical_isRadicalSubobject i p) hrad

/-- Finite-length radical induction for any class of cyclic images. -/
theorem finiteRepresentableImage_isUniserial_of_closedRadicalSuccessors
    {G : CoveringHom.FiniteDimensionalModuleCategory
      (C := S.IndecCategoryᵒᵖ) k}
    (Good : ∀ (i : S.IndecCategory),
        (S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G) → Prop)
    (hsuccessor : ∀ (i : S.IndecCategory)
      (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G),
        Good i p → p ≠ 0 →
        ¬ IsZero
          ((imageSubobject
              (S.finiteRestrictedContravariantRepresentableRadicalInclusion i ≫
                S.finiteRepresentableImagePresentation i p) :
            CoveringHom.FiniteDimensionalModuleCategory
              (C := S.IndecCategoryᵒᵖ) k)) →
        ∃ (j : S.IndecCategory)
          (q : S.finiteRestrictedContravariantRepresentable (S.fgObj j) ⟶ G),
          Good j q ∧ q ≠ 0 ∧
            Nonempty
              ((imageSubobject
                    (S.finiteRestrictedContravariantRepresentableRadicalInclusion i ≫
                      S.finiteRepresentableImagePresentation i p) :
                  CoveringHom.FiniteDimensionalModuleCategory
                    (C := S.IndecCategoryᵒᵖ) k) ≅
                S.finiteRepresentableImage j q))
    (i : S.IndecCategory)
    (p : S.finiteRestrictedContravariantRepresentable (S.fgObj i) ⟶ G)
    (hgood : Good i p) (hp : p ≠ 0) :
    IsUniserialObject (S.finiteRepresentableImage i p) := by
  let main : ∀ n : ℕ,
      ∀ (j : S.IndecCategory)
        (q : S.finiteRestrictedContravariantRepresentable (S.fgObj j) ⟶ G),
        CoveringHom.moduleTotalDimension
            (S.finiteRepresentableImage j q) = n →
          Good j q → q ≠ 0 →
          IsUniserialObject (S.finiteRepresentableImage j q) := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
        intro j q hdim hgood hq
        let R := imageSubobject
          (S.finiteRestrictedContravariantRepresentableRadicalInclusion j ≫
            S.finiteRepresentableImagePresentation j q)
        by_cases hRzero : IsZero
            (R : CoveringHom.FiniteDimensionalModuleCategory
              (C := S.IndecCategoryᵒᵖ) k)
        · apply S.finiteRepresentableImage_isUniserial_of_radical j q
          exact IsUniserialObject.of_isZero hRzero
        · obtain ⟨j', q', hgood', hq', ⟨e⟩⟩ :=
            hsuccessor j q hgood hq hRzero
          have hRproper : R ≠ ⊤ :=
            S.finiteRepresentableImageRadical_ne_top j q hq
          have hRarrowNotIso : ¬ IsIso R.arrow := by
            intro hiso
            letI : IsIso R.arrow := hiso
            apply hRproper
            simpa using
              (Subobject.isIso_iff_mk_eq_top R.arrow).mp
                (inferInstance : IsIso R.arrow)
          have hRdim : CoveringHom.moduleTotalDimension
                (R : CoveringHom.FiniteDimensionalModuleCategory
                  (C := S.IndecCategoryᵒᵖ) k) < n := by
            rw [← hdim]
            exact CoveringHom.moduleTotalDimension_lt_of_mono_not_isIso
              (R : CoveringHom.FiniteDimensionalModuleCategory
                (C := S.IndecCategoryᵒᵖ) k)
              (S.finiteRepresentableImage j q) R.arrow hRarrowNotIso
          have hdimIso : CoveringHom.moduleTotalDimension
                (R : CoveringHom.FiniteDimensionalModuleCategory
                  (C := S.IndecCategoryᵒᵖ) k) =
              CoveringHom.moduleTotalDimension
                (S.finiteRepresentableImage j' q') := by
            unfold CoveringHom.moduleTotalDimension
            apply finsum_congr
            intro X
            exact (asIso (e.hom.hom.hom.app X)).toLinearEquiv.finrank_eq
          have hnext : IsUniserialObject
              (S.finiteRepresentableImage j' q') :=
            ih (CoveringHom.moduleTotalDimension
              (S.finiteRepresentableImage j' q'))
              (by rw [← hdimIso]; exact hRdim)
              j' q' rfl hgood' hq'
          have hrad : IsUniserialObject
              (R : CoveringHom.FiniteDimensionalModuleCategory
                (C := S.IndecCategoryᵒᵖ) k) :=
            hnext.congr e.symm
          exact S.finiteRepresentableImage_isUniserial_of_radical j q hrad
  exact main
    (CoveringHom.moduleTotalDimension (S.finiteRepresentableImage i p))
    i p rfl hgood hp

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
