import MagnitudeConjecture.Algebra.RightModulePrimitiveIdempotent
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# The primitive quotient `A/AeA`

This file identifies the coordinate-zero deletion used by the compiled
primitive mesh package with the frozen manuscript's literal quotient by the
two-sided ideal `AeA`.
-/

set_option autoImplicit false

noncomputable section

open CategoryTheory

namespace MagnitudeConjecture.RightModule

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]

/-- The two-sided ideal denoted `AeA` in the manuscript: the two-sided ideal
generated by `e`. -/
def primitiveIdeal (e : A) : TwoSidedIdeal A :=
  TwoSidedIdeal.span {e}

/-- The manuscript's primitive quotient algebra `A/AeA`. -/
abbrev primitiveQuotientAlgebra (e : A) :=
  (primitiveIdeal e).ringCon.Quotient

/-- The canonical quotient map `A ⟶ A/AeA`. -/
def primitiveQuotientMap (e : A) : A →+* primitiveQuotientAlgebra e :=
  (primitiveIdeal e).ringCon.mk'

/-- The kernel of the primitive quotient map is exactly `AeA`. -/
theorem primitiveQuotientMap_ker (e : A) :
    TwoSidedIdeal.ker (primitiveQuotientMap e) = primitiveIdeal e := by
  exact TwoSidedIdeal.ker_ringCon_mk' (primitiveIdeal e)

/-- Membership in `AeA` is equivalent to vanishing in `A/AeA`. -/
theorem mem_primitiveIdeal_iff_quotient_eq_zero {e a : A} :
    a ∈ primitiveIdeal e ↔ primitiveQuotientMap e a = 0 := by
  rw [← TwoSidedIdeal.mem_ker, primitiveQuotientMap_ker]

/-- The primitive generator is zero in `A/AeA`. -/
@[simp]
theorem primitiveQuotientMap_generator (e : A) :
    primitiveQuotientMap e e = 0 := by
  rw [← mem_primitiveIdeal_iff_quotient_eq_zero]
  exact TwoSidedIdeal.subset_span (Set.mem_singleton e)

/-- A right module is annihilated by a two-sided ideal when every element of
the ideal acts as zero. -/
def IsAnnihilatedBy (I : TwoSidedIdeal A)
    (X : FinitelyGeneratedCategory A) : Prop :=
  ∀ x : X, ∀ a : A, a ∈ I → (MulOpposite.op a) • x = 0

/-- A right module is annihilated by `AeA` exactly when `e` itself acts as
zero. -/
theorem isAnnihilatedBy_primitiveIdeal_iff (e : A)
    (X : FinitelyGeneratedCategory A) :
    IsAnnihilatedBy (primitiveIdeal e) X ↔
      ∀ x : X, (MulOpposite.op e) • x = 0 := by
  constructor
  · intro h x
    exact h x e (TwoSidedIdeal.subset_span (Set.mem_singleton e))
  · intro he x a ha
    have hAll : ∀ a : A, a ∈ primitiveIdeal e →
        ∀ x : X, (MulOpposite.op a) • x = 0 := by
      intro a ha
      induction ha using TwoSidedIdeal.span_induction with
      | mem a ha =>
          have hae : a = e := Set.mem_singleton_iff.mp ha
          simpa [hae] using he
      | zero => intro x; simp
      | add a b _ _ ha hb =>
          intro x
          rw [MulOpposite.op_add, add_smul, ha x, hb x, add_zero]
      | neg a _ ha =>
          intro x
          change (-MulOpposite.op a) • x = 0
          rw [neg_smul, ha x, neg_zero]
      | left_absorb b a _ ha =>
          intro x
          change (MulOpposite.op (b * a)) • x = 0
          rw [MulOpposite.op_mul, mul_smul]
          exact ha ((MulOpposite.op b) • x)
      | right_absorb b a _ ha =>
          intro x
          change (MulOpposite.op (a * b)) • x = 0
          rw [MulOpposite.op_mul, mul_smul, ha x, smul_zero]
    exact hAll a ha x

namespace FiniteIndecomposableSkeleton

variable (S : RightModule.FiniteIndecomposableSkeleton k A)

/-- The labels killed by the primitive coordinate are exactly the
indecomposable modules annihilated by the manuscript's ideal `AeA`. -/
theorem mem_primitiveKilledLabels_iff_isAnnihilatedBy
    {e : A} (D : PrimitiveIdempotentData e) (x : Fin S.n) :
    x ∈ S.primitiveKilledLabels D ↔
      IsAnnihilatedBy (primitiveIdeal e) (S.fgObj x) := by
  rw [isAnnihilatedBy_primitiveIdeal_iff]
  rfl

/-- Equivalently, the zero set of the primitive multiplicity is the literal
`AeA`-annihilated subcategory. -/
theorem primitiveMultiplicity_eq_zero_iff_isAnnihilatedBy
    {e : A} (D : PrimitiveIdempotentData e) (x : Fin S.n) :
    S.primitiveMultiplicity D x = 0 ↔
      IsAnnihilatedBy (primitiveIdeal e) (S.fgObj x) := by
  rw [← S.mem_primitiveKilledLabels_iff_isAnnihilatedBy D]
  exact (S.mem_primitiveKilledLabels_iff_primitiveMultiplicity_zero D x).symm

end FiniteIndecomposableSkeleton

end MagnitudeConjecture.RightModule
