import MagnitudeConjecture.Algebra.RightModulePrimitiveIdempotent

/-! # Modules generated by their idempotent coordinate -/
set_option autoImplicit false
noncomputable section
open CategoryTheory
open scoped ModuleCat.Algebra
namespace MagnitudeConjecture.RightModule
universe u
variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]

/-- The right submodule generated by Xe. -/
def coordinateGeneratedSubmodule (e : A) (X : FinitelyGeneratedCategory A) :
    Submodule Aᵐᵒᵖ X :=
  Submodule.span Aᵐᵒᵖ (idempotentCoordinate (k := k) e X : Set X)

/-- Every element of X is generated by its coordinate Xe. -/
def IsGeneratedAtIdempotent (e : A) (X : FinitelyGeneratedCategory A) : Prop :=
  coordinateGeneratedSubmodule (k := k) e X = ⊤

/-- A map from a module generated at e to a module killed by e is zero. -/
theorem hom_eq_zero_of_generated_at_idempotent
    {e : A} (he : IsIdempotentElem e)
    {X Y : FinitelyGeneratedCategory A}
    (hX : IsGeneratedAtIdempotent (k := k) e X)
    (hY : ∀ y : Y, (MulOpposite.op e) • y = 0) (f : X ⟶ Y) : f = 0 := by
  have hk : coordinateGeneratedSubmodule (k := k) e X ≤ LinearMap.ker f.hom.hom := by
    apply Submodule.span_le.mpr
    intro x hx
    change f x = 0
    calc
      f x = f ((MulOpposite.op e) • x) := by
        rw [idempotentCoordinate_fixed he X ⟨x, hx⟩]
      _ = (MulOpposite.op e) • f x := f.hom.hom.map_smul _ _
      _ = 0 := hY _
  change coordinateGeneratedSubmodule (k := k) e X = ⊤ at hX
  rw [hX] at hk
  apply FGModuleCat.hom_ext
  ext x
  exact hk (Submodule.mem_top : x ∈ (⊤ : Submodule Aᵐᵒᵖ X))

/-- The module generated by a vector-space set of relations inside Ve. -/
def generatedCoordinateRelations (e : A) (V : FinitelyGeneratedCategory A)
    (R : Submodule k (idempotentCoordinate (k := k) e V)) : Submodule Aᵐᵒᵖ V :=
  Submodule.span Aᵐᵒᵖ ((fun x : idempotentCoordinate (k := k) e V ↦ (x : V)) '' (R : Set _))

/-- A module map killing the coordinate relations kills the generated
relation submodule. -/
theorem generatedCoordinateRelations_le_ker
    (e : A) {V W : FinitelyGeneratedCategory A}
    (R : Submodule k (idempotentCoordinate (k := k) e V)) (f : V ⟶ W)
    (hf : ∀ r : idempotentCoordinate (k := k) e V, r ∈ R → f (r : V) = 0) :
    generatedCoordinateRelations e V R ≤ LinearMap.ker f.hom.hom := by
  apply Submodule.span_le.mpr
  rintro _ ⟨r, hr, rfl⟩
  exact hf r hr

/-- The generated relation submodule, bundled as a finite right module. -/
def generatedCoordinateRelationsFGObj (e : A) (V : FinitelyGeneratedCategory A)
    (R : Submodule k (idempotentCoordinate (k := k) e V)) :
    FinitelyGeneratedCategory A :=
  FGModuleCat.of Aᵐᵒᵖ (generatedCoordinateRelations e V R)

/-- The relation module is itself generated at e, as required for the
Ext-vanishing step of the realization. -/
theorem generatedCoordinateRelations_isGenerated
    {e : A} (he : IsIdempotentElem e) (V : FinitelyGeneratedCategory A)
    (R : Submodule k (idempotentCoordinate (k := k) e V)) :
    IsGeneratedAtIdempotent (k := k) e (generatedCoordinateRelationsFGObj e V R) := by
  let K := generatedCoordinateRelations e V R
  let M := generatedCoordinateRelationsFGObj e V R
  let G := coordinateGeneratedSubmodule (k := k) e M
  have hg : K ≤ G.map K.subtype := by
    apply Submodule.span_le.mpr
    rintro _ ⟨r, hr, rfl⟩
    let rK : K := ⟨r, Submodule.subset_span ⟨r, hr, rfl⟩⟩
    have hcoord : rK ∈ idempotentCoordinate (k := k) e M := by
      refine ⟨rK, ?_⟩
      change (MulOpposite.op e) • rK = rK
      apply Subtype.ext
      exact idempotentCoordinate_fixed he V r
    refine ⟨rK, ?_, rfl⟩
    change (rK : M) ∈ Submodule.span Aᵐᵒᵖ (idempotentCoordinate (k := k) e M : Set M)
    exact Submodule.subset_span hcoord
  change G = ⊤
  apply top_unique
  intro x _
  obtain ⟨y, hy, heq⟩ := hg x.property
  have hyx : y = x := Subtype.ext heq
  rwa [hyx] at hy

end MagnitudeConjecture.RightModule
