import MagnitudeConjecture.Algebra.RepresentationFiniteQuotient
import MagnitudeConjecture.Algebra.RightModuleDirectedCartan
import MagnitudeConjecture.CategoryTheory.AlmostSplitEquivalence
import Mathlib.Algebra.Algebra.Opposite

/-!
# Middle-support quotient algebras

For a basic algebra, choose its complete primitive idempotents in the same
indexing as the indecomposable projective labels of the right-module
skeleton.  The support algebra of a module is the quotient which kills the
sum of the complementary primitive idempotents.  Its module category is the
full exact subcategory of modules supported on the chosen vertices, exactly
as in Appendix A of the frozen manuscript.

The quotient is constructed on the left-module side over `Aᵐᵒᵖ` and then
opposed back to a right-module algebra.  This makes the side convention
literal and avoids identifying the support quotient with the generally
different corner algebra.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits
open scoped BigOperators ModuleCat.Algebra

namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
variable {S : RightModule.FiniteIndecomposableSkeleton k A}

/-- A complete primitive-idempotent presentation indexed by the literal
indecomposable projective labels of `S`.  The last field fixes the indexing:
the right ideal generated by the idempotent at `p` is represented by `p`.
-/
structure PrimitiveProjectivePresentation
    (S : RightModule.FiniteIndecomposableSkeleton k A) where
  idempotent : S.ProjectiveLabel → A
  complete : CompleteOrthogonalIdempotents idempotent
  primitive : ∀ p, RightModule.PrimitiveIdempotentData (idempotent p)
  sourceLabel : ∀ p,
    S.primitiveSourceProjectiveLabel (primitive p) = p

namespace PrimitiveProjectivePresentation

variable (P : S.PrimitiveProjectivePresentation)

/-- The presentation identifies each chosen primitive right ideal with its
literal ambient projective label. -/
def primitiveProjectiveIso (p : S.ProjectiveLabel) :
    RightModule.rightIdealFGObj (P.idempotent p) ≅ S.fgObj p.label :=
  (S.primitiveSourceIso (P.primitive p)).trans <|
    eqToIso (congrArg S.fgObj
      (congrArg ProjectiveLabel.label (P.sourceLabel p)))

/-- The sum of the primitive idempotents outside the projective support of
`X`. -/
def complementaryIdempotent
    (P : S.PrimitiveProjectivePresentation)
    (X : RightModule.FinitelyGeneratedCategory A) : A := by
  classical
  exact ∑ p ∈ Finset.univ.filter
    (fun p ↦ p ∉ S.projectiveSupport X), P.idempotent p

/-- The complementary sum is an idempotent. -/
theorem complementaryIdempotent_isIdempotentElem
    (X : RightModule.FinitelyGeneratedCategory A) :
    IsIdempotentElem (P.complementaryIdempotent X) := by
  classical
  let horth : OrthogonalIdempotents P.idempotent :=
    P.complete.toOrthogonalIdempotents
  simpa only [complementaryIdempotent] using
    (horth.isIdempotentElem_sum
      (s := Finset.univ.filter
        (fun p ↦ p ∉ S.projectiveSupport X)))

/-- A primitive idempotent acts by zero on a module exactly when its
projective label is absent from the module's support. -/
theorem not_mem_projectiveSupport_iff_idempotent_smul_eq_zero
    (p : S.ProjectiveLabel)
    (M : RightModule.FinitelyGeneratedCategory A) :
    p ∉ S.projectiveSupport M ↔
      ∀ m : M, (MulOpposite.op (P.idempotent p)) • m = 0 := by
  let D := P.primitive p
  have hlabel : S.primitiveSourceLabel D = p.label :=
    congrArg ProjectiveLabel.label (P.sourceLabel p)
  constructor
  · intro hp
    have hpHom : Module.finrank k
        (S.fgObj p.label ⟶ M) = 0 := by
      rw [finrank_zero_iff_forall_zero]
      intro f
      by_contra hf
      exact hp ⟨f, hf⟩
    have hsourceHom : Module.finrank k
        (S.fgObj (S.primitiveSourceLabel D) ⟶ M) = 0 := by
      rw [hlabel]
      exact hpHom
    have hcoordinate : Module.finrank k
        (RightModule.idempotentCoordinate (k := k) (P.idempotent p) M) = 0 := by
      rw [← (S.primitiveSourceHomCoordinateEquiv D M).finrank_eq]
      exact hsourceHom
    exact (RightModule.finrank_idempotentCoordinate_eq_zero_iff
      D.idempotent M).1 hcoordinate
  · intro hzero hp
    have hcoordinate : Module.finrank k
        (RightModule.idempotentCoordinate (k := k) (P.idempotent p) M) = 0 :=
      (RightModule.finrank_idempotentCoordinate_eq_zero_iff
        D.idempotent M).2 hzero
    have hsourceHom : Module.finrank k
        (S.fgObj (S.primitiveSourceLabel D) ⟶ M) = 0 := by
      rw [(S.primitiveSourceHomCoordinateEquiv D M).finrank_eq]
      exact hcoordinate
    have hpHom : Module.finrank k (S.fgObj p.label ⟶ M) = 0 := by
      rw [← hlabel]
      exact hsourceHom
    obtain ⟨f, hf⟩ := hp
    exact hf ((finrank_zero_iff_forall_zero.mp hpHom) f)

/-- If the projective support of `M` lies in that of `X`, then the
complementary idempotent of `X` annihilates `M`. -/
theorem complementaryIdempotent_smul_eq_zero_of_support_subset
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) (m : M) :
    (MulOpposite.op (P.complementaryIdempotent X)) • m = 0 := by
  classical
  rw [show MulOpposite.op (P.complementaryIdempotent X) =
      ∑ p ∈ Finset.univ.filter
        (fun p ↦ p ∉ S.projectiveSupport X),
          MulOpposite.op (P.idempotent p) by
    simp [complementaryIdempotent], Finset.sum_smul]
  apply Finset.sum_eq_zero
  intro p hp
  have hpX : p ∉ S.projectiveSupport X := by simpa using hp
  have hpM : p ∉ S.projectiveSupport M := fun hp' ↦ hpX (hsub hp')
  exact (P.not_mem_projectiveSupport_iff_idempotent_smul_eq_zero p M).1
    hpM m

/-- On the left-module side, the support ideal is generated by the opposite
of the complementary idempotent. -/
def supportIdeal
    (P : S.PrimitiveProjectivePresentation)
    (X : RightModule.FinitelyGeneratedCategory A) :
    TwoSidedIdeal Aᵐᵒᵖ :=
  TwoSidedIdeal.span {MulOpposite.op (P.complementaryIdempotent X)}

/-- Every omitted primitive idempotent belongs to the ideal generated by
the complementary idempotent. -/
theorem op_idempotent_mem_supportIdeal_of_not_mem
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : S.ProjectiveLabel) (hp : p ∉ S.projectiveSupport X) :
    MulOpposite.op (P.idempotent p) ∈ P.supportIdeal X := by
  classical
  have hpFilter : p ∈ Finset.univ.filter
      (fun q ↦ q ∉ S.projectiveSupport X) := by
    simp [hp]
  have hmul : P.idempotent p * P.complementaryIdempotent X =
      P.idempotent p := by
    simpa only [complementaryIdempotent] using
      P.complete.toOrthogonalIdempotents.mul_sum_of_mem hpFilter
  have hgenerator : MulOpposite.op (P.complementaryIdempotent X) ∈
      P.supportIdeal X :=
    TwoSidedIdeal.subset_span (Set.mem_singleton _)
  have hproduct := (P.supportIdeal X).mul_mem_right
    (MulOpposite.op (P.complementaryIdempotent X))
    (MulOpposite.op (P.idempotent p)) hgenerator
  rw [← MulOpposite.op_mul, hmul] at hproduct
  exact hproduct

/-- Every module whose support lies in that of `X` is annihilated by the
support ideal. -/
theorem isTorsionBySupportIdeal_of_support_subset
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    Module.IsTorsionBySet Aᵐᵒᵖ M (P.supportIdeal X).asIdeal := by
  have hgenerator : ∀ m : M,
      (MulOpposite.op (P.complementaryIdempotent X)) • m = 0 :=
    P.complementaryIdempotent_smul_eq_zero_of_support_subset X M hsub
  have hAll : ∀ a : Aᵐᵒᵖ, a ∈ P.supportIdeal X →
      ∀ m : M, a • m = 0 := by
    intro a ha
    induction ha using TwoSidedIdeal.span_induction with
    | mem a ha =>
        have hae : a = MulOpposite.op (P.complementaryIdempotent X) :=
          Set.mem_singleton_iff.mp ha
        simpa [hae] using hgenerator
    | zero => intro m; simp
    | add a b _ _ ha hb =>
        intro m
        rw [add_smul, ha m, hb m, add_zero]
    | neg a _ ha =>
        intro m
        rw [neg_smul, ha m, neg_zero]
    | left_absorb b a _ ha =>
        intro m
        rw [mul_smul, ha m, smul_zero]
    | right_absorb b a _ ha =>
        intro m
        rw [mul_smul]
        exact ha (b • m)
  intro m a
  exact hAll a.1 a.2 m

/-- The literal quotient ring whose left modules are the right `A`-modules
supported on `X`. -/
abbrev LeftSupportQuotient
    (P : S.PrimitiveProjectivePresentation)
    (X : RightModule.FinitelyGeneratedCategory A) :=
  Aᵐᵒᵖ ⧸ (P.supportIdeal X).asIdeal

/-- The same support quotient, oriented as a right-module algebra. -/
abbrev SupportAlgebra
    (P : S.PrimitiveProjectivePresentation)
    (X : RightModule.FinitelyGeneratedCategory A) :=
  (P.LeftSupportQuotient X)ᵐᵒᵖ

noncomputable instance leftSupportQuotientModuleFinite
    (X : RightModule.FinitelyGeneratedCategory A) :
    Module.Finite k (P.LeftSupportQuotient X) := by
  infer_instance

noncomputable instance leftSupportQuotientNoetherian
    (X : RightModule.FinitelyGeneratedCategory A) :
    IsNoetherianRing (P.LeftSupportQuotient X) :=
  IsNoetherianRing.of_finite k (P.LeftSupportQuotient X)

noncomputable instance supportAlgebraModuleFinite
    (X : RightModule.FinitelyGeneratedCategory A) :
    Module.Finite k (P.SupportAlgebra X) := by
  infer_instance

noncomputable instance supportAlgebraNoetherian
    (X : RightModule.FinitelyGeneratedCategory A) :
    IsNoetherianRing (P.SupportAlgebra X)ᵐᵒᵖ :=
  IsNoetherianRing.of_finite k (P.SupportAlgebra X)ᵐᵒᵖ

/-- Representation-finiteness descends from the ambient algebra to the
literal support quotient. -/
theorem supportAlgebra_isRepresentationFinite
    (hA : RightModule.IsRepresentationFinite k A)
    (X : RightModule.FinitelyGeneratedCategory A) :
    RightModule.IsRepresentationFinite k (P.SupportAlgebra X) := by
  have hleft : LeftModule.IsRepresentationFinite k Aᵐᵒᵖ := hA
  have hquot : LeftModule.IsRepresentationFinite k
      (P.LeftSupportQuotient X) :=
    LeftModule.IsRepresentationFinite.quotient hleft (P.supportIdeal X)
  change LeftModule.IsRepresentationFinite k
    (P.LeftSupportQuotient X)ᵐᵒᵖᵐᵒᵖ
  exact hquot.of_algEquiv (AlgEquiv.opOp k (P.LeftSupportQuotient X))

/-- The duplicate-free finite indecomposable right-module skeleton of the
support quotient. -/
def supportAlgebraSkeleton
    (hA : RightModule.IsRepresentationFinite k A)
    (X : RightModule.FinitelyGeneratedCategory A) :
    RightModule.FiniteIndecomposableSkeleton k (P.SupportAlgebra X) :=
  Classical.choice
    (RightModule.FiniteIndecomposableSkeleton.exists_of_isRepresentationFinite
      (P.supportAlgebra_isRepresentationFinite hA X))

/-- A supported ambient right module, regarded literally as a left module
over the quotient of `Aᵐᵒᵖ`. -/
def leftSupportObj
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    ModuleCat (P.LeftSupportQuotient X) := by
  let htor := P.isTorsionBySupportIdeal_of_support_subset X M hsub
  letI : Module (P.LeftSupportQuotient X) M := htor.module
  exact ModuleCat.of (P.LeftSupportQuotient X) M

/-- The full subcategory of ambient finitely generated right modules whose
projective support lies in that of `X`. -/
def SupportedOn (X : RightModule.FinitelyGeneratedCategory A) :
    ObjectProperty (RightModule.FinitelyGeneratedCategory A) :=
  fun M ↦ S.projectiveSupport M ⊆ S.projectiveSupport X

/-- The manuscript's full subcategory of modules supported on `X`. -/
abbrev SupportSubcategory (X : RightModule.FinitelyGeneratedCategory A) :=
  (SupportedOn (S := S) X).FullSubcategory

/-- The quotient-module construction does not change the underlying
finite-dimensional `k`-vector space. -/
def leftSupportObjLinearEquiv
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    M ≃ₗ[k] P.leftSupportObj X M hsub := by
  let htor := P.isTorsionBySupportIdeal_of_support_subset X M hsub
  letI : Module (P.LeftSupportQuotient X) M := htor.module
  change M ≃ₗ[k] ModuleCat.of (P.LeftSupportQuotient X) M
  exact {
    toFun := fun m ↦ m
    invFun := fun m ↦ m
    left_inv := fun _ ↦ rfl
    right_inv := fun _ ↦ rfl
    map_add' := fun _ _ ↦ rfl
    map_smul' := by
      intro c m
      change c • m =
        (Ideal.Quotient.mk (P.supportIdeal X).asIdeal
          (algebraMap k Aᵐᵒᵖ c)) • m
      exact (htor.mk_smul (algebraMap k Aᵐᵒᵖ c) m).symm }

/-- Restricting the quotient action recovers the original ambient right
module, by the identity map on its underlying carrier. -/
def leftSupportObjRestrictIso
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    (ModuleCat.restrictScalars
      (Ideal.Quotient.mk (P.supportIdeal X).asIdeal)).obj
        (P.leftSupportObj X M hsub) ≅ M.obj := by
  let htor := P.isTorsionBySupportIdeal_of_support_subset X M hsub
  letI : Module (P.LeftSupportQuotient X) M := htor.module
  change (ModuleCat.restrictScalars
    (Ideal.Quotient.mk (P.supportIdeal X).asIdeal)).obj
      (ModuleCat.of (P.LeftSupportQuotient X) M) ≅ M.obj
  exact LinearEquiv.toModuleIso {
    toFun := fun m ↦ m
    invFun := fun m ↦ m
    left_inv := fun _ ↦ rfl
    right_inv := fun _ ↦ rfl
    map_add' := fun _ _ ↦ rfl
    map_smul' := fun a m ↦ htor.mk_smul a m }

/-- Every ambient morphism between modules supported on `X` is linear over
the support quotient.  This is the fullness part of the manuscript's
"full exact subcategory" assertion. -/
def leftSupportMap
    (X M N : RightModule.FinitelyGeneratedCategory A)
    (hM : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hN : S.projectiveSupport N ⊆ S.projectiveSupport X)
    (f : M ⟶ N) :
    P.leftSupportObj X M hM ⟶ P.leftSupportObj X N hN := by
  let hMtor := P.isTorsionBySupportIdeal_of_support_subset X M hM
  let hNtor := P.isTorsionBySupportIdeal_of_support_subset X N hN
  letI : Module (P.LeftSupportQuotient X) M := hMtor.module
  letI : Module (P.LeftSupportQuotient X) N := hNtor.module
  change ModuleCat.of (P.LeftSupportQuotient X) M ⟶
    ModuleCat.of (P.LeftSupportQuotient X) N
  exact ModuleCat.ofHom {
    toFun := f
    map_add' := f.hom.hom.map_add
    map_smul' := by
      intro b m
      obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective b
      simp only [RingHom.id_apply]
      rw [hNtor.mk_smul]
      exact f.hom.hom.map_smul a m }

@[simp]
theorem leftSupportMap_apply
    (X M N : RightModule.FinitelyGeneratedCategory A)
    (hM : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hN : S.projectiveSupport N ⊆ S.projectiveSupport X)
    (f : M ⟶ N) (m : M) :
    P.leftSupportMap X M N hM hN f m = f m := by
  change f m = f m
  rfl

/-- The quotient object bundled in the finitely generated module category.
Finite generation follows from finite-dimensionality over `k`. -/
def leftSupportFGObj
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    FGModuleCat.{u} (P.LeftSupportQuotient X) := by
  letI : Module.Finite k (P.leftSupportObj X M hsub) := by
    letI : Module.Finite k M :=
      RightModule.finite_over_field_of_finitelyGenerated k A M
    exact Module.Finite.equiv (P.leftSupportObjLinearEquiv X M hsub)
  letI : Module.Finite (P.LeftSupportQuotient X)
      (P.leftSupportObj X M hsub) :=
    Module.Finite.of_restrictScalars_finite k (P.LeftSupportQuotient X)
      (P.leftSupportObj X M hsub)
  exact FGModuleCat.of (P.LeftSupportQuotient X)
    (P.leftSupportObj X M hsub)

/-- Passage from the supported full subcategory to finitely generated
modules over the literal support quotient. -/
def leftSupportFunctor
    (X : RightModule.FinitelyGeneratedCategory A) :
    SupportSubcategory (S := S) X ⥤
      FGModuleCat.{u} (P.LeftSupportQuotient X) where
  obj M := P.leftSupportFGObj X M.obj M.property
  map {M N} f := ObjectProperty.homMk
    (P.leftSupportMap X M.obj N.obj M.property N.property f.hom)
  map_id M := by
    apply FGModuleCat.hom_ext
    ext m
    rfl
  map_comp f g := by
    apply FGModuleCat.hom_ext
    ext m
    rfl

/-- Inflate a finitely generated quotient module to an ambient finitely
generated right `A`-module. -/
def leftSupportInflateFGObj
    (X : RightModule.FinitelyGeneratedCategory A)
    (N : FGModuleCat.{u} (P.LeftSupportQuotient X)) :
    RightModule.FinitelyGeneratedCategory A := by
  let q := Ideal.Quotient.mk (P.supportIdeal X).asIdeal
  let U := (ModuleCat.restrictScalars q).obj N.obj
  letI : Module.Finite k N := Module.Finite.trans
    (P.LeftSupportQuotient X) N
  letI : Module.Finite k U := by
    exact Module.Finite.equiv
      (LeftModule.quotientRestrictLinearEquiv (P.supportIdeal X) N.obj)
  letI : Module.Finite Aᵐᵒᵖ U :=
    Module.Finite.of_restrictScalars_finite k Aᵐᵒᵖ U
  exact ⟨U, show Module.Finite Aᵐᵒᵖ U from inferInstance⟩

/-- Inflation from the support quotient lands in the supported full
subcategory. -/
theorem projectiveSupport_leftSupportInflateFGObj_subset
    (X : RightModule.FinitelyGeneratedCategory A)
    (N : FGModuleCat.{u} (P.LeftSupportQuotient X)) :
    S.projectiveSupport (P.leftSupportInflateFGObj X N) ⊆
      S.projectiveSupport X := by
  intro p hp
  by_contra hpX
  have hzero : ∀ n : N,
      (MulOpposite.op (P.idempotent p)) •
        (show P.leftSupportInflateFGObj X N from n) = 0 := by
    intro n
    change (Ideal.Quotient.mk (P.supportIdeal X).asIdeal
      (MulOpposite.op (P.idempotent p))) • n = 0
    rw [Ideal.Quotient.eq_zero_iff_mem.mpr
      (P.op_idempotent_mem_supportIdeal_of_not_mem X p hpX), zero_smul]
  exact
    ((P.not_mem_projectiveSupport_iff_idempotent_smul_eq_zero p
      (P.leftSupportInflateFGObj X N)).2 hzero) hp

/-- Inflation along the quotient map, with its image bundled in the
supported full subcategory. -/
def leftSupportInflateFunctor
    (X : RightModule.FinitelyGeneratedCategory A) :
    FGModuleCat.{u} (P.LeftSupportQuotient X) ⥤
      SupportSubcategory (S := S) X where
  obj N := ⟨P.leftSupportInflateFGObj X N,
    P.projectiveSupport_leftSupportInflateFGObj_subset X N⟩
  map {M N} f := ObjectProperty.homMk <| ObjectProperty.homMk <|
    (ModuleCat.restrictScalars
      (Ideal.Quotient.mk (P.supportIdeal X).asIdeal)).map f.hom
  map_id M := by
    apply ObjectProperty.hom_ext
    apply ObjectProperty.hom_ext
    rfl
  map_comp f g := by
    apply ObjectProperty.hom_ext
    apply ObjectProperty.hom_ext
    rfl

/-- Restricting a supported quotient object returns its original ambient
module.  This is the unit component of the support equivalence. -/
def leftSupportUnitIsoApp
    (X : RightModule.FinitelyGeneratedCategory A)
    (M : SupportSubcategory (S := S) X) :
    M ≅ (P.leftSupportFunctor X ⋙ P.leftSupportInflateFunctor X).obj M :=
  ObjectProperty.isoMk _ <| ObjectProperty.isoMk _ <|
    (P.leftSupportObjRestrictIso X M.obj M.property).symm

/-- Applying the quotient action to an inflated quotient module returns
the original quotient module. -/
def leftSupportCounitIsoApp
    (X : RightModule.FinitelyGeneratedCategory A)
    (N : FGModuleCat.{u} (P.LeftSupportQuotient X)) :
    (P.leftSupportInflateFunctor X ⋙ P.leftSupportFunctor X).obj N ≅ N := by
  apply ObjectProperty.isoMk
  apply LeftModule.quotientRestrictIso (P.supportIdeal X)
  exact P.leftSupportObjRestrictIso X
    (P.leftSupportInflateFGObj X N)
    (P.projectiveSupport_leftSupportInflateFGObj_subset X N)

/-- Finitely generated modules over the literal support quotient are
equivalent to the full subcategory of ambient modules supported on `X`. -/
def leftSupportEquivalence
    (X : RightModule.FinitelyGeneratedCategory A) :
    SupportSubcategory (S := S) X ≌
      FGModuleCat.{u} (P.LeftSupportQuotient X) where
  functor := P.leftSupportFunctor X
  inverse := P.leftSupportInflateFunctor X
  unitIso := NatIso.ofComponents (P.leftSupportUnitIsoApp X) (by
    intro M N f
    apply ObjectProperty.hom_ext
    apply ObjectProperty.hom_ext
    ext m
    rfl)
  counitIso := NatIso.ofComponents (P.leftSupportCounitIsoApp X) (by
    intro M N f
    apply ObjectProperty.hom_ext
    ext m
    rfl)

/-- The middle term of a chosen nonprojective right almost-split sequence,
as an object of its own supported full subcategory. -/
def rightSequenceMiddleSupportObj
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    SupportSubcategory (S := S)
      (S.minimalRightAlmostSplitAt z.1).middle :=
  ⟨(S.minimalRightAlmostSplitAt z.1).middle, Set.Subset.rfl⟩

/-- The endpoint of the sequence lies in the middle-support subcategory. -/
def rightSequenceTargetSupportObj
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    SupportSubcategory (S := S)
      (S.minimalRightAlmostSplitAt z.1).middle :=
  ⟨S.fgObj z.1, (S.rightSequence_endpointSupport_subset_middle z).2⟩

/-- The chosen right almost-split map, restricted to the full subcategory
supported on its middle term. -/
def rightSequenceSupportMap
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    rightSequenceMiddleSupportObj (S := S) z ⟶
      rightSequenceTargetSupportObj (S := S) z :=
  ObjectProperty.homMk (S.minimalRightAlmostSplitAt z.1).map

/-- Restriction to the middle-support full subcategory preserves the right
almost-split property. -/
theorem rightSequenceSupportMap_isRightAlmostSplit
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightAlmostSplit
      (rightSequenceSupportMap (S := S) z) := by
  let B := S.minimalRightAlmostSplitAt z.1
  constructor
  · intro hs
    apply B.rightAlmostSplit.not_isSplitEpi
    obtain ⟨s⟩ := hs.exists_splitEpi
    exact IsSplitEpi.mk' {
      section_ := s.section_.hom
      id := by
        have hsId := congrArg (fun f ↦ f.hom) s.id
        change s.section_.hom ≫
          (S.minimalRightAlmostSplitAt z.1).map = 𝟙 _ at hsId
        exact hsId }
  · intro Y g hg
    have hgAmbient : ¬ IsSplitEpi g.hom := by
      intro hs
      apply hg
      obtain ⟨s⟩ := hs.exists_splitEpi
      exact IsSplitEpi.mk' {
        section_ := ObjectProperty.homMk s.section_
        id := by
          apply ObjectProperty.hom_ext
          exact s.id }
    obtain ⟨h, hh⟩ := B.rightAlmostSplit.factors g.hom hgAmbient
    refine ⟨ObjectProperty.homMk h, ?_⟩
    apply ObjectProperty.hom_ext
    exact hh

/-- The restricted right almost-split map remains right minimal. -/
theorem rightSequenceSupportMap_isRightMinimal
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightMinimal
      (rightSequenceSupportMap (S := S) z) := by
  intro e he
  have heAmbient : e.hom ≫
      (S.minimalRightAlmostSplitAt z.1).map =
      (S.minimalRightAlmostSplitAt z.1).map := by
    have he' := congrArg (fun f ↦ f.hom) he
    change e.hom ≫ (S.minimalRightAlmostSplitAt z.1).map =
      (S.minimalRightAlmostSplitAt z.1).map at he'
    exact he'
  letI : IsIso e.hom :=
    (S.minimalRightAlmostSplitAt z.1).rightMinimal e.hom heAmbient
  let eIso := ObjectProperty.isoMk
    (SupportedOn (S := S) (S.minimalRightAlmostSplitAt z.1).middle)
    (asIso e.hom)
  have heq : eIso.hom = e := by
    apply ObjectProperty.hom_ext
    rfl
  rw [← heq]
  infer_instance

/-- The supported right almost-split map, transported to finitely generated
modules over the literal quotient of `Aᵐᵒᵖ`. -/
def rightSequenceLeftSupportMap
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :=
  (P.leftSupportEquivalence
      (S.minimalRightAlmostSplitAt z.1).middle).functor.map
    (rightSequenceSupportMap (S := S) z)

/-- The transported quotient map is right almost split. -/
theorem rightSequenceLeftSupportMap_isRightAlmostSplit
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightAlmostSplit
      (P.rightSequenceLeftSupportMap z) :=
  (rightSequenceSupportMap_isRightAlmostSplit (S := S) z).map_equivalence
    (P.leftSupportEquivalence
      (S.minimalRightAlmostSplitAt z.1).middle)

/-- The transported quotient map is right minimal. -/
theorem rightSequenceLeftSupportMap_isRightMinimal
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightMinimal
      (P.rightSequenceLeftSupportMap z) :=
  (rightSequenceSupportMap_isRightMinimal (S := S) z).map_equivalence
    (P.leftSupportEquivalence
      (S.minimalRightAlmostSplitAt z.1).middle)

/-- Reorientation from left modules over the quotient of `Aᵐᵒᵖ` to
right modules over the support algebra. -/
abbrev leftToRightSupportEquivalence
    (X : RightModule.FinitelyGeneratedCategory A) :
    ModuleCat (P.LeftSupportQuotient X) ≌
      RightModule.Category (P.SupportAlgebra X) :=
  LeftModule.moduleEquivalenceOfAlgEquiv
    (AlgEquiv.opOp k (P.LeftSupportQuotient X))

/-- The same reorientation on literal finitely generated module
categories. -/
def leftToRightSupportFGEquivalence
    (X : RightModule.FinitelyGeneratedCategory A) :
    FGModuleCat.{u} (P.LeftSupportQuotient X) ≌
      RightModule.FinitelyGeneratedCategory (P.SupportAlgebra X) :=
  LeftModule.fgModuleEquivalenceOfAlgEquiv
    (AlgEquiv.opOp k (P.LeftSupportQuotient X))

noncomputable instance leftToRightSupportFGEquivalenceFunctorAdditive
    (X : RightModule.FinitelyGeneratedCategory A) :
    (P.leftToRightSupportFGEquivalence X).functor.Additive := by
  dsimp [leftToRightSupportFGEquivalence]
  infer_instance

noncomputable instance leftToRightSupportFGEquivalenceInverseAdditive
    (X : RightModule.FinitelyGeneratedCategory A) :
    (P.leftToRightSupportFGEquivalence X).inverse.Additive := by
  dsimp [leftToRightSupportFGEquivalence]
  infer_instance

/-- The paper's supported full subcategory, identified directly with
finitely generated right modules over the support algebra. -/
def supportEquivalence
    (X : RightModule.FinitelyGeneratedCategory A) :
    SupportSubcategory (S := S) X ≌
      RightModule.FinitelyGeneratedCategory (P.SupportAlgebra X) :=
  (P.leftSupportEquivalence X).trans
    (P.leftToRightSupportFGEquivalence X)

/-- A supported ambient module, bundled as a finitely generated right
module over the support algebra. -/
def supportFGObj
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    RightModule.FinitelyGeneratedCategory (P.SupportAlgebra X) :=
  (P.leftToRightSupportFGEquivalence X).functor.obj
    (P.leftSupportFGObj X M hsub)

/-- An epimorphism in the supported full subcategory is an epimorphism in
the ambient finitely generated module category.  This follows by transporting
it to the literal quotient category, where epimorphisms are the surjective
module maps; the support functor does not change the underlying function. -/
theorem supportSubcategory_epi_ambient
    (P : S.PrimitiveProjectivePresentation)
    (X : RightModule.FinitelyGeneratedCategory A)
    {M N : SupportSubcategory (S := S) X}
    (f : M ⟶ N) [Epi f] : Epi f.hom := by
  apply (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_epi_iff_surjective
    f.hom).2
  haveI : Epi ((P.supportEquivalence X).functor.map f) := inferInstance
  have hsurjective :=
    (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_epi_iff_surjective
      ((P.supportEquivalence X).functor.map f)).1
      inferInstance
  intro y
  obtain ⟨x, hx⟩ := hsurjective y
  exact ⟨x, hx⟩

/-- A projective ambient module supported on `X` remains projective over the
literal support quotient. -/
theorem supportFGObj_projective
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Projective M) :
    Projective (P.supportFGObj X M hsub) := by
  let M' : SupportSubcategory (S := S) X := ⟨M, hsub⟩
  have hM' : Projective M' := by
    constructor
    intro E Y f e _hepi
    letI : Epi e.hom := P.supportSubcategory_epi_ambient X e
    obtain ⟨g, hg⟩ := hM.factors f.hom e.hom
    refine ⟨ObjectProperty.homMk g, ?_⟩
    apply ObjectProperty.hom_ext
    exact hg
  exact (P.supportEquivalence X).map_projective_iff M' |>.2 hM'

/-- The chosen right almost-split map transported all the way to finitely
generated right modules over the support algebra. -/
def rightSequenceSupportAlgebraMap
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :=
  (P.supportEquivalence
      (S.minimalRightAlmostSplitAt z.1).middle).functor.map
    (rightSequenceSupportMap (S := S) z)

/-- The support-algebra map is right almost split. -/
theorem rightSequenceSupportAlgebraMap_isRightAlmostSplit
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightAlmostSplit
      (P.rightSequenceSupportAlgebraMap z) :=
  (rightSequenceSupportMap_isRightAlmostSplit (S := S) z).map_equivalence
    (P.supportEquivalence
      (S.minimalRightAlmostSplitAt z.1).middle)

/-- The support-algebra map is right minimal. -/
theorem rightSequenceSupportAlgebraMap_isRightMinimal
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightMinimal
      (P.rightSequenceSupportAlgebraMap z) :=
  (rightSequenceSupportMap_isRightMinimal (S := S) z).map_equivalence
    (P.supportEquivalence
      (S.minimalRightAlmostSplitAt z.1).middle)

/-- A supported ambient right module, now oriented as a right module over
the support algebra. -/
def supportObj
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    RightModule.Category (P.SupportAlgebra X) :=
  (P.supportFGObj X M hsub).obj

/-- Reorientation likewise preserves the underlying `k`-vector space. -/
def leftSupportObjToSupportObjLinearEquiv
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    P.leftSupportObj X M hsub ≃ₗ[k] P.supportObj X M hsub :=
  LeftModule.moduleEquivalenceOfAlgEquivObjLinearEquiv
    (AlgEquiv.opOp k (P.LeftSupportQuotient X))
    (P.leftSupportObj X M hsub)

/-- A supported ambient finite module remains finite-dimensional over `k`
after passage to the support algebra. -/
theorem supportObj_moduleFinite
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    Module.Finite k (P.supportObj X M hsub) := by
  letI : Module.Finite k M :=
    RightModule.finite_over_field_of_finitelyGenerated k A M
  letI : Module.Finite k (P.leftSupportObj X M hsub) :=
    Module.Finite.equiv (P.leftSupportObjLinearEquiv X M hsub)
  exact Module.Finite.equiv
    (P.leftSupportObjToSupportObjLinearEquiv X M hsub)

/-- If the ambient supported module is indecomposable, so is the quotient
module before reorientation. -/
theorem leftSupportObj_indecomposable
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Indecomposable M.obj) :
    Indecomposable (P.leftSupportObj X M hsub) := by
  let F := ModuleCat.restrictScalars
    (Ideal.Quotient.mk (P.supportIdeal X).asIdeal)
  letI : PreservesBinaryBiproducts F :=
    preservesBinaryBiproducts_of_preservesBinaryProducts F
  constructor
  · intro hzero
    apply hM.1
    exact (P.leftSupportObjRestrictIso X M hsub).isZero_iff.mp
      (F.map_isZero hzero)
  · intro Y Z e
    let e' : M.obj ≅ F.obj Y ⊞ F.obj Z :=
      (P.leftSupportObjRestrictIso X M hsub).symm.trans
        ((F.mapIso e).trans (F.mapBiprod Y Z))
    rcases hM.2 (F.obj Y) (F.obj Z) e' with hY | hZ
    · left
      rw [ModuleCat.isZero_iff_subsingleton] at hY ⊢
      exact hY
    · right
      rw [ModuleCat.isZero_iff_subsingleton] at hZ ⊢
      exact hZ

/-- Indecomposability is also preserved after orienting the quotient object
as a right module over the support algebra. -/
theorem supportObj_indecomposable
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Indecomposable M.obj) :
    Indecomposable (P.supportObj X M hsub) :=
  (LeftModule.indecomposable_functor_obj_iff
    (P.leftToRightSupportEquivalence X)
    (P.leftSupportObj X M hsub)).2
      (P.leftSupportObj_indecomposable X M hsub hM)

/-- The exact finite-indecomposable package needed to select the
corresponding vertex of the support-algebra skeleton. -/
theorem supportObj_isFiniteIndecomposable
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Indecomposable M.obj) :
    RightModule.IsFiniteIndecomposable k (P.SupportAlgebra X)
      (P.supportObj X M hsub) :=
  ⟨P.supportObj_moduleFinite X M hsub,
    P.supportObj_indecomposable X M hsub hM⟩

/-- The chosen label of a supported indecomposable in the duplicate-free
skeleton of the support algebra. -/
def supportLabel
    (hA : RightModule.IsRepresentationFinite k A)
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Indecomposable M.obj) :
    Fin (P.supportAlgebraSkeleton hA X).n :=
  Classical.choose
    ((P.supportAlgebraSkeleton hA X).complete
      (P.supportObj X M hsub)
      (P.supportObj_isFiniteIndecomposable X M hsub hM))

/-- The selected support-algebra label represents the supported module. -/
def supportObjIsoSkeletonObj
    (hA : RightModule.IsRepresentationFinite k A)
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Indecomposable M.obj) :
    P.supportObj X M hsub ≅
      (P.supportAlgebraSkeleton hA X).obj
        (P.supportLabel hA X M hsub hM) :=
  Classical.choice
    (Classical.choose_spec
      ((P.supportAlgebraSkeleton hA X).complete
        (P.supportObj X M hsub)
        (P.supportObj_isFiniteIndecomposable X M hsub hM)))

/-- The selected support-algebra label represents the supported module in the
literal finitely generated category. -/
def supportFGObjIsoSkeletonFG
    (hA : RightModule.IsRepresentationFinite k A)
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Indecomposable M.obj) :
    P.supportFGObj X M hsub ≅
      (P.supportAlgebraSkeleton hA X).fgObj
        (P.supportLabel hA X M hsub hM) :=
  ObjectProperty.isoMk _ <|
    P.supportObjIsoSkeletonObj hA X M hsub hM

/-- Every displayed indecomposable summand of the chosen right
almost-split middle term is supported on that middle term. -/
theorem rightSequenceMiddleSummand_support_subset
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)})
    (t : (S.minimalRightAlmostSplitAt z.1).index) :
    S.projectiveSupport
        (S.fgObj ((S.minimalRightAlmostSplitAt z.1).label t)) ⊆
      S.projectiveSupport (S.minimalRightAlmostSplitAt z.1).middle := by
  intro p hp
  exact (S.mem_projectiveSupport_rightMiddle_iff z.1 p).2 ⟨t, hp⟩

/-- The support-algebra skeleton label representing the endpoint of the
chosen sequence. -/
def rightSequenceSupportTargetLabel
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    Fin (P.supportAlgebraSkeleton hA
      (S.minimalRightAlmostSplitAt z.1).middle).n :=
  P.supportLabel hA (S.minimalRightAlmostSplitAt z.1).middle
    (S.fgObj z.1) (S.rightSequence_endpointSupport_subset_middle z).2
    (S.obj_indecomposable z.1)

/-- The support-algebra skeleton label representing the translated source
of the chosen sequence. -/
def rightSequenceSupportSourceLabel
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    Fin (P.supportAlgebraSkeleton hA
      (S.minimalRightAlmostSplitAt z.1).middle).n :=
  P.supportLabel hA (S.minimalRightAlmostSplitAt z.1).middle
    (S.fgObj (S.rightTranslationLabel z))
    (S.rightSequence_endpointSupport_subset_middle z).1
    (S.obj_indecomposable (S.rightTranslationLabel z))

/-- The support-algebra skeleton label representing a displayed middle
summand. -/
def rightSequenceSupportMiddleLabel
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)})
    (t : (S.minimalRightAlmostSplitAt z.1).index) :
    Fin (P.supportAlgebraSkeleton hA
      (S.minimalRightAlmostSplitAt z.1).middle).n :=
  P.supportLabel hA (S.minimalRightAlmostSplitAt z.1).middle
    (S.fgObj ((S.minimalRightAlmostSplitAt z.1).label t))
    (rightSequenceMiddleSummand_support_subset (S := S) z t)
    (S.obj_indecomposable
      ((S.minimalRightAlmostSplitAt z.1).label t))

/-- The quotient endpoint is the finitely generated skeleton object at its
selected label. -/
def rightSequenceSupportTargetIsoSkeletonFG
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    P.supportFGObj (S.minimalRightAlmostSplitAt z.1).middle
        (S.fgObj z.1) (S.rightSequence_endpointSupport_subset_middle z).2 ≅
      (P.supportAlgebraSkeleton hA
        (S.minimalRightAlmostSplitAt z.1).middle).fgObj
          (P.rightSequenceSupportTargetLabel hA z) :=
  ObjectProperty.isoMk _ <|
    P.supportObjIsoSkeletonObj hA
      (S.minimalRightAlmostSplitAt z.1).middle (S.fgObj z.1)
      (S.rightSequence_endpointSupport_subset_middle z).2
      (S.obj_indecomposable z.1)

/-- The quotient translated source is the finitely generated skeleton
object at its selected label. -/
def rightSequenceSupportSourceIsoSkeletonFG
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    P.supportFGObj (S.minimalRightAlmostSplitAt z.1).middle
        (S.fgObj (S.rightTranslationLabel z))
        (S.rightSequence_endpointSupport_subset_middle z).1 ≅
      (P.supportAlgebraSkeleton hA
        (S.minimalRightAlmostSplitAt z.1).middle).fgObj
          (P.rightSequenceSupportSourceLabel hA z) :=
  ObjectProperty.isoMk _ <|
    P.supportObjIsoSkeletonObj hA
      (S.minimalRightAlmostSplitAt z.1).middle
      (S.fgObj (S.rightTranslationLabel z))
      (S.rightSequence_endpointSupport_subset_middle z).1
      (S.obj_indecomposable (S.rightTranslationLabel z))

/-- Each displayed quotient middle summand is the finitely generated
skeleton object at its selected label. -/
def rightSequenceSupportMiddleIsoSkeletonFG
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)})
    (t : (S.minimalRightAlmostSplitAt z.1).index) :
    P.supportFGObj (S.minimalRightAlmostSplitAt z.1).middle
        (S.fgObj ((S.minimalRightAlmostSplitAt z.1).label t))
        (rightSequenceMiddleSummand_support_subset (S := S) z t) ≅
      (P.supportAlgebraSkeleton hA
        (S.minimalRightAlmostSplitAt z.1).middle).fgObj
          (P.rightSequenceSupportMiddleLabel hA z t) :=
  ObjectProperty.isoMk _ <|
    P.supportObjIsoSkeletonObj hA
      (S.minimalRightAlmostSplitAt z.1).middle
      (S.fgObj ((S.minimalRightAlmostSplitAt z.1).label t))
      (rightSequenceMiddleSummand_support_subset (S := S) z t)
      (S.obj_indecomposable
        ((S.minimalRightAlmostSplitAt z.1).label t))

/-- Postcompose the transported map with the selected endpoint isomorphism,
so that it ends at the literal object of the support-algebra skeleton. -/
def rightSequenceSupportSkeletonMap
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :=
  P.rightSequenceSupportAlgebraMap z ≫
    (P.rightSequenceSupportTargetIsoSkeletonFG hA z).hom

/-- The skeleton-targeted support-algebra map remains right almost split. -/
theorem rightSequenceSupportSkeletonMap_isRightAlmostSplit
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightAlmostSplit
      (P.rightSequenceSupportSkeletonMap hA z) :=
  (P.rightSequenceSupportAlgebraMap_isRightAlmostSplit z).postcomp_iso
    (P.rightSequenceSupportTargetIsoSkeletonFG hA z)

/-- The skeleton-targeted support-algebra map remains right minimal. -/
theorem rightSequenceSupportSkeletonMap_isRightMinimal
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IsRightMinimal
      (P.rightSequenceSupportSkeletonMap hA z) :=
  (P.rightSequenceSupportAlgebraMap_isRightMinimal z).postcomp_iso
    (P.rightSequenceSupportTargetIsoSkeletonFG hA z)

/-- The actual transported sequence, bundled as a minimal right
almost-split decomposition at the selected support-algebra endpoint. -/
def rightSequenceSupportMinimalRightAlmostSplitDecomposition
    (hA : RightModule.IsRepresentationFinite k A)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)}) :
    QuotientSubmoduleEquidistribution.IndecomposableSkeleton.MinimalRightAlmostSplitDecomposition
      (P.supportAlgebraSkeleton hA
        (S.minimalRightAlmostSplitAt z.1).middle).almostSplitSkeleton
      (P.rightSequenceSupportTargetLabel hA z) :=
  QuotientSubmoduleEquidistribution.IndecomposableSkeleton.MinimalRightAlmostSplitDecomposition.ofMap
      (P.supportAlgebraSkeleton hA
        (S.minimalRightAlmostSplitAt z.1).middle).almostSplitSkeleton
      (P.rightSequenceSupportSkeletonMap hA z)
      (RightModule.FiniteIndecomposableSkeleton.fgModule_isFiniteLength
        (k := k) (A := P.SupportAlgebra
          (S.minimalRightAlmostSplitAt z.1).middle) _)
      (P.rightSequenceSupportSkeletonMap_isRightAlmostSplit hA z)
      (P.rightSequenceSupportSkeletonMap_isRightMinimal hA z)

end PrimitiveProjectivePresentation

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
