import MagnitudeConjecture.Algebra.RightModuleGeneratedRelationsQuotient

/-! # Indexed coordinate images under generated-relations quotients -/
set_option autoImplicit false
noncomputable section
open CategoryTheory
open scoped ModuleCat.Algebra
namespace MagnitudeConjecture.RightModule
universe u
variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]

/-- Evaluation at a chosen vector of Qe, with values in Xe. -/
def coordinateEvaluation (e : A) (Q : FinitelyGeneratedCategory A)
    (v : idempotentCoordinate (k := k) e Q) (X : FinitelyGeneratedCategory A) :
    (Q ⟶ X) →ₗ[k] idempotentCoordinate (k := k) e X where
  toFun f := idempotentCoordinateMap e f v
  map_add' f g := by
    apply Subtype.ext
    change (f.hom.hom + g.hom.hom) v.1 = f.hom.hom v.1 + g.hom.hom v.1
    rfl
  map_smul' c f := by
    apply Subtype.ext
    change (c • f.hom.hom) v.1 = c • f.hom.hom v.1
    rfl

/-- Evaluation is precomposition from eA expressed in idempotent coordinates. -/
theorem coordinateEvaluation_eq_precomposition
    {e : A} (he : IsIdempotentElem e)
    (Q X : FinitelyGeneratedCategory A) (u : rightIdealFGObj e ⟶ Q) (f : Q ⟶ X) :
    coordinateEvaluation e Q (rightIdealHomCoordinateEquiv (k := k) he Q u) X f =
      rightIdealHomCoordinateEquiv (k := k) he X (u ≫ f) := by
  rfl

/-- The indexed subspace generated by evaluating maps out of Q at v. -/
def coordinateEvaluationImage (e : A) (Q : FinitelyGeneratedCategory A)
    (v : idempotentCoordinate (k := k) e Q) (X : FinitelyGeneratedCategory A) :
    Submodule k (idempotentCoordinate (k := k) e X) :=
  LinearMap.range (coordinateEvaluation e Q v X)

/-- Evaluation commutes with passage along a module morphism. -/
theorem coordinateEvaluation_comp (e : A) (Q : FinitelyGeneratedCategory A)
    (v : idempotentCoordinate (k := k) e Q)
    {X Y : FinitelyGeneratedCategory A} (f : Q ⟶ X) (q : X ⟶ Y) :
    coordinateEvaluation e Q v Y (f ≫ q) =
      idempotentCoordinateMap e q (coordinateEvaluation e Q v X f) := by
  rfl

/-- Lifting every map from Q identifies its indexed subspace in the target
with the image of the indexed subspace in the source. -/
theorem coordinateEvaluationImage_map_eq_of_lift
    (e : A) (Q : FinitelyGeneratedCategory A)
    (v : idempotentCoordinate (k := k) e Q)
    {X Y : FinitelyGeneratedCategory A} (q : X ⟶ Y)
    (hlift : ∀ f : Q ⟶ Y, ∃ g : Q ⟶ X, g ≫ q = f) :
    (coordinateEvaluationImage e Q v X).map (idempotentCoordinateMap e q) =
      coordinateEvaluationImage e Q v Y := by
  ext y
  constructor
  · rintro ⟨x, ⟨f, rfl⟩, rfl⟩
    exact ⟨f ≫ q, coordinateEvaluation_comp e Q v f q⟩
  · rintro ⟨f, rfl⟩
    obtain ⟨g, rfl⟩ := hlift f
    exact ⟨coordinateEvaluation e Q v X g, ⟨g, rfl⟩,
      (coordinateEvaluation_comp e Q v g q).symm⟩

namespace FiniteIndecomposableSkeleton
variable (S : FiniteIndecomposableSkeleton k A)

/-- The indexed subspace of the actual generated-relations quotient is the
image of the presentation's indexed subspace. -/
theorem generatedRelationsQuotient_coordinateImage
    [HasExt.{u} (FGModuleCat.{u} Aᵐᵒᵖ)]
    {e : A} (D : PrimitiveIdempotentData e)
    (p : S.FactorProjectiveLabel (S.primitiveKilledLabels D))
    (v : idempotentCoordinate (k := k) e (S.fgObj p.1.1))
    (V : FinitelyGeneratedCategory A)
    (R : Submodule k (idempotentCoordinate (k := k) e V)) :
    (coordinateEvaluationImage e (S.fgObj p.1.1) v V).map
      (idempotentCoordinateMap e (quotientFGMap V (generatedCoordinateRelations e V R))) =
    coordinateEvaluationImage e (S.fgObj p.1.1) v
      (quotientFGObj V (generatedCoordinateRelations e V R)) :=
  coordinateEvaluationImage_map_eq_of_lift e _ v _
    (S.generatedRelationsQuotient_hom_lift D p V R)

/-- Under Me≃W, the quotient indexed subspace is exactly π of the
presentation indexed subspace. -/
theorem generatedRelationsQuotient_coordinateImage_target
    [HasExt.{u} (FGModuleCat.{u} Aᵐᵒᵖ)] [IsAlgClosed k]
    (H : S.HasAcyclicNonzeroNonisomorphisms)
    {e : A} (D : PrimitiveIdempotentData e)
    (p : S.FactorProjectiveLabel (S.primitiveKilledLabels D))
    (v : idempotentCoordinate (k := k) e (S.fgObj p.1.1))
    (V : FinitelyGeneratedCategory A)
    {W : Type u} [AddCommGroup W] [Module k W]
    (π : idempotentCoordinate (k := k) e V →ₗ[k] W) (hπ : Function.Surjective π) :
    (coordinateEvaluationImage e (S.fgObj p.1.1) v
      (quotientFGObj V (generatedCoordinateRelations e V (LinearMap.ker π)))).map
      (S.directedGeneratedRelations_coordinateEquivTarget H D V π hπ).toLinearMap =
    (coordinateEvaluationImage e (S.fgObj p.1.1) v V).map π := by
  rw [← S.generatedRelationsQuotient_coordinateImage D p v V (LinearMap.ker π),
    ← Submodule.map_comp]
  congr 1
  ext x
  exact generatedRelations_coordinateEquivTarget_map D.idempotent
    (S.primitive_opposite_corner_scalar H D) V π hπ x

end FiniteIndecomposableSkeleton
end MagnitudeConjecture.RightModule
