import MagnitudeConjecture.Algebra.RightModuleOrdinaryQuiverAdaptedRepresentatives
import MagnitudeConjecture.Algebra.RightModulePrimitiveProjectiveCoordinates
import MagnitudeConjecture.Algebra.UniserialModule
import MagnitudeConjecture.CategoryTheory.LinearPathDecomposition

/-!
# The first Kupisch comparison for ordinary-quiver forks

The two nonzero composites in a right-continuation fork lie in the principal
right ideal generated by the coordinate of their common first arrow.
Uniseriality compares those two elements.  Projecting the resulting scalar to
the appropriate primitive-idempotent corner and transporting it back through
the selected-projective coordinate equivalence gives exactly one of the two
factorizations used in the Skowroński--Waschbüsch correction.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open QuotientSubmoduleEquidistribution.CategoricalIdeal

namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
variable {S : RightModule.FiniteIndecomposableSkeleton k A}

local instance : Quiver S.ProjectiveLabel := S.ordinaryQuiver
local instance (x y : S.ProjectiveLabel) : Fintype (x ⟶ y) :=
  S.ordinaryArrowFintype x y

namespace OrdinaryArrowRepresentatives

/-- If the Hom-space between two selected projectives is uniserial under
postcomposition by endomorphisms of its codomain, then the corresponding
ordinary-quiver vertices support at most one arrow.  Indeed, comparability
would make one arrow representative a postcomposition multiple of the other;
the scalar part survives modulo the radical square while the radical part
does not, contradicting linear independence of distinct arrow classes. -/
theorem eq_of_codomainHom_uniserial [IsAlgClosed k]
    (D : S.OrdinaryArrowRepresentatives)
    {x y : S.ProjectiveLabel}
    (huni : IsUniserialModule
      (End (S.ordinaryProjectiveObj x))
      (S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x))
    (a b : S.OrdinaryArrow x y) :
    a = b := by
  by_contra hab
  let Q := S.projectiveRadicalSquareSubmodule x y
  have hli := D.homModSquare_linearIndependent x y
  rcases huni.smul_comparable (D.hom a) (D.hom b) with habMul | hbaMul
  · obtain ⟨r, hr⟩ := habMul
    change D.hom a ≫ End.asHom r = D.hom b at hr
    obtain ⟨c, hc⟩ :=
      S.exists_scalar_sub_mem_projectiveRadical x (End.asHom r)
    have hsq : D.hom a ≫
        (End.asHom r - c • 𝟙 (S.ordinaryProjectiveObj x)) ∈ Q := by
      change D.hom a ≫
        (End.asHom r - c • 𝟙 (S.ordinaryProjectiveObj x)) ∈
          (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
      rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
        HomIdeal.pow_one]
      exact HomIdeal.comp_mem_mul (D.hom_mem_radical a) hc
    have hzero : Q.mkQ
        (D.hom b - c • D.hom a) = 0 := by
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, ← hr]
      simpa only [Preadditive.comp_sub, Linear.comp_smul,
        Category.comp_id] using hsq
    have hrel : Q.mkQ (D.hom b) = c • Q.mkQ (D.hom a) := by
      rw [Q.mkQ.map_sub, sub_eq_zero] at hzero
      exact hzero
    apply hli.notMem_span b
    rw [hrel]
    exact Submodule.smul_mem _ c (Submodule.subset_span ⟨a, by
      simpa [hab], rfl⟩)
  · obtain ⟨r, hr⟩ := hbaMul
    change D.hom b ≫ End.asHom r = D.hom a at hr
    obtain ⟨c, hc⟩ :=
      S.exists_scalar_sub_mem_projectiveRadical x (End.asHom r)
    have hsq : D.hom b ≫
        (End.asHom r - c • 𝟙 (S.ordinaryProjectiveObj x)) ∈ Q := by
      change D.hom b ≫
        (End.asHom r - c • 𝟙 (S.ordinaryProjectiveObj x)) ∈
          (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
      rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
        HomIdeal.pow_one]
      exact HomIdeal.comp_mem_mul (D.hom_mem_radical b) hc
    have hzero : Q.mkQ
        (D.hom a - c • D.hom b) = 0 := by
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, ← hr]
      simpa only [Preadditive.comp_sub, Linear.comp_smul,
        Category.comp_id] using hsq
    have hrel : Q.mkQ (D.hom a) = c • Q.mkQ (D.hom b) := by
      rw [Q.mkQ.map_sub, sub_eq_zero] at hzero
      exact hzero
    apply hli.notMem_span a
    rw [hrel]
    exact Submodule.smul_mem _ c (Submodule.subset_span ⟨b, by
      simpa only [Set.mem_compl_iff, Set.mem_singleton_iff] using Ne.symm hab, rfl⟩)

/-- The domain-endomorphism analogue of
`eq_of_codomainHom_uniserial`.  Uniseriality for precomposition by the
opposite endomorphism ring also forces uniqueness of an ordinary arrow
between fixed vertices. -/
theorem eq_of_domainHom_uniserial [IsAlgClosed k]
    (D : S.OrdinaryArrowRepresentatives)
    {x y : S.ProjectiveLabel}
    (huni : IsUniserialModule
      (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
      (S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x))
    (a b : S.OrdinaryArrow x y) :
    a = b := by
  by_contra hab
  let Q := S.projectiveRadicalSquareSubmodule x y
  have hli := D.homModSquare_linearIndependent x y
  rcases huni.smul_comparable (D.hom a) (D.hom b) with habMul | hbaMul
  · obtain ⟨r, hr⟩ := habMul
    change End.asHom r.unop ≫ D.hom a = D.hom b at hr
    obtain ⟨c, hc⟩ :=
      S.exists_scalar_sub_mem_projectiveRadical y (End.asHom r.unop)
    have hsq :
        (End.asHom r.unop - c • 𝟙 (S.ordinaryProjectiveObj y)) ≫
          D.hom a ∈ Q := by
      change
        (End.asHom r.unop - c • 𝟙 (S.ordinaryProjectiveObj y)) ≫
          D.hom a ∈
            (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
      rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
        HomIdeal.pow_one]
      exact HomIdeal.comp_mem_mul hc (D.hom_mem_radical a)
    have hzero : Q.mkQ (D.hom b - c • D.hom a) = 0 := by
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, ← hr]
      simpa only [Preadditive.sub_comp, Linear.smul_comp,
        Category.id_comp] using hsq
    have hrel : Q.mkQ (D.hom b) = c • Q.mkQ (D.hom a) := by
      rw [Q.mkQ.map_sub, sub_eq_zero] at hzero
      exact hzero
    apply hli.notMem_span b
    rw [hrel]
    exact Submodule.smul_mem _ c (Submodule.subset_span ⟨a, by
      simpa [hab], rfl⟩)
  · obtain ⟨r, hr⟩ := hbaMul
    change End.asHom r.unop ≫ D.hom b = D.hom a at hr
    obtain ⟨c, hc⟩ :=
      S.exists_scalar_sub_mem_projectiveRadical y (End.asHom r.unop)
    have hsq :
        (End.asHom r.unop - c • 𝟙 (S.ordinaryProjectiveObj y)) ≫
          D.hom b ∈ Q := by
      change
        (End.asHom r.unop - c • 𝟙 (S.ordinaryProjectiveObj y)) ≫
          D.hom b ∈
            (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
      rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
        HomIdeal.pow_one]
      exact HomIdeal.comp_mem_mul hc (D.hom_mem_radical b)
    have hzero : Q.mkQ (D.hom a - c • D.hom b) = 0 := by
      rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, ← hr]
      simpa only [Preadditive.sub_comp, Linear.smul_comp,
        Category.id_comp] using hsq
    have hrel : Q.mkQ (D.hom a) = c • Q.mkQ (D.hom b) := by
      rw [Q.mkQ.map_sub, sub_eq_zero] at hzero
      exact hzero
    apply hli.notMem_span a
    rw [hrel]
    exact Submodule.smul_mem _ c (Submodule.subset_span ⟨b, by
      simpa only [Set.mem_compl_iff, Set.mem_singleton_iff] using Ne.symm hab, rfl⟩)

/-- The two continuation targets are also distinct under Kupisch's literal
left-or-right uniserial alternative. -/
theorem RightContinuationFork.followingTarget_ne_of_uniserialAlternative
    [IsAlgClosed k]
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork)
    (huni : ∀ z : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj F.middleVertex))
          (S.ordinaryProjectiveObj z ⟶
            S.ordinaryProjectiveObj F.middleVertex) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj z))ᵐᵒᵖ
          (S.ordinaryProjectiveObj z ⟶
            S.ordinaryProjectiveObj F.middleVertex)) :
    F.following₁.1.1 ≠ F.following₂.1.1 := by
  intro htarget
  apply F.distinct
  rcases F with
    ⟨start, middle, first, ⟨⟨z₁, b₁⟩, hb₁⟩, ⟨⟨z₂, b₂⟩, hb₂⟩, hdistinct⟩
  simp only at htarget ⊢
  subst z₂
  rcases huni z₁ with hcodomain | hdomain
  · have hb : b₁ = b₂ :=
      D.eq_of_codomainHom_uniserial hcodomain b₁ b₂
    subst b₂
    rfl
  · have hb : b₁ = b₂ :=
      D.eq_of_domainHom_uniserial hdomain b₁ b₂
    subst b₂
    rfl

/-- Once the first Kupisch comparison has produced a radical connector, a
second uniserial comparison produces the radical endomorphism used in the SW
correction.  The opposite comparison order is impossible: it would express
an ordinary-arrow representative as a radical-square morphism. -/
theorem exists_rightFork_secondComparison
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork)
    (connector :
      S.ordinaryProjectiveObj F.following₂.1.1 ⟶
        S.ordinaryProjectiveObj F.following₁.1.1)
    (hconnector : connector ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.following₂.1.1)
        (S.ordinaryProjectiveObj F.following₁.1.1))
    (huni : IsUniserialModule
      (End (S.ordinaryProjectiveObj F.middleVertex))
      (S.ordinaryProjectiveObj F.following₂.1.1 ⟶
        S.ordinaryProjectiveObj F.middleVertex)) :
    ∃ e : S.ordinaryProjectiveObj F.middleVertex ⟶
        S.ordinaryProjectiveObj F.middleVertex,
      e ∈ S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.middleVertex)
          (S.ordinaryProjectiveObj F.middleVertex) ∧
      connector ≫ D.hom F.following₁.1.2 =
        D.hom F.following₂.1.2 ≫ e := by
  have hconnectorComp :
      connector ≫ D.hom F.following₁.1.2 ∈
        S.projectiveRadicalSquareSubmodule
          F.middleVertex F.following₂.1.1 := by
    change connector ≫ D.hom F.following₁.1.2 ∈
      (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
    rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
      HomIdeal.pow_one]
    exact HomIdeal.comp_mem_mul hconnector
      (D.hom_mem_radical F.following₁.1.2)
  rcases huni.smul_comparable
      (connector ≫ D.hom F.following₁.1.2)
      (D.hom F.following₂.1.2) with himpossible | hsurviving
  · obtain ⟨r, hr⟩ := himpossible
    change (connector ≫ D.hom F.following₁.1.2) ≫ End.asHom r =
      D.hom F.following₂.1.2 at hr
    exfalso
    apply D.hom_not_mem_radicalSquare F.following₂.1.2
    rw [← hr]
    exact (S.projectiveNilpotentRadicalData.ideal.pow 2).postcomp
      (End.asHom r) hconnectorComp
  · obtain ⟨r, hr⟩ := hsurviving
    change D.hom F.following₂.1.2 ≫ End.asHom r =
      connector ≫ D.hom F.following₁.1.2 at hr
    refine ⟨End.asHom r, ?_, hr.symm⟩
    apply D.codomainEndomorphism_mem_radical_of_comp_mem_radicalSquare
      F.following₂.1.2
    rw [hr]
    exact hconnectorComp

/-- The domain-uniserial alternative in Kupisch condition (K)(2) is
incompatible with the already obtained first comparison.  Comparability
would either put an ordinary arrow in the radical square, or make the
original nonzero two-arrow composite fixed by a radical endomorphism.  The
latter is impossible because one minus a nilpotent is invertible. -/
theorem false_of_rightFork_firstComparison_of_domainHom_uniserial
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork)
    (connector :
      S.ordinaryProjectiveObj F.following₂.1.1 ⟶
        S.ordinaryProjectiveObj F.following₁.1.1)
    (hconnector : connector ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.following₂.1.1)
        (S.ordinaryProjectiveObj F.following₁.1.1))
    (hfirst :
      D.hom F.following₂.1.2 ≫ D.hom F.first =
        connector ≫ D.hom F.following₁.1.2 ≫ D.hom F.first)
    (huni : IsUniserialModule
      (End (S.ordinaryProjectiveObj F.following₂.1.1))ᵐᵒᵖ
      (S.ordinaryProjectiveObj F.following₂.1.1 ⟶
        S.ordinaryProjectiveObj F.middleVertex)) :
    False := by
  have hconnectorComp :
      connector ≫ D.hom F.following₁.1.2 ∈
        S.projectiveRadicalSquareSubmodule
          F.middleVertex F.following₂.1.1 := by
    change connector ≫ D.hom F.following₁.1.2 ∈
      (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
    rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
      HomIdeal.pow_one]
    exact HomIdeal.comp_mem_mul hconnector
      (D.hom_mem_radical F.following₁.1.2)
  rcases huni.smul_comparable
      (connector ≫ D.hom F.following₁.1.2)
      (D.hom F.following₂.1.2) with himpossible | hsurviving
  · obtain ⟨r, hr⟩ := himpossible
    change End.asHom r.unop ≫
        (connector ≫ D.hom F.following₁.1.2) =
      D.hom F.following₂.1.2 at hr
    exfalso
    apply D.hom_not_mem_radicalSquare F.following₂.1.2
    rw [← hr]
    exact (S.projectiveNilpotentRadicalData.ideal.pow 2).precomp
      (End.asHom r.unop) hconnectorComp
  · obtain ⟨r, hr⟩ := hsurviving
    change End.asHom r.unop ≫ D.hom F.following₂.1.2 =
      connector ≫ D.hom F.following₁.1.2 at hr
    have hrRadical : End.asHom r.unop ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.following₂.1.1)
          (S.ordinaryProjectiveObj F.following₂.1.1) := by
      apply D.domainEndomorphism_mem_radical_of_comp_mem_radicalSquare
        F.following₂.1.2
      rw [hr]
      exact hconnectorComp
    have hfixed :
        D.hom F.following₂.1.2 ≫ D.hom F.first =
          End.asHom r.unop ≫
            (D.hom F.following₂.1.2 ≫ D.hom F.first) := by
      calc
        D.hom F.following₂.1.2 ≫ D.hom F.first =
            connector ≫ D.hom F.following₁.1.2 ≫ D.hom F.first :=
          hfirst
        _ = (connector ≫ D.hom F.following₁.1.2) ≫
            D.hom F.first := (Category.assoc _ _ _).symm
        _ = (End.asHom r.unop ≫
            D.hom F.following₂.1.2) ≫ D.hom F.first := by
          rw [hr]
        _ = End.asHom r.unop ≫
            (D.hom F.following₂.1.2 ≫ D.hom F.first) := by
          simp only [Category.assoc]
    have hnilpotent :=
      S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal
        hrRadical
    have hunit : IsUnit (1 - End.of (End.asHom r.unop)) :=
      hnilpotent.isUnit_one_sub
    let u : End (S.ordinaryProjectiveObj F.following₂.1.1) :=
      1 - End.of (End.asHom r.unop)
    letI : IsIso (End.asHom u) :=
      (CategoryTheory.isUnit_iff_isIso u).mp hunit
    have hcompZero :
        End.asHom u ≫
          (D.hom F.following₂.1.2 ≫ D.hom F.first) = 0 := by
      dsimp only [u]
      change
        ((𝟙 (S.ordinaryProjectiveObj F.following₂.1.1) -
            End.asHom r.unop) ≫ D.hom F.following₂.1.2) ≫
          D.hom F.first = 0
      rw [Preadditive.sub_comp, Category.id_comp,
        Preadditive.sub_comp]
      exact sub_eq_zero.mpr hfixed
    have hzeroOriginal :
        D.hom F.following₂.1.2 ≫ D.hom F.first = 0 := by
      apply (cancel_epi (End.asHom u)).1
      simpa using hcompZero
    exact F.following₂.2 hzeroOriginal

/-- Kupisch's literal left-or-right alternative gives the radical corner
comparison: the codomain-uniserial branch constructs it, while the
domain-uniserial branch is excluded by the first comparison and nilpotence. -/
theorem exists_rightFork_secondComparison_of_uniserialAlternative
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork)
    (connector :
      S.ordinaryProjectiveObj F.following₂.1.1 ⟶
        S.ordinaryProjectiveObj F.following₁.1.1)
    (hconnector : connector ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.following₂.1.1)
        (S.ordinaryProjectiveObj F.following₁.1.1))
    (hfirst :
      D.hom F.following₂.1.2 ≫ D.hom F.first =
        connector ≫ D.hom F.following₁.1.2 ≫ D.hom F.first)
    (huni :
      IsUniserialModule
          (End (S.ordinaryProjectiveObj F.middleVertex))
          (S.ordinaryProjectiveObj F.following₂.1.1 ⟶
            S.ordinaryProjectiveObj F.middleVertex) ∨
        IsUniserialModule
          (End (S.ordinaryProjectiveObj F.following₂.1.1))ᵐᵒᵖ
          (S.ordinaryProjectiveObj F.following₂.1.1 ⟶
            S.ordinaryProjectiveObj F.middleVertex)) :
    ∃ e : S.ordinaryProjectiveObj F.middleVertex ⟶
        S.ordinaryProjectiveObj F.middleVertex,
      e ∈ S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.middleVertex)
          (S.ordinaryProjectiveObj F.middleVertex) ∧
      connector ≫ D.hom F.following₁.1.2 =
        D.hom F.following₂.1.2 ≫ e := by
  rcases huni with hcodomain | hdomain
  · exact D.exists_rightFork_secondComparison F connector hconnector
      hcodomain
  · exact False.elim
      (D.false_of_rightFork_firstComparison_of_domainHom_uniserial
        F connector hconnector hfirst hdomain)

/-- The two predecessor sources in a left fork are distinct under Kupisch's
literal left-or-right uniserial alternative. -/
theorem LeftContinuationFork.precedingSource_ne_of_uniserialAlternative
    [IsAlgClosed k]
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork)
    (huni : ∀ z : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj z))
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj z) ∨
        IsUniserialModule
          (End (S.ordinaryProjectiveObj F.middleVertex))ᵐᵒᵖ
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj z)) :
    F.preceding₁.1.1 ≠ F.preceding₂.1.1 := by
  intro hsource
  apply F.distinct
  rcases F with
    ⟨middle, target, second, ⟨⟨z₁, c₁⟩, hc₁⟩, ⟨⟨z₂, c₂⟩, hc₂⟩, hdistinct⟩
  simp only at hsource ⊢
  subst z₂
  rcases huni z₁ with hcodomain | hdomain
  · have hc : c₁ = c₂ :=
      D.eq_of_codomainHom_uniserial hcodomain c₁ c₂
    subst c₂
    rfl
  · have hc : c₁ = c₂ :=
      D.eq_of_domainHom_uniserial hdomain c₁ c₂
    subst c₂
    rfl

/-- Once the first left Kupisch comparison has produced a radical connector,
domain-Hom uniseriality produces the radical middle endomorphism used in the
symmetric SW correction. -/
theorem exists_leftFork_secondComparison
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork)
    (connector :
      S.ordinaryProjectiveObj F.preceding₁.1.1 ⟶
        S.ordinaryProjectiveObj F.preceding₂.1.1)
    (hconnector : connector ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.preceding₁.1.1)
        (S.ordinaryProjectiveObj F.preceding₂.1.1))
    (huni : IsUniserialModule
      (End (S.ordinaryProjectiveObj F.middleVertex))ᵐᵒᵖ
      (S.ordinaryProjectiveObj F.middleVertex ⟶
        S.ordinaryProjectiveObj F.preceding₂.1.1)) :
    ∃ e : S.ordinaryProjectiveObj F.middleVertex ⟶
        S.ordinaryProjectiveObj F.middleVertex,
      e ∈ S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.middleVertex)
          (S.ordinaryProjectiveObj F.middleVertex) ∧
      D.hom F.preceding₁.1.2 ≫ connector =
        e ≫ D.hom F.preceding₂.1.2 := by
  have hconnectorComp :
      D.hom F.preceding₁.1.2 ≫ connector ∈
        S.projectiveRadicalSquareSubmodule
          F.preceding₂.1.1 F.middleVertex := by
    change D.hom F.preceding₁.1.2 ≫ connector ∈
      (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
    rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
      HomIdeal.pow_one]
    exact HomIdeal.comp_mem_mul
      (D.hom_mem_radical F.preceding₁.1.2) hconnector
  rcases huni.smul_comparable
      (D.hom F.preceding₁.1.2 ≫ connector)
      (D.hom F.preceding₂.1.2) with himpossible | hsurviving
  · obtain ⟨r, hr⟩ := himpossible
    change End.asHom r.unop ≫
        (D.hom F.preceding₁.1.2 ≫ connector) =
      D.hom F.preceding₂.1.2 at hr
    exfalso
    apply D.hom_not_mem_radicalSquare F.preceding₂.1.2
    rw [← hr]
    exact (S.projectiveNilpotentRadicalData.ideal.pow 2).precomp
      (End.asHom r.unop) hconnectorComp
  · obtain ⟨r, hr⟩ := hsurviving
    change End.asHom r.unop ≫ D.hom F.preceding₂.1.2 =
      D.hom F.preceding₁.1.2 ≫ connector at hr
    refine ⟨End.asHom r.unop, ?_, hr.symm⟩
    apply D.domainEndomorphism_mem_radical_of_comp_mem_radicalSquare
      F.preceding₂.1.2
    rw [hr]
    exact hconnectorComp

/-- The codomain-uniserial alternative in Kupisch condition (K)(2) is
incompatible with an already obtained first left comparison. -/
theorem false_of_leftFork_firstComparison_of_codomainHom_uniserial
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork)
    (connector :
      S.ordinaryProjectiveObj F.preceding₁.1.1 ⟶
        S.ordinaryProjectiveObj F.preceding₂.1.1)
    (hconnector : connector ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.preceding₁.1.1)
        (S.ordinaryProjectiveObj F.preceding₂.1.1))
    (hfirst :
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
        D.hom F.second ≫ D.hom F.preceding₁.1.2 ≫ connector)
    (huni : IsUniserialModule
      (End (S.ordinaryProjectiveObj F.preceding₂.1.1))
      (S.ordinaryProjectiveObj F.middleVertex ⟶
        S.ordinaryProjectiveObj F.preceding₂.1.1)) :
    False := by
  have hconnectorComp :
      D.hom F.preceding₁.1.2 ≫ connector ∈
        S.projectiveRadicalSquareSubmodule
          F.preceding₂.1.1 F.middleVertex := by
    change D.hom F.preceding₁.1.2 ≫ connector ∈
      (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
    rw [show 2 = 1 + 1 by omega, HomIdeal.pow_add,
      HomIdeal.pow_one]
    exact HomIdeal.comp_mem_mul
      (D.hom_mem_radical F.preceding₁.1.2) hconnector
  rcases huni.smul_comparable
      (D.hom F.preceding₁.1.2 ≫ connector)
      (D.hom F.preceding₂.1.2) with himpossible | hsurviving
  · obtain ⟨r, hr⟩ := himpossible
    change (D.hom F.preceding₁.1.2 ≫ connector) ≫
        End.asHom r = D.hom F.preceding₂.1.2 at hr
    exfalso
    apply D.hom_not_mem_radicalSquare F.preceding₂.1.2
    rw [← hr]
    exact (S.projectiveNilpotentRadicalData.ideal.pow 2).postcomp
      (End.asHom r) hconnectorComp
  · obtain ⟨r, hr⟩ := hsurviving
    change D.hom F.preceding₂.1.2 ≫ End.asHom r =
      D.hom F.preceding₁.1.2 ≫ connector at hr
    have hrRadical : End.asHom r ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.preceding₂.1.1)
          (S.ordinaryProjectiveObj F.preceding₂.1.1) := by
      apply D.codomainEndomorphism_mem_radical_of_comp_mem_radicalSquare
        F.preceding₂.1.2
      rw [hr]
      exact hconnectorComp
    have hfixed :
        D.hom F.second ≫ D.hom F.preceding₂.1.2 =
          (D.hom F.second ≫ D.hom F.preceding₂.1.2) ≫
            End.asHom r := by
      calc
        D.hom F.second ≫ D.hom F.preceding₂.1.2 =
            D.hom F.second ≫ D.hom F.preceding₁.1.2 ≫
              connector := hfirst
        _ = D.hom F.second ≫
            (D.hom F.preceding₁.1.2 ≫ connector) := rfl
        _ = D.hom F.second ≫
            (D.hom F.preceding₂.1.2 ≫ End.asHom r) := by
          rw [hr]
        _ = (D.hom F.second ≫ D.hom F.preceding₂.1.2) ≫
            End.asHom r := (Category.assoc _ _ _).symm
    have hnilpotent :=
      S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal
        hrRadical
    have hunit : IsUnit (1 - End.of (End.asHom r)) :=
      hnilpotent.isUnit_one_sub
    let u : End (S.ordinaryProjectiveObj F.preceding₂.1.1) :=
      1 - End.of (End.asHom r)
    letI : IsIso (End.asHom u) :=
      (CategoryTheory.isUnit_iff_isIso u).mp hunit
    have hcompZero :
        (D.hom F.second ≫ D.hom F.preceding₂.1.2) ≫
          End.asHom u = 0 := by
      dsimp only [u]
      change
        D.hom F.second ≫ D.hom F.preceding₂.1.2 ≫
          (𝟙 (S.ordinaryProjectiveObj F.preceding₂.1.1) -
            End.asHom r) = 0
      rw [Preadditive.comp_sub, Category.comp_id]
      exact sub_eq_zero.mpr hfixed
    have hzeroOriginal :
        D.hom F.second ≫ D.hom F.preceding₂.1.2 = 0 := by
      apply (cancel_mono (End.asHom u)).1
      simpa using hcompZero
    exact F.preceding₂.2 hzeroOriginal

/-- Kupisch's literal alternative gives the radical middle endomorphism for
the left correction: the domain branch constructs it, while the codomain
branch is excluded by the first comparison and nilpotence. -/
theorem exists_leftFork_secondComparison_of_uniserialAlternative
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork)
    (connector :
      S.ordinaryProjectiveObj F.preceding₁.1.1 ⟶
        S.ordinaryProjectiveObj F.preceding₂.1.1)
    (hconnector : connector ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.preceding₁.1.1)
        (S.ordinaryProjectiveObj F.preceding₂.1.1))
    (hfirst :
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
        D.hom F.second ≫ D.hom F.preceding₁.1.2 ≫ connector)
    (huni :
      IsUniserialModule
          (End (S.ordinaryProjectiveObj F.preceding₂.1.1))
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj F.preceding₂.1.1) ∨
        IsUniserialModule
          (End (S.ordinaryProjectiveObj F.middleVertex))ᵐᵒᵖ
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj F.preceding₂.1.1)) :
    ∃ e : S.ordinaryProjectiveObj F.middleVertex ⟶
        S.ordinaryProjectiveObj F.middleVertex,
      e ∈ S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.middleVertex)
          (S.ordinaryProjectiveObj F.middleVertex) ∧
      D.hom F.preceding₁.1.2 ≫ connector =
        e ≫ D.hom F.preceding₂.1.2 := by
  rcases huni with hcodomain | hdomain
  · exact False.elim
      (D.false_of_leftFork_firstComparison_of_codomainHom_uniserial
        F connector hconnector hfirst hcodomain)
  · exact D.exists_leftFork_secondComparison F connector hconnector
      hdomain

/-- Every radical endomorphism of a selected projective is a finite sum of
maps which first follow an ordinary arrow out of that projective.  Fullness
gives a free-path preimage; the only possible length-zero term is a scalar
identity, and nilpotence of the projective radical forces that scalar to
vanish. -/
theorem exists_eq_outgoing_sum_of_mem_projectiveRadical [IsAlgClosed k]
    (D : S.OrdinaryArrowRepresentatives)
    (x : S.ProjectiveLabel)
    (e : S.ordinaryProjectiveObj x ⟶ S.ordinaryProjectiveObj x)
    (he : e ∈ S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x)) :
    ∃ h : ∀ a : Quiver.Costar x,
        S.ordinaryProjectiveObj a.1 ⟶ S.ordinaryProjectiveObj x,
      e = ∑ a : Quiver.Costar x, D.hom a.2 ≫ h a := by
  classical
  obtain ⟨q, hq⟩ := D.exists_realization_preimage e
  obtain ⟨r, c, hc⟩ :=
    LinearPathCategory.exists_eq_smul_id_add_outgoingSum q
  let h : ∀ a : Quiver.Costar x,
      S.ordinaryProjectiveObj a.1 ⟶ S.ordinaryProjectiveObj x :=
    fun a ↦ D.realization.map (c a)
  have houtgoing :
      D.realization.map (LinearPathCategory.outgoingSum c) =
        ∑ a : Quiver.Costar x, D.hom a.2 ≫ h a := by
    change
      (LinearPathCategory.lift S.ordinaryProjectiveObj
        (fun {_ _} (a : S.OrdinaryArrow _ _) ↦ D.hom a)).map
          (LinearPathCategory.outgoingSum c) = _
    exact LinearPathCategory.lift_map_outgoingSum
      S.ordinaryProjectiveObj
      (fun {_ _} (a : S.OrdinaryArrow _ _) ↦ D.hom a) c
  have heq : e = r • 𝟙 (S.ordinaryProjectiveObj x) +
      ∑ a : Quiver.Costar x, D.hom a.2 ≫ h a := by
    rw [← hq, hc, D.realization.map_add, Functor.map_smul,
      D.realization.map_id, houtgoing]
    change r • 𝟙 (S.ordinaryProjectiveObj x) +
      ∑ a : Quiver.Costar x, D.hom a.2 ≫ h a = _
    rfl
  have hsumRadical :
      (∑ a : Quiver.Costar x, D.hom a.2 ≫ h a) ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x) := by
    apply (S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj x)
      (S.ordinaryProjectiveObj x)).sum_mem
    intro a _
    exact S.projectiveNilpotentRadicalData.ideal.postcomp
      (h a) (D.hom_mem_radical a.2)
  have hscalarRadical : r • 𝟙 (S.ordinaryProjectiveObj x) ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x) := by
    have hsub := AddSubgroup.sub_mem
      (S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x))
      he hsumRadical
    rw [heq] at hsub
    simpa using hsub
  have hr : r = 0 := by
    by_contra hr
    have hradicalAmbient :
        QuotientSubmoduleEquidistribution.CategoricalRadical.IsRadicalMorphism
          (S.projectiveInclusion.map
            (r • 𝟙 (S.ordinaryProjectiveObj x))) :=
      (S.fgNilpotentRadicalData.mem_ideal_iff _).1 hscalarRadical
    letI : IsLocalRing (End (S.fgObj x.label)) :=
      S.fgObj_end_isLocalRing x.label
    have hnot : ¬ IsSplitEpi
        (S.projectiveInclusion.map
          (r • 𝟙 (S.ordinaryProjectiveObj x))) :=
      (MagnitudeConjecture.CategoryTheory.isRadicalMorphism_iff_not_isSplitEpi_of_local_end
        (S.fgObj_indecomposable x.label).1 _).1 hradicalAmbient
    apply hnot
    rw [Functor.map_smul, S.projectiveInclusion.map_id]
    exact MagnitudeConjecture.isSplitEpi_smul_id_of_ne_zero
      (S.fgObj x.label) hr
  refine ⟨h, ?_⟩
  rw [heq, hr, zero_smul, zero_add]

/-- Dually, every radical endomorphism of a selected projective is a finite
sum of maps which end with an ordinary arrow into that projective. -/
theorem exists_eq_incoming_sum_of_mem_projectiveRadical [IsAlgClosed k]
    (D : S.OrdinaryArrowRepresentatives)
    (x : S.ProjectiveLabel)
    (e : S.ordinaryProjectiveObj x ⟶ S.ordinaryProjectiveObj x)
    (he : e ∈ S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x)) :
    ∃ h : ∀ a : Quiver.Star x,
        S.ordinaryProjectiveObj x ⟶ S.ordinaryProjectiveObj a.1,
      e = ∑ a : Quiver.Star x, h a ≫ D.hom a.2 := by
  classical
  obtain ⟨q, hq⟩ := D.exists_realization_preimage e
  obtain ⟨r, c, hc⟩ :=
    LinearPathCategory.exists_eq_smul_id_add_incomingSum q
  let h : ∀ a : Quiver.Star x,
      S.ordinaryProjectiveObj x ⟶ S.ordinaryProjectiveObj a.1 :=
    fun a ↦ D.realization.map (c a)
  have hincoming :
      D.realization.map (LinearPathCategory.incomingSum c) =
        ∑ a : Quiver.Star x, h a ≫ D.hom a.2 := by
    rw [LinearPathCategory.incomingSum, D.realization.map_sum]
    apply Finset.sum_congr rfl
    intro a _
    rw [Functor.map_comp]
    dsimp only [h]
    rw [D.realization_map_pathHom]
    change D.realization.map (c a) ≫
        LinearPathCategory.pathMap S.ordinaryProjectiveObj
          (fun {_ _} (b : S.OrdinaryArrow _ _) ↦ D.hom b)
          a.2.toPath =
      D.realization.map (c a) ≫ D.hom a.2
    have ha :
        LinearPathCategory.pathMap S.ordinaryProjectiveObj
            (fun {_ _} (b : S.OrdinaryArrow _ _) ↦ D.hom b)
            a.2.toPath =
          D.hom a.2 :=
      LinearPathCategory.pathMap_toPath S.ordinaryProjectiveObj
        (fun {_ _} (b : S.OrdinaryArrow _ _) ↦ D.hom b) a.2
    exact congrArg (fun f ↦ D.realization.map (c a) ≫ f) ha
  have heq : e = r • 𝟙 (S.ordinaryProjectiveObj x) +
      ∑ a : Quiver.Star x, h a ≫ D.hom a.2 := by
    rw [← hq, hc, D.realization.map_add, Functor.map_smul,
      D.realization.map_id, hincoming]
    change r • 𝟙 (S.ordinaryProjectiveObj x) +
      ∑ a : Quiver.Star x, h a ≫ D.hom a.2 = _
    rfl
  have hsumRadical :
      (∑ a : Quiver.Star x, h a ≫ D.hom a.2) ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x) := by
    apply (S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj x)
      (S.ordinaryProjectiveObj x)).sum_mem
    intro a _
    exact S.projectiveNilpotentRadicalData.ideal.precomp
      (h a) (D.hom_mem_radical a.2)
  have hscalarRadical : r • 𝟙 (S.ordinaryProjectiveObj x) ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x) := by
    have hsub := AddSubgroup.sub_mem
      (S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x))
      he hsumRadical
    rw [heq] at hsub
    simpa using hsub
  have hr : r = 0 := by
    by_contra hr
    have hradicalAmbient :
        QuotientSubmoduleEquidistribution.CategoricalRadical.IsRadicalMorphism
          (S.projectiveInclusion.map
            (r • 𝟙 (S.ordinaryProjectiveObj x))) :=
      (S.fgNilpotentRadicalData.mem_ideal_iff _).1 hscalarRadical
    letI : IsLocalRing (End (S.fgObj x.label)) :=
      S.fgObj_end_isLocalRing x.label
    have hnot : ¬ IsSplitEpi
        (S.projectiveInclusion.map
          (r • 𝟙 (S.ordinaryProjectiveObj x))) :=
      (MagnitudeConjecture.CategoryTheory.isRadicalMorphism_iff_not_isSplitEpi_of_local_end
        (S.fgObj_indecomposable x.label).1 _).1 hradicalAmbient
    apply hnot
    rw [Functor.map_smul, S.projectiveInclusion.map_id]
    exact MagnitudeConjecture.isSplitEpi_smul_id_of_ne_zero
      (S.fgObj x.label) hr
  refine ⟨h, ?_⟩
  rw [heq, hr, zero_smul, zero_add]

end OrdinaryArrowRepresentatives

/-- The two source-faithful Kupisch comparisons attached to one chosen
ordering of a right fork.  This is the algebraic core of the local SW
correction, before extracting the second incoming arrow required by the
zero-monotonicity argument. -/
structure RightKupischComparisonData
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork) where
  connector :
    S.ordinaryProjectiveObj F.following₂.1.1 ⟶
      S.ordinaryProjectiveObj F.following₁.1.1
  connector_mem_radical : connector ∈
    S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj F.following₂.1.1)
      (S.ordinaryProjectiveObj F.following₁.1.1)
  firstComparison :
    D.hom F.following₂.1.2 ≫ D.hom F.first =
      connector ≫ D.hom F.following₁.1.2 ≫ D.hom F.first
  cornerEndomorphism :
    S.ordinaryProjectiveObj F.middleVertex ⟶
      S.ordinaryProjectiveObj F.middleVertex
  cornerEndomorphism_mem_radical : cornerEndomorphism ∈
    S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj F.middleVertex)
      (S.ordinaryProjectiveObj F.middleVertex)
  secondComparison :
    connector ≫ D.hom F.following₁.1.2 =
      D.hom F.following₂.1.2 ≫ cornerEndomorphism

namespace RightKupischComparisonData

/-- The codomain correction supplied by the two Kupisch comparisons kills
the selected composite.  The proof also covers the loop case in which the
changed continuation is itself the common first arrow, so both occurrences
are perturbed. -/
theorem kills
    {D : S.OrdinaryArrowRepresentatives}
    {F : D.RightContinuationFork}
    (C : RightKupischComparisonData D F) :
    (D.perturbAt F.changedArrow
      (D.codomainCorrection F.changedArrow C.cornerEndomorphism
        C.cornerEndomorphism_mem_radical)).twoStepComposite
          F.killedTwoStep = 0 := by
  have hrelation :
      D.hom F.following₂.1.2 ≫ D.hom F.first =
        (D.hom F.following₂.1.2 ≫ C.cornerEndomorphism) ≫
          D.hom F.first := by
    calc
      D.hom F.following₂.1.2 ≫ D.hom F.first =
          C.connector ≫ D.hom F.following₁.1.2 ≫ D.hom F.first :=
        C.firstComparison
      _ = (D.hom F.following₂.1.2 ≫ C.cornerEndomorphism) ≫
          D.hom F.first := by
        rw [← Category.assoc, C.secondComparison]
  change
    (D.perturbAt
        ⟨F.middleVertex, F.following₂.1.1, F.following₂.1.2⟩
        (D.codomainCorrection
          ⟨F.middleVertex, F.following₂.1.1, F.following₂.1.2⟩
          C.cornerEndomorphism C.cornerEndomorphism_mem_radical)).hom
          F.following₂.1.2 ≫
      (D.perturbAt
        ⟨F.middleVertex, F.following₂.1.1, F.following₂.1.2⟩
        (D.codomainCorrection
          ⟨F.middleVertex, F.following₂.1.1, F.following₂.1.2⟩
          C.cornerEndomorphism C.cornerEndomorphism_mem_radical)).hom
          F.first = 0
  by_cases hfirst :
      (⟨F.startVertex, F.middleVertex, F.first⟩ :
        S.OrdinaryArrowTotal) = F.changedArrow
  · rcases F with
      ⟨start, middle, first, ⟨⟨z₁, b⟩, hb⟩, ⟨⟨z₂, g⟩, hg⟩, hdistinct⟩
    simp only [OrdinaryArrowRepresentatives.RightContinuationFork.changedArrow]
      at hfirst hrelation ⊢
    cases hfirst
    have hpost := congrArg
      (fun f ↦ f ≫ C.cornerEndomorphism) hrelation
    simp only [Category.assoc] at hpost
    rw [D.perturbAt_hom_self]
    change
      (D.hom first + -(D.hom first ≫ C.cornerEndomorphism)) ≫
        (D.hom first + -(D.hom first ≫ C.cornerEndomorphism)) = 0
    simp only [Preadditive.add_comp, Preadditive.comp_add,
      Preadditive.neg_comp, Preadditive.comp_neg]
    rw [hrelation]
    simp only [Category.assoc]
    rw [hpost]
    abel
  · have hfirst' :
        (⟨F.startVertex, F.middleVertex, F.first⟩ :
          S.OrdinaryArrowTotal) ≠
        ⟨F.middleVertex, F.following₂.1.1, F.following₂.1.2⟩ := by
      simpa only [OrdinaryArrowRepresentatives.RightContinuationFork.changedArrow]
        using hfirst
    rw [D.perturbAt_hom_self,
      D.perturbAt_hom_eq_of_ne
        ⟨F.middleVertex, F.following₂.1.1, F.following₂.1.2⟩
        (D.codomainCorrection
          ⟨F.middleVertex, F.following₂.1.1, F.following₂.1.2⟩
          C.cornerEndomorphism C.cornerEndomorphism_mem_radical)
        F.first hfirst']
    change
      (D.hom F.following₂.1.2 +
          -(D.hom F.following₂.1.2 ≫ C.cornerEndomorphism)) ≫
        D.hom F.first = 0
    simp only [Preadditive.add_comp, Preadditive.neg_comp]
    rw [hrelation]
    simp

/-- The radical corner endomorphism in the Kupisch comparison must contain a
second incoming ordinary-arrow branch on which the changed continuation is
nonzero.  Otherwise its outgoing-arrow decomposition would make the original
nonzero composite fixed by a radical endomorphism; nilpotence then gives the
Nakayama contradiction. -/
theorem exists_secondPredecessor [IsAlgClosed k]
    {D : S.OrdinaryArrowRepresentatives}
    {F : D.RightContinuationFork}
    (C : RightKupischComparisonData D F) :
    ∃ d : Quiver.Costar F.middleVertex,
      F.firstPredecessor ≠ d ∧
        D.hom F.following₂.1.2 ≫ D.hom d.2 ≠ 0 := by
  by_contra hnone
  have hzero : ∀ d : Quiver.Costar F.middleVertex,
      F.firstPredecessor ≠ d →
        D.hom F.following₂.1.2 ≫ D.hom d.2 = 0 := by
    intro d hd
    by_contra hne
    exact hnone ⟨d, hd, hne⟩
  obtain ⟨h, he⟩ :=
    D.exists_eq_outgoing_sum_of_mem_projectiveRadical
      F.middleVertex C.cornerEndomorphism
      C.cornerEndomorphism_mem_radical
  have hpost :
      D.hom F.following₂.1.2 ≫ C.cornerEndomorphism =
        (D.hom F.following₂.1.2 ≫
          D.hom F.firstPredecessor.2) ≫ h F.firstPredecessor := by
    calc
      D.hom F.following₂.1.2 ≫ C.cornerEndomorphism =
          ∑ d : Quiver.Costar F.middleVertex,
            (D.hom F.following₂.1.2 ≫ D.hom d.2) ≫ h d := by
        rw [he, Preadditive.comp_sum]
        simp only [Category.assoc]
      _ = (D.hom F.following₂.1.2 ≫
          D.hom F.firstPredecessor.2) ≫ h F.firstPredecessor := by
        rw [Finset.sum_eq_single F.firstPredecessor]
        · intro d _ hd
          rw [hzero d (Ne.symm hd)]
          simp
        · simp
  have hfixed :
      D.hom F.following₂.1.2 ≫ D.hom F.first =
        (D.hom F.following₂.1.2 ≫ C.cornerEndomorphism) ≫
          D.hom F.first := by
    calc
      D.hom F.following₂.1.2 ≫ D.hom F.first =
          C.connector ≫ D.hom F.following₁.1.2 ≫ D.hom F.first :=
        C.firstComparison
      _ = (D.hom F.following₂.1.2 ≫ C.cornerEndomorphism) ≫
          D.hom F.first := by
        rw [← Category.assoc, C.secondComparison]
  let n : S.ordinaryProjectiveObj F.startVertex ⟶
      S.ordinaryProjectiveObj F.startVertex :=
    h F.firstPredecessor ≫ D.hom F.first
  have hnRadical : n ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.startVertex)
        (S.ordinaryProjectiveObj F.startVertex) :=
    S.projectiveNilpotentRadicalData.ideal.precomp
      (h F.firstPredecessor) (D.hom_mem_radical F.first)
  have hfixedN :
      D.hom F.following₂.1.2 ≫ D.hom F.first =
        (D.hom F.following₂.1.2 ≫ D.hom F.first) ≫ n := by
    calc
      D.hom F.following₂.1.2 ≫ D.hom F.first =
          (D.hom F.following₂.1.2 ≫ C.cornerEndomorphism) ≫
            D.hom F.first := hfixed
      _ = ((D.hom F.following₂.1.2 ≫
          D.hom F.firstPredecessor.2) ≫ h F.firstPredecessor) ≫
            D.hom F.first := by rw [hpost]
      _ = (D.hom F.following₂.1.2 ≫ D.hom F.first) ≫ n := by
        simp only [n,
          OrdinaryArrowRepresentatives.RightContinuationFork.firstPredecessor,
          Category.assoc]
  have hnilpotent :=
    S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal hnRadical
  have hunit : IsUnit (1 - End.of n) := hnilpotent.isUnit_one_sub
  let u : End (S.ordinaryProjectiveObj F.startVertex) := 1 - End.of n
  letI : IsIso (End.asHom u) :=
    (CategoryTheory.isUnit_iff_isIso u).mp hunit
  have hcompZero :
      (D.hom F.following₂.1.2 ≫ D.hom F.first) ≫
          End.asHom u = 0 := by
    change
      D.hom F.following₂.1.2 ≫ D.hom F.first -
        (D.hom F.following₂.1.2 ≫ D.hom F.first) ≫ n = 0
    exact sub_eq_zero.mpr hfixedN
  have hzeroOriginal :
      D.hom F.following₂.1.2 ≫ D.hom F.first = 0 := by
    apply (cancel_mono (End.asHom u)).1
    simpa using hcompZero
  exact F.following₂.2 hzeroOriginal

/-- Package the extracted predecessor and the already proved correction as
the exact local datum consumed by the finite SW minimization. -/
noncomputable def toRightSWCorrectionData [IsAlgClosed k]
    {D : S.OrdinaryArrowRepresentatives}
    {F : D.RightContinuationFork}
    (C : RightKupischComparisonData D F) :
    OrdinaryArrowRepresentatives.RightSWCorrectionData D F := by
  let d := Classical.choose C.exists_secondPredecessor
  have hd := Classical.choose_spec C.exists_secondPredecessor
  exact {
    secondPredecessor := d
    secondPredecessor_ne := hd.1
    secondPredecessor_composite_ne := hd.2
    cornerEndomorphism := C.cornerEndomorphism
    cornerEndomorphism_mem_radical := C.cornerEndomorphism_mem_radical
    kills := C.kills }

end RightKupischComparisonData

/-- The two source-faithful Kupisch comparisons attached to one chosen
ordering of a left fork. -/
structure LeftKupischComparisonData
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork) where
  connector :
    S.ordinaryProjectiveObj F.preceding₁.1.1 ⟶
      S.ordinaryProjectiveObj F.preceding₂.1.1
  connector_mem_radical : connector ∈
    S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj F.preceding₁.1.1)
      (S.ordinaryProjectiveObj F.preceding₂.1.1)
  firstComparison :
    D.hom F.second ≫ D.hom F.preceding₂.1.2 =
      D.hom F.second ≫ D.hom F.preceding₁.1.2 ≫ connector
  cornerEndomorphism :
    S.ordinaryProjectiveObj F.middleVertex ⟶
      S.ordinaryProjectiveObj F.middleVertex
  cornerEndomorphism_mem_radical : cornerEndomorphism ∈
    S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj F.middleVertex)
      (S.ordinaryProjectiveObj F.middleVertex)
  secondComparison :
    D.hom F.preceding₁.1.2 ≫ connector =
      cornerEndomorphism ≫ D.hom F.preceding₂.1.2

namespace LeftKupischComparisonData

/-- The domain correction supplied by the two left Kupisch comparisons kills
the selected composite, including the possible loop case. -/
theorem kills
    {D : S.OrdinaryArrowRepresentatives}
    {F : D.LeftContinuationFork}
    (C : LeftKupischComparisonData D F) :
    (D.perturbAt F.changedArrow
      (D.domainCorrection F.changedArrow C.cornerEndomorphism
        C.cornerEndomorphism_mem_radical)).twoStepComposite
          F.killedTwoStep = 0 := by
  have hrelation :
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
        D.hom F.second ≫
          (C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2) := by
    calc
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
          D.hom F.second ≫ D.hom F.preceding₁.1.2 ≫
            C.connector := C.firstComparison
      _ = D.hom F.second ≫
          (C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2) := by
        rw [C.secondComparison]
  change
    (D.perturbAt
        ⟨F.preceding₂.1.1, F.middleVertex, F.preceding₂.1.2⟩
        (D.domainCorrection
          ⟨F.preceding₂.1.1, F.middleVertex, F.preceding₂.1.2⟩
          C.cornerEndomorphism C.cornerEndomorphism_mem_radical)).hom
          F.second ≫
      (D.perturbAt
        ⟨F.preceding₂.1.1, F.middleVertex, F.preceding₂.1.2⟩
        (D.domainCorrection
          ⟨F.preceding₂.1.1, F.middleVertex, F.preceding₂.1.2⟩
          C.cornerEndomorphism C.cornerEndomorphism_mem_radical)).hom
          F.preceding₂.1.2 = 0
  by_cases hsecond :
      (⟨F.middleVertex, F.targetVertex, F.second⟩ :
        S.OrdinaryArrowTotal) = F.changedArrow
  · rcases F with
      ⟨middle, target, second, ⟨⟨z₁, c⟩, hc⟩, ⟨⟨z₂, g⟩, hg⟩, hdistinct⟩
    simp only [OrdinaryArrowRepresentatives.LeftContinuationFork.changedArrow]
      at hsecond hrelation ⊢
    cases hsecond
    have hpre := congrArg
      (fun f ↦ C.cornerEndomorphism ≫ f) hrelation
    rw [D.perturbAt_hom_self]
    change
      (D.hom g + -(C.cornerEndomorphism ≫ D.hom g)) ≫
        (D.hom g + -(C.cornerEndomorphism ≫ D.hom g)) = 0
    simp only [Preadditive.add_comp, Preadditive.comp_add,
      Preadditive.neg_comp, Preadditive.comp_neg]
    rw [hrelation]
    simp only [Category.assoc]
    rw [hpre]
    abel
  · have hsecond' :
        (⟨F.middleVertex, F.targetVertex, F.second⟩ :
          S.OrdinaryArrowTotal) ≠
        ⟨F.preceding₂.1.1, F.middleVertex, F.preceding₂.1.2⟩ := by
      simpa only [OrdinaryArrowRepresentatives.LeftContinuationFork.changedArrow]
        using hsecond
    rw [D.perturbAt_hom_self,
      D.perturbAt_hom_eq_of_ne
        ⟨F.preceding₂.1.1, F.middleVertex, F.preceding₂.1.2⟩
        (D.domainCorrection
          ⟨F.preceding₂.1.1, F.middleVertex, F.preceding₂.1.2⟩
          C.cornerEndomorphism C.cornerEndomorphism_mem_radical)
        F.second hsecond']
    change
      D.hom F.second ≫
        (D.hom F.preceding₂.1.2 +
          -(C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2)) = 0
    simp only [Preadditive.comp_add, Preadditive.comp_neg]
    rw [hrelation]
    simp

/-- The radical middle endomorphism in a left Kupisch comparison contains a
second outgoing branch on which the changed predecessor is nonzero. -/
theorem exists_secondFollowing [IsAlgClosed k]
    {D : S.OrdinaryArrowRepresentatives}
    {F : D.LeftContinuationFork}
    (C : LeftKupischComparisonData D F) :
    ∃ d : Quiver.Star F.middleVertex,
      F.firstFollowing ≠ d ∧
        D.hom d.2 ≫ D.hom F.preceding₂.1.2 ≠ 0 := by
  by_contra hnone
  have hzero : ∀ d : Quiver.Star F.middleVertex,
      F.firstFollowing ≠ d →
        D.hom d.2 ≫ D.hom F.preceding₂.1.2 = 0 := by
    intro d hd
    by_contra hne
    exact hnone ⟨d, hd, hne⟩
  obtain ⟨h, he⟩ :=
    D.exists_eq_incoming_sum_of_mem_projectiveRadical
      F.middleVertex C.cornerEndomorphism
      C.cornerEndomorphism_mem_radical
  have hpre :
      C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2 =
        h F.firstFollowing ≫
          (D.hom F.firstFollowing.2 ≫
            D.hom F.preceding₂.1.2) := by
    calc
      C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2 =
          ∑ d : Quiver.Star F.middleVertex,
            h d ≫ (D.hom d.2 ≫ D.hom F.preceding₂.1.2) := by
        rw [he, Preadditive.sum_comp]
        simp only [Category.assoc]
      _ = h F.firstFollowing ≫
          (D.hom F.firstFollowing.2 ≫
            D.hom F.preceding₂.1.2) := by
        rw [Finset.sum_eq_single F.firstFollowing]
        · intro d _ hd
          rw [hzero d (Ne.symm hd)]
          simp
        · simp
  have hfixed :
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
        D.hom F.second ≫
          (C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2) := by
    calc
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
          D.hom F.second ≫ D.hom F.preceding₁.1.2 ≫
            C.connector := C.firstComparison
      _ = D.hom F.second ≫
          (C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2) := by
        rw [C.secondComparison]
  let n : S.ordinaryProjectiveObj F.targetVertex ⟶
      S.ordinaryProjectiveObj F.targetVertex :=
    D.hom F.second ≫ h F.firstFollowing
  have hnRadical : n ∈
      S.projectiveNilpotentRadicalData.ideal.hom
        (S.ordinaryProjectiveObj F.targetVertex)
        (S.ordinaryProjectiveObj F.targetVertex) :=
    S.projectiveNilpotentRadicalData.ideal.postcomp
      (h F.firstFollowing) (D.hom_mem_radical F.second)
  have hfixedN :
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
        n ≫ (D.hom F.second ≫ D.hom F.preceding₂.1.2) := by
    calc
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
          D.hom F.second ≫
            (C.cornerEndomorphism ≫ D.hom F.preceding₂.1.2) :=
        hfixed
      _ = D.hom F.second ≫
          (h F.firstFollowing ≫
            (D.hom F.firstFollowing.2 ≫
              D.hom F.preceding₂.1.2)) := by rw [hpre]
      _ = n ≫
          (D.hom F.second ≫ D.hom F.preceding₂.1.2) := by
        simp only [n,
          OrdinaryArrowRepresentatives.LeftContinuationFork.firstFollowing,
          Category.assoc]
  have hnilpotent :=
    S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal hnRadical
  have hunit : IsUnit (1 - End.of n) := hnilpotent.isUnit_one_sub
  let u : End (S.ordinaryProjectiveObj F.targetVertex) := 1 - End.of n
  letI : IsIso (End.asHom u) :=
    (CategoryTheory.isUnit_iff_isIso u).mp hunit
  have hcompZero :
      End.asHom u ≫
        (D.hom F.second ≫ D.hom F.preceding₂.1.2) = 0 := by
    dsimp only [u]
    change
      ((𝟙 (S.ordinaryProjectiveObj F.targetVertex) - n) ≫
          D.hom F.second) ≫ D.hom F.preceding₂.1.2 = 0
    rw [Preadditive.sub_comp, Category.id_comp,
      Preadditive.sub_comp]
    exact sub_eq_zero.mpr hfixedN
  have hzeroOriginal :
      D.hom F.second ≫ D.hom F.preceding₂.1.2 = 0 := by
    apply (cancel_epi (End.asHom u)).1
    simpa using hcompZero
  exact F.preceding₂.2 hzeroOriginal

/-- Package the left comparison and extracted following arrow as the exact
local datum consumed by finite minimization. -/
noncomputable def toLeftSWCorrectionData [IsAlgClosed k]
    {D : S.OrdinaryArrowRepresentatives}
    {F : D.LeftContinuationFork}
    (C : LeftKupischComparisonData D F) :
    OrdinaryArrowRepresentatives.LeftSWCorrectionData D F := by
  let d := Classical.choose C.exists_secondFollowing
  have hd := Classical.choose_spec C.exists_secondFollowing
  exact {
    secondFollowing := d
    secondFollowing_ne := hd.1
    secondFollowing_composite_ne := hd.2
    cornerEndomorphism := C.cornerEndomorphism
    cornerEndomorphism_mem_radical := C.cornerEndomorphism_mem_radical
    kills := C.kills }

end LeftKupischComparisonData

namespace PrimitiveProjectivePresentation

/-- A two-arrow composite, bundled in the principal right ideal generated by
the coordinate of its first arrow. -/
def compositeInArrowRightIdeal
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    {x y z : S.ProjectiveLabel}
    (a : S.OrdinaryArrow x y) (b : S.OrdinaryArrow y z) :
    RightModule.rightIdeal (P.projectiveHomCoordinate (D.hom a)) := by
  refine ⟨P.projectiveHomCoordinate (D.hom b ≫ D.hom a), ?_⟩
  refine ⟨P.projectiveHomCoordinate (D.hom b), ?_⟩
  rw [P.projectiveHomCoordinate_comp]
  exact RightModule.rightRegularLeftMul_apply _ _

@[simp]
theorem compositeInArrowRightIdeal_coe
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    {x y z : S.ProjectiveLabel}
    (a : S.OrdinaryArrow x y) (b : S.OrdinaryArrow y z) :
    (P.compositeInArrowRightIdeal D a b : A) =
      P.projectiveHomCoordinate (D.hom b ≫ D.hom a) :=
  rfl

/-- Uniseriality of the principal right ideal generated by the common first
arrow compares the two nonzero composites in one of the two source-faithful
orders and converts the scalar into a corner-supported projective connector. -/
theorem exists_rightFork_firstComparison
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork)
    (huni : IsUniserialModule Aᵐᵒᵖ
      (RightModule.rightIdeal
        (P.projectiveHomCoordinate (D.hom F.first)))) :
    (∃ connector :
        S.ordinaryProjectiveObj F.following₂.1.1 ⟶
          S.ordinaryProjectiveObj F.following₁.1.1,
      D.hom F.following₂.1.2 ≫ D.hom F.first =
        connector ≫ D.hom F.following₁.1.2 ≫ D.hom F.first) ∨
    (∃ connector :
        S.ordinaryProjectiveObj F.following₁.1.1 ⟶
          S.ordinaryProjectiveObj F.following₂.1.1,
      D.hom F.following₁.1.2 ≫ D.hom F.first =
        connector ≫ D.hom F.following₂.1.2 ≫ D.hom F.first) := by
  let u₁ := P.compositeInArrowRightIdeal D F.first F.following₁.1.2
  let u₂ := P.compositeInArrowRightIdeal D F.first F.following₂.1.2
  rcases huni.smul_comparable u₁ u₂ with h₁₂ | h₂₁
  · obtain ⟨r, hr⟩ := h₁₂
    let z := P.idempotent F.following₁.1.1 * r.unop *
      P.idempotent F.following₂.1.1
    have hzLeft : P.idempotent F.following₁.1.1 * z = z := by
      simp only [z, ← mul_assoc, (P.primitive F.following₁.1.1).idempotent.eq]
    have hzRight : z * P.idempotent F.following₂.1.1 = z := by
      simp only [z, mul_assoc, (P.primitive F.following₂.1.1).idempotent.eq]
    let connector :
        S.ordinaryProjectiveObj F.following₂.1.1 ⟶
          S.ordinaryProjectiveObj F.following₁.1.1 :=
      P.projectiveHomOfCoordinate z hzLeft hzRight
    left
    refine ⟨connector, ?_⟩
    apply P.projectiveHomCoordinate_injective
      F.following₂.1.1 F.startVertex
    have hrA := congrArg
      (fun w : RightModule.rightIdeal
        (P.projectiveHomCoordinate (D.hom F.first)) ↦ w.1) hr
    change
      P.projectiveHomCoordinate (D.hom F.following₁.1.2 ≫ D.hom F.first) *
          r.unop =
        P.projectiveHomCoordinate (D.hom F.following₂.1.2 ≫ D.hom F.first)
      at hrA
    simp only [P.projectiveHomCoordinate_comp] at hrA ⊢
    rw [P.projectiveHomCoordinate_projectiveHomOfCoordinate]
    let a := P.projectiveHomCoordinate (D.hom F.first)
    let b := P.projectiveHomCoordinate (D.hom F.following₁.1.2)
    let g := P.projectiveHomCoordinate (D.hom F.following₂.1.2)
    change a * g = (a * b) * z
    change (a * b) * r.unop = a * g at hrA
    have hbe : b * P.idempotent F.following₁.1.1 = b :=
      P.projectiveHomCoordinate_mul_idempotent
        (D.hom F.following₁.1.2)
    have hge : g * P.idempotent F.following₂.1.1 = g :=
      P.projectiveHomCoordinate_mul_idempotent
        (D.hom F.following₂.1.2)
    calc
      a * g = (a * b) * r.unop := hrA.symm
      _ = (a * b) * (P.idempotent F.following₁.1.1 * r.unop *
          P.idempotent F.following₂.1.1) := by
        symm
        calc
          (a * b) * (P.idempotent F.following₁.1.1 * r.unop *
              P.idempotent F.following₂.1.1) =
              (((a * b) * P.idempotent F.following₁.1.1) * r.unop) *
                P.idempotent F.following₂.1.1 := by
            simp only [mul_assoc]
          _ = ((a * b) * r.unop) * P.idempotent F.following₂.1.1 := by
            rw [mul_assoc a b, hbe]
          _ = (a * g) * P.idempotent F.following₂.1.1 := by rw [hrA]
          _ = a * (g * P.idempotent F.following₂.1.1) := by rw [mul_assoc]
          _ = a * g := by rw [hge]
          _ = (a * b) * r.unop := hrA.symm
      _ = (a * b) * z := rfl
  · obtain ⟨r, hr⟩ := h₂₁
    let z := P.idempotent F.following₂.1.1 * r.unop *
      P.idempotent F.following₁.1.1
    have hzLeft : P.idempotent F.following₂.1.1 * z = z := by
      simp only [z, ← mul_assoc, (P.primitive F.following₂.1.1).idempotent.eq]
    have hzRight : z * P.idempotent F.following₁.1.1 = z := by
      simp only [z, mul_assoc, (P.primitive F.following₁.1.1).idempotent.eq]
    let connector :
        S.ordinaryProjectiveObj F.following₁.1.1 ⟶
          S.ordinaryProjectiveObj F.following₂.1.1 :=
      P.projectiveHomOfCoordinate z hzLeft hzRight
    right
    refine ⟨connector, ?_⟩
    apply P.projectiveHomCoordinate_injective
      F.following₁.1.1 F.startVertex
    have hrA := congrArg
      (fun w : RightModule.rightIdeal
        (P.projectiveHomCoordinate (D.hom F.first)) ↦ w.1) hr
    change
      P.projectiveHomCoordinate (D.hom F.following₂.1.2 ≫ D.hom F.first) *
          r.unop =
        P.projectiveHomCoordinate (D.hom F.following₁.1.2 ≫ D.hom F.first)
      at hrA
    simp only [P.projectiveHomCoordinate_comp] at hrA ⊢
    rw [P.projectiveHomCoordinate_projectiveHomOfCoordinate]
    let a := P.projectiveHomCoordinate (D.hom F.first)
    let b := P.projectiveHomCoordinate (D.hom F.following₂.1.2)
    let g := P.projectiveHomCoordinate (D.hom F.following₁.1.2)
    change a * g = (a * b) * z
    change (a * b) * r.unop = a * g at hrA
    have hbe : b * P.idempotent F.following₂.1.1 = b :=
      P.projectiveHomCoordinate_mul_idempotent
        (D.hom F.following₂.1.2)
    have hge : g * P.idempotent F.following₁.1.1 = g :=
      P.projectiveHomCoordinate_mul_idempotent
        (D.hom F.following₁.1.2)
    calc
      a * g = (a * b) * r.unop := hrA.symm
      _ = (a * b) * (P.idempotent F.following₂.1.1 * r.unop *
          P.idempotent F.following₁.1.1) := by
        symm
        calc
          (a * b) * (P.idempotent F.following₂.1.1 * r.unop *
              P.idempotent F.following₁.1.1) =
              (((a * b) * P.idempotent F.following₂.1.1) * r.unop) *
                P.idempotent F.following₁.1.1 := by
            simp only [mul_assoc]
          _ = ((a * b) * r.unop) * P.idempotent F.following₁.1.1 := by
            rw [mul_assoc a b, hbe]
          _ = (a * g) * P.idempotent F.following₁.1.1 := by rw [hrA]
          _ = a * (g * P.idempotent F.following₁.1.1) := by rw [mul_assoc]
          _ = a * g := by rw [hge]
          _ = (a * b) * r.unop := hrA.symm
      _ = (a * b) * z := rfl

/-- Under Kupisch's literal codomain-or-domain uniserial alternative, the two
successive comparisons produce complete comparison data for one of the two
orderings of the fork.  The domain-uniserial branch is ruled out by
nilpotence.  The disjunction records the order selected by uniseriality rather
than imposing a stronger predetermined orientation. -/
theorem exists_rightKupischComparisonChoice [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork)
    (hprincipal : IsUniserialModule Aᵐᵒᵖ
      (RightModule.rightIdeal
        (P.projectiveHomCoordinate (D.hom F.first))))
    (hcorner : ∀ z : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj F.middleVertex))
          (S.ordinaryProjectiveObj z ⟶
            S.ordinaryProjectiveObj F.middleVertex) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj z))ᵐᵒᵖ
          (S.ordinaryProjectiveObj z ⟶
            S.ordinaryProjectiveObj F.middleVertex)) :
    Nonempty (RightKupischComparisonData D F) ∨
      Nonempty (RightKupischComparisonData D F.swap) := by
  rcases P.exists_rightFork_firstComparison D F hprincipal with
      ⟨connector, hfirst⟩ | ⟨connector, hfirst⟩
  · have htarget : F.following₁.1.1 ≠ F.following₂.1.1 :=
      OrdinaryArrowRepresentatives.RightContinuationFork.followingTarget_ne_of_uniserialAlternative
        D F hcorner
    have hconnector : connector ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.following₂.1.1)
          (S.ordinaryProjectiveObj F.following₁.1.1) :=
      S.mem_projectiveRadical_of_ne htarget connector
    obtain ⟨e, he, hsecond⟩ :=
      D.exists_rightFork_secondComparison_of_uniserialAlternative
        F connector hconnector hfirst (hcorner F.following₂.1.1)
    left
    exact ⟨{
      connector := connector
      connector_mem_radical := hconnector
      firstComparison := hfirst
      cornerEndomorphism := e
      cornerEndomorphism_mem_radical := he
      secondComparison := hsecond }⟩
  · have htarget : F.swap.following₁.1.1 ≠
        F.swap.following₂.1.1 :=
      OrdinaryArrowRepresentatives.RightContinuationFork.followingTarget_ne_of_uniserialAlternative
        D F.swap hcorner
    have hconnector : connector ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.swap.following₂.1.1)
          (S.ordinaryProjectiveObj F.swap.following₁.1.1) :=
      S.mem_projectiveRadical_of_ne htarget connector
    obtain ⟨e, he, hsecond⟩ :=
      D.exists_rightFork_secondComparison_of_uniserialAlternative
        F.swap connector hconnector hfirst
          (hcorner F.swap.following₂.1.1)
    right
    exact ⟨{
      connector := connector
      connector_mem_radical := hconnector
      firstComparison := hfirst
      cornerEndomorphism := e
      cornerEndomorphism_mem_radical := he
      secondComparison := hsecond }⟩

/-- Kupisch's uniserial alternative supplies the exact unordered right-hand
correction choice consumed by the finite adapted-representative
construction. -/
theorem exists_rightSWCorrectionChoice [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.RightContinuationFork)
    (hprincipal : IsUniserialModule Aᵐᵒᵖ
      (RightModule.rightIdeal
        (P.projectiveHomCoordinate (D.hom F.first))))
    (hcorner : ∀ z : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj F.middleVertex))
          (S.ordinaryProjectiveObj z ⟶
            S.ordinaryProjectiveObj F.middleVertex) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj z))ᵐᵒᵖ
          (S.ordinaryProjectiveObj z ⟶
            S.ordinaryProjectiveObj F.middleVertex)) :
    OrdinaryArrowRepresentatives.RightSWCorrectionChoice D F := by
  rcases P.exists_rightKupischComparisonChoice D F hprincipal hcorner with
      hcomparison | hcomparison
  · left
    exact ⟨(Classical.choice hcomparison).toRightSWCorrectionData⟩
  · right
    exact ⟨(Classical.choice hcomparison).toRightSWCorrectionData⟩

/-- A two-arrow composite bundled in the principal left ideal generated by
the coordinate of its second arrow. -/
def compositeInArrowLeftIdeal
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    {x y z : S.ProjectiveLabel}
    (a : S.OrdinaryArrow x y) (b : S.OrdinaryArrow y z) :
    RightModule.leftIdeal (P.projectiveHomCoordinate (D.hom b)) := by
  refine ⟨P.projectiveHomCoordinate (D.hom b ≫ D.hom a), ?_⟩
  refine ⟨P.projectiveHomCoordinate (D.hom a), ?_⟩
  rw [P.projectiveHomCoordinate_comp]
  rfl

@[simp]
theorem compositeInArrowLeftIdeal_coe
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    {x y z : S.ProjectiveLabel}
    (a : S.OrdinaryArrow x y) (b : S.OrdinaryArrow y z) :
    (P.compositeInArrowLeftIdeal D a b : A) =
      P.projectiveHomCoordinate (D.hom b ≫ D.hom a) :=
  rfl

/-- Uniseriality of the principal left ideal generated by the common second
arrow compares the two nonzero composites and turns the selected multiplier
into a corner-supported connector. -/
theorem exists_leftFork_firstComparison
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork)
    (huni : IsUniserialModule A
      (RightModule.leftIdeal
        (P.projectiveHomCoordinate (D.hom F.second)))) :
    (∃ connector :
        S.ordinaryProjectiveObj F.preceding₁.1.1 ⟶
          S.ordinaryProjectiveObj F.preceding₂.1.1,
      D.hom F.second ≫ D.hom F.preceding₂.1.2 =
        D.hom F.second ≫ D.hom F.preceding₁.1.2 ≫ connector) ∨
    (∃ connector :
        S.ordinaryProjectiveObj F.preceding₂.1.1 ⟶
          S.ordinaryProjectiveObj F.preceding₁.1.1,
      D.hom F.second ≫ D.hom F.preceding₁.1.2 =
        D.hom F.second ≫ D.hom F.preceding₂.1.2 ≫ connector) := by
  let u₁ := P.compositeInArrowLeftIdeal D F.preceding₁.1.2 F.second
  let u₂ := P.compositeInArrowLeftIdeal D F.preceding₂.1.2 F.second
  rcases huni.smul_comparable u₁ u₂ with h₁₂ | h₂₁
  · obtain ⟨r, hr⟩ := h₁₂
    let z := P.idempotent F.preceding₂.1.1 * r *
      P.idempotent F.preceding₁.1.1
    have hzLeft : P.idempotent F.preceding₂.1.1 * z = z := by
      simp only [z, ← mul_assoc,
        (P.primitive F.preceding₂.1.1).idempotent.eq]
    have hzRight : z * P.idempotent F.preceding₁.1.1 = z := by
      simp only [z, mul_assoc,
        (P.primitive F.preceding₁.1.1).idempotent.eq]
    let connector :
        S.ordinaryProjectiveObj F.preceding₁.1.1 ⟶
          S.ordinaryProjectiveObj F.preceding₂.1.1 :=
      P.projectiveHomOfCoordinate z hzLeft hzRight
    left
    refine ⟨connector, ?_⟩
    apply P.projectiveHomCoordinate_injective
      F.targetVertex F.preceding₂.1.1
    have hrA := congrArg
      (fun w : RightModule.leftIdeal
        (P.projectiveHomCoordinate (D.hom F.second)) ↦ w.1) hr
    change
      r * P.projectiveHomCoordinate
          (D.hom F.second ≫ D.hom F.preceding₁.1.2) =
        P.projectiveHomCoordinate
          (D.hom F.second ≫ D.hom F.preceding₂.1.2)
      at hrA
    simp only [P.projectiveHomCoordinate_comp] at hrA ⊢
    rw [P.projectiveHomCoordinate_projectiveHomOfCoordinate]
    let a := P.projectiveHomCoordinate (D.hom F.second)
    let b := P.projectiveHomCoordinate (D.hom F.preceding₁.1.2)
    let g := P.projectiveHomCoordinate (D.hom F.preceding₂.1.2)
    change g * a = z * b * a
    change r * (b * a) = g * a at hrA
    have heb : P.idempotent F.preceding₁.1.1 * b = b :=
      P.idempotent_mul_projectiveHomCoordinate
        (D.hom F.preceding₁.1.2)
    have heg : P.idempotent F.preceding₂.1.1 * g = g :=
      P.idempotent_mul_projectiveHomCoordinate
        (D.hom F.preceding₂.1.2)
    calc
      g * a = P.idempotent F.preceding₂.1.1 * (g * a) := by
        rw [← mul_assoc, heg]
      _ = P.idempotent F.preceding₂.1.1 * (r * (b * a)) := by
        rw [hrA]
      _ = (P.idempotent F.preceding₂.1.1 * r *
          P.idempotent F.preceding₁.1.1) * b * a := by
        simp only [mul_assoc, heb]
      _ = z * b * a := rfl
  · obtain ⟨r, hr⟩ := h₂₁
    let z := P.idempotent F.preceding₁.1.1 * r *
      P.idempotent F.preceding₂.1.1
    have hzLeft : P.idempotent F.preceding₁.1.1 * z = z := by
      simp only [z, ← mul_assoc,
        (P.primitive F.preceding₁.1.1).idempotent.eq]
    have hzRight : z * P.idempotent F.preceding₂.1.1 = z := by
      simp only [z, mul_assoc,
        (P.primitive F.preceding₂.1.1).idempotent.eq]
    let connector :
        S.ordinaryProjectiveObj F.preceding₂.1.1 ⟶
          S.ordinaryProjectiveObj F.preceding₁.1.1 :=
      P.projectiveHomOfCoordinate z hzLeft hzRight
    right
    refine ⟨connector, ?_⟩
    apply P.projectiveHomCoordinate_injective
      F.targetVertex F.preceding₁.1.1
    have hrA := congrArg
      (fun w : RightModule.leftIdeal
        (P.projectiveHomCoordinate (D.hom F.second)) ↦ w.1) hr
    change
      r * P.projectiveHomCoordinate
          (D.hom F.second ≫ D.hom F.preceding₂.1.2) =
        P.projectiveHomCoordinate
          (D.hom F.second ≫ D.hom F.preceding₁.1.2)
      at hrA
    simp only [P.projectiveHomCoordinate_comp] at hrA ⊢
    rw [P.projectiveHomCoordinate_projectiveHomOfCoordinate]
    let a := P.projectiveHomCoordinate (D.hom F.second)
    let b := P.projectiveHomCoordinate (D.hom F.preceding₂.1.2)
    let g := P.projectiveHomCoordinate (D.hom F.preceding₁.1.2)
    change g * a = z * b * a
    change r * (b * a) = g * a at hrA
    have heb : P.idempotent F.preceding₂.1.1 * b = b :=
      P.idempotent_mul_projectiveHomCoordinate
        (D.hom F.preceding₂.1.2)
    have heg : P.idempotent F.preceding₁.1.1 * g = g :=
      P.idempotent_mul_projectiveHomCoordinate
        (D.hom F.preceding₁.1.2)
    calc
      g * a = P.idempotent F.preceding₁.1.1 * (g * a) := by
        rw [← mul_assoc, heg]
      _ = P.idempotent F.preceding₁.1.1 * (r * (b * a)) := by
        rw [hrA]
      _ = (P.idempotent F.preceding₁.1.1 * r *
          P.idempotent F.preceding₂.1.1) * b * a := by
        simp only [mul_assoc, heb]
      _ = z * b * a := rfl

/-- The principal-left-ideal comparison and Kupisch's literal Hom-bimodule
alternative give complete comparison data for one ordering of a left fork. -/
theorem exists_leftKupischComparisonChoice [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork)
    (hprincipal : IsUniserialModule A
      (RightModule.leftIdeal
        (P.projectiveHomCoordinate (D.hom F.second))))
    (hcorner : ∀ z : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj z))
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj z) ∨
        IsUniserialModule
          (End (S.ordinaryProjectiveObj F.middleVertex))ᵐᵒᵖ
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj z)) :
    Nonempty (LeftKupischComparisonData D F) ∨
      Nonempty (LeftKupischComparisonData D F.swap) := by
  rcases P.exists_leftFork_firstComparison D F hprincipal with
      ⟨connector, hfirst⟩ | ⟨connector, hfirst⟩
  · have hsource : F.preceding₁.1.1 ≠ F.preceding₂.1.1 :=
      OrdinaryArrowRepresentatives.LeftContinuationFork.precedingSource_ne_of_uniserialAlternative
        D F hcorner
    have hconnector : connector ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.preceding₁.1.1)
          (S.ordinaryProjectiveObj F.preceding₂.1.1) :=
      S.mem_projectiveRadical_of_ne hsource.symm connector
    obtain ⟨e, he, hsecond⟩ :=
      D.exists_leftFork_secondComparison_of_uniserialAlternative
        F connector hconnector hfirst (hcorner F.preceding₂.1.1)
    left
    exact ⟨{
      connector := connector
      connector_mem_radical := hconnector
      firstComparison := hfirst
      cornerEndomorphism := e
      cornerEndomorphism_mem_radical := he
      secondComparison := hsecond }⟩
  · have hsource : F.swap.preceding₁.1.1 ≠
        F.swap.preceding₂.1.1 :=
      OrdinaryArrowRepresentatives.LeftContinuationFork.precedingSource_ne_of_uniserialAlternative
        D F.swap hcorner
    have hconnector : connector ∈
        S.projectiveNilpotentRadicalData.ideal.hom
          (S.ordinaryProjectiveObj F.swap.preceding₁.1.1)
          (S.ordinaryProjectiveObj F.swap.preceding₂.1.1) :=
      S.mem_projectiveRadical_of_ne hsource.symm connector
    obtain ⟨e, he, hsecond⟩ :=
      D.exists_leftFork_secondComparison_of_uniserialAlternative
        F.swap connector hconnector hfirst
          (hcorner F.swap.preceding₂.1.1)
    right
    exact ⟨{
      connector := connector
      connector_mem_radical := hconnector
      firstComparison := hfirst
      cornerEndomorphism := e
      cornerEndomorphism_mem_radical := he
      secondComparison := hsecond }⟩

/-- Kupisch's uniserial alternative supplies the exact unordered left-hand
correction choice consumed by finite adapted-representative construction. -/
theorem exists_leftSWCorrectionChoice [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    (F : D.LeftContinuationFork)
    (hprincipal : IsUniserialModule A
      (RightModule.leftIdeal
        (P.projectiveHomCoordinate (D.hom F.second))))
    (hcorner : ∀ z : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj z))
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj z) ∨
        IsUniserialModule
          (End (S.ordinaryProjectiveObj F.middleVertex))ᵐᵒᵖ
          (S.ordinaryProjectiveObj F.middleVertex ⟶
            S.ordinaryProjectiveObj z)) :
    OrdinaryArrowRepresentatives.LeftSWCorrectionChoice D F := by
  rcases P.exists_leftKupischComparisonChoice D F hprincipal hcorner with
      hcomparison | hcomparison
  · left
    exact ⟨(Classical.choice hcomparison).toLeftSWCorrectionData⟩
  · right
    exact ⟨(Classical.choice hcomparison).toLeftSWCorrectionData⟩

end PrimitiveProjectivePresentation

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
