import MagnitudeConjecture.Algebra.RightModuleTauAssembly
import QuotientSubmoduleEquidistribution.CategoryTheory.LinearGeneratedHomIdeal
import QuotientSubmoduleEquidistribution.CategoryTheory.IdempotentLifting
import Mathlib.CategoryTheory.Simple

/-!
# Literal factor categories of finite right-module categories

This file constructs the manuscript's categorical quotient by morphisms
factoring through the additive closure of a selected set of indecomposable
modules.  It deliberately stops before the factor tau-sequences: the quotient
category, its linear and additive structures, its finite biproducts, and its
surviving skeleton are the reusable substrate for that construction.
-/

set_option autoImplicit false

noncomputable section

open CategoryTheory CategoryTheory.Limits
open QuotientSubmoduleEquidistribution
open QuotientSubmoduleEquidistribution.CategoricalIdeal
open QuotientSubmoduleEquidistribution.CategoricalRadical
open scoped ModuleCat.Algebra

namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
variable (S : RightModule.FiniteIndecomposableSkeleton k A)

attribute [local instance] HasFiniteBiproducts.of_hasFiniteCoproducts

/-- The full additive subcategory generated by a set of selected
indecomposable labels. -/
abbrev SelectedAddCategory (K : Set (Fin S.n)) :=
  (S.almostSplitSkeleton.generated K).FullSubcategory

/-- A morphism factors through the additive closure of `K`. -/
def FactorsThroughSelected (K : Set (Fin S.n))
    {X Z : RightModule.FinitelyGeneratedCategory A} (f : X ⟶ Z) : Prop :=
  ∃ M : RightModule.FinitelyGeneratedCategory A,
    S.almostSplitSkeleton.InAdd K M ∧
      ∃ (left : X ⟶ M) (right : M ⟶ Z), left ≫ right = f

/-- The maps in the complete additive category which factor through the
selected additive subcategory. -/
def factorThroughSelectedMaps (K : Set (Fin S.n))
    (X Y : S.SelectedAddCategory Set.univ) : Set (X ⟶ Y) :=
  {f | S.FactorsThroughSelected K f.hom}

private theorem inAdd_biprod
    {K : Set (Fin S.n)} {M N : RightModule.FinitelyGeneratedCategory A}
    (hM : S.almostSplitSkeleton.InAdd K M)
    (hN : S.almostSplitSkeleton.InAdd K N) :
    S.almostSplitSkeleton.InAdd K (M ⊞ N) := by
  let F : WalkingPair → RightModule.FinitelyGeneratedCategory A :=
    pairFunction M N
  have hF : ∀ j, S.almostSplitSkeleton.InAdd K (F j) := by
    intro j
    cases j with
    | left => exact hM
    | right => exact hN
  have hsum := S.almostSplitSkeleton.inAdd_biproduct
    (FintypeCat.of WalkingPair) F hF
  let b : BinaryBicone M N := (biproduct.bicone F).toBinaryBicone
  have hb : b.IsBilimit :=
    (Bicone.toBinaryBiconeIsBilimit (biproduct.bicone F)).symm
      (biproduct.isBilimit F)
  exact
    (S.almostSplitSkeleton.inAdd_iff_of_iso
      (biprod.uniqueUpToIso M N hb)).1 hsum

private theorem factorsThroughSelected_zero
    (K : Set (Fin S.n))
    {X Y : RightModule.FinitelyGeneratedCategory A} :
    S.FactorsThroughSelected K (0 : X ⟶ Y) := by
  let F : Empty → RightModule.FinitelyGeneratedCategory A := Empty.elim
  let M := biproduct F
  have hM : S.almostSplitSkeleton.InAdd K M :=
    S.almostSplitSkeleton.inAdd_biproduct
      (FintypeCat.of Empty) F (fun j ↦ j.elim)
  exact ⟨M, hM, 0, 0, by simp⟩

private theorem FactorsThroughSelected.add
    {K : Set (Fin S.n)} {X Y : RightModule.FinitelyGeneratedCategory A}
    {f g : X ⟶ Y}
    (hf : S.FactorsThroughSelected K f)
    (hg : S.FactorsThroughSelected K g) :
    S.FactorsThroughSelected K (f + g) := by
  rcases hf with ⟨M, hM, leftM, rightM, hfacM⟩
  rcases hg with ⟨N, hN, leftN, rightN, hfacN⟩
  refine ⟨M ⊞ N, S.inAdd_biprod hM hN,
    biprod.lift leftM leftN, biprod.desc rightM rightN, ?_⟩
  rw [biprod.lift_desc, hfacM, hfacN]

private theorem FactorsThroughSelected.neg
    {K : Set (Fin S.n)} {X Y : RightModule.FinitelyGeneratedCategory A}
    {f : X ⟶ Y} (hf : S.FactorsThroughSelected K f) :
    S.FactorsThroughSelected K (-f) := by
  rcases hf with ⟨M, hM, left, right, hfac⟩
  exact ⟨M, hM, -left, right, by simp [hfac]⟩

private theorem factorThroughSelectedMaps_precomp
    {K : Set (Fin S.n)} {X Y Z : S.SelectedAddCategory Set.univ}
    (f : X ⟶ Y) {g : Y ⟶ Z}
    (hg : g ∈ S.factorThroughSelectedMaps K Y Z) :
    f ≫ g ∈ S.factorThroughSelectedMaps K X Z := by
  rcases hg with ⟨M, hM, left, right, hfac⟩
  exact ⟨M, hM, f.hom ≫ left, right, by
    rw [Category.assoc, hfac]
    rfl⟩

private theorem factorThroughSelectedMaps_postcomp
    {K : Set (Fin S.n)} {X Y Z : S.SelectedAddCategory Set.univ}
    {f : X ⟶ Y} (g : Y ⟶ Z)
    (hf : f ∈ S.factorThroughSelectedMaps K X Y) :
    f ≫ g ∈ S.factorThroughSelectedMaps K X Z := by
  rcases hf with ⟨M, hM, left, right, hfac⟩
  exact ⟨M, hM, left, right ≫ g.hom, by
    rw [← Category.assoc, hfac]
    rfl⟩

/-- The additive two-sided Hom ideal of maps factoring through the selected
additive subcategory. -/
def factorThroughSelectedIdeal (K : Set (Fin S.n)) :
    CategoricalIdeal.HomIdeal (S.SelectedAddCategory Set.univ) where
  hom X Y :=
    { carrier := S.factorThroughSelectedMaps K X Y
      zero_mem' := S.factorsThroughSelected_zero K
      add_mem' := fun hf hg ↦ hf.add S hg
      neg_mem' := fun hf ↦ hf.neg S }
  precomp := S.factorThroughSelectedMaps_precomp
  postcomp := S.factorThroughSelectedMaps_postcomp

/-- The literal factor category `add(ind mod A) / [add K]`. -/
abbrev FactorCategory (K : Set (Fin S.n)) :=
  CategoryTheory.Quotient (S.factorThroughSelectedIdeal K).rel

noncomputable instance factorCategoryPreadditive (K : Set (Fin S.n)) :
    Preadditive (S.FactorCategory K) :=
  (S.factorThroughSelectedIdeal K).quotientPreadditive

/-- The quotient functor from the complete additive category. -/
abbrev factorFunctor (K : Set (Fin S.n)) :
    S.SelectedAddCategory Set.univ ⥤ S.FactorCategory K :=
  CategoryTheory.Quotient.functor (S.factorThroughSelectedIdeal K).rel

noncomputable instance factorFunctor_additive (K : Set (Fin S.n)) :
    (S.factorFunctor K).Additive :=
  CategoryTheory.Quotient.functor_additive
    (S.factorThroughSelectedIdeal K).rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        (S.factorThroughSelectedIdeal K).add_compatible
          f₁ f₂ g₁ g₂ hf hg)

noncomputable instance factorCategoryLinear (K : Set (Fin S.n)) :
    Linear k (S.FactorCategory K) :=
  (S.factorThroughSelectedIdeal K).quotientLinear

noncomputable instance factorFunctor_linear (K : Set (Fin S.n)) :
    (S.factorFunctor K).Linear k :=
  (S.factorThroughSelectedIdeal K).quotientFunctorLinear

/-- The complete additive category has finite biproducts. -/
theorem selectedAddCategoryHasFiniteBiproducts :
    HasFiniteBiproducts (S.SelectedAddCategory Set.univ) where
  out n :=
    { has_biproduct := fun X ↦ by
        classical
        let B : S.SelectedAddCategory Set.univ :=
          ⟨biproduct (fun j : Fin n ↦ (X j).obj),
            S.almostSplitSkeleton.inAdd_biproduct
              (FintypeCat.of (Fin n)) (fun j ↦ (X j).obj)
              (fun j ↦ (X j).property)⟩
        let b : Bicone X :=
          { pt := B
            π := fun j ↦ ObjectProperty.homMk
              (biproduct.π (fun i : Fin n ↦ (X i).obj) j)
            ι := fun j ↦ ObjectProperty.homMk
              (biproduct.ι (fun i : Fin n ↦ (X i).obj) j)
            ι_π := by
              intro j i
              apply ObjectProperty.hom_ext
              by_cases h : j = i
              · subst i
                simpa using biproduct.ι_π_self
                  (fun t : Fin n ↦ (X t).obj) j
              · simpa [h] using biproduct.ι_π_ne
                  (fun t : Fin n ↦ (X t).obj) h }
        apply HasBiproduct.mk
        exact
          { bicone := b
            isBilimit := isBilimitOfTotal b (by
              let U := ObjectProperty.ι
                (S.almostSplitSkeleton.generated Set.univ).carrier
              apply U.map_injective
              rw [U.map_sum, U.map_id]
              exact biproduct.total) } }

noncomputable instance selectedAddCategory_hasFiniteBiproducts :
    HasFiniteBiproducts (S.SelectedAddCategory Set.univ) :=
  S.selectedAddCategoryHasFiniteBiproducts

/-- The full additive closure of the skeleton is closed under retracts and is
therefore idempotent-complete. -/
theorem selectedAddCategory_isIdempotentComplete :
    IsIdempotentComplete (S.SelectedAddCategory Set.univ) := by
  refine ⟨?_⟩
  intro X p hp
  have hp' : p.hom ≫ p.hom = p.hom :=
    congrArg (fun q ↦ q.hom) hp
  obtain ⟨Z, i, e, hi, he⟩ :=
    IsIdempotentComplete.idempotents_split X.obj p.hom hp'
  let r : Retract Z X.obj :=
    { i := i
      r := e
      retract := hi }
  let Z' : S.SelectedAddCategory Set.univ :=
    ⟨Z, S.almostSplitSkeleton.inAdd_of_retract r X.property⟩
  refine ⟨Z', ObjectProperty.homMk i, ObjectProperty.homMk e, ?_, ?_⟩
  · apply ObjectProperty.hom_ext
    exact hi
  · apply ObjectProperty.hom_ext
    exact he

noncomputable instance selectedAddCategory_idempotentComplete :
    IsIdempotentComplete (S.SelectedAddCategory Set.univ) :=
  S.selectedAddCategory_isIdempotentComplete

/-- The factor category inherits finite biproducts from its source. -/
theorem factorCategoryHasFiniteBiproducts (K : Set (Fin S.n)) :
    HasFiniteBiproducts (S.FactorCategory K) := by
  letI : HasFiniteBiproducts (S.SelectedAddCategory Set.univ) :=
    S.selectedAddCategoryHasFiniteBiproducts
  letI : HasFiniteProducts (S.FactorCategory K) :=
    Functor.hasFiniteProducts_of_additive_of_essSurj (S.factorFunctor K)
  exact HasFiniteBiproducts.of_hasFiniteProducts

noncomputable instance factorCategory_hasFiniteBiproducts
    (K : Set (Fin S.n)) : HasFiniteBiproducts (S.FactorCategory K) :=
  S.factorCategoryHasFiniteBiproducts K

noncomputable instance factorCategory_hasBinaryBiproducts
    (K : Set (Fin S.n)) : HasBinaryBiproducts (S.FactorCategory K) :=
  HasBinaryBiproducts.of_hasBinaryCoproducts

/-- Completeness of the finite skeleton puts every finitely generated module
in the additive closure of all skeleton labels. -/
theorem inAdd_univ (X : RightModule.FinitelyGeneratedCategory A) :
    S.almostSplitSkeleton.InAdd Set.univ X := by
  obtain ⟨n, a, ⟨e⟩⟩ := S.fgObj_decomposition (k := k) X
  exact ⟨{
    index := FintypeCat.of (Fin n)
    label := a
    mem := fun _ ↦ Set.mem_univ _
    iso := e }⟩

/-- A finitely generated module regarded canonically as an object of the
complete additive subcategory. -/
abbrev ambientAddObject (X : RightModule.FinitelyGeneratedCategory A) :
    S.SelectedAddCategory Set.univ :=
  ⟨X, S.inAdd_univ X⟩

/-- The fully faithful inclusion into the explicit additive closure of the
finite skeleton. -/
abbrev ambientAddFunctor :
    RightModule.FinitelyGeneratedCategory A ⥤
      S.SelectedAddCategory Set.univ where
  obj := S.ambientAddObject
  map f := ObjectProperty.homMk f
  map_id _ := by
    apply ObjectProperty.hom_ext
    rfl
  map_comp _ _ := by
    apply ObjectProperty.hom_ext
    rfl

noncomputable instance ambientAddFunctor_additive :
    S.ambientAddFunctor.Additive where
  map_add := by
    intro X Y f g
    apply ObjectProperty.hom_ext
    rfl

noncomputable instance ambientAddFunctor_linear :
    S.ambientAddFunctor.Linear k where
  map_smul := by
    intro X Y r f
    apply ObjectProperty.hom_ext
    rfl

/-- The literal quotient functor defined on every finitely generated right
module. -/
abbrev factorModuleFunctor (K : Set (Fin S.n)) :
    RightModule.FinitelyGeneratedCategory A ⥤ S.FactorCategory K :=
  S.ambientAddFunctor ⋙ S.factorFunctor K

/-- A chosen ambient indecomposable as an object of the complete additive
category. -/
def ambientAddPoint (i : Fin S.n) : S.SelectedAddCategory Set.univ :=
  ⟨S.fgObj i, S.almostSplitSkeleton.inAdd_obj (Set.mem_univ i)⟩

/-- Labels which survive the quotient by `add K`. -/
abbrev SurvivingLabel (K : Set (Fin S.n)) := {i : Fin S.n // i ∉ K}

/-- A surviving selected indecomposable in the factor category. -/
abbrev factorObject (K : Set (Fin S.n)) (x : S.SurvivingLabel K) :
    S.FactorCategory K :=
  (S.factorFunctor K).obj (S.ambientAddPoint x.1)

/-- A selected label becomes a zero object in the factor category. -/
theorem factorObject_isZero_of_mem
    (K : Set (Fin S.n)) {i : Fin S.n} (hi : i ∈ K) :
    IsZero ((S.factorFunctor K).obj (S.ambientAddPoint i)) := by
  let I := S.factorThroughSelectedIdeal K
  let F := S.factorFunctor K
  rw [IsZero.iff_id_eq_zero, ← F.map_id]
  apply (I.map_eq_zero_iff (𝟙 (S.ambientAddPoint i))).2
  exact ⟨S.fgObj i, S.almostSplitSkeleton.inAdd_obj hi,
    𝟙 _, 𝟙 _, by
      change 𝟙 (S.fgObj i) ≫ 𝟙 (S.fgObj i) = 𝟙 (S.fgObj i)
      simp⟩

/-- A label outside `K` remains nonzero in the factor category. -/
theorem factorObject_not_isZero
    (K : Set (Fin S.n)) (x : S.SurvivingLabel K) :
    ¬ IsZero (S.factorObject K x) := by
  let I := S.factorThroughSelectedIdeal K
  let F := S.factorFunctor K
  intro hzero
  have hqid : 𝟙 (S.factorObject K x) = 0 :=
    (IsZero.iff_id_eq_zero _).1 hzero
  have hidzero : F.map (𝟙 (S.ambientAddPoint x.1)) = 0 := by
    simpa only [F.map_id] using hqid
  have hfac : S.FactorsThroughSelected K (𝟙 (S.fgObj x.1)) :=
    (I.map_eq_zero_iff (𝟙 (S.ambientAddPoint x.1))).1 hidzero
  rcases hfac with ⟨M, hM, left, right, hcomp⟩
  let r : Retract (S.fgObj x.1) M :=
    { i := left, r := right, retract := hcomp }
  exact x.2 (S.almostSplitSkeleton.index_mem_of_retract_inAdd r hM)

/-- The quotient functor on a surviving object's endomorphisms, bundled as a
ring homomorphism. -/
def factorEndRingHom (K : Set (Fin S.n)) (x : S.SurvivingLabel K) :
    End (S.ambientAddPoint x.1) →+* End (S.factorObject K x) where
  toFun := (S.factorFunctor K).map
  map_one' := (S.factorFunctor K).map_id _
  map_mul' f g := (S.factorFunctor K).map_comp g f
  map_zero' := (S.factorFunctor K).map_zero _ _
  map_add' _ _ := (S.factorFunctor K).map_add

private theorem isLocalRing_of_surjective_ringHom
    {R T : Type*} [Ring R] [Ring T] [IsLocalRing R] [Nontrivial T]
    (φ : R →+* T) (hφ : Function.Surjective φ) : IsLocalRing T := by
  apply IsLocalRing.of_isUnit_or_isUnit_one_sub_self
  intro t
  obtain ⟨r, rfl⟩ := hφ t
  have hsum : IsUnit (r + (1 - r)) := by
    rw [add_sub_cancel]
    exact isUnit_one
  rcases IsLocalRing.isUnit_or_isUnit_of_isUnit_add hsum with hr | hr
  · exact Or.inl (hr.map φ)
  · exact Or.inr (by
      simpa only [map_sub, map_one] using hr.map φ)

/-- A surviving indecomposable retains a local endomorphism ring in the
literal factor category. -/
theorem factorObject_end_isLocalRing
    (K : Set (Fin S.n)) (x : S.SurvivingLabel K) :
    IsLocalRing (End (S.factorObject K x)) := by
  let U := ObjectProperty.ι
    (S.almostSplitSkeleton.generated Set.univ).carrier
  letI : IsLocalRing (End (S.ambientAddPoint x.1)) := by
    letI : IsLocalRing (End (U.obj (S.ambientAddPoint x.1))) := by
      change IsLocalRing (End (S.fgObj x.1))
      exact S.fgObj_end_isLocalRing x.1
    exact MagnitudeConjecture.RingEquiv.isLocalRing_noncomm
      (CategoryTheory.Functor.endRingEquivOfFullyFaithful U
        (S.ambientAddPoint x.1)).symm
  letI : Nontrivial (End (S.factorObject K x)) :=
    ⟨1, 0, by
      intro h
      apply S.factorObject_not_isZero K x
      rw [IsZero.iff_id_eq_zero]
      exact h⟩
  exact isLocalRing_of_surjective_ringHom (S.factorEndRingHom K x)
    (S.factorFunctor K).map_surjective

/-- A surviving skeleton object remains indecomposable after quotienting. -/
theorem factorObject_indecomposable
    (K : Set (Fin S.n)) (x : S.SurvivingLabel K) :
    Indecomposable (S.factorObject K x) := by
  letI : IsLocalRing (End (S.factorObject K x)) :=
    S.factorObject_end_isLocalRing K x
  exact MagnitudeConjecture.CategoryTheory.indecomposable_of_local_end
    (S.factorObject K x)

/-- A morphism in the full additive subcategory is radical whenever its
underlying module morphism is radical. -/
theorem selectedAdd_isRadicalMorphism_of_hom
    {X Y : S.SelectedAddCategory Set.univ} (f : X ⟶ Y)
    (hf : IsRadicalMorphism f.hom) : IsRadicalMorphism f := by
  intro g
  let U := ObjectProperty.ι
    (S.almostSplitSkeleton.generated Set.univ).carrier
  let q := 𝟙 X - f ≫ g
  have hq : IsIso (U.map q) := by
    dsimp only [U, q]
    exact hf g.hom
  letI : IsIso (U.map q) := hq
  exact Functor.ReflectsIsomorphisms.reflects U q

private theorem isZero_source_of_radical_isIso
    {C : Type*} [CategoryTheory.Category C] [Preadditive C]
    {X Y : C} (f : X ⟶ Y) (hf : IsRadicalMorphism f) [IsIso f] :
    IsZero X := by
  let r := inv f
  have hr : f ≫ r = 𝟙 X := by simp [r]
  have hi : IsIso (𝟙 X - f ≫ r) := hf r
  have hzero : 𝟙 X - f ≫ r = 0 := by rw [hr, sub_self]
  haveI : IsIso (0 : X ⟶ X) := hzero ▸ hi
  exact (IsZero.iff_isSplitEpi_eq_zero (0 : X ⟶ X)).2 rfl

/-- Distinct surviving skeleton labels remain nonisomorphic in the literal
factor category. -/
theorem factorObject_skeletal
    (K : Set (Fin S.n)) {x y : S.SurvivingLabel K}
    (e : Nonempty (S.factorObject K x ≅ S.factorObject K y)) : x = y := by
  let I := S.factorThroughSelectedIdeal K
  let F := S.factorFunctor K
  obtain ⟨e⟩ := e
  obtain ⟨f, hf⟩ := F.map_surjective e.hom
  have hsplit : IsSplitMono f.hom := by
    by_contra hnot
    have hradModule : IsRadicalMorphism f.hom :=
      (S.almostSplitSkeleton.isRadicalMorphism_iff_not_isSplitMono_from_obj
        f.hom).2 hnot
    have hradAdd : IsRadicalMorphism f :=
      S.selectedAdd_isRadicalMorphism_of_hom f hradModule
    have hradMap : IsRadicalMorphism (F.map f) :=
      I.map_isRadicalMorphism f hradAdd
    have hradHom : IsRadicalMorphism e.hom := by
      rw [← hf]
      exact hradMap
    letI : IsIso e.hom := e.isIso_hom
    have hzero : IsZero (S.factorObject K x) :=
      isZero_source_of_radical_isIso e.hom hradHom
    exact (S.factorObject_not_isZero K x hzero).elim
  obtain ⟨sm⟩ := hsplit.exists_splitMono
  let rt : Retract (S.fgObj x.1) (S.fgObj y.1) :=
    { i := f.hom
      r := sm.retraction
      retract := sm.id }
  have hxy : x.1 = y.1 := by
    simpa only [Set.mem_singleton_iff] using
      S.almostSplitSkeleton.index_mem_of_retract_inAdd rt
        (S.almostSplitSkeleton.inAdd_obj (Set.mem_singleton y.1))
  apply Subtype.ext
  exact hxy

/-- Hom spaces in the literal factor category remain finite-dimensional. -/
noncomputable instance factorCategoryHomFinite
    (K : Set (Fin S.n)) (X Y : S.FactorCategory K) :
    Module.Finite k (X ⟶ Y) := by
  let F := S.factorFunctor K
  letI : Module.Finite k
      (X.as.obj ⟶ Y.as.obj) := inferInstance
  letI : Module.Finite k (X.as ⟶ Y.as) :=
    Module.Finite.equiv
      (InducedCategory.homLinearEquiv (R := k)).symm
  exact Module.Finite.of_surjective
    (F.mapLinearMap k (X := X.as) (Y := Y.as)) F.map_surjective

/-- The two canonical ways to send a skeleton object to the factor category
are equal up to the proof carried by the full additive subcategory. -/
def factorAmbientPointIsoFactorModule
    (K : Set (Fin S.n)) (i : Fin S.n) :
    (S.factorFunctor K).obj (S.ambientAddPoint i) ≅
      (S.factorModuleFunctor K).obj (S.fgObj i) :=
  eqToIso (by
    apply CategoryTheory.Quotient.ext
    apply ObjectProperty.FullSubcategory.ext
    rfl)

/-- Removing the summands outside a decidable subfamily does not change a
finite biproduct when all of those summands are zero. -/
def factorBiproductIsoSubtypeOfIsZero
    {K : Set (Fin S.n)} {J : Type*} [Fintype J]
    (f : J → S.FactorCategory K) (p : J → Prop) [DecidablePred p]
    (hzero : ∀ j, ¬ p j → IsZero (f j)) :
    (⨁ f) ≅ (⨁ Subtype.restrict p f) where
  hom := biproduct.toSubtype f p
  inv := biproduct.fromSubtype f p
  hom_inv_id := by
    classical
    rw [biproduct.toSubtype_fromSubtype]
    apply biproduct.hom_ext
    intro j
    by_cases hj : p j
    · simp [hj]
    · rw [biproduct.map_π, if_neg hj, comp_zero, Category.id_comp]
      exact (hzero j hj).eq_of_tgt 0 (biproduct.π f j)
  inv_hom_id := biproduct.fromSubtype_toSubtype f p

/-- Every object of the literal factor category is a finite biproduct of the
surviving skeleton objects. -/
theorem factorCategory_obj_decomposition
    (K : Set (Fin S.n)) (X : S.FactorCategory K) :
    ∃ (m : ℕ) (label : Fin m → S.SurvivingLabel K),
      Nonempty (X ≅ ⨁ fun i ↦ S.factorObject K (label i)) := by
  classical
  let FM := S.factorModuleFunctor K
  obtain ⟨n, a, ⟨e⟩⟩ := S.fgObj_decomposition (k := k) X.as.obj
  let J := {i : Fin n // a i ∉ K}
  let ε : J ≃ Fin (Fintype.card J) := Fintype.equivFin J
  let label : Fin (Fintype.card J) → S.SurvivingLabel K :=
    fun t ↦ ⟨a (ε.symm t), (ε.symm t).2⟩
  let eSource : X ≅ FM.obj X.as.obj :=
    eqToIso (by
      apply CategoryTheory.Quotient.ext
      apply ObjectProperty.FullSubcategory.ext
      rfl)
  let eAll : X ≅ ⨁ fun i : Fin n ↦ FM.obj (S.fgObj (a i)) :=
    eSource.trans ((FM.mapIso e).trans
      (FM.mapBiproduct (fun i : Fin n ↦ S.fgObj (a i))))
  let eDelete :
      (⨁ fun i : Fin n ↦ FM.obj (S.fgObj (a i))) ≅
        ⨁ fun i : J ↦ FM.obj (S.fgObj (a i.1)) :=
    S.factorBiproductIsoSubtypeOfIsZero
      (fun i : Fin n ↦ FM.obj (S.fgObj (a i)))
      (fun i ↦ a i ∉ K) (by
        intro i hi
        have hiK : a i ∈ K := not_not.mp hi
        exact (S.factorObject_isZero_of_mem K hiK).of_iso
          (S.factorAmbientPointIsoFactorModule K (a i)))
  let eReindex :
      (⨁ fun i : J ↦ FM.obj (S.fgObj (a i.1))) ≅
        ⨁ fun t : Fin (Fintype.card J) ↦
          S.factorObject K (label t) :=
    biproduct.whiskerEquiv ε
      (fun i : J ↦ eqToIso (by
        apply CategoryTheory.Quotient.ext
        apply ObjectProperty.FullSubcategory.ext
        simp [label, FM]
        rfl))
  exact ⟨Fintype.card J, label,
    ⟨eAll.trans (eDelete.trans eReindex)⟩⟩

/-- Split a nonempty finite biproduct into its first summand and the remaining
tail. -/
private def finSuccBiproductIso
    {K : Set (Fin S.n)} {m : ℕ}
    (F : Fin (m + 1) → S.FactorCategory K) :
    (⨁ F) ≅ (F 0 ⊞ (⨁ fun i : Fin m ↦ F i.succ)) := by
  let T : Fin m → S.FactorCategory K := fun i ↦ F i.succ
  let q : (⨁ F) ⟶ (⨁ T) :=
    biproduct.lift fun i : Fin m ↦ biproduct.π F i.succ
  let r : (⨁ T) ⟶ (⨁ F) :=
    biproduct.desc fun i : Fin m ↦ biproduct.ι F i.succ
  have hhead_q : biproduct.ι F 0 ≫ q = 0 := by
    apply biproduct.hom_ext
    intro i
    rw [Category.assoc, biproduct.lift_π, zero_comp]
    exact biproduct.ι_π_ne F (Fin.succ_ne_zero i).symm
  have htail_q (i : Fin m) :
      biproduct.ι F i.succ ≫ q = biproduct.ι T i := by
    apply biproduct.hom_ext
    intro j
    by_cases h : i = j
    · subst h
      simp [q, T, Category.assoc]
    · rw [Category.assoc, biproduct.lift_π,
          biproduct.ι_π_ne F (fun hs ↦ h (Fin.succ_inj.mp hs)),
          biproduct.ι_π_ne T h]
  have hr_head : r ≫ biproduct.π F 0 = 0 := by
    apply biproduct.hom_ext'
    intro i
    rw [← Category.assoc, biproduct.ι_desc, comp_zero]
    exact biproduct.ι_π_ne F (Fin.succ_ne_zero i)
  have hr_tail (i : Fin m) :
      r ≫ biproduct.π F i.succ = biproduct.π T i := by
    apply biproduct.hom_ext'
    intro j
    by_cases h : j = i
    · subst h
      simp [r, T]
    · rw [← Category.assoc, biproduct.ι_desc,
          biproduct.ι_π_ne F (fun hs ↦ h (Fin.succ_inj.mp hs)),
          biproduct.ι_π_ne T h]
  have hrq : r ≫ q = 𝟙 (⨁ T) := by
    apply biproduct.hom_ext'
    intro i
    rw [← Category.assoc, biproduct.ι_desc, htail_q, Category.comp_id]
  have hhead_qr : biproduct.ι F 0 ≫ q ≫ r = 0 := by
    rw [← Category.assoc, hhead_q, zero_comp]
  have htail_qr (i : Fin m) :
      biproduct.ι F i.succ ≫ q ≫ r = biproduct.ι F i.succ := by
    rw [← Category.assoc, htail_q, biproduct.ι_desc]
  exact
    { hom := biprod.lift (biproduct.π F 0) q
      inv := biprod.desc (biproduct.ι F 0) r
      hom_inv_id := by
        apply biproduct.hom_ext'
        intro j
        refine Fin.cases ?_ (fun i ↦ ?_) j
        · simpa using hhead_qr
        · simpa using htail_qr i
      inv_hom_id := by
        apply biprod.hom_ext'
        · apply biprod.hom_ext
          · simp
          · simpa [Category.assoc] using hhead_q
        · apply biprod.hom_ext
          · simpa [Category.assoc] using hr_head
          · simpa [Category.assoc] using hrq }

/-- The surviving labels exhaust all indecomposable objects of the literal
factor category. -/
theorem factorCategory_obj_complete
    (K : Set (Fin S.n)) (X : S.FactorCategory K)
    (hX : Indecomposable X) :
    ∃ x : S.SurvivingLabel K,
      Nonempty (X ≅ S.factorObject K x) := by
  classical
  obtain ⟨m, label, ⟨e⟩⟩ := S.factorCategory_obj_decomposition K X
  cases m with
  | zero =>
      have hzeroSum : IsZero
          (⨁ fun i : Fin 0 ↦ S.factorObject K (label i)) := by
        rw [IsZero.iff_id_eq_zero]
        apply biproduct.hom_ext
        intro i
        exact Fin.elim0 i
      exact (hX.1 (hzeroSum.of_iso e)).elim
  | succ m =>
      let F : Fin (m + 1) → S.FactorCategory K :=
        fun i ↦ S.factorObject K (label i)
      let eSplit : X ≅ F 0 ⊞ (⨁ fun i : Fin m ↦ F i.succ) :=
        e.trans (S.finSuccBiproductIso F)
      rcases hX.2 _ _ eSplit with hhead | htail
      · exact ((S.factorObject_not_isZero K (label 0)) hhead).elim
      · haveI : IsIso
            (biprod.inl : F 0 ⟶ F 0 ⊞ (⨁ fun i : Fin m ↦ F i.succ)) :=
          (Biprod.isIso_inl_iff_isZero _ _).2 htail
        exact ⟨label 0, ⟨eSplit.trans (asIso biprod.inl).symm⟩⟩

/-- On a biproduct of surviving representatives, every endomorphism killed by
the quotient functor is nilpotent. -/
theorem factorFunctor_kernel_isNilpotent_on_surviving_biproduct
    (K : Set (Fin S.n)) {m : ℕ}
    (label : Fin m → S.SurvivingLabel K)
    (f : End (⨁ fun i ↦ S.ambientAddPoint (label i).1))
    (hf : (S.factorFunctor K).map f = 0) : IsNilpotent f := by
  let I := S.factorThroughSelectedIdeal K
  let Q := S.fgNilpotentRadicalData
  have hfactor : S.FactorsThroughSelected K f.hom :=
    (I.map_eq_zero_iff f).1 hf
  obtain ⟨M, hM, left, right, hcomp⟩ := hfactor
  let U := ObjectProperty.ι
    (S.almostSplitSkeleton.generated Set.univ).carrier
  let φ : U.obj (⨁ fun i ↦ S.ambientAddPoint (label i).1) ≅
      ⨁ fun i ↦ S.fgObj (label i).1 :=
    U.mapBiproduct (fun i ↦ S.ambientAddPoint (label i).1)
  let leftB : (⨁ fun i ↦ S.fgObj (label i).1) ⟶ M :=
    φ.inv ≫ left
  have hleftB : leftB ∈ Q.ideal.hom _ M := by
    apply
      QuotientSubmoduleEquidistribution.Iyama.mem_radicalIdeal_of_biproduct_source_components
        Q leftB
    intro i
    apply (Q.mem_ideal_iff _).2
    let a : S.fgObj (label i).1 ⟶ M :=
      biproduct.ι (fun j : Fin m ↦ S.fgObj (label j).1) i ≫ leftB
    have haNot : ¬ IsSplitMono a := by
      intro ha
      letI : IsSplitMono a := ha
      let r : Retract (S.fgObj (label i).1) M :=
        { i := a
          r := retraction a
          retract := IsSplitMono.id a }
      exact (label i).2
        (S.almostSplitSkeleton.index_mem_of_retract_inAdd r hM)
    exact
      (S.almostSplitSkeleton.isRadicalMorphism_iff_not_isSplitMono_from_obj
        a).2 haNot
  have hleft : left ∈ Q.ideal.hom _ M := by
    have heq : φ.hom ≫ leftB = left := by
      dsimp only [leftB]
      simpa only [Category.assoc] using φ.hom_inv_id_assoc left
    rw [← heq]
    exact Q.ideal.precomp φ.hom hleftB
  have hfRad : f.hom ∈ Q.ideal.hom _ _ := by
    rw [← hcomp]
    exact Q.ideal.postcomp right hleft
  let e : End (⨁ fun i ↦ S.ambientAddPoint (label i).1) ≃+*
      End ((⨁ fun i ↦ S.ambientAddPoint (label i).1).obj) :=
    { InducedCategory.endEquiv with
      map_add' := fun _ _ ↦ rfl }
  have hnil : IsNilpotent (e f) := by
    have hef : e f = End.of f.hom := rfl
    rw [hef]
    exact Q.isNilpotent_end_of_mem_ideal hfRad
  have hback := hnil.map e.symm.toRingHom
  simpa using hback

/-- The literal factor category is idempotent-complete. -/
theorem factorCategory_isIdempotentComplete
    (K : Set (Fin S.n)) : IsIdempotentComplete (S.FactorCategory K) := by
  let F := S.factorFunctor K
  apply
    QuotientSubmoduleEquidistribution.CategoryTheory.IdempotentLifting.isIdempotentComplete_of_objectwise_nilpotent_kernel
      F
  intro X
  obtain ⟨m, label, ⟨e⟩⟩ := S.factorCategory_obj_decomposition K X
  let Y : S.SelectedAddCategory Set.univ :=
    ⨁ fun i : Fin m ↦ S.ambientAddPoint (label i).1
  let ε : F.obj Y ≅ X :=
    (F.mapBiproduct
      (fun i : Fin m ↦ S.ambientAddPoint (label i).1)).trans e.symm
  refine ⟨Y, ε, ?_⟩
  intro f hf
  exact S.factorFunctor_kernel_isNilpotent_on_surviving_biproduct
    K label f hf

noncomputable instance factorCategory_idempotentComplete
    (K : Set (Fin S.n)) : IsIdempotentComplete (S.FactorCategory K) :=
  S.factorCategory_isIdempotentComplete K

/-- The biproduct of all surviving representatives is an additive generator
of the literal factor category. -/
def factorAdditiveGenerator (K : Set (Fin S.n)) : S.FactorCategory K := by
  classical
  exact ⨁ fun x : S.SurvivingLabel K ↦ S.factorObject K x

/-- Every quotient object is a retract of a finite biproduct of copies of the
surviving additive generator. -/
theorem factorAdditiveGenerator_isFiniteAddGenerator
    (K : Set (Fin S.n)) :
    MagnitudeConjecture.CategoryTheory.IsFiniteAddGenerator
      (S.factorAdditiveGenerator K) := by
  classical
  intro X
  obtain ⟨m, label, ⟨e⟩⟩ := S.factorCategory_obj_decomposition K X
  let F : Fin m → S.FactorCategory K :=
    fun j ↦ S.factorObject K (label j)
  let intoGenerator : ∀ j : Fin m,
      F j ⟶ S.factorAdditiveGenerator K :=
    fun j ↦ biproduct.ι
      (fun x : S.SurvivingLabel K ↦ S.factorObject K x) (label j)
  let outOfGenerator : ∀ j : Fin m,
      S.factorAdditiveGenerator K ⟶ F j :=
    fun j ↦ biproduct.π
      (fun x : S.SurvivingLabel K ↦ S.factorObject K x) (label j)
  let iB : (⨁ F) ⟶
      ⨁ fun _ : Fin m ↦ S.factorAdditiveGenerator K :=
    biproduct.map intoGenerator
  let rB : (⨁ fun _ : Fin m ↦ S.factorAdditiveGenerator K) ⟶ ⨁ F :=
    biproduct.map outOfGenerator
  have hir : iB ≫ rB = 𝟙 (⨁ F) := by
    apply biproduct.hom_ext'
    intro j
    apply biproduct.hom_ext
    intro l
    by_cases hjl : j = l
    · subst l
      simp [iB, rB, intoGenerator, outOfGenerator]
      change biproduct.ι
          (fun x : S.SurvivingLabel K ↦ S.factorObject K x) (label j) ≫
        biproduct.π
          (fun x : S.SurvivingLabel K ↦ S.factorObject K x) (label j) =
        𝟙 (S.factorObject K (label j))
      exact biproduct.ι_π_self _ _
    · simp [iB, rB, intoGenerator, outOfGenerator, hjl]
  exact ⟨{
    n := m
    retract := {
      i := e.hom ≫ iB
      r := rB ≫ e.inv
      retract := by
        rw [Category.assoc, ← Category.assoc iB, hir]
        simp } }⟩

/-- The quotient additive generator has an Artinian endomorphism ring because
its endomorphism space is finite-dimensional over the coefficient field. -/
noncomputable instance factorAdditiveGeneratorEndArtinian
    (K : Set (Fin S.n)) :
    IsArtinianRing (End (S.factorAdditiveGenerator K)) := by
  letI : Module.Finite k (End (S.factorAdditiveGenerator K)) :=
    S.factorCategoryHomFinite K _ _
  exact IsArtinianRing.of_finite k (End (S.factorAdditiveGenerator K))

/-- The literal factor category has a nilpotent categorical radical. -/
def factorNilpotentRadicalData (K : Set (Fin S.n)) :
    NilpotentRadicalData (S.FactorCategory K) :=
  MagnitudeConjecture.CategoryTheory.nilpotentRadicalDataOfArtinianGenerator
    (S.factorAdditiveGenerator K)
    (S.factorAdditiveGenerator_isFiniteAddGenerator K)

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
