import MagnitudeConjecture.Algebra.RightModuleGeneratedAtIdempotent
import MagnitudeConjecture.Algebra.RightModuleTranslation
import MagnitudeConjecture.Algebra.RightModulePrimitiveBoundary
import MagnitudeConjecture.CategoryTheory.AlmostSplitExtVanishing

/-! # Ext vanishing for modules generated at an idempotent -/
set_option autoImplicit false
noncomputable section
open CategoryTheory CategoryTheory.Limits CategoryTheory.Abelian
open QuotientSubmoduleEquidistribution
open scoped ModuleCat.Algebra
namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
universe u
variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
variable [HasExt.{u} (FGModuleCat.{u} Aᵐᵒᵖ)]
variable (S : FiniteIndecomposableSkeleton k A)

/-- Hom vanishing into the translate annihilates extensions out of its
nonprojective endpoint. No directedness hypothesis is needed. -/
theorem extOne_eq_zero_of_hom_to_rightTranslation_zero
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)})
    (K : FinitelyGeneratedCategory A)
    (hHom : ∀ f : K ⟶ S.fgObj (S.rightTranslationLabel z), f = 0)
    (xi : Ext.{u} (S.fgObj z.1) K 1) : xi = 0 := by
  let : EnoughProjectives (FGModuleCat.{u} Aᵐᵒᵖ) :=
    MagnitudeConjecture.fgModuleCat_enoughProjectives Aᵐᵒᵖ
  let B := S.minimalRightAlmostSplitAt z.1
  have : Epi B.map :=
    IndecomposableSkeleton.IsRightAlmostSplit.epi_of_not_projective_obj
      S.almostSplitSkeleton B.map B.rightAlmostSplit z.2
  let T := ShortComplex.mk (kernel.ι B.map) B.map (kernel.condition B.map)
  have ht : T.ShortExact := { exact := ShortComplex.exact_kernel B.map }
  apply MagnitudeConjecture.CategoryTheory.extOne_eq_zero_of_hom_to_almostSplit_kernel_zero
    ht B.rightAlmostSplit K ?_ xi
  intro f
  apply (cancel_mono (S.rightTranslationKernelIso z).hom).1
  simpa using hHom (f ≫ (S.rightTranslationKernelIso z).hom)

/-- A module generated at e has no extensions from a nonprojective module
whose AR translate is killed by e. -/
theorem extOne_eq_zero_of_generated_at_idempotent
    {e : A} (he : IsIdempotentElem e)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)})
    (K : FinitelyGeneratedCategory A)
    (hK : IsGeneratedAtIdempotent (k := k) e K)
    (htau : ∀ y : S.fgObj (S.rightTranslationLabel z), MulOpposite.op e • y = 0)
    (xi : Ext.{u} (S.fgObj z.1) K 1) : xi = 0 :=
  S.extOne_eq_zero_of_hom_to_rightTranslation_zero z K
    (fun f ↦ hom_eq_zero_of_generated_at_idempotent he hK htau f) xi

/-- In particular, the module generated by coordinate relations satisfies
this Ext vanishing. -/
theorem generatedCoordinateRelations_extOne_eq_zero
    {e : A} (he : IsIdempotentElem e)
    (z : {z : Fin S.n // ¬ Projective (S.fgObj z)})
    (V : FinitelyGeneratedCategory A)
    (R : Submodule k (idempotentCoordinate (k := k) e V))
    (htau : ∀ y : S.fgObj (S.rightTranslationLabel z), MulOpposite.op e • y = 0)
    (xi : Ext.{u} (S.fgObj z.1) (generatedCoordinateRelationsFGObj e V R) 1) :
    xi = 0 :=
  S.extOne_eq_zero_of_generated_at_idempotent he z _
    (generatedCoordinateRelations_isGenerated he V R) htau xi

/-- Every tau-projective of the primitive factor has vanishing Ext into a
module generated at e, including the ambient projective case. -/
theorem factorProjective_extOne_eq_zero_of_generated
    {e : A} (D : PrimitiveIdempotentData e)
    (p : S.FactorProjectiveLabel (S.primitiveKilledLabels D))
    (K : FinitelyGeneratedCategory A)
    (hK : IsGeneratedAtIdempotent (k := k) e K)
    (xi : Ext.{u} (S.fgObj p.1.1) K 1) : xi = 0 := by
  rcases PrimitiveMultiplicityInput.factorProjective_ambient_projective_or_translation_killed
    (S := S) (S.primitiveMultiplicityInput D) p.1 p.2 with hp | ⟨hnp, hk⟩
  · let := hp
    exact Ext.eq_zero_of_projective xi
  · exact S.extOne_eq_zero_of_generated_at_idempotent D.idempotent
      ⟨p.1.1, hnp⟩ K hK hk xi

/-- Maps from the primitive factor's tau-projectives lift across every
short exact sequence whose kernel is generated at e. -/
theorem factorProjective_hom_lift_of_generated_kernel
    {e : A} (D : PrimitiveIdempotentData e)
    (p : S.FactorProjectiveLabel (S.primitiveKilledLabels D))
    {T : ShortComplex (FinitelyGeneratedCategory A)} (hT : T.ShortExact)
    (hK : IsGeneratedAtIdempotent (k := k) e T.X₁)
    (f : S.fgObj p.1.1 ⟶ T.X₃) :
    ∃ g : S.fgObj p.1.1 ⟶ T.X₂, g ≫ T.g = f :=
  MagnitudeConjecture.CategoryTheory.hom_lift_of_extOne_eq_zero hT _
    (S.factorProjective_extOne_eq_zero_of_generated D p T.X₁ hK) f

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
