import MagnitudeConjecture.Algebra.CornerQuotient
import MagnitudeConjecture.Algebra.RightModuleSupportDirected

/-!
# Primitive coordinates in literal support quotients

For a primitive vertex belonging to a selected support, its image in the
literal complementary-vertex quotient is nonzero and primitive.  The right
ideal generated by this image is therefore the actual projective coordinate
in the support-algebra skeleton.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open scoped ModuleCat.Algebra

namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
variable {S : RightModule.FiniteIndecomposableSkeleton k A}

namespace PrimitiveProjectivePresentation

variable (P : S.PrimitiveProjectivePresentation)

/-- The literal quotient map, reoriented from the quotient of `Aᵐᵒᵖ` to a
ring map from `A` into the right-module support algebra. -/
def supportQuotientMap
    (X : RightModule.FinitelyGeneratedCategory A) :
    A →+* P.SupportAlgebra X :=
  (RingHom.op (Ideal.Quotient.mk (P.supportIdeal X).asIdeal)).comp
    (RingEquiv.opOp A).toRingHom

@[simp]
theorem supportQuotientMap_apply
    (X : RightModule.FinitelyGeneratedCategory A) (a : A) :
    P.supportQuotientMap X a =
      MulOpposite.op
        (Ideal.Quotient.mk (P.supportIdeal X).asIdeal
          (MulOpposite.op a)) :=
  rfl

/-- The support quotient map is surjective. -/
theorem supportQuotientMap_surjective
    (X : RightModule.FinitelyGeneratedCategory A) :
    Function.Surjective (P.supportQuotientMap X) := by
  intro b
  obtain ⟨a, ha⟩ := Ideal.Quotient.mk_surjective b.unop
  refine ⟨a.unop, ?_⟩
  apply MulOpposite.unop_injective
  simpa only [supportQuotientMap_apply, MulOpposite.unop_op,
    MulOpposite.op_unop] using ha

/-- The image in the support quotient of one ambient primitive idempotent. -/
def supportIdempotent
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : S.ProjectiveLabel) : P.SupportAlgebra X :=
  P.supportQuotientMap X (P.idempotent p)

/-- A primitive idempotent whose vertex belongs to the selected support has
nonzero image in the literal support quotient. -/
theorem supportIdempotent_ne_zero
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : S.ProjectiveLabel) (hp : p ∈ S.projectiveSupport X) :
    P.supportIdempotent X p ≠ 0 := by
  intro hzero
  have hquotientZero : Ideal.Quotient.mk (P.supportIdeal X).asIdeal
      (MulOpposite.op (P.idempotent p)) = 0 := by
    have h := congrArg MulOpposite.unop hzero
    simpa only [supportIdempotent, supportQuotientMap_apply,
      MulOpposite.unop_op, MulOpposite.unop_zero] using h
  have hmem : MulOpposite.op (P.idempotent p) ∈
      (P.supportIdeal X).asIdeal := by
    rw [← Ideal.Quotient.eq_zero_iff_mem]
    exact hquotientZero
  have hzeroAction : ∀ m : X,
      (MulOpposite.op (P.idempotent p)) • m = 0 := by
    have htor : Module.IsTorsionBySet Aᵐᵒᵖ X
        (P.supportIdeal X).asIdeal :=
      P.isTorsionBySupportIdeal_of_support_subset X X Set.Subset.rfl
    intro m
    exact @htor m ⟨MulOpposite.op (P.idempotent p), hmem⟩
  exact ((P.not_mem_projectiveSupport_iff_idempotent_smul_eq_zero p X).2
    hzeroAction) hp

/-- An omitted ambient primitive idempotent has zero image in the support
quotient. -/
theorem supportIdempotent_eq_zero_of_not_mem
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : S.ProjectiveLabel) (hp : p ∉ S.projectiveSupport X) :
    P.supportIdempotent X p = 0 := by
  apply MulOpposite.unop_injective
  change Ideal.Quotient.mk (P.supportIdeal X).asIdeal
      (MulOpposite.op (P.idempotent p)) = 0
  rw [Ideal.Quotient.eq_zero_iff_mem]
  exact P.op_idempotent_mem_supportIdeal_of_not_mem X p hp

/-- Ambient projective labels which survive in the selected support. -/
abbrev SupportedProjectiveLabel
    (X : RightModule.FinitelyGeneratedCategory A) :=
  {p : S.ProjectiveLabel // p ∈ S.projectiveSupport X}

noncomputable instance supportedProjectiveLabelFintype
    (X : RightModule.FinitelyGeneratedCategory A) :
    Fintype (SupportedProjectiveLabel (S := S) X) :=
  by
    classical
    exact Subtype.fintype fun p ↦ p ∈ S.projectiveSupport X

/-- The surviving complete family of primitive idempotents in the literal
support algebra. -/
def supportedIdempotent
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : SupportedProjectiveLabel (S := S) X) : P.SupportAlgebra X :=
  P.supportIdempotent X p.1

/-- The surviving quotient idempotents are still a complete orthogonal
family. -/
theorem supportedIdempotents_complete
    (X : RightModule.FinitelyGeneratedCategory A) :
    CompleteOrthogonalIdempotents (P.supportedIdempotent X) := by
  classical
  have hall : CompleteOrthogonalIdempotents
      (fun p : S.ProjectiveLabel ↦ P.supportIdempotent X p) := by
    simpa only [supportIdempotent, Function.comp_def] using
      P.complete.map (P.supportQuotientMap X)
  refine ⟨⟨?_, ?_⟩, ?_⟩
  · intro p
    exact hall.idem p.1
  · intro p q hpq
    exact hall.ortho (fun h ↦ hpq (Subtype.ext h))
  · have hsplit := Fintype.sum_subtype_add_sum_subtype
        (fun p : S.ProjectiveLabel ↦ p ∈ S.projectiveSupport X)
        (fun p ↦ P.supportIdempotent X p)
    have hzero : ∑ p : {p : S.ProjectiveLabel //
        p ∉ S.projectiveSupport X}, P.supportIdempotent X p.1 = 0 := by
      apply Finset.sum_eq_zero
      intro p _
      exact P.supportIdempotent_eq_zero_of_not_mem X p.1 p.2
    change ∑ p : SupportedProjectiveLabel (S := S) X,
      P.supportIdempotent X p.1 = 1
    calc
      ∑ p : SupportedProjectiveLabel (S := S) X,
          P.supportIdempotent X p.1 =
          (∑ p : SupportedProjectiveLabel (S := S) X,
            P.supportIdempotent X p.1) +
          ∑ p : {p : S.ProjectiveLabel //
            p ∉ S.projectiveSupport X}, P.supportIdempotent X p.1 := by
              rw [hzero, add_zero]
      _ = ∑ p : S.ProjectiveLabel, P.supportIdempotent X p := hsplit
      _ = 1 := hall.complete

/-- Membership in projective support produces a nonzero vector in the
corresponding ambient idempotent coordinate. -/
theorem exists_ne_zero_idempotentCoordinate_of_mem_support
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : S.ProjectiveLabel) (hp : p ∈ S.projectiveSupport X) :
    ∃ x : RightModule.idempotentCoordinate (k := k) (P.idempotent p) X,
      x ≠ 0 := by
  by_contra hnone
  push Not at hnone
  have hzero : ∀ m : X, (MulOpposite.op (P.idempotent p)) • m = 0 := by
    intro m
    let x : RightModule.idempotentCoordinate (k := k) (P.idempotent p) X :=
      ⟨(MulOpposite.op (P.idempotent p)) • m, ⟨m, rfl⟩⟩
    exact congrArg Subtype.val (hnone x)
  exact ((P.not_mem_projectiveSupport_iff_idempotent_smul_eq_zero p X).2
    hzero) hp

/-- Passage to the support algebra preserves the underlying `k`-vector
space. -/
def ambientToSupportLinearEquiv
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X) :
    M ≃ₗ[k] P.supportFGObj X M hsub :=
  (P.leftSupportObjLinearEquiv X M hsub).trans
    (P.leftSupportObjToSupportObjLinearEquiv X M hsub)

/-- On a supported module, the quotient idempotent acts by the original
ambient idempotent. -/
theorem supportIdempotent_smul
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (p : S.ProjectiveLabel) (m : M) :
    (MulOpposite.op (P.supportIdempotent X p)) •
        P.ambientToSupportLinearEquiv X M hsub m =
      P.ambientToSupportLinearEquiv X M hsub
        ((MulOpposite.op (P.idempotent p)) • m) := by
  rfl

/-- The ambient primitive coordinate and the corresponding coordinate in
the literal support quotient are the same `k`-vector space. -/
def idempotentCoordinateSupportEquiv
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (p : S.ProjectiveLabel) :
    RightModule.idempotentCoordinate (k := k) (P.idempotent p) M ≃ₗ[k]
      RightModule.idempotentCoordinate (k := k)
        (P.supportIdempotent X p) (P.supportFGObj X M hsub) where
  toFun x := by
    refine ⟨P.ambientToSupportLinearEquiv X M hsub x.1, ?_⟩
    obtain ⟨m, hm⟩ := x.2
    refine ⟨P.ambientToSupportLinearEquiv X M hsub m, ?_⟩
    change (MulOpposite.op (P.supportIdempotent X p)) •
      P.ambientToSupportLinearEquiv X M hsub m =
        P.ambientToSupportLinearEquiv X M hsub x.1
    rw [P.supportIdempotent_smul]
    change (MulOpposite.op (P.idempotent p)) • m = x.1 at hm
    exact congrArg (P.ambientToSupportLinearEquiv X M hsub) hm
  invFun x := by
    refine ⟨(P.ambientToSupportLinearEquiv X M hsub).symm x.1, ?_⟩
    obtain ⟨m, hm⟩ := x.2
    refine ⟨(P.ambientToSupportLinearEquiv X M hsub).symm m, ?_⟩
    apply (P.ambientToSupportLinearEquiv X M hsub).injective
    change P.ambientToSupportLinearEquiv X M hsub
        ((MulOpposite.op (P.idempotent p)) •
          (P.ambientToSupportLinearEquiv X M hsub).symm m) =
      P.ambientToSupportLinearEquiv X M hsub
        ((P.ambientToSupportLinearEquiv X M hsub).symm x.1)
    rw [← P.supportIdempotent_smul]
    change (MulOpposite.op (P.supportIdempotent X p)) • m = x.1 at hm
    simpa using hm
  map_add' x y := by
    apply Subtype.ext
    exact (P.ambientToSupportLinearEquiv X M hsub).map_add x.1 y.1
  map_smul' c x := by
    apply Subtype.ext
    exact (P.ambientToSupportLinearEquiv X M hsub).map_smul c x.1
  left_inv x := by
    apply Subtype.ext
    exact (P.ambientToSupportLinearEquiv X M hsub).left_inv x.1
  right_inv x := by
    apply Subtype.ext
    exact (P.ambientToSupportLinearEquiv X M hsub).right_inv x.1

/-- The surviving image of an ambient primitive idempotent is primitive in
the literal support algebra. -/
theorem supportPrimitiveIdempotentData
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : S.ProjectiveLabel) (hp : p ∈ S.projectiveSupport X) :
    RightModule.PrimitiveIdempotentData (P.supportIdempotent X p) :=
  (P.primitive p).map_of_surjective (k := k)
    (P.supportQuotientMap X) (P.supportQuotientMap_surjective X)
      (P.supportIdempotent_ne_zero X p hp)

/-- Every surviving primitive projective maps nontrivially to the selected
support module itself. -/
theorem exists_ne_zero_hom_from_supportedRightIdeal
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : SupportedProjectiveLabel (S := S) X) :
    ∃ f : RightModule.rightIdealFGObj (P.supportIdempotent X p.1) ⟶
        P.supportFGObj X X Set.Subset.rfl,
      f ≠ 0 := by
  let Dp := P.supportPrimitiveIdempotentData X p.1 p.2
  obtain ⟨x, hx⟩ :=
    P.exists_ne_zero_idempotentCoordinate_of_mem_support X p.1 p.2
  let y := P.idempotentCoordinateSupportEquiv X X Set.Subset.rfl p.1 x
  have hy : y ≠ 0 := by
    intro hzero
    apply hx
    exact (P.idempotentCoordinateSupportEquiv X X
      Set.Subset.rfl p.1).injective (by simpa [y] using hzero)
  let E := RightModule.rightIdealHomCoordinateEquiv (k := k)
    Dp.idempotent (P.supportFGObj X X Set.Subset.rfl)
  refine ⟨E.symm y, ?_⟩
  intro hzero
  apply hy
  rw [← E.apply_symm_apply y, hzero, map_zero]

/-- Every surviving primitive injective receives a nonzero map from the
selected support module itself. -/
theorem exists_ne_zero_hom_to_supportedPrimitiveInjective
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : SupportedProjectiveLabel (S := S) X) :
    ∃ f : P.supportFGObj X X Set.Subset.rfl ⟶
        RightModule.primitiveInjectiveFGObj (k := k)
          (P.supportIdempotent X p.1),
      f ≠ 0 := by
  let Dp := P.supportPrimitiveIdempotentData X p.1 p.2
  obtain ⟨x, hx⟩ :=
    P.exists_ne_zero_idempotentCoordinate_of_mem_support X p.1 p.2
  let y := P.idempotentCoordinateSupportEquiv X X Set.Subset.rfl p.1 x
  have hy : y ≠ 0 := by
    intro hzero
    apply hx
    exact (P.idempotentCoordinateSupportEquiv X X
      Set.Subset.rfl p.1).injective (by simpa [y] using hzero)
  obtain ⟨φ, hφ⟩ := Module.Projective.exists_dual_ne_zero k hy
  have hφ0 : φ ≠ 0 := by
    intro hzero
    exact hφ (by rw [hzero, LinearMap.zero_apply])
  let E := RightModule.primitiveInjectiveHomCoordinateDualEquiv (k := k)
    Dp.idempotent (P.supportFGObj X X Set.Subset.rfl)
  refine ⟨E.symm φ, ?_⟩
  intro hzero
  apply hφ0
  rw [← E.apply_symm_apply φ, hzero, map_zero]

/-- A surviving primitive projective maps nontrivially to any supported
module on which its ambient primitive coordinate is nonzero. -/
theorem exists_ne_zero_hom_from_supportedRightIdeal_to_supportFGObj
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (p : S.ProjectiveLabel) (hpX : p ∈ S.projectiveSupport X)
    (hpM : p ∈ S.projectiveSupport M) :
    ∃ f : RightModule.rightIdealFGObj
          (P.supportedIdempotent X ⟨p, hpX⟩) ⟶
        P.supportFGObj X M hsub,
      f ≠ 0 := by
  let Dp : RightModule.PrimitiveIdempotentData
      (P.supportedIdempotent X ⟨p, hpX⟩) := by
    simpa only [supportedIdempotent] using
      P.supportPrimitiveIdempotentData X p hpX
  obtain ⟨x, hx⟩ :=
    P.exists_ne_zero_idempotentCoordinate_of_mem_support M p hpM
  let y := P.idempotentCoordinateSupportEquiv X M hsub p x
  have hy : y ≠ 0 := by
    intro hzero
    apply hx
    exact (P.idempotentCoordinateSupportEquiv X M hsub p).injective
      (by simpa [y] using hzero)
  let E := RightModule.rightIdealHomCoordinateEquiv (k := k)
    Dp.idempotent (P.supportFGObj X M hsub)
  refine ⟨E.symm y, ?_⟩
  intro hzero
  apply hy
  rw [← E.apply_symm_apply y, hzero, map_zero]
  rfl

/-- A surviving primitive injective receives a nonzero map from any
supported module on which its ambient primitive coordinate is nonzero. -/
theorem exists_ne_zero_hom_from_supportFGObj_to_supportedPrimitiveInjective
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (p : S.ProjectiveLabel) (hpX : p ∈ S.projectiveSupport X)
    (hpM : p ∈ S.projectiveSupport M) :
    ∃ f : P.supportFGObj X M hsub ⟶
        RightModule.primitiveInjectiveFGObj (k := k)
          (P.supportedIdempotent X ⟨p, hpX⟩),
      f ≠ 0 := by
  let Dp : RightModule.PrimitiveIdempotentData
      (P.supportedIdempotent X ⟨p, hpX⟩) := by
    simpa only [supportedIdempotent] using
      P.supportPrimitiveIdempotentData X p hpX
  obtain ⟨x, hx⟩ :=
    P.exists_ne_zero_idempotentCoordinate_of_mem_support M p hpM
  let y := P.idempotentCoordinateSupportEquiv X M hsub p x
  have hy : y ≠ 0 := by
    intro hzero
    apply hx
    exact (P.idempotentCoordinateSupportEquiv X M hsub p).injective
      (by simpa [y] using hzero)
  obtain ⟨φ, hφ⟩ := Module.Projective.exists_dual_ne_zero k hy
  have hφ0 : φ ≠ 0 := by
    intro hzero
    exact hφ (by rw [hzero, LinearMap.zero_apply])
  let E := RightModule.primitiveInjectiveHomCoordinateDualEquiv (k := k)
    Dp.idempotent (P.supportFGObj X M hsub)
  refine ⟨E.symm φ, ?_⟩
  intro hzero
  apply hφ0
  rw [← E.apply_symm_apply φ, hzero, map_zero]
  rfl

/-- The actual indecomposable-projective coordinate in the chosen support
algebra skeleton attached to a supported ambient primitive vertex. -/
def supportProjectiveCoordinate
    (hA : RightModule.IsRepresentationFinite k A)
    (X : RightModule.FinitelyGeneratedCategory A)
    (p : S.ProjectiveLabel) (hp : p ∈ S.projectiveSupport X) :
    (P.supportAlgebraSkeleton hA X).ProjectiveLabel :=
  (P.supportAlgebraSkeleton hA X).primitiveSourceProjectiveLabel
    (P.supportPrimitiveIdempotentData X p hp)

/-- The Hom dimension from the selected support-projective coordinate is the
ambient `p`-idempotent coordinate.  In particular, this statement is
independent of the arbitrary duplicate-free skeleton chosen for the support
algebra. -/
theorem supportProjectiveHom_finrank_eq_idempotentCoordinate
    (hA : RightModule.IsRepresentationFinite k A)
    (X M : RightModule.FinitelyGeneratedCategory A)
    (hsub : S.projectiveSupport M ⊆ S.projectiveSupport X)
    (hM : Indecomposable M.obj)
    (p : S.ProjectiveLabel) (hp : p ∈ S.projectiveSupport X) :
    Module.finrank k
        ((P.supportAlgebraSkeleton hA X).fgObj
            (P.supportProjectiveCoordinate hA X p hp).label ⟶
          (P.supportAlgebraSkeleton hA X).fgObj
            (P.supportLabel hA X M hsub hM)) =
      Module.finrank k
        (RightModule.idempotentCoordinate (k := k) (P.idempotent p) M) := by
  let T := P.supportAlgebraSkeleton hA X
  let Dp := P.supportPrimitiveIdempotentData X p hp
  let i := P.supportFGObjIsoSkeletonFG hA X M hsub hM
  calc
    Module.finrank k
        (T.fgObj (T.primitiveSourceProjectiveLabel Dp).label ⟶
          T.fgObj (P.supportLabel hA X M hsub hM)) =
        Module.finrank k
          (T.fgObj (T.primitiveSourceLabel Dp) ⟶
            P.supportFGObj X M hsub) :=
      (CategoryTheory.Linear.homCongr k
        (Iso.refl (T.fgObj (T.primitiveSourceLabel Dp))) i).finrank_eq.symm
    _ = Module.finrank k
        (RightModule.idempotentCoordinate (k := k)
          (P.supportIdempotent X p) (P.supportFGObj X M hsub)) :=
      (T.primitiveSourceHomCoordinateEquiv Dp
        (P.supportFGObj X M hsub)).finrank_eq
    _ = Module.finrank k
        (RightModule.idempotentCoordinate (k := k) (P.idempotent p) M) :=
      (P.idempotentCoordinateSupportEquiv X M hsub p).finrank_eq.symm

/-- A supported indecomposable has the same projective-Hom coordinate before
and after passage to the literal support quotient. -/
theorem supportProjectiveHomVector_eq_ambient
    (hA : RightModule.IsRepresentationFinite k A)
    (X : RightModule.FinitelyGeneratedCategory A)
    (x : Fin S.n)
    (hsub : S.projectiveSupport (S.fgObj x) ⊆ S.projectiveSupport X)
    (p : S.ProjectiveLabel) (hp : p ∈ S.projectiveSupport X) :
    (P.supportAlgebraSkeleton hA X).projectiveHomVector
        (P.supportLabel hA X (S.fgObj x) hsub
          (S.obj_indecomposable x))
        (P.supportProjectiveCoordinate hA X p hp) =
      S.projectiveHomVector x p := by
  change (Module.finrank k
      ((P.supportAlgebraSkeleton hA X).fgObj
          (P.supportProjectiveCoordinate hA X p hp).label ⟶
        (P.supportAlgebraSkeleton hA X).fgObj
          (P.supportLabel hA X (S.fgObj x) hsub
            (S.obj_indecomposable x))) : ℤ) =
    (Module.finrank k (S.fgObj p.label ⟶ S.fgObj x) : ℤ)
  exact_mod_cast (calc
    Module.finrank k
        ((P.supportAlgebraSkeleton hA X).fgObj
            (P.supportProjectiveCoordinate hA X p hp).label ⟶
          (P.supportAlgebraSkeleton hA X).fgObj
            (P.supportLabel hA X (S.fgObj x) hsub
              (S.obj_indecomposable x))) =
        Module.finrank k
          (RightModule.idempotentCoordinate (k := k)
            (P.idempotent p) (S.fgObj x)) :=
      P.supportProjectiveHom_finrank_eq_idempotentCoordinate
        hA X (S.fgObj x) hsub (S.obj_indecomposable x) p hp
    _ = Module.finrank k (S.fgObj p.label ⟶ S.fgObj x) := by
      rw [← congrArg ProjectiveLabel.label (P.sourceLabel p)]
      exact (S.primitiveSourceHomCoordinateEquiv
        (P.primitive p) (S.fgObj x)).finrank_eq.symm)

/-- At the ambient primitive source selected by `D`, the support-projective
coordinate is exactly the manuscript's primitive multiplicity. -/
theorem supportProjectiveHomVector_eq_primitiveMultiplicity
    (hA : RightModule.IsRepresentationFinite k A)
    {e : A} (D : RightModule.PrimitiveIdempotentData e)
    (X : RightModule.FinitelyGeneratedCategory A)
    (x : Fin S.n)
    (hsub : S.projectiveSupport (S.fgObj x) ⊆ S.projectiveSupport X)
    (hp : S.primitiveSourceProjectiveLabel D ∈ S.projectiveSupport X) :
    (P.supportAlgebraSkeleton hA X).projectiveHomVector
        (P.supportLabel hA X (S.fgObj x) hsub
          (S.obj_indecomposable x))
        (P.supportProjectiveCoordinate hA X
          (S.primitiveSourceProjectiveLabel D) hp) =
      (S.primitiveMultiplicity D x : ℤ) := by
  rw [P.supportProjectiveHomVector_eq_ambient]
  exact S.projectiveHomVector_primitiveSource D x

end PrimitiveProjectivePresentation

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
