import MagnitudeConjecture.Algebra.BiserialBranchPlacement
import MagnitudeConjecture.Algebra.RightModuleOrdinaryQuiverKupischComparison
import MagnitudeConjecture.Algebra.RightModulePrimitiveProjectiveKupisch

/-!
# Uniserial ideals generated by ordinary arrows

The preliminary Skowroński--Waschbüsch lemma starts from a biserial
primitive-projective presentation and Kupisch condition `(K)(2)`.  This file
derives the missing structural input: every representative of an ordinary
arrow generates a uniserial principal right ideal, and dually a uniserial
principal left ideal.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open QuotientSubmoduleEquidistribution
open QuotientSubmoduleEquidistribution.CategoricalRadical

namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing A] [IsNoetherianRing Aᵐᵒᵖ]
variable {S : RightModule.FiniteIndecomposableSkeleton k A}

namespace PrimitiveProjectivePresentation

private theorem uniserial_range_comp_linearEquiv_iff
    {R M N : Type*} [Ring R]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (f : M →ₗ[R] N) (e : N ≃ₗ[R] N) :
    IsUniserialModule R (LinearMap.range (e.toLinearMap.comp f)) ↔
      IsUniserialModule R (LinearMap.range f) := by
  have hrange : (LinearMap.range f).map e.toLinearMap =
      LinearMap.range (e.toLinearMap.comp f) := by
    rw [LinearMap.range_comp]
  let erange : LinearMap.range f ≃ₗ[R]
      LinearMap.range (e.toLinearMap.comp f) :=
    e.ofSubmodules _ _ hrange
  exact ⟨fun h ↦ IsUniserialModule.congr erange.symm h,
    fun h ↦ IsUniserialModule.congr erange h⟩

private theorem uniserial_range_comp_domainLinearEquiv_iff
    {R M N : Type*} [Ring R]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (f : M →ₗ[R] N) (e : M ≃ₗ[R] M) :
    IsUniserialModule R (LinearMap.range (f.comp e.toLinearMap)) ↔
      IsUniserialModule R (LinearMap.range f) := by
  rw [e.range_comp f]

private theorem uniserial_range_postcomp_linearEquiv
    {R M N P' : Type*} [Ring R]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    [AddCommGroup P'] [Module R P']
    (f : M →ₗ[R] N) (e : N ≃ₗ[R] P')
    (h : IsUniserialModule R (LinearMap.range f)) :
    IsUniserialModule R (LinearMap.range (e.toLinearMap.comp f)) := by
  have hrange : (LinearMap.range f).map e.toLinearMap =
      LinearMap.range (e.toLinearMap.comp f) := by
    rw [LinearMap.range_comp]
  exact IsUniserialModule.congr (e.ofSubmodules _ _ hrange) h

private theorem uniserial_range_precomp_linearEquiv
    {R M M' N : Type*} [Ring R]
    [AddCommGroup M] [Module R M] [AddCommGroup M'] [Module R M']
    [AddCommGroup N] [Module R N]
    (f : M →ₗ[R] N) (e : M' ≃ₗ[R] M)
    (h : IsUniserialModule R (LinearMap.range f)) :
    IsUniserialModule R (LinearMap.range (f.comp e.toLinearMap)) := by
  rw [e.range_comp f]
  exact h

omit [IsNoetherianRing A] in
/-- Kupisch condition `(K)(2)` makes the first radical layer of every
selected projective coordinate-thin. -/
theorem boundaryRadicalTop_isCoordinateThin_of_uniserialAlternative
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation)
    (D : S.OrdinaryArrowRepresentatives)
    (hHomAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x))
    (x : S.ProjectiveLabel) :
    RightModule.IsCoordinateThin (k := k) P.idempotent
      (S.projectiveBoundaryRadicalTop x) := by
  intro y
  have harrowSubsingleton : Subsingleton (S.OrdinaryArrow x y) :=
    ⟨fun a b ↦ by
      rcases hHomAlternative x y with htarget | hsource
      · exact D.eq_of_codomainHom_uniserial htarget a b
      · exact D.eq_of_domainHom_uniserial hsource a b⟩
  have hirr : Module.finrank k
      (S.projectiveIrreducibleHomSpace x y) ≤ 1 := by
    have hcard : Fintype.card (S.OrdinaryArrow x y) ≤ 1 :=
      Fintype.card_le_one_iff_subsingleton.mpr harrowSubsingleton
    simpa only [Fintype.card_ulift, Fintype.card_fin] using hcard
  have hlabel : S.primitiveSourceLabel (P.primitive y) = y.label :=
    congrArg ProjectiveLabel.label (P.sourceLabel y)
  have hcoord :=
    (S.primitiveSourceHomCoordinateEquiv
      (P.primitive y) (S.projectiveBoundaryRadicalTop x)).finrank_eq
  rw [hlabel] at hcoord
  rw [← hcoord,
    ← (S.projectiveIrrBoundaryTopHomEquiv x y).finrank_eq]
  exact hirr

/-- The image of a selected-projective morphism, after transport to literal
principal projectives, is canonically the principal right ideal generated by
its algebra coordinate. -/
def projectiveHomRangePrincipalRightIdealLinearEquiv
    (P : S.PrimitiveProjectivePresentation)
    {p q : S.ProjectiveLabel}
    (f : S.ordinaryProjectiveObj p ⟶ S.ordinaryProjectiveObj q) :
    LinearMap.range (P.projectiveHomTransport f).hom.hom ≃ₗ[Aᵐᵒᵖ]
      RightModule.rightIdeal (P.projectiveHomCoordinate f) := by
  let t := P.projectiveHomTransport f
  let c := P.projectiveHomCoordinate f
  have happly (z : RightModule.rightIdealFGObj (P.idempotent p)) :
      (t.hom.hom z).1 = c * z.1 := by
    obtain ⟨r, hr⟩ := z.2
    change P.idempotent p * r = z.1 at hr
    have hz : (MulOpposite.op r) •
        RightModule.rightIdealGenerator (P.idempotent p) = z := by
      apply Subtype.ext
      exact hr
    have hc : (t.hom.hom
        (RightModule.rightIdealGenerator (P.idempotent p))).1 = c := by
      rfl
    calc
      (t.hom.hom z).1 =
          (t.hom.hom ((MulOpposite.op r) •
            RightModule.rightIdealGenerator (P.idempotent p))).1 := by
              rw [hz]
      _ = ((MulOpposite.op r) • t.hom.hom
            (RightModule.rightIdealGenerator (P.idempotent p))).1 := by
              exact congrArg Subtype.val
                (t.hom.hom.map_smul (MulOpposite.op r)
                  (RightModule.rightIdealGenerator (P.idempotent p)))
      _ = (t.hom.hom
            (RightModule.rightIdealGenerator (P.idempotent p))).1 * r := rfl
      _ = c * r := by rw [hc]
      _ = c * (P.idempotent p * r) := by
        rw [← mul_assoc, P.projectiveHomCoordinate_mul_idempotent f]
      _ = c * z.1 := by rw [hr]
  let toFun : LinearMap.range t.hom.hom →
      RightModule.rightIdeal c := fun z ↦
    ⟨z.1.1, by
      rcases z.2 with ⟨w, hw⟩
      refine ⟨w.1, ?_⟩
      change c * w.1 = z.1.1
      rw [← happly w]
      exact congrArg Subtype.val hw⟩
  let witness (z : RightModule.rightIdeal c) : A :=
    Classical.choose z.2
  have witness_spec (z : RightModule.rightIdeal c) :
      c * witness z = z.1 := Classical.choose_spec z.2
  let source (z : RightModule.rightIdeal c) :
      RightModule.rightIdealFGObj (P.idempotent p) :=
    ⟨P.idempotent p * witness z, ⟨witness z, rfl⟩⟩
  let invFun : RightModule.rightIdeal c →
      LinearMap.range t.hom.hom := fun z ↦
    ⟨t.hom.hom (source z), ⟨source z, rfl⟩⟩
  refine {
    toFun := toFun
    invFun := invFun
    left_inv := by
      intro z
      apply Subtype.ext
      change t.hom.hom (source (toFun z)) = z.1
      apply Subtype.ext
      rw [happly,
        show (source (toFun z)).1 =
          P.idempotent p * witness (toFun z) by rfl,
        ← mul_assoc, P.projectiveHomCoordinate_mul_idempotent f,
        witness_spec]
    right_inv := by
      intro z
      apply Subtype.ext
      change (t.hom.hom (source z)).1 = z.1
      rw [happly, show (source z).1 = P.idempotent p * witness z by rfl,
        ← mul_assoc, P.projectiveHomCoordinate_mul_idempotent f,
        witness_spec]
    map_add' := by
      intro z w
      apply Subtype.ext
      rfl
    map_smul' := by
      intro r z
      apply Subtype.ext
      rfl }

/-- A radical morphism can be changed only by an internal radical-square
morphism so that its image lies in one uniserial branch of the target
projective radical. -/
theorem exists_radicalSquare_lift_with_uniserial_range_of_radical
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial)
    (D : S.OrdinaryArrowRepresentatives)
    (hHomAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x))
    {x y : S.ProjectiveLabel} (f : S.projectiveRadicalSubmodule x y) :
    ∃ b : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x,
      IsUniserialModule Aᵐᵒᵖ
          (LinearMap.range (S.ordinaryProjectiveFGHom b).hom.hom) ∧
        b - f.1 ∈ S.projectiveRadicalSquareSubmodule x y := by
  let L : RightModule.FinitelyGeneratedCategory A := S.fgObj x.label
  let E : RightModule.FinitelyGeneratedCategory A := S.fgObj y.label
  let J : Submodule Aᵐᵒᵖ L := Module.jacobson Aᵐᵒᵖ L
  let J2 : Submodule Aᵐᵒᵖ J := Module.jacobson Aᵐᵒᵖ J
  let Q : RightModule.FinitelyGeneratedCategory A :=
    S.projectiveBoundaryRadicalTop x
  let q : J →ₗ[Aᵐᵒᵖ] Q := J2.mkQ
  let aTop : E →ₗ[Aᵐᵒᵖ] Q :=
    (S.projectiveRadicalToBoundaryTopHom x y f).hom.hom
  have hQthin : RightModule.IsCoordinateThin (k := k) P.idempotent Q :=
    P.boundaryRadicalTop_isCoordinateThin_of_uniserialAlternative
      D hHomAlternative x
  have hLbis : IsBiserialModule Aᵐᵒᵖ L := by
    let e : RightModule.rightIdealFGObj (P.idempotent x) ≃ₗ[Aᵐᵒᵖ] L :=
      FGModuleCat.isoToLinearEquiv (P.primitiveProjectiveIso x)
    exact IsBiserialModule.congr e
      (IsBiserialObject.toIsBiserialModule_of_fg _ (hP.1 x))
  rcases hLbis with ⟨U, V, hUV, hUuni, hVuni, -⟩
  have hUle : U ≤ J := by
    change U ≤ Module.jacobson Aᵐᵒᵖ L
    rw [← hUV]
    exact le_sup_left
  have hVle : V ≤ J := by
    change V ≤ Module.jacobson Aᵐᵒᵖ L
    rw [← hUV]
    exact le_sup_right
  let UJ : Submodule Aᵐᵒᵖ J := U.comap J.subtype
  let VJ : Submodule Aᵐᵒᵖ J := V.comap J.subtype
  let Ubar : Submodule Aᵐᵒᵖ Q := UJ.map q
  let Vbar : Submodule Aᵐᵒᵖ Q := VJ.map q
  have hUJtop : UJ ⊔ VJ = ⊤ := by
    apply Submodule.map_injective_of_injective J.subtype_injective
    rw [Submodule.map_sup, Submodule.map_comap_subtype,
      Submodule.map_comap_subtype, inf_eq_right.mpr hUle,
      inf_eq_right.mpr hVle, hUV]
    simp [J]
  have hUbarVbar : Ubar ⊔ Vbar = ⊤ := by
    change UJ.map q ⊔ VJ.map q = ⊤
    rw [← Submodule.map_sup, hUJtop, Submodule.map_top]
    exact LinearMap.range_eq_top.mpr J2.mkQ_surjective
  have haTopRange : LinearMap.range aTop ≤ Ubar ⊔ Vbar := by
    rw [hUbarVbar]
    exact le_top
  have hEtop : IsSimpleModule Aᵐᵒᵖ
      (E ⧸ Module.jacobson Aᵐᵒᵖ E) := by
    exact S.projectiveSimpleTop_isSimpleModule y
  have lift_branch
      (W : Submodule Aᵐᵒᵖ L)
      (hWle : W ≤ J)
      (hWuni : IsUniserialModule Aᵐᵒᵖ W)
      (hTop : LinearMap.range aTop ≤
        (W.comap J.subtype).map q) :
      ∃ b : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x,
        IsUniserialModule Aᵐᵒᵖ
            (LinearMap.range (S.ordinaryProjectiveFGHom b).hom.hom) ∧
          b - f.1 ∈ S.projectiveRadicalSquareSubmodule x y := by
    let WJ : Submodule Aᵐᵒᵖ J := W.comap J.subtype
    let Wbar : Submodule Aᵐᵒᵖ Q := WJ.map q
    let wToQ : WJ →ₗ[Aᵐᵒᵖ] Q := q.comp WJ.subtype
    let wToBar : WJ →ₗ[Aᵐᵒᵖ] Wbar :=
      wToQ.codRestrict Wbar (fun z ↦ ⟨z, z.2, rfl⟩)
    have hwSurjective : Function.Surjective wToBar := by
      rintro ⟨z, hz⟩
      rcases hz with ⟨w, hw, hwz⟩
      exact ⟨⟨w, hw⟩, Subtype.ext hwz⟩
    let aToBar : E →ₗ[Aᵐᵒᵖ] Wbar :=
      aTop.codRestrict Wbar (fun z ↦
        hTop (LinearMap.mem_range_self aTop z))
    let wHom : RightModule.submoduleFGObj
        (RightModule.submoduleFGObj L J) WJ ⟶
          RightModule.submoduleFGObj Q Wbar :=
      ConcreteCategory.ofHom wToBar
    let aHom : E ⟶ RightModule.submoduleFGObj Q Wbar :=
      ConcreteCategory.ofHom aToBar
    let wInc : RightModule.submoduleFGObj Q Wbar ⟶ Q :=
      ConcreteCategory.ofHom Wbar.subtype
    letI : Epi wHom := by
      apply (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_epi_iff_surjective
        wHom).2
      exact hwSurjective
    letI : Projective E := y.projective
    obtain ⟨l, hl⟩ := Projective.factors aHom wHom
    let bLin : E →ₗ[Aᵐᵒᵖ] L :=
      J.subtype.comp (WJ.subtype.comp l.hom.hom)
    let bFG : E ⟶ L := ConcreteCategory.ofHom bLin
    let b : S.ordinaryProjectiveObj y ⟶
        S.ordinaryProjectiveObj x := InducedCategory.homMk bFG
    have hbRangeW : LinearMap.range bLin ≤ W := by
      rintro z ⟨w, rfl⟩
      exact (l.hom.hom w).2
    have hbUni : IsUniserialModule Aᵐᵒᵖ
        (LinearMap.range bLin) :=
      IsUniserialModule.of_injective hWuni
        (Submodule.inclusion hbRangeW)
        (Submodule.inclusion_injective hbRangeW)
    have hbRadical : b ∈ S.projectiveRadicalSubmodule x y := by
      apply S.mem_projectiveRadical_of_range_le_jacobson
      exact hbRangeW.trans hWle
    let bRad : S.projectiveRadicalSubmodule x y := ⟨b, hbRadical⟩
    have hbTop : S.projectiveRadicalToBoundaryTopHom x y bRad =
        S.projectiveRadicalToBoundaryTopHom x y f := by
      calc
        S.projectiveRadicalToBoundaryTopHom x y bRad =
            l ≫ wHom ≫ wInc := by
          apply FGModuleCat.hom_ext
          ext z
          rfl
        _ = aHom ≫ wInc := by
          rw [← Category.assoc, hl]
        _ = S.projectiveRadicalToBoundaryTopHom x y f := by
          apply FGModuleCat.hom_ext
          ext z
          rfl
    have hdiffRadical : b - f.1 ∈
        S.projectiveRadicalSubmodule x y :=
      Submodule.sub_mem _ hbRadical f.2
    let diffRad : S.projectiveRadicalSubmodule x y :=
      ⟨b - f.1, hdiffRadical⟩
    have hdiffKer : diffRad ∈
        LinearMap.ker (S.projectiveRadicalToBoundaryTopHom x y) := by
      rw [LinearMap.mem_ker]
      change S.projectiveRadicalToBoundaryTopHom x y bRad -
          S.projectiveRadicalToBoundaryTopHom x y f = 0
      rw [hbTop, sub_self]
    have hdiffSquare : b - f.1 ∈
        S.projectiveRadicalSquareSubmodule x y := by
      have h := hdiffKer
      rw [S.ker_projectiveRadicalToBoundaryTopHom x y] at h
      exact h
    refine ⟨b, ?_, hdiffSquare⟩
    change IsUniserialModule Aᵐᵒᵖ (LinearMap.range bLin)
    exact hbUni
  rcases
      linearMap_range_le_left_or_le_right_of_coordinateThin_sup_of_simpleTop
        P.idempotent P.complete Q hQthin Ubar Vbar E aTop
          haTopRange hEtop with hleft | hright
  · exact lift_branch U hUle hUuni hleft
  · exact lift_branch V hVle hVuni hright

/-- The radical lift specialized to a displayed ordinary-arrow
representative. -/
theorem exists_radicalSquare_lift_with_uniserial_range
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial)
    (D : S.OrdinaryArrowRepresentatives)
    (hHomAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x))
    {x y : S.ProjectiveLabel} (a : S.OrdinaryArrow x y) :
    ∃ b : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x,
      IsUniserialModule Aᵐᵒᵖ
          (LinearMap.range (S.ordinaryProjectiveFGHom b).hom.hom) ∧
        b - D.hom a ∈ S.projectiveRadicalSquareSubmodule x y :=
  P.exists_radicalSquare_lift_with_uniserial_range_of_radical
    hP D hHomAlternative (D.representative a)

omit [IsNoetherianRing A] in
/-- A postcomposition multiplier carrying a radical morphism which survives
modulo the radical square into the square is itself radical. -/
theorem codomainEndomorphism_mem_radical_of_nonSquare
    {x y : S.ProjectiveLabel}
    (f : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x)
    (hf : f ∉ S.projectiveRadicalSquareSubmodule x y)
    (e : S.ordinaryProjectiveObj x ⟶ S.ordinaryProjectiveObj x)
    (hcomp : f ≫ e ∈ S.projectiveRadicalSquareSubmodule x y) :
    e ∈ S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x) := by
  by_contra he
  have heAmbient :
      ¬ CategoricalRadical.IsRadicalMorphism
        (S.projectiveInclusion.map e) := by
    intro heRad
    apply he
    rw [S.projectiveNilpotentRadicalData.mem_ideal_iff]
    exact (isRadicalMorphism_iff_map_of_fullyFaithful
        S.projectiveInclusion
        (CategoryTheory.fullyFaithfulInducedFunctor _) e).2 heRad
  letI : IsLocalRing (End (S.fgObj x.label)) :=
    S.fgObj_end_isLocalRing x.label
  have heSplitAmbient : IsSplitMono (S.projectiveInclusion.map e) := by
    by_contra hsplit
    exact heAmbient
      ((MagnitudeConjecture.CategoryTheory.isRadicalMorphism_iff_not_isSplitMono_of_local_end
          (S.fgObj_indecomposable x.label).1 _).2 hsplit)
  letI : IsSplitMono (S.projectiveInclusion.map e) := heSplitAmbient
  letI : S.projectiveInclusion.Full :=
    (CategoryTheory.fullyFaithfulInducedFunctor _).full
  letI : S.projectiveInclusion.Faithful :=
    (CategoryTheory.fullyFaithfulInducedFunctor _).faithful
  have heSplit : IsSplitMono e := by
    apply IsSplitMono.mk'
    refine ⟨S.projectiveInclusion.preimage
      (retraction (S.projectiveInclusion.map e)), ?_⟩
    apply S.projectiveInclusion.map_injective
    rw [S.projectiveInclusion.map_comp,
      S.projectiveInclusion.map_preimage,
      IsSplitMono.id]
    exact (S.projectiveInclusion.map_id _).symm
  letI : IsSplitMono e := heSplit
  apply hf
  have hcancel :=
    (S.projectiveNilpotentRadicalData.ideal.pow 2).postcomp
      (retraction e) hcomp
  change f ∈ (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
  simpa only [Category.assoc, IsSplitMono.id, Category.comp_id] using hcancel

omit [IsNoetherianRing A] in
/-- The precomposition analogue of
`codomainEndomorphism_mem_radical_of_nonSquare`. -/
theorem domainEndomorphism_mem_radical_of_nonSquare
    {x y : S.ProjectiveLabel}
    (f : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x)
    (hf : f ∉ S.projectiveRadicalSquareSubmodule x y)
    (e : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj y)
    (hcomp : e ≫ f ∈ S.projectiveRadicalSquareSubmodule x y) :
    e ∈ S.projectiveNilpotentRadicalData.ideal.hom
      (S.ordinaryProjectiveObj y) (S.ordinaryProjectiveObj y) := by
  by_contra he
  have heAmbient :
      ¬ CategoricalRadical.IsRadicalMorphism
        (S.projectiveInclusion.map e) := by
    intro heRad
    apply he
    rw [S.projectiveNilpotentRadicalData.mem_ideal_iff]
    exact (isRadicalMorphism_iff_map_of_fullyFaithful
        S.projectiveInclusion
        (CategoryTheory.fullyFaithfulInducedFunctor _) e).2 heRad
  letI : IsLocalRing (End (S.fgObj y.label)) :=
    S.fgObj_end_isLocalRing y.label
  have heSplitAmbient : IsSplitEpi (S.projectiveInclusion.map e) := by
    by_contra hsplit
    exact heAmbient
      ((MagnitudeConjecture.CategoryTheory.isRadicalMorphism_iff_not_isSplitEpi_of_local_end
          (S.fgObj_indecomposable y.label).1 _).2 hsplit)
  letI : IsSplitEpi (S.projectiveInclusion.map e) := heSplitAmbient
  letI : S.projectiveInclusion.Full :=
    (CategoryTheory.fullyFaithfulInducedFunctor _).full
  letI : S.projectiveInclusion.Faithful :=
    (CategoryTheory.fullyFaithfulInducedFunctor _).faithful
  have heSplit : IsSplitEpi e := by
    apply IsSplitEpi.mk'
    refine ⟨S.projectiveInclusion.preimage
      (section_ (S.projectiveInclusion.map e)), ?_⟩
    apply S.projectiveInclusion.map_injective
    rw [S.projectiveInclusion.map_comp,
      S.projectiveInclusion.map_preimage,
      IsSplitEpi.id]
    exact (S.projectiveInclusion.map_id _).symm
  letI : IsSplitEpi e := heSplit
  apply hf
  have hcancel :=
    (S.projectiveNilpotentRadicalData.ideal.pow 2).precomp
      (section_ e) hcomp
  change f ∈ (S.projectiveNilpotentRadicalData.ideal.pow 2).hom _ _
  simpa only [← Category.assoc, IsSplitEpi.id, Category.id_comp] using hcancel

/-- The radical-square branch lift and Kupisch `(K)(2)` imply that every
radical morphism which survives modulo the radical square has uniserial
image.  The endpoint multiplier relating it to the branch lift differs from
the identity by a nilpotent radical endomorphism and is therefore invertible. -/
theorem radical_range_isUniserial_of_not_mem_square
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial)
    (D : S.OrdinaryArrowRepresentatives)
    (hHomAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x))
    {x y : S.ProjectiveLabel}
    (f : S.projectiveRadicalSubmodule x y)
    (hf : f.1 ∉ S.projectiveRadicalSquareSubmodule x y) :
    IsUniserialModule Aᵐᵒᵖ
      (LinearMap.range
        (S.ordinaryProjectiveFGHom f.1).hom.hom) := by
  obtain ⟨b, hbUni, hdiff⟩ :=
    P.exists_radicalSquare_lift_with_uniserial_range_of_radical
      hP D hHomAlternative f
  let aLin : S.fgObj y.label →ₗ[Aᵐᵒᵖ] S.fgObj x.label :=
    (S.ordinaryProjectiveFGHom f.1).hom.hom
  let bLin : S.fgObj y.label →ₗ[Aᵐᵒᵖ] S.fgObj x.label :=
    (S.ordinaryProjectiveFGHom b).hom.hom
  have hbRadical : b ∈ S.projectiveRadicalSubmodule x y := by
    have hsqRad := S.projectiveRadicalSquare_le_radical x y hdiff
    have hsum : b = (b - f.1) + f.1 := by abel
    rw [hsum]
    exact Submodule.add_mem _ hsqRad f.2
  have target_postcomp
      (r : End (S.ordinaryProjectiveObj x)) (hr : IsUnit r)
      (hrel : f.1 ≫ End.asHom r = b) :
      IsUniserialModule Aᵐᵒᵖ (LinearMap.range aLin) := by
    haveI : IsIso (End.asHom r) :=
      (CategoryTheory.isUnit_iff_isIso r).mp hr
    let i : S.fgObj x.label ≅ S.fgObj x.label :=
      S.projectiveInclusion.mapIso
        (@asIso _ _ _ _ (End.asHom r)
          ((CategoryTheory.isUnit_iff_isIso r).mp hr))
    let e : S.fgObj x.label ≃ₗ[Aᵐᵒᵖ] S.fgObj x.label :=
      FGModuleCat.isoToLinearEquiv i
    have he : e.toLinearMap =
        (S.ordinaryProjectiveFGHom (End.asHom r)).hom.hom := rfl
    have hlin : e.toLinearMap.comp aLin = bLin := by
      rw [he]
      apply LinearMap.ext
      intro z
      have hz := congrArg
        (fun f : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x ↦
          (S.ordinaryProjectiveFGHom f).hom.hom z) hrel
      exact hz
    apply (uniserial_range_comp_linearEquiv_iff aLin e).mp
    rw [hlin]
    exact hbUni
  have target_postcomp_rev
      (r : End (S.ordinaryProjectiveObj x)) (hr : IsUnit r)
      (hrel : b ≫ End.asHom r = f.1) :
      IsUniserialModule Aᵐᵒᵖ (LinearMap.range aLin) := by
    haveI : IsIso (End.asHom r) :=
      (CategoryTheory.isUnit_iff_isIso r).mp hr
    let i : S.fgObj x.label ≅ S.fgObj x.label :=
      S.projectiveInclusion.mapIso
        (@asIso _ _ _ _ (End.asHom r)
          ((CategoryTheory.isUnit_iff_isIso r).mp hr))
    let e : S.fgObj x.label ≃ₗ[Aᵐᵒᵖ] S.fgObj x.label :=
      FGModuleCat.isoToLinearEquiv i
    have he : e.toLinearMap =
        (S.ordinaryProjectiveFGHom (End.asHom r)).hom.hom := rfl
    have hlin : e.toLinearMap.comp bLin = aLin := by
      rw [he]
      apply LinearMap.ext
      intro z
      have hz := congrArg
        (fun f : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x ↦
          (S.ordinaryProjectiveFGHom f).hom.hom z) hrel
      exact hz
    rw [← hlin]
    exact (uniserial_range_comp_linearEquiv_iff bLin e).mpr hbUni
  have source_precomp
      (r : End (S.ordinaryProjectiveObj y)) (hr : IsUnit r)
      (hrel : End.asHom r ≫ f.1 = b) :
      IsUniserialModule Aᵐᵒᵖ (LinearMap.range aLin) := by
    haveI : IsIso (End.asHom r) :=
      (CategoryTheory.isUnit_iff_isIso r).mp hr
    let i : S.fgObj y.label ≅ S.fgObj y.label :=
      S.projectiveInclusion.mapIso
        (@asIso _ _ _ _ (End.asHom r)
          ((CategoryTheory.isUnit_iff_isIso r).mp hr))
    let e : S.fgObj y.label ≃ₗ[Aᵐᵒᵖ] S.fgObj y.label :=
      FGModuleCat.isoToLinearEquiv i
    have he : e.toLinearMap =
        (S.ordinaryProjectiveFGHom (End.asHom r)).hom.hom := rfl
    have hlin : aLin.comp e.toLinearMap = bLin := by
      rw [he]
      apply LinearMap.ext
      intro z
      have hz := congrArg
        (fun f : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x ↦
          (S.ordinaryProjectiveFGHom f).hom.hom z) hrel
      exact hz
    apply (uniserial_range_comp_domainLinearEquiv_iff aLin e).mp
    rw [hlin]
    exact hbUni
  have source_precomp_rev
      (r : End (S.ordinaryProjectiveObj y)) (hr : IsUnit r)
      (hrel : End.asHom r ≫ b = f.1) :
      IsUniserialModule Aᵐᵒᵖ (LinearMap.range aLin) := by
    haveI : IsIso (End.asHom r) :=
      (CategoryTheory.isUnit_iff_isIso r).mp hr
    let i : S.fgObj y.label ≅ S.fgObj y.label :=
      S.projectiveInclusion.mapIso
        (@asIso _ _ _ _ (End.asHom r)
          ((CategoryTheory.isUnit_iff_isIso r).mp hr))
    let e : S.fgObj y.label ≃ₗ[Aᵐᵒᵖ] S.fgObj y.label :=
      FGModuleCat.isoToLinearEquiv i
    have he : e.toLinearMap =
        (S.ordinaryProjectiveFGHom (End.asHom r)).hom.hom := rfl
    have hlin : bLin.comp e.toLinearMap = aLin := by
      rw [he]
      apply LinearMap.ext
      intro z
      have hz := congrArg
        (fun f : S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x ↦
          (S.ordinaryProjectiveFGHom f).hom.hom z) hrel
      exact hz
    rw [← hlin]
    exact (uniserial_range_comp_domainLinearEquiv_iff bLin e).mpr hbUni
  rcases hHomAlternative x y with htarget | hsource
  · rcases htarget.smul_comparable f.1 b with h | h
    · obtain ⟨r, hr⟩ := h
      change f.1 ≫ End.asHom r = b at hr
      have hradical : End.asHom r - 𝟙 (S.ordinaryProjectiveObj x) ∈
          S.projectiveNilpotentRadicalData.ideal.hom
            (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x) := by
        apply codomainEndomorphism_mem_radical_of_nonSquare f.1 hf
        simpa only [Preadditive.comp_sub, Category.comp_id, hr] using hdiff
      have hnilpotent :=
        S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal
          hradical
      have hunit : IsUnit r := by
        have heq : 1 + End.of
            (End.asHom r - 𝟙 (S.ordinaryProjectiveObj x)) = r := by
          change 1 + (r - 1) = r
          abel
        rw [← heq]
        exact hnilpotent.isUnit_one_add
      exact target_postcomp r hunit hr
    · obtain ⟨r, hr⟩ := h
      change b ≫ End.asHom r = f.1 at hr
      have hnegDiff : f.1 - b ∈
          S.projectiveRadicalSquareSubmodule x y := by
        simpa only [neg_sub] using
          (S.projectiveRadicalSquareSubmodule x y).neg_mem hdiff
      have hpost : (f.1 - b) ≫ End.asHom r ∈
          S.projectiveRadicalSquareSubmodule x y :=
        (S.projectiveNilpotentRadicalData.ideal.pow 2).postcomp
          (End.asHom r) hnegDiff
      have hcomp : f.1 ≫
          (𝟙 (S.ordinaryProjectiveObj x) - End.asHom r) ∈
            S.projectiveRadicalSquareSubmodule x y := by
        have heq : f.1 ≫
              (𝟙 (S.ordinaryProjectiveObj x) - End.asHom r) =
            -((f.1 - b) ≫ End.asHom r) := by
          rw [Preadditive.comp_sub, Category.comp_id,
            Preadditive.sub_comp, hr]
          abel
        rw [heq]
        exact (S.projectiveRadicalSquareSubmodule x y).neg_mem hpost
      have hradical : 𝟙 (S.ordinaryProjectiveObj x) - End.asHom r ∈
          S.projectiveNilpotentRadicalData.ideal.hom
            (S.ordinaryProjectiveObj x) (S.ordinaryProjectiveObj x) :=
        codomainEndomorphism_mem_radical_of_nonSquare f.1 hf _ hcomp
      have hnilpotent :=
        S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal
          hradical
      have hunit : IsUnit r := by
        have heq : 1 - End.of
            (𝟙 (S.ordinaryProjectiveObj x) - End.asHom r) = r := by
          change 1 - (1 - r) = r
          abel
        rw [← heq]
        exact hnilpotent.isUnit_one_sub
      exact target_postcomp_rev r hunit hr
  · rcases hsource.smul_comparable f.1 b with h | h
    · obtain ⟨r, hr⟩ := h
      change End.asHom r.unop ≫ f.1 = b at hr
      have hradical : End.asHom r.unop -
          𝟙 (S.ordinaryProjectiveObj y) ∈
          S.projectiveNilpotentRadicalData.ideal.hom
            (S.ordinaryProjectiveObj y) (S.ordinaryProjectiveObj y) := by
        apply domainEndomorphism_mem_radical_of_nonSquare f.1 hf
        simpa only [Preadditive.sub_comp, Category.id_comp, hr] using hdiff
      have hnilpotent :=
        S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal
          hradical
      have hunit : IsUnit r.unop := by
        have heq : 1 + End.of
            (End.asHom r.unop - 𝟙 (S.ordinaryProjectiveObj y)) =
              r.unop := by
          change 1 + (r.unop - 1) = r.unop
          abel
        rw [← heq]
        exact hnilpotent.isUnit_one_add
      exact source_precomp r.unop hunit hr
    · obtain ⟨r, hr⟩ := h
      change End.asHom r.unop ≫ b = f.1 at hr
      have hnegDiff : f.1 - b ∈
          S.projectiveRadicalSquareSubmodule x y := by
        simpa only [neg_sub] using
          (S.projectiveRadicalSquareSubmodule x y).neg_mem hdiff
      have hpre : End.asHom r.unop ≫ (f.1 - b) ∈
          S.projectiveRadicalSquareSubmodule x y :=
        (S.projectiveNilpotentRadicalData.ideal.pow 2).precomp
          (End.asHom r.unop) hnegDiff
      have hcomp :
          (𝟙 (S.ordinaryProjectiveObj y) - End.asHom r.unop) ≫
              f.1 ∈ S.projectiveRadicalSquareSubmodule x y := by
        have heq :
            (𝟙 (S.ordinaryProjectiveObj y) - End.asHom r.unop) ≫
                f.1 =
              -(End.asHom r.unop ≫ (f.1 - b)) := by
          rw [Preadditive.sub_comp, Category.id_comp,
            Preadditive.comp_sub, hr]
          abel
        rw [heq]
        exact (S.projectiveRadicalSquareSubmodule x y).neg_mem hpre
      have hradical : 𝟙 (S.ordinaryProjectiveObj y) -
          End.asHom r.unop ∈
          S.projectiveNilpotentRadicalData.ideal.hom
            (S.ordinaryProjectiveObj y) (S.ordinaryProjectiveObj y) :=
        domainEndomorphism_mem_radical_of_nonSquare f.1 hf _ hcomp
      have hnilpotent :=
        S.projectiveNilpotentRadicalData.isNilpotent_end_of_mem_ideal
          hradical
      have hunit : IsUnit r.unop := by
        have heq : 1 - End.of
            (𝟙 (S.ordinaryProjectiveObj y) - End.asHom r.unop) =
              r.unop := by
          change 1 - (1 - r.unop) = r.unop
          abel
        rw [← heq]
        exact hnilpotent.isUnit_one_sub
      exact source_precomp_rev r.unop hunit hr

/-- Every displayed ordinary-arrow representative has uniserial image. -/
theorem ordinaryArrow_range_isUniserial
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial)
    (D : S.OrdinaryArrowRepresentatives)
    (hHomAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x))
    {x y : S.ProjectiveLabel} (a : S.OrdinaryArrow x y) :
    IsUniserialModule Aᵐᵒᵖ
      (LinearMap.range
        (S.ordinaryProjectiveFGHom (D.hom a)).hom.hom) :=
  P.radical_range_isUniserial_of_not_mem_square
    hP D hHomAlternative (D.representative a)
      (D.hom_not_mem_radicalSquare a)

/-- Every radical morphism which survives modulo the radical square
generates a uniserial principal right ideal. -/
theorem radical_rightIdeal_isUniserial_of_not_mem_square
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial)
    (D : S.OrdinaryArrowRepresentatives)
    (hHomAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x))
    {x y : S.ProjectiveLabel}
    (f : S.projectiveRadicalSubmodule x y)
    (hf : f.1 ∉ S.projectiveRadicalSquareSubmodule x y) :
    IsUniserialModule Aᵐᵒᵖ
      (RightModule.rightIdeal
        (P.projectiveHomCoordinate f.1)) := by
  let aLin : S.fgObj y.label →ₗ[Aᵐᵒᵖ] S.fgObj x.label :=
    (S.ordinaryProjectiveFGHom f.1).hom.hom
  have haUni : IsUniserialModule Aᵐᵒᵖ
      (LinearMap.range aLin) :=
    P.radical_range_isUniserial_of_not_mem_square
      hP D hHomAlternative f hf
  let sourceEquiv :
      RightModule.rightIdealFGObj (P.idempotent y) ≃ₗ[Aᵐᵒᵖ]
        S.fgObj y.label :=
    FGModuleCat.isoToLinearEquiv (P.primitiveProjectiveIso y)
  let targetEquiv : S.fgObj x.label ≃ₗ[Aᵐᵒᵖ]
      RightModule.rightIdealFGObj (P.idempotent x) :=
    FGModuleCat.isoToLinearEquiv (P.primitiveProjectiveIso x).symm
  have hpre : IsUniserialModule Aᵐᵒᵖ
      (LinearMap.range (aLin.comp sourceEquiv.toLinearMap)) :=
    uniserial_range_precomp_linearEquiv aLin sourceEquiv haUni
  have hpost : IsUniserialModule Aᵐᵒᵖ
      (LinearMap.range (targetEquiv.toLinearMap.comp
        (aLin.comp sourceEquiv.toLinearMap))) :=
    uniserial_range_postcomp_linearEquiv
      (aLin.comp sourceEquiv.toLinearMap) targetEquiv hpre
  have htransport : targetEquiv.toLinearMap.comp
        (aLin.comp sourceEquiv.toLinearMap) =
      (P.projectiveHomTransport f.1).hom.hom := by
    apply LinearMap.ext
    intro z
    rfl
  rw [htransport] at hpost
  exact IsUniserialModule.congr
    (P.projectiveHomRangePrincipalRightIdealLinearEquiv f.1) hpost

/-- Every displayed ordinary-arrow representative generates a uniserial
principal right ideal. -/
theorem ordinaryArrow_rightIdeal_isUniserial
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial)
    (D : S.OrdinaryArrowRepresentatives)
    (hHomAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶
            S.ordinaryProjectiveObj x))
    {x y : S.ProjectiveLabel} (a : S.OrdinaryArrow x y) :
    IsUniserialModule Aᵐᵒᵖ
      (RightModule.rightIdeal
        (P.projectiveHomCoordinate (D.hom a))) :=
  P.radical_rightIdeal_isUniserial_of_not_mem_square
    hP D hHomAlternative (D.representative a)
      (D.hom_not_mem_radicalSquare a)

omit [IsNoetherianRing A] in
@[simp]
theorem oppositePresentation_idempotent_oppositeProjectiveCoordinate
    [IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ]
    (P : S.PrimitiveProjectivePresentation) (p : S.ProjectiveLabel) :
    P.oppositePresentation.idempotent
        (P.oppositeProjectiveCoordinate p) =
      P.oppositeIdempotent p := by
  exact congrArg P.oppositeIdempotent
    (P.oppositeProjectiveEquiv.symm_apply_apply p)

omit [IsNoetherianRing A] in
private theorem oppositePrimitiveSourceIso_naturality
    [IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ]
    (P : S.PrimitiveProjectivePresentation)
    {r p : S.ProjectiveLabel} (h : r = p) :
    (eqToIso (congrArg RightModule.rightIdealFGObj
      (congrArg P.oppositeIdempotent h))).trans
        (S.contragredientSkeleton.primitiveSourceIso
          (P.oppositePrimitive p)) =
      (S.contragredientSkeleton.primitiveSourceIso
        (P.oppositePrimitive r)).trans
        (eqToIso (congrArg S.contragredientSkeleton.fgObj
          (congrArg (fun s ↦ S.contragredientSkeleton.primitiveSourceLabel
            (P.oppositePrimitive s)) h))) := by
  subst p
  apply Iso.ext
  simp only [Iso.trans_hom, eqToIso.hom]
  rw [eqToHom_refl, eqToHom_refl, Category.id_comp, Category.comp_id]

omit [IsNoetherianRing A] [IsNoetherianRing Aᵐᵒᵖ] in
private theorem eqToIso_comp_apply_rightIdealGenerator_val
    [IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ]
    {e e' g g' : Aᵐᵒᵖ} (he : e = e') (hg : g = g')
    (m : RightModule.rightIdealFGObj e' ⟶
      RightModule.rightIdealFGObj g') :
    (((eqToIso (congrArg RightModule.rightIdealFGObj he)).hom ≫ m ≫
        (eqToIso (congrArg RightModule.rightIdealFGObj hg)).inv).hom.hom
          (RightModule.rightIdealGenerator e)).1 =
      (m.hom.hom (RightModule.rightIdealGenerator e')).1 := by
  subst e'
  subst g'
  rw [eqToIso_refl, eqToIso_refl]
  simp

omit [IsNoetherianRing A] in
theorem oppositePresentation_primitiveProjectiveIso_coordinate
    [IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ]
    (P : S.PrimitiveProjectivePresentation) (p : S.ProjectiveLabel) :
    P.oppositePresentation.primitiveProjectiveIso
        (P.oppositeProjectiveCoordinate p) =
      (eqToIso (congrArg RightModule.rightIdealFGObj
        (P.oppositePresentation_idempotent_oppositeProjectiveCoordinate p))).trans
          (P.oppositeProjectiveCoordinateIso p) := by
  have h : P.oppositeProjectiveEquiv.symm
      (P.oppositeProjectiveCoordinate p) = p := by
    change P.oppositeProjectiveEquiv.symm
      (P.oppositeProjectiveEquiv p) = p
    exact P.oppositeProjectiveEquiv.symm_apply_apply p
  simpa only [primitiveProjectiveIso, oppositePresentation,
      oppositeProjectiveCoordinateIso, oppositeProjectiveCoordinate,
      oppositeProjectiveEquiv, primitiveSourceProjectiveLabel] using
    (oppositePrimitiveSourceIso_naturality P h).symm

omit [IsNoetherianRing A] in
/-- The opposite-presentation coordinate of a dualized projective radical
morphism is the opposite of its original algebra coordinate. -/
theorem opposite_projectiveRadical_coordinate
    [IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ]
    (P : S.PrimitiveProjectivePresentation)
    {p q : S.ProjectiveLabel}
    (f : S.projectiveRadicalSubmodule p q) :
    P.oppositePresentation.projectiveHomCoordinate
        (P.projectiveRadicalOppositeLinearEquiv p q f).1 =
      MulOpposite.op (P.projectiveHomCoordinate f.1) := by
  let fop := (P.projectiveRadicalOppositeLinearEquiv p q f).1
  let m : RightModule.rightIdealFGObj (P.oppositeIdempotent p) ⟶
      RightModule.rightIdealFGObj (P.oppositeIdempotent q) :=
    (P.oppositeProjectiveCoordinateIso p).hom ≫
      P.oppositeProjectiveMap f.1.hom ≫
        (P.oppositeProjectiveCoordinateIso q).inv
  have htransport :
      P.oppositePresentation.projectiveHomTransport fop =
        (eqToIso (congrArg RightModule.rightIdealFGObj
          (P.oppositePresentation_idempotent_oppositeProjectiveCoordinate p))).hom ≫
          m ≫
            (eqToIso (congrArg RightModule.rightIdealFGObj
              (P.oppositePresentation_idempotent_oppositeProjectiveCoordinate q))).inv := by
    unfold projectiveHomTransport
    rw [P.oppositePresentation_primitiveProjectiveIso_coordinate p,
      P.oppositePresentation_primitiveProjectiveIso_coordinate q]
    simp [fop, m, projectiveRadicalOppositeLinearEquiv,
      projectiveOppositeHomLinearEquiv,
      FiniteIndecomposableSkeleton.projectiveInclusion, Category.assoc]
    rfl
  change
    (((P.oppositePresentation.projectiveHomTransport fop).hom.hom
        (RightModule.rightIdealGenerator
          (P.oppositePresentation.idempotent
            (P.oppositeProjectiveCoordinate p)))).1) =
      MulOpposite.op (P.projectiveHomCoordinate f.1)
  rw [htransport]
  rw [eqToIso_comp_apply_rightIdealGenerator_val
    (P.oppositePresentation_idempotent_oppositeProjectiveCoordinate p)
    (P.oppositePresentation_idempotent_oppositeProjectiveCoordinate q) m]
  dsimp only [m]
  have hliteral := P.oppositeProjectiveMap_literal_apply f.1.hom
    (RightModule.rightIdealGenerator (P.oppositeIdempotent p))
  have hcoordinate :
      (((P.primitiveProjectiveIso q).hom ≫ f.1.hom ≫
        (P.primitiveProjectiveIso p).inv).hom.hom
          (RightModule.rightIdealGenerator (P.idempotent q))).1 =
        P.projectiveHomCoordinate f.1 := by
    rfl
  simp only [ordinaryProjectiveObj] at hliteral
  calc
    _ = MulOpposite.op
        ((RightModule.rightIdealGenerator
          (P.oppositeIdempotent p)).1.unop *
            (((P.primitiveProjectiveIso q).hom ≫ f.1.hom ≫
              (P.primitiveProjectiveIso p).inv).hom.hom
                (RightModule.rightIdealGenerator (P.idempotent q))).1) :=
      hliteral
    _ = MulOpposite.op
        (P.idempotent p * P.projectiveHomCoordinate f.1) := by
      rw [hcoordinate]
      rfl
    _ = MulOpposite.op (P.projectiveHomCoordinate f.1) := by
      rw [P.idempotent_mul_projectiveHomCoordinate f.1]

omit [FiniteDimensional k A] [IsNoetherianRing A]
    [IsNoetherianRing Aᵐᵒᵖ] in
private theorem representationFinite_of_skeleton
    (S : RightModule.FiniteIndecomposableSkeleton k A) :
    RightModule.IsRepresentationFinite k A := by
  refine ⟨S.n, S.obj, ?_, ?_⟩
  · intro i
    exact ⟨S.obj_finite i, S.obj_indecomposable i⟩
  · intro M hM
    exact S.complete M hM

/-- Every displayed ordinary-arrow representative generates a uniserial
principal left ideal. -/
theorem ordinaryArrow_leftIdeal_isUniserial
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial)
    (D : S.OrdinaryArrowRepresentatives)
    {x y : S.ProjectiveLabel} (a : S.OrdinaryArrow x y) :
    IsUniserialModule A
      (RightModule.leftIdeal
        (P.projectiveHomCoordinate (D.hom a))) := by
  letI : IsNoetherianRing (Aᵐᵒᵖ)ᵐᵒᵖ :=
    IsNoetherianRing.of_finite k _
  let T := S.contragredientSkeleton
  let Pop := P.oppositePresentation
  let Dop : T.OrdinaryArrowRepresentatives := {
    representative := fun {_ _} b ↦ T.ordinaryArrowRadical b
    representative_mkQ := fun {_ _} b ↦ T.ordinaryArrowRadical_mkQ b }
  have hAop : RightModule.IsRepresentationFinite k Aᵐᵒᵖ := by
    exact representationFinite_of_skeleton S.contragredientSkeleton
  have hAlternative : ∀ u v : T.ProjectiveLabel,
      IsUniserialModule (End (T.ordinaryProjectiveObj u))
          (T.ordinaryProjectiveObj v ⟶ T.ordinaryProjectiveObj u) ∨
        IsUniserialModule (End (T.ordinaryProjectiveObj v))ᵐᵒᵖ
          (T.ordinaryProjectiveObj v ⟶ T.ordinaryProjectiveObj u) := by
    intro u v
    exact Pop.finiteIdeal_projectiveHom_uniserialAlternative hAop
      (T.ordinaryProjectiveObj v) (T.ordinaryProjectiveObj u)
  let fop := P.projectiveRadicalOppositeLinearEquiv x y
    (D.representative a)
  have hfop : fop.1 ∉ T.projectiveRadicalSquareSubmodule
      (P.oppositeProjectiveCoordinate y)
      (P.oppositeProjectiveCoordinate x) := by
    intro hf
    exact D.hom_not_mem_radicalSquare a
      ((P.projectiveRadicalOppositeLinearEquiv_mem_square_iff
        x y (D.representative a)).1 hf)
  have hright : IsUniserialModule (Aᵐᵒᵖ)ᵐᵒᵖ
      (RightModule.rightIdeal
        (Pop.projectiveHomCoordinate fop.1)) :=
    Pop.radical_rightIdeal_isUniserial_of_not_mem_square
      (P.oppositePresentation_isBiserial hP) Dop hAlternative fop hfop
  rw [P.opposite_projectiveRadical_coordinate (D.representative a)] at hright
  exact RightModule.leftIdeal_isUniserial_of_oppositeRightIdeal
    (P.projectiveHomCoordinate (D.hom a)) hright

/-- A representation-finite biserial primitive presentation admits ordinary
arrow representatives satisfying both special-biserial continuation bounds. -/
theorem exists_adapted_of_isBiserial
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial) :
    ∃ D : S.OrdinaryArrowRepresentatives,
      D.HasRightContinuationBound ∧ D.HasLeftContinuationBound := by
  have hA : RightModule.IsRepresentationFinite k A :=
    representationFinite_of_skeleton S
  have hAlternative : ∀ x y : S.ProjectiveLabel,
      IsUniserialModule (End (S.ordinaryProjectiveObj x))
          (S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x) ∨
        IsUniserialModule (End (S.ordinaryProjectiveObj y))ᵐᵒᵖ
          (S.ordinaryProjectiveObj y ⟶ S.ordinaryProjectiveObj x) := by
    intro x y
    exact P.finiteIdeal_projectiveHom_uniserialAlternative hA
      (S.ordinaryProjectiveObj y) (S.ordinaryProjectiveObj x)
  exact
    OrdinaryArrowRepresentatives.exists_adapted_of_isBiserial_of_swCorrectionData
      P hP
      (fun D F ↦
        P.exists_rightSWCorrectionChoice D F
          (P.ordinaryArrow_rightIdeal_isUniserial hP D hAlternative F.first)
          (fun z ↦ hAlternative F.middleVertex z))
      (fun D F ↦
        P.exists_leftSWCorrectionChoice D F
          (P.ordinaryArrow_leftIdeal_isUniserial hP D F.second)
          (fun z ↦ hAlternative z F.middleVertex))

/-- A representation-finite biserial basic algebra has a literal
special-biserial bound-quiver presentation. -/
theorem admitsSpecialBiserialPresentation_of_isBiserial
    [IsAlgClosed k]
    (P : S.PrimitiveProjectivePresentation) (hP : P.IsBiserial) :
    BoundQuiver.AdmitsSpecialBiserialPresentation k S.basicAlgebra := by
  obtain ⟨D, hRight, hLeft⟩ := P.exists_adapted_of_isBiserial hP
  exact ⟨{
    Vertex := S.OrdinaryLiftedVertex
    vertexFintype := inferInstance
    quiver := inferInstance
    arrowFintype := fun _ _ ↦ inferInstance
    presentation := D.liftedSpecialBiserialPresentation
      P hP hRight hLeft }⟩

end PrimitiveProjectivePresentation

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
