import MagnitudeConjecture.Algebra.LocalRingJacobson
import MagnitudeConjecture.Algebra.RightModulePrimitiveCornerCategory
import MagnitudeConjecture.Algebra.RightModuleRepresentationFiniteIdeals
import MagnitudeConjecture.LinearAlgebra.LocalAlgebraResidue
import Mathlib.CategoryTheory.Preadditive.Opposite
import Mathlib.Order.Atoms.Finite
import Mathlib.RingTheory.Jacobson.Radical
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.Algebra.Module.Submodule.RestrictScalars
import Mathlib.Tactic.Module

/-!
# Finite ideal lattices and primitive-projective Hom chains

For a complete primitive-projective presentation, endpoint-stable subspaces
of a concrete corner Hom space embed into the ambient two-sided ideal lattice.
The remainder of the Jans pencil argument will use this finiteness together
with the residue characters of the local endpoint endomorphism rings.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open Mathlib.Tactic.Module
open scoped Pointwise

namespace MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton

universe u

variable {k A : Type u} [Field k] [Ring A] [Algebra k A]
variable [FiniteDimensional k A] [IsNoetherianRing Aᵐᵒᵖ]
variable {S : RightModule.FiniteIndecomposableSkeleton k A}

namespace PrimitiveProjectivePresentation

variable (P : S.PrimitiveProjectivePresentation)

/-- The selected corner of an ambient two-sided ideal. -/
def finiteIdealCorner (I : TwoSidedIdeal A)
    (p q : P.PrimitiveCornerCategory) : Submodule k (p ⟶ q) where
  carrier := {f | f.1 ∈ I}
  zero_mem' := I.zero_mem
  add_mem' hf hg := I.add_mem hf hg
  smul_mem' c f hf := by
    change c • f.1 ∈ I
    rw [Algebra.smul_def]
    exact I.mul_mem_left _ _ hf

theorem finiteIdealCorner_isHomSubbimodule (I : TwoSidedIdeal A)
    (p q : P.PrimitiveCornerCategory) :
    IsHomSubbimodule (P.finiteIdealCorner I p q) := by
  constructor
  · intro a f hf
    change f.1 * a.1 ∈ I
    exact I.mul_mem_right _ _ hf
  · intro b f hf
    change b.1 * f.1 ∈ I
    exact I.mul_mem_left _ _ hf

/-- The ambient ideal generated by an endpoint-stable Hom subspace. -/
def finiteIdealHomSpan {p q : P.PrimitiveCornerCategory}
    (T : Submodule k (p ⟶ q)) : TwoSidedIdeal A :=
  TwoSidedIdeal.span ((fun f : p ⟶ q => f.1) '' (T : Set (p ⟶ q)))

/-- Project an ambient algebra element to a chosen primitive corner. -/
private def finiteIdealCornerProjection
    (p q : P.PrimitiveCornerCategory) (a : A) : p ⟶ q :=
  ⟨P.idempotent (P.cornerVertex q) * a *
      P.idempotent (P.cornerVertex p), ⟨a, rfl⟩⟩

@[simp]
private theorem finiteIdealCornerProjection_val
    (p q : P.PrimitiveCornerCategory) (a : A) :
    (P.finiteIdealCornerProjection p q a).1 =
      P.idempotent (P.cornerVertex q) * a *
        P.idempotent (P.cornerVertex p) :=
  rfl

@[simp]
private theorem finiteIdealHom_zero_val
    {p q : P.PrimitiveCornerCategory} :
    ((0 : p ⟶ q)).1 = (0 : A) :=
  rfl

@[simp]
private theorem finiteIdealHom_add_val
    {p q : P.PrimitiveCornerCategory} (f g : p ⟶ q) :
    (f + g).1 = f.1 + g.1 :=
  rfl

@[simp]
private theorem finiteIdealHom_neg_val
    {p q : P.PrimitiveCornerCategory} (f : p ⟶ q) :
    (-f).1 = -f.1 :=
  rfl

@[simp]
private theorem finiteIdealCornerProjection_val_hom
    {p q : P.PrimitiveCornerCategory} (f : p ⟶ q) :
    P.finiteIdealCornerProjection p q f.1 = f := by
  apply Subtype.ext
  simp only [finiteIdealCornerProjection_val]
  rw [P.primitiveCornerCategory_idempotent_mul_val,
    P.primitiveCornerCategory_val_mul_idempotent]

/-- Generating an ambient ideal and taking the original corner recovers an
endpoint-stable Hom subspace exactly. -/
theorem finiteIdealCorner_homSpan_eq
    {p q : P.PrimitiveCornerCategory} (T : Submodule k (p ⟶ q))
    (hT : IsHomSubbimodule T) :
    P.finiteIdealCorner (P.finiteIdealHomSpan T) p q = T := by
  apply le_antisymm
  · intro f hf
    change f.1 ∈ TwoSidedIdeal.span
      ((fun g : p ⟶ q => g.1) '' (T : Set (p ⟶ q))) at hf
    rw [TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure] at hf
    have hproj : ∀ z : A,
        z ∈ AddSubgroup.closure
          (Set.univ * ((fun g : p ⟶ q => g.1) ''
            (T : Set (p ⟶ q))) * Set.univ) →
        P.finiteIdealCornerProjection p q z ∈ T := by
      intro z hz
      induction hz using AddSubgroup.closure_induction with
      | mem z hz =>
          rcases hz with
            ⟨_, ⟨a, -, z, ⟨g, hg, rfl⟩, rfl⟩, b, -, rfl⟩
          let ap : End p :=
            ⟨P.idempotent (P.cornerVertex p) * b *
              P.idempotent (P.cornerVertex p), ⟨b, rfl⟩⟩
          let bq : End q :=
            ⟨P.idempotent (P.cornerVertex q) * a *
              P.idempotent (P.cornerVertex q), ⟨a, rfl⟩⟩
          have hm : (ap.asHom ≫ g) ≫ bq.asHom ∈ T :=
            hT.2 bq (hT.1 ap hg)
          have heq : P.finiteIdealCornerProjection p q (a * g.1 * b) =
              (ap.asHom ≫ g) ≫ bq.asHom := by
            apply Subtype.ext
            dsimp [finiteIdealCornerProjection, ap, bq]
            have hL := P.primitiveCornerCategory_idempotent_mul_val g
            have hR := P.primitiveCornerCategory_val_mul_idempotent g
            have hL' (z : A) :
                P.idempotent (P.cornerVertex q) * (g.1 * z) =
                  g.1 * z := by
              rw [← mul_assoc, hL]
            have hR' (z : A) :
                g.1 * (P.idempotent (P.cornerVertex p) * z) =
                  g.1 * z := by
              rw [← mul_assoc, hR]
            simp only [mul_assoc, hL', hR']
          rw [heq]
          exact hm
      | zero =>
          have heq : P.finiteIdealCornerProjection p q 0 = 0 := by
            apply Subtype.ext
            simp only [finiteIdealCornerProjection_val,
              finiteIdealHom_zero_val, mul_zero, zero_mul]
          rw [heq]
          exact T.zero_mem
      | add a b _ _ ha hb =>
          have heq : P.finiteIdealCornerProjection p q (a + b) =
              P.finiteIdealCornerProjection p q a +
                P.finiteIdealCornerProjection p q b := by
            apply Subtype.ext
            simp only [finiteIdealCornerProjection_val,
              finiteIdealHom_add_val, mul_add, add_mul]
          rw [heq]
          exact T.add_mem ha hb
      | neg a _ ha =>
          have heq : P.finiteIdealCornerProjection p q (-a) =
              -P.finiteIdealCornerProjection p q a := by
            apply Subtype.ext
            simp only [finiteIdealCornerProjection_val,
              finiteIdealHom_neg_val, mul_neg, neg_mul]
          rw [heq]
          exact T.neg_mem ha
    have hp := hproj f.1 hf
    rw [P.finiteIdealCornerProjection_val_hom f] at hp
    exact hp
  · intro f hf
    apply TwoSidedIdeal.subset_span
    exact ⟨f, hf, rfl⟩

/-- Bundled endpoint-stable Hom subspaces. -/
private def FiniteIdealHomSubbimodule
    (p q : P.PrimitiveCornerCategory) :=
  {T : Submodule k (p ⟶ q) // IsHomSubbimodule T}

private instance finiteIdealHomSubbimodule_partialOrder
    (p q : P.PrimitiveCornerCategory) :
    PartialOrder (P.FiniteIdealHomSubbimodule p q) :=
  PartialOrder.lift Subtype.val Subtype.val_injective

private def finiteIdealHomSubbimoduleIdeal
    {p q : P.PrimitiveCornerCategory}
    (T : P.FiniteIdealHomSubbimodule p q) : TwoSidedIdeal A :=
  P.finiteIdealHomSpan T.1

private theorem finiteIdealHomSubbimoduleIdeal_injective
    {p q : P.PrimitiveCornerCategory} :
    Function.Injective
      (P.finiteIdealHomSubbimoduleIdeal :
        P.FiniteIdealHomSubbimodule p q → TwoSidedIdeal A) := by
  intro T U h
  apply Subtype.ext
  have hT := P.finiteIdealCorner_homSpan_eq T.1 T.2
  have hU := P.finiteIdealCorner_homSpan_eq U.1 U.2
  rw [← hT, ← hU]
  change P.finiteIdealHomSpan T.1 = P.finiteIdealHomSpan U.1 at h
  rw [h]

private noncomputable instance finiteIdealHomSubbimodule_finite
    [Finite (TwoSidedIdeal A)] (p q : P.PrimitiveCornerCategory) :
    Finite (P.FiniteIdealHomSubbimodule p q) :=
  Finite.of_injective P.finiteIdealHomSubbimoduleIdeal
    P.finiteIdealHomSubbimoduleIdeal_injective

/-- Nilpotent Nakayama iteration for subspaces of a module over a
finite-dimensional (possibly noncommutative) algebra. -/
private theorem le_of_le_sup_nilpotent_smul
    {E M : Type u} [Ring E] [Algebra k E]
    [AddCommGroup M] [Module k M] [Module E M] [IsScalarTower k E M]
    (J : Submodule k E) (W T : Submodule k M)
    (hW : ∀ (a : E) {w : M}, w ∈ W → a • w ∈ W)
    (hJ : IsNilpotent J) (h : T ≤ W ⊔ J • T) : T ≤ W := by
  have hn : ∀ n : ℕ, T ≤ W ⊔ J ^ n • T := by
    intro n
    induction n with
    | zero =>
        simpa only [Submodule.pow_zero, Submodule.one_smul]
          using (show T ≤ W ⊔ T from le_sup_right)
    | succ n ih =>
        refine ih.trans (sup_le le_sup_left ?_)
        have hmono : J ^ n • T ≤ J ^ n • (W ⊔ J • T) :=
          Submodule.smul_mono le_rfl h
        refine hmono.trans ?_
        rw [Submodule.smul_sup]
        apply sup_le
        · refine (Submodule.smul_le.2 ?_).trans le_sup_left
          intro a _ w hw
          exact hW a hw
        · rw [← Submodule.smul_assoc]
          change (J ^ n * J) • T ≤ W ⊔ J ^ (n + 1) • T
          rw [← Submodule.pow_succ]
          exact le_sup_right
  obtain ⟨n, hnil⟩ := hJ
  have hn' := hn n
  rw [hnil] at hn'
  simpa only [Submodule.zero_eq_bot, Submodule.bot_smul,
    sup_bot_eq] using hn'

/-- The Jacobson radical, regarded over the coefficient field, remains a
nilpotent subspace in a finite-dimensional algebra. -/
private theorem restrictScalars_jacobson_isNilpotent
    {E : Type u} [Ring E] [Algebra k E] [FiniteDimensional k E] :
    IsNilpotent ((Ring.jacobson E).restrictScalars k) := by
  letI : IsArtinianRing E := IsArtinianRing.of_finite k E
  have hnil : IsNilpotent (Ring.jacobson E) := by
    simpa only [Ideal.jacobson_bot] using
      (IsArtinianRing.isNilpotent_jacobson_bot (R := E))
  obtain ⟨n, hn⟩ := hnil
  refine ⟨n + 1, ?_⟩
  rw [← Submodule.restrictScalars_pow (A := k) (B := E)
    (C := E) (I := (Ring.jacobson E : Submodule E E))
    n.succ_ne_zero]
  have hpow : (Ring.jacobson E : Ideal E) ^ (n + 1) = 0 := by
    rw [(Ring.jacobson E).pow_succ, hn, zero_mul]
  rw [show (Ring.jacobson E : Submodule E E) ^ (n + 1) = ⊥ by
    exact congrArg (fun I : Ideal E => (I : Submodule E E)) hpow]
  exact Submodule.restrictScalars_bot k E E

/-- Scalar multiplication through the target endomorphism algebra agrees
with the ambient `k`-linear structure on a Hom space. -/
private instance finiteIdealTargetScalarTower
    (p q : P.PrimitiveCornerCategory) :
    IsScalarTower k (End q) (p ⟶ q) where
  smul_assoc c b f := by
    change f ≫ (c • b).asHom = c • (f ≫ b.asHom)
    exact CategoryTheory.Linear.comp_smul p q q f c b.asHom

/-- Enlarge a Hom subspace by the action of the target Jacobson radical. -/
private def finiteIdealTargetRadicalExtension
    {p q : P.PrimitiveCornerCategory}
    (W T : Submodule k (p ⟶ q)) : Submodule k (p ⟶ q) :=
  W ⊔ (Ring.jacobson (End q)).restrictScalars k • T

/-- The target-radical extension remains stable under both endpoints. -/
private theorem finiteIdealTargetRadicalExtension_isHomSubbimodule
    {p q : P.PrimitiveCornerCategory}
    (W T : Submodule k (p ⟶ q))
    (hW : IsHomSubbimodule W) (hT : IsHomSubbimodule T) :
    IsHomSubbimodule (P.finiteIdealTargetRadicalExtension W T) := by
  let J : Submodule k (End q) :=
    (Ring.jacobson (End q)).restrictScalars k
  constructor
  · intro a f hf
    change f ∈ W ⊔ J • T at hf
    change a.asHom ≫ f ∈ W ⊔ J • T
    rcases Submodule.mem_sup.mp hf with ⟨w, hw, z, hz, rfl⟩
    rw [Preadditive.comp_add]
    apply Submodule.add_mem
    · exact (show W ≤ W ⊔ J • T from le_sup_left) (hW.1 a hw)
    · apply (show J • T ≤ W ⊔ J • T from le_sup_right)
      refine Submodule.smul_induction_on hz ?_ ?_
      · intro r hr t ht
        have hgen : r • (a.asHom ≫ t) ∈ J • T :=
          Submodule.smul_mem_smul hr (hT.1 a ht)
        change a.asHom ≫ (t ≫ r.asHom) ∈ J • T
        change (a.asHom ≫ t) ≫ r.asHom ∈ J • T at hgen
        simpa only [Category.assoc] using hgen
      · intro x y hx hy
        rw [Preadditive.comp_add]
        exact Submodule.add_mem _ hx hy
  · intro b f hf
    change f ∈ W ⊔ J • T at hf
    change f ≫ b.asHom ∈ W ⊔ J • T
    rcases Submodule.mem_sup.mp hf with ⟨w, hw, z, hz, rfl⟩
    rw [Preadditive.add_comp]
    apply Submodule.add_mem
    · exact (show W ≤ W ⊔ J • T from le_sup_left) (hW.2 b hw)
    · apply (show J • T ≤ W ⊔ J • T from le_sup_right)
      refine Submodule.smul_induction_on hz ?_ ?_
      · intro r hr t ht
        have hbr : b * r ∈ J := by
          exact (Ring.jacobson (End q)).mul_mem_left b hr
        have hgen : (b * r) • t ∈ J • T :=
          Submodule.smul_mem_smul hbr ht
        change (t ≫ r.asHom) ≫ b.asHom ∈ J • T
        change t ≫ (r.asHom ≫ b.asHom) ∈ J • T at hgen
        simpa only [Category.assoc] using hgen
      · intro x y hx hy
        rw [Preadditive.add_comp]
        exact Submodule.add_mem _ hx hy

/-- At a cover of endpoint-stable Hom subspaces, adding the target
Jacobson-radical action produces no new vectors. -/
private theorem finiteIdealTargetRadicalExtension_eq_of_homCover
    {p q : P.PrimitiveCornerCategory}
    (W T : Submodule k (p ⟶ q))
    (hW : IsHomSubbimodule W) (hT : IsHomSubbimodule T)
    (hWT : W ≤ T) (hne : W ≠ T)
    (hcover : ∀ U : Submodule k (p ⟶ q),
      IsHomSubbimodule U → W ≤ U → U ≤ T → U = W ∨ U = T) :
    P.finiteIdealTargetRadicalExtension W T = W := by
  let J : Submodule k (End q) :=
    (Ring.jacobson (End q)).restrictScalars k
  let U := P.finiteIdealTargetRadicalExtension W T
  have hWU : W ≤ U := le_sup_left
  have hradT : J • T ≤ T := by
    apply Submodule.smul_le.2
    intro r _ t ht
    exact hT.2 r ht
  have hUT : U ≤ T := sup_le hWT hradT
  rcases hcover U
      (P.finiteIdealTargetRadicalExtension_isHomSubbimodule W T hW hT)
      hWU hUT with hUW | hUTeq
  · exact hUW
  · exfalso
    letI : Module.Finite k (End q) :=
      P.primitiveCornerCategoryHomFinite q q
    have hle : T ≤ W ⊔ J • T := by
      change T ≤ U
      exact hUTeq.symm.le
    have hTW : T ≤ W := le_of_le_sup_nilpotent_smul J W T
      (fun b _ hw ↦ hW.2 b hw)
      (restrictScalars_jacobson_isNilpotent (E := End q)) hle
    exact hne (le_antisymm hWT hTW)

/-- Scalar multiplication through the opposite source endomorphism algebra
agrees with the ambient `k`-linear structure on a Hom space. -/
private instance finiteIdealSourceScalarTower
    (p q : P.PrimitiveCornerCategory) :
    IsScalarTower k (End p)ᵐᵒᵖ (p ⟶ q) where
  smul_assoc c a f := by
    change (c • a.unop).asHom ≫ f = c • (a.unop.asHom ≫ f)
    exact CategoryTheory.Linear.smul_comp p p q c a.unop.asHom f

/-- Enlarge a Hom subspace by the action of the source Jacobson radical. -/
private def finiteIdealSourceRadicalExtension
    {p q : P.PrimitiveCornerCategory}
    (W T : Submodule k (p ⟶ q)) : Submodule k (p ⟶ q) :=
  W ⊔ (Ring.jacobson (End p)ᵐᵒᵖ).restrictScalars k • T

/-- The source-radical extension remains stable under both endpoints. -/
private theorem finiteIdealSourceRadicalExtension_isHomSubbimodule
    {p q : P.PrimitiveCornerCategory}
    (W T : Submodule k (p ⟶ q))
    (hW : IsHomSubbimodule W) (hT : IsHomSubbimodule T) :
    IsHomSubbimodule (P.finiteIdealSourceRadicalExtension W T) := by
  let J : Submodule k (End p)ᵐᵒᵖ :=
    (Ring.jacobson (End p)ᵐᵒᵖ).restrictScalars k
  constructor
  · intro a f hf
    change f ∈ W ⊔ J • T at hf
    change a.asHom ≫ f ∈ W ⊔ J • T
    rcases Submodule.mem_sup.mp hf with ⟨w, hw, z, hz, rfl⟩
    rw [Preadditive.comp_add]
    apply Submodule.add_mem
    · exact (show W ≤ W ⊔ J • T from le_sup_left) (hW.1 a hw)
    · apply (show J • T ≤ W ⊔ J • T from le_sup_right)
      refine Submodule.smul_induction_on hz ?_ ?_
      · intro r hr t ht
        have har : MulOpposite.op a * r ∈ J := by
          exact (Ring.jacobson (End p)ᵐᵒᵖ).mul_mem_left
            (MulOpposite.op a) hr
        have hgen : (MulOpposite.op a * r) • t ∈ J • T :=
          Submodule.smul_mem_smul har ht
        change a.asHom ≫ (r.unop.asHom ≫ t) ∈ J • T
        change (a.asHom ≫ r.unop.asHom) ≫ t ∈ J • T at hgen
        simpa only [Category.assoc] using hgen
      · intro x y hx hy
        rw [Preadditive.comp_add]
        exact Submodule.add_mem _ hx hy
  · intro b f hf
    change f ∈ W ⊔ J • T at hf
    change f ≫ b.asHom ∈ W ⊔ J • T
    rcases Submodule.mem_sup.mp hf with ⟨w, hw, z, hz, rfl⟩
    rw [Preadditive.add_comp]
    apply Submodule.add_mem
    · exact (show W ≤ W ⊔ J • T from le_sup_left) (hW.2 b hw)
    · apply (show J • T ≤ W ⊔ J • T from le_sup_right)
      refine Submodule.smul_induction_on hz ?_ ?_
      · intro r hr t ht
        have hgen : r • (t ≫ b.asHom) ∈ J • T :=
          Submodule.smul_mem_smul hr (hT.2 b ht)
        change (r.unop.asHom ≫ t) ≫ b.asHom ∈ J • T
        change r.unop.asHom ≫ (t ≫ b.asHom) ∈ J • T at hgen
        simpa only [Category.assoc] using hgen
      · intro x y hx hy
        rw [Preadditive.add_comp]
        exact Submodule.add_mem _ hx hy

/-- At a cover of endpoint-stable Hom subspaces, adding the source
Jacobson-radical action produces no new vectors. -/
private theorem finiteIdealSourceRadicalExtension_eq_of_homCover
    {p q : P.PrimitiveCornerCategory}
    (W T : Submodule k (p ⟶ q))
    (hW : IsHomSubbimodule W) (hT : IsHomSubbimodule T)
    (hWT : W ≤ T) (hne : W ≠ T)
    (hcover : ∀ U : Submodule k (p ⟶ q),
      IsHomSubbimodule U → W ≤ U → U ≤ T → U = W ∨ U = T) :
    P.finiteIdealSourceRadicalExtension W T = W := by
  let J : Submodule k (End p)ᵐᵒᵖ :=
    (Ring.jacobson (End p)ᵐᵒᵖ).restrictScalars k
  let U := P.finiteIdealSourceRadicalExtension W T
  have hWU : W ≤ U := le_sup_left
  have hradT : J • T ≤ T := by
    apply Submodule.smul_le.2
    intro r _ t ht
    exact hT.1 r.unop ht
  have hUT : U ≤ T := sup_le hWT hradT
  rcases hcover U
      (P.finiteIdealSourceRadicalExtension_isHomSubbimodule W T hW hT)
      hWU hUT with hUW | hUTeq
  · exact hUW
  · exfalso
    letI : Module.Finite k (End p) :=
      P.primitiveCornerCategoryHomFinite p p
    letI : Module.Finite k (End p)ᵐᵒᵖ :=
      Module.Finite.equiv (MulOpposite.opLinearEquiv k)
    have hle : T ≤ W ⊔ J • T := by
      change T ≤ U
      exact hUTeq.symm.le
    have hTW : T ≤ W := le_of_le_sup_nilpotent_smul J W T
      (fun a _ hw ↦ hW.1 a.unop hw)
      (restrictScalars_jacobson_isNilpotent (E := (End p)ᵐᵒᵖ)) hle
    exact hne (le_antisymm hWT hTW)

/-- On a cover, every target endomorphism acts by its local-algebra residue
character modulo the lower Hom subbimodule. -/
private theorem finiteIdeal_target_action_sub_residue_mem_of_homCover
    [IsAlgClosed k] {p q : P.PrimitiveCornerCategory}
    [Module.Finite k (End q)]
    (W T : Submodule k (p ⟶ q))
    (hW : IsHomSubbimodule W) (hT : IsHomSubbimodule T)
    (hWT : W ≤ T) (hne : W ≠ T)
    (hcover : ∀ U : Submodule k (p ⟶ q),
      IsHomSubbimodule U → W ≤ U → U ≤ T → U = W ∨ U = T)
    {f : p ⟶ q} (hf : f ∈ T) (b : End q) :
    f ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • f ∈ W := by
  let ρ := LocalAlgebraResidue.residueAlgHom k (End q)
  let n : End q := b - ρ b • 1
  have hnres : ρ n = 0 := by
    dsimp only [n]
    rw [map_sub, map_smul, map_one, smul_eq_mul, mul_one, sub_self]
  have hnNonunit : ¬ IsUnit n :=
    (LocalAlgebraResidue.mem_ker_residueLinearMap_iff
      (k := k) (E := End q) n).1 (by
        change LocalAlgebraResidue.residueScalar k n = 0
        exact hnres)
  letI : IsArtinianRing (End q) := IsArtinianRing.of_finite k (End q)
  have hnJ : n ∈ Ring.jacobson (End q) :=
    (mem_ringJacobson_iff_not_isUnit (End q) n).2 hnNonunit
  have hrad : n • f ∈
      (Ring.jacobson (End q)).restrictScalars k • T :=
    Submodule.smul_mem_smul hnJ hf
  have hmem : n • f ∈ W := by
    have hext : n • f ∈ P.finiteIdealTargetRadicalExtension W T :=
      (show (Ring.jacobson (End q)).restrictScalars k • T ≤
        P.finiteIdealTargetRadicalExtension W T from le_sup_right) hrad
    rw [P.finiteIdealTargetRadicalExtension_eq_of_homCover
      W T hW hT hWT hne hcover] at hext
    exact hext
  have hcomp : n • f =
      f ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • f := by
    change f ≫ (b.asHom - ρ b • 𝟙 q) = _
    rw [Preadditive.comp_sub, CategoryTheory.Linear.comp_smul,
      Category.comp_id]
    rfl
  rw [hcomp] at hmem
  exact hmem

/-- On a cover, every source endomorphism acts by its local-algebra residue
character modulo the lower Hom subbimodule. -/
private theorem finiteIdeal_source_action_sub_residue_mem_of_homCover
    [IsAlgClosed k] {p q : P.PrimitiveCornerCategory}
    [Module.Finite k (End p)]
    (W T : Submodule k (p ⟶ q))
    (hW : IsHomSubbimodule W) (hT : IsHomSubbimodule T)
    (hWT : W ≤ T) (hne : W ≠ T)
    (hcover : ∀ U : Submodule k (p ⟶ q),
      IsHomSubbimodule U → W ≤ U → U ≤ T → U = W ∨ U = T)
    {f : p ⟶ q} (hf : f ∈ T) (a : End p) :
    a.asHom ≫ f - LocalAlgebraResidue.residueScalar k a • f ∈ W := by
  letI : IsLocalRing (End p)ᵐᵒᵖ := mulOpposite_isLocalRing
  letI : Module.Finite k (End p)ᵐᵒᵖ :=
    Module.Finite.equiv (MulOpposite.opLinearEquiv k)
  let ρ := LocalAlgebraResidue.residueAlgHom k (End p)
  let n : End p := a - ρ a • 1
  have hnres : ρ n = 0 := by
    dsimp only [n]
    rw [map_sub, map_smul, map_one, smul_eq_mul, mul_one, sub_self]
  have hnNonunit : ¬ IsUnit n :=
    (LocalAlgebraResidue.mem_ker_residueLinearMap_iff
      (k := k) (E := End p) n).1 (by
        change LocalAlgebraResidue.residueScalar k n = 0
        exact hnres)
  have hnNonunitOp : ¬ IsUnit (MulOpposite.op n) := by
    simpa using hnNonunit
  letI : IsArtinianRing (End p)ᵐᵒᵖ :=
    IsArtinianRing.of_finite k (End p)ᵐᵒᵖ
  have hnJ : MulOpposite.op n ∈ Ring.jacobson (End p)ᵐᵒᵖ :=
    (mem_ringJacobson_iff_not_isUnit ((End p)ᵐᵒᵖ)
      (MulOpposite.op n)).2 hnNonunitOp
  have hrad : MulOpposite.op n • f ∈
      (Ring.jacobson (End p)ᵐᵒᵖ).restrictScalars k • T :=
    Submodule.smul_mem_smul hnJ hf
  have hmem : MulOpposite.op n • f ∈ W := by
    have hext : MulOpposite.op n • f ∈
        P.finiteIdealSourceRadicalExtension W T :=
      (show (Ring.jacobson (End p)ᵐᵒᵖ).restrictScalars k • T ≤
        P.finiteIdealSourceRadicalExtension W T from le_sup_right) hrad
    rw [P.finiteIdealSourceRadicalExtension_eq_of_homCover
      W T hW hT hWT hne hcover] at hext
    exact hext
  have hcomp : MulOpposite.op n • f =
      a.asHom ≫ f - LocalAlgebraResidue.residueScalar k a • f := by
    change (a.asHom - ρ a • 𝟙 p) ≫ f = _
    rw [Preadditive.sub_comp, CategoryTheory.Linear.smul_comp,
      Category.id_comp]
    rfl
  rw [hcomp] at hmem
  exact hmem

/-- The line through `x + c • y`, enlarged by a fixed lower submodule. -/
private def finiteIdealPencilSubmodule
    {p q : P.PrimitiveCornerCategory} (W : Submodule k (p ⟶ q))
    (x y : p ⟶ q) (c : k) : Submodule k (p ⟶ q) :=
  W ⊔ Submodule.span k ({x + c • y} : Set (p ⟶ q))

/-- If both vectors transform by the endpoint residue characters modulo
`W`, every member of their projective pencil is endpoint-stable. -/
private theorem finiteIdealPencil_isHomSubbimodule
    [IsAlgClosed k] {p q : P.PrimitiveCornerCategory}
    [Module.Finite k (End p)] [Module.Finite k (End q)]
    (W : Submodule k (p ⟶ q)) (hW : IsHomSubbimodule W)
    (x y : p ⟶ q)
    (hxSource : ∀ a : End p,
      a.asHom ≫ x - LocalAlgebraResidue.residueScalar k a • x ∈ W)
    (hySource : ∀ a : End p,
      a.asHom ≫ y - LocalAlgebraResidue.residueScalar k a • y ∈ W)
    (hxTarget : ∀ b : End q,
      x ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • x ∈ W)
    (hyTarget : ∀ b : End q,
      y ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • y ∈ W)
    (c : k) :
    IsHomSubbimodule (P.finiteIdealPencilSubmodule W x y c) := by
  let z : p ⟶ q := x + c • y
  let U := P.finiteIdealPencilSubmodule W x y c
  have hzmem : z ∈ U := by
    apply (show Submodule.span k ({x + c • y} : Set (p ⟶ q)) ≤ U from
      le_sup_right)
    apply Submodule.subset_span
    simp only [Set.mem_singleton_iff]
    rfl
  have hzSource (a : End p) :
      a.asHom ≫ z - LocalAlgebraResidue.residueScalar k a • z ∈ W := by
    have h := W.add_mem (hxSource a) (W.smul_mem c (hySource a))
    convert h using 1
    dsimp only [z]
    simp only [Preadditive.comp_add, CategoryTheory.Linear.comp_smul]
    module
  have hzTarget (b : End q) :
      z ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • z ∈ W := by
    have h := W.add_mem (hxTarget b) (W.smul_mem c (hyTarget b))
    convert h using 1
    dsimp only [z]
    simp only [Preadditive.add_comp, CategoryTheory.Linear.smul_comp]
    module
  constructor
  · intro a f hf
    rcases Submodule.mem_sup.mp hf with ⟨w, hw, r, hr, rfl⟩
    obtain ⟨d, rfl⟩ := Submodule.mem_span_singleton.mp hr
    rw [Preadditive.comp_add, CategoryTheory.Linear.comp_smul]
    apply U.add_mem
    · exact (show W ≤ U from le_sup_left) (hW.1 a hw)
    · apply U.smul_mem
      have hrad :
          a.asHom ≫ z - LocalAlgebraResidue.residueScalar k a • z ∈ U :=
        (show W ≤ U from le_sup_left) (hzSource a)
      have hscalar : LocalAlgebraResidue.residueScalar k a • z ∈ U :=
        U.smul_mem _ hzmem
      have heq : a.asHom ≫ z =
          (a.asHom ≫ z - LocalAlgebraResidue.residueScalar k a • z) +
            LocalAlgebraResidue.residueScalar k a • z := by
        module
      rw [heq]
      exact U.add_mem hrad hscalar
  · intro b f hf
    rcases Submodule.mem_sup.mp hf with ⟨w, hw, r, hr, rfl⟩
    obtain ⟨d, rfl⟩ := Submodule.mem_span_singleton.mp hr
    rw [Preadditive.add_comp, CategoryTheory.Linear.smul_comp]
    apply U.add_mem
    · exact (show W ≤ U from le_sup_left) (hW.2 b hw)
    · apply U.smul_mem
      have hrad :
          z ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • z ∈ U :=
        (show W ≤ U from le_sup_left) (hzTarget b)
      have hscalar : LocalAlgebraResidue.residueScalar k b • z ∈ U :=
        U.smul_mem _ hzmem
      have heq : z ≫ b.asHom =
          (z ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • z) +
            LocalAlgebraResidue.residueScalar k b • z := by
        module
      rw [heq]
      exact U.add_mem hrad hscalar

/-- Independent directions modulo `W` give distinct members of the pencil. -/
private theorem finiteIdealPencilSubmodule_injective
    {p q : P.PrimitiveCornerCategory} (W : Submodule k (p ⟶ q))
    (x y : p ⟶ q)
    (hindependent : ∀ a b : k,
      a • x + b • y ∈ W → a = 0 ∧ b = 0) :
    Function.Injective (P.finiteIdealPencilSubmodule W x y) := by
  intro c d hcd
  let zc : p ⟶ q := x + c • y
  let zd : p ⟶ q := x + d • y
  have hzc : zc ∈ P.finiteIdealPencilSubmodule W x y c := by
    apply (show Submodule.span k ({x + c • y} : Set (p ⟶ q)) ≤
      P.finiteIdealPencilSubmodule W x y c from le_sup_right)
    exact Submodule.subset_span (by simp [zc])
  have hzcd : zc ∈ P.finiteIdealPencilSubmodule W x y d := by
    rw [← hcd]
    exact hzc
  rcases Submodule.mem_sup.mp hzcd with ⟨w, hw, r, hr, hsum⟩
  obtain ⟨e, he⟩ := Submodule.mem_span_singleton.mp hr
  have hlinear : (1 - e) • x + (c - e * d) • y = w := by
    dsimp only [zc, zd] at hsum he
    rw [← he] at hsum
    calc
      (1 - e) • x + (c - e * d) • y =
          (x + c • y) - e • (x + d • y) := by module
      _ = w := by rw [← hsum]; module
  have hmem : (1 - e) • x + (c - e * d) • y ∈ W := by
    rw [hlinear]
    exact hw
  obtain ⟨he1, hced⟩ := hindependent (1 - e) (c - e * d) hmem
  have heq : e = 1 := (sub_eq_zero.mp he1).symm
  rw [heq, one_mul, sub_eq_zero] at hced
  exact hced

/-- Vectors chosen in distinct branches above an intersection are linearly
independent modulo that intersection. -/
private theorem finiteIdeal_fork_linear_independent_mod_inf
    {p q : P.PrimitiveCornerCategory}
    (W T U : Submodule k (p ⟶ q)) (hW : W = T ⊓ U)
    (x y : p ⟶ q) (hxT : x ∈ T) (hxW : x ∉ W)
    (hyU : y ∈ U) (hyW : y ∉ W) :
    ∀ a b : k, a • x + b • y ∈ W → a = 0 ∧ b = 0 := by
  intro a b hab
  have hWU : W ≤ U := by
    rw [hW]
    exact inf_le_right
  have hWT : W ≤ T := by
    rw [hW]
    exact inf_le_left
  have haxU : a • x ∈ U := by
    have hsub := U.sub_mem (hWU hab) (U.smul_mem b hyU)
    have hcalc : a • x = (a • x + b • y) - b • y := by
      module
    rw [hcalc]
    exact hsub
  have haxW : a • x ∈ W := by
    rw [hW]
    exact ⟨T.smul_mem a hxT, haxU⟩
  have ha : a = 0 := by
    by_contra ha0
    apply hxW
    have hinv := W.smul_mem a⁻¹ haxW
    simpa only [smul_smul, inv_mul_cancel₀ ha0, one_smul] using hinv
  have hbyT : b • y ∈ T := by
    have hsub := T.sub_mem (hWT hab) (T.smul_mem a hxT)
    rw [ha, zero_smul, sub_zero] at hsub
    simpa only [zero_add] using hsub
  have hbyW : b • y ∈ W := by
    rw [hW]
    exact ⟨hbyT, U.smul_mem b hyU⟩
  have hb : b = 0 := by
    by_contra hb0
    apply hyW
    have hinv := W.smul_mem b⁻¹ hbyW
    simpa only [smul_smul, inv_mul_cancel₀ hb0, one_smul] using hinv
  exact ⟨ha, hb⟩

/-- Representation-finiteness forces every pair of endpoint-stable
subspaces of a concrete primitive-projective Hom space to be comparable. -/
theorem finiteIdeal_homSubbimodule_comparable
    [IsAlgClosed k]
    (hA : RightModule.IsRepresentationFinite k A)
    {p q : P.PrimitiveCornerCategory}
    (T U : Submodule k (p ⟶ q))
    (hT : IsHomSubbimodule T) (hU : IsHomSubbimodule U) :
    T ≤ U ∨ U ≤ T := by
  letI : Finite (TwoSidedIdeal A) := hA.finite_twoSidedIdeal
  letI : Module.Finite k (End p) :=
    P.primitiveCornerCategoryHomFinite p p
  letI : Module.Finite k (End q) :=
    P.primitiveCornerCategoryHomFinite q q
  letI : Finite (P.FiniteIdealHomSubbimodule p q) :=
    finiteIdealHomSubbimodule_finite P p q
  by_contra hcomparable
  push Not at hcomparable
  rcases hcomparable with ⟨hTnotU, hUnotT⟩
  let W : Submodule k (p ⟶ q) := T ⊓ U
  have hW : IsHomSubbimodule W := by
    constructor
    · intro a f hf
      exact ⟨hT.1 a hf.1, hU.1 a hf.2⟩
    · intro b f hf
      exact ⟨hT.2 b hf.1, hU.2 b hf.2⟩
  let Tb : P.FiniteIdealHomSubbimodule p q := ⟨T, hT⟩
  let Ub : P.FiniteIdealHomSubbimodule p q := ⟨U, hU⟩
  let Wb : P.FiniteIdealHomSubbimodule p q := ⟨W, hW⟩
  have hWltTcar : W < T := by
    apply lt_of_le_of_ne
    · exact inf_le_left
    · intro hEq
      apply hTnotU
      rw [← hEq]
      exact inf_le_right
  have hWltUcar : W < U := by
    apply lt_of_le_of_ne
    · exact inf_le_right
    · intro hEq
      apply hUnotT
      rw [← hEq]
      exact inf_le_left
  have hWltT : Wb < Tb := hWltTcar
  have hWltU : Wb < Ub := hWltUcar
  obtain ⟨Pb, hcovP, hPleT⟩ := hWltT.exists_covby_le
  obtain ⟨Qb, hcovQ, hQleU⟩ := hWltU.exists_covby_le
  have hWPcar : W < Pb.1 := hcovP.lt
  have hWQcar : W < Qb.1 := hcovQ.lt
  have hcoverP : ∀ R : Submodule k (p ⟶ q),
      IsHomSubbimodule R → W ≤ R → R ≤ Pb.1 →
        R = W ∨ R = Pb.1 := by
    intro R hR hWR hRP
    let Rb : P.FiniteIdealHomSubbimodule p q := ⟨R, hR⟩
    have hWRb : Wb ≤ Rb := hWR
    have hRPb : Rb ≤ Pb := hRP
    rcases hcovP.eq_or_eq hWRb hRPb with hRW | hRP'
    · exact Or.inl (congrArg Subtype.val hRW)
    · exact Or.inr (congrArg Subtype.val hRP')
  have hcoverQ : ∀ R : Submodule k (p ⟶ q),
      IsHomSubbimodule R → W ≤ R → R ≤ Qb.1 →
        R = W ∨ R = Qb.1 := by
    intro R hR hWR hRQ
    let Rb : P.FiniteIdealHomSubbimodule p q := ⟨R, hR⟩
    have hWRb : Wb ≤ Rb := hWR
    have hRQb : Rb ≤ Qb := hRQ
    rcases hcovQ.eq_or_eq hWRb hRQb with hRW | hRQ'
    · exact Or.inl (congrArg Subtype.val hRW)
    · exact Or.inr (congrArg Subtype.val hRQ')
  have hWinter : W = Pb.1 ⊓ Qb.1 := by
    apply le_antisymm
    · intro f hf
      exact ⟨hcovP.le hf, hcovQ.le hf⟩
    · intro f hf
      change f ∈ T ∧ f ∈ U
      exact ⟨hPleT hf.1, hQleU hf.2⟩
  obtain ⟨x, hxP, hxW⟩ := SetLike.exists_of_lt hWPcar
  obtain ⟨y, hyQ, hyW⟩ := SetLike.exists_of_lt hWQcar
  have hxSource (a : End p) :
      a.asHom ≫ x - LocalAlgebraResidue.residueScalar k a • x ∈ W :=
    P.finiteIdeal_source_action_sub_residue_mem_of_homCover
      W Pb.1 hW Pb.2 hcovP.le (ne_of_lt hWPcar) hcoverP hxP a
  have hySource (a : End p) :
      a.asHom ≫ y - LocalAlgebraResidue.residueScalar k a • y ∈ W :=
    P.finiteIdeal_source_action_sub_residue_mem_of_homCover
      W Qb.1 hW Qb.2 hcovQ.le (ne_of_lt hWQcar) hcoverQ hyQ a
  have hxTarget (b : End q) :
      x ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • x ∈ W :=
    P.finiteIdeal_target_action_sub_residue_mem_of_homCover
      W Pb.1 hW Pb.2 hcovP.le (ne_of_lt hWPcar) hcoverP hxP b
  have hyTarget (b : End q) :
      y ≫ b.asHom - LocalAlgebraResidue.residueScalar k b • y ∈ W :=
    P.finiteIdeal_target_action_sub_residue_mem_of_homCover
      W Qb.1 hW Qb.2 hcovQ.le (ne_of_lt hWQcar) hcoverQ hyQ b
  have hindependent : ∀ a b : k,
      a • x + b • y ∈ W → a = 0 ∧ b = 0 :=
    P.finiteIdeal_fork_linear_independent_mod_inf
      W Pb.1 Qb.1 hWinter x y hxP hxW hyQ hyW
  let F : k → P.FiniteIdealHomSubbimodule p q := fun c ↦
    ⟨P.finiteIdealPencilSubmodule W x y c,
      P.finiteIdealPencil_isHomSubbimodule W hW x y
        hxSource hySource hxTarget hyTarget c⟩
  have hFinjective : Function.Injective F := by
    intro c d hcd
    apply P.finiteIdealPencilSubmodule_injective W x y hindependent
    exact congrArg Subtype.val hcd
  obtain ⟨c, d, hcd, hFcd⟩ :=
    Finite.exists_ne_map_eq_of_infinite F
  exact hcd (hFinjective hFcd)

end PrimitiveProjectivePresentation

end MagnitudeConjecture.RightModule.FiniteIndecomposableSkeleton
