import MagnitudeConjecture.Algebra.StringProjectiveARCount
import MagnitudeConjecture.Algebra.BiserialRadicalTruncation
import Mathlib.LinearAlgebra.Projection

/-!
# Cokernels of arrows in a string category algebra

For a displayed arrow `a : x ⟶ y`, Butler--Ringel's module `V(a)` is the
quotient of the represented projective at `y` by the submodule generated by
`a`.  This file packages that quotient literally and records its first local
properties: the arrow-generated submodule lies in the projective radical, so
the quotient retains the simple top and is indecomposable.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open QuotientSubmoduleEquidistribution

namespace MagnitudeConjecture.BoundQuiver

universe u

variable {k A Q : Type u} [Field k] [Ring A] [Algebra k A]
variable [Fintype Q] [Quiver.{u} Q]
variable [∀ x y : Q, Fintype (x ⟶ y)]

namespace StringPresentation

noncomputable local instance arrowCokernelAlgebraFiniteDimensional
    (P : StringPresentation k A Q) :
    FiniteDimensional k P.quotientCategoryAlgebra := by
  let hP := finiteRepresentablesOfAdmissible P.toPresentation.admissible
  exact
    CoveringHom.finiteCategoryProjectiveGenerator.algebra_finiteDimensional hP

noncomputable local instance arrowCokernelAlgebraOppositeIsNoetherian
    (P : StringPresentation k A Q) :
    IsNoetherianRing P.quotientCategoryAlgebraᵐᵒᵖ :=
  IsNoetherianRing.of_finite k _

/-- The submodule of the represented target projective generated by a
displayed arrow. -/
abbrev arrowCokernelSubmodule
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    Submodule P.quotientCategoryAlgebraᵐᵒᵖ (P.representedVertexModule y) :=
  LinearMap.range (P.representedArrowLinearMap a)

/-- Butler--Ringel's arrow-indexed module `V(a)`, retained in the finitely
generated module category. -/
def arrowCokernelFGObj
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    FGModuleCat P.quotientCategoryAlgebraᵐᵒᵖ := by
  letI : Module.Finite P.quotientCategoryAlgebraᵐᵒᵖ
      (P.representedVertexModule y) := inferInstance
  exact RightModule.quotientFGObj (P.representedVertexModule y)
    (P.arrowCokernelSubmodule a)

/-- The canonical projection from the represented target projective to
`V(a)`. -/
def arrowCokernelProjection
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.representedVertexModule y →ₗ[P.quotientCategoryAlgebraᵐᵒᵖ]
      P.arrowCokernelFGObj a := by
  exact (P.arrowCokernelSubmodule a).mkQ

/-- The canonical projection onto `V(a)`, bundled in the finitely generated
module category. -/
def arrowCokernelProjectionHom
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.representedVertexModule y ⟶ P.arrowCokernelFGObj a :=
  ConcreteCategory.ofHom (P.arrowCokernelProjection a)

/-- An arrow-generated submodule is one summand of the represented
projective's radical. -/
theorem arrowCokernelSubmodule_le_jacobson
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.arrowCokernelSubmodule a ≤
      Module.jacobson P.quotientCategoryAlgebraᵐᵒᵖ
        (P.representedVertexModule y) := by
  classical
  rw [← P.incomingArrowRangeSum_eq_jacobson y]
  rintro g ⟨f, rfl⟩
  let ga : P.arrowCokernelSubmodule a :=
    ⟨P.representedArrowLinearMap a f, ⟨f, rfl⟩⟩
  let v : ∀ b : DisplayedIncomingArrow y,
      LinearMap.range (P.representedArrowLinearMap b.2) :=
    Pi.single ⟨x, a⟩ ga
  refine ⟨v, ?_⟩
  change (∑ b : DisplayedIncomingArrow y, (v b).1) = _
  rw [Finset.sum_eq_single ⟨x, a⟩]
  · rw [show v ⟨x, a⟩ = ga by simp [v]]
  · intro b _ hba
    simp [v, hba]
  · simp

/-- The branch killed in `V(a)` is nonzero. -/
theorem arrowCokernelSubmodule_ne_bot
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.arrowCokernelSubmodule a ≠ ⊥ :=
  Submodule.nontrivial_iff_ne_bot.mp
    (P.representedArrowLinearRange_nontrivial a)

/-- The represented target projective has simple top. -/
theorem representedVertexModule_top_isSimple
    (P : StringPresentation k A Q) (y : Q) :
    IsSimpleModule P.quotientCategoryAlgebraᵐᵒᵖ
      (P.representedVertexModule y ⧸
        Module.jacobson P.quotientCategoryAlgebraᵐᵒᵖ
          (P.representedVertexModule y)) := by
  apply isSimpleModule_iff_isCoatom.mpr
  rw [← P.incomingArrowRangeSum_eq_jacobson y]
  exact P.incomingArrowRangeSum_isCoatom y

/-- The branch killed in `V(a)` is a proper submodule of its represented
projective. -/
theorem arrowCokernelSubmodule_ne_top
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.arrowCokernelSubmodule a ≠ ⊤ := by
  intro htop
  have hJtop :
      Module.jacobson P.quotientCategoryAlgebraᵐᵒᵖ
          (P.representedVertexModule y) = ⊤ := by
    apply top_unique
    rw [← htop]
    exact P.arrowCokernelSubmodule_le_jacobson a
  exact
    (isSimpleModule_iff_isCoatom.mp
      (P.representedVertexModule_top_isSimple y)).ne_top hJtop

/-- Quotienting a represented projective by one arrow-generated branch
preserves its simple top. -/
theorem arrowCokernelFGObj_top_isSimple
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    IsSimpleModule P.quotientCategoryAlgebraᵐᵒᵖ
      (P.arrowCokernelFGObj a ⧸
        Module.jacobson P.quotientCategoryAlgebraᵐᵒᵖ
          (P.arrowCokernelFGObj a)) := by
  exact isSimpleModule_top_quotient_of_le_jacobson
    (P.arrowCokernelSubmodule a)
    (P.arrowCokernelSubmodule_le_jacobson a)
    (P.representedVertexModule_top_isSimple y)

/-- The canonical projection onto `V(a)` is surjective. -/
theorem arrowCokernelProjection_surjective
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    Function.Surjective (P.arrowCokernelProjection a) :=
  (P.arrowCokernelSubmodule a).mkQ_surjective

/-- The bundled canonical projection onto `V(a)` is epic. -/
instance arrowCokernelProjectionHom_epi
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    Epi (P.arrowCokernelProjectionHom a) :=
  (QuotientSubmoduleEquidistribution.IndecomposableSkeleton.fg_epi_iff_surjective
    (P.arrowCokernelProjectionHom a)).2
      (P.arrowCokernelProjection_surjective a)

/-- The kernel of the canonical projection onto `V(a)` is precisely the
arrow-generated branch. -/
theorem arrowCokernelProjection_ker
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    LinearMap.ker (P.arrowCokernelProjection a) =
      P.arrowCokernelSubmodule a :=
  Submodule.ker_mkQ _

/-- The canonical projection onto `V(a)` is nonzero. -/
theorem arrowCokernelProjectionHom_ne_zero
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.arrowCokernelProjectionHom a ≠ 0 := by
  intro hzero
  have hlinearZero : P.arrowCokernelProjection a = 0 :=
    congrArg (fun f : P.representedVertexModule y ⟶
      P.arrowCokernelFGObj a ↦ f.hom.hom) hzero
  apply P.arrowCokernelSubmodule_ne_top a
  rw [← P.arrowCokernelProjection_ker a,
    LinearMap.ker_eq_top.mpr hlinearZero]

/-- The canonical projective epimorphism onto `V(a)` is right minimal. -/
theorem arrowCokernelProjectionHom_isRightMinimal
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    IsRightMinimal (P.arrowCokernelProjectionHom a) := by
  letI : IsLocalRing
      (Module.End P.quotientCategoryAlgebraᵐᵒᵖ
        (P.representedVertexModule y)) :=
    P.representedVertexModuleEnd_isLocalRing y
  letI : IsLocalRing (End (P.representedVertexModule y)) :=
    MagnitudeConjecture.RingEquiv.isLocalRing_noncomm
      (RightModule.FiniteIndecomposableSkeleton.fgEndModuleEndRingEquiv
        (P.representedVertexModule y)).symm
  exact isRightMinimal_of_localEnd_of_ne_zero
    (P.arrowCokernelProjectionHom a)
      (P.arrowCokernelProjectionHom_ne_zero a)

/-- The represented target projective and its canonical quotient map form
the minimal projective presentation of `V(a)`. -/
def arrowCokernelMinimalProjectivePresentation
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    MinimalProjectivePresentation (P.arrowCokernelFGObj a) where
  p := P.representedVertexModule y
  f := P.arrowCokernelProjectionHom a
  projective := P.representedVertexModule_projective y
  epi := inferInstance
  rightMinimal := P.arrowCokernelProjectionHom_isRightMinimal a

/-- Every arrow-indexed cokernel `V(a)` is nonzero. -/
theorem arrowCokernelFGObj_nontrivial
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    Nontrivial (P.arrowCokernelFGObj a) :=
  (IsUniserialModule.isIndecomposableModule_of_simpleTop
    (P.arrowCokernelFGObj_top_isSimple a)).nontrivial

/-- Every arrow-indexed cokernel `V(a)` is indecomposable. -/
theorem arrowCokernelFGObj_indecomposable
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    Indecomposable (P.arrowCokernelFGObj a) := by
  apply
    (RightModule.FiniteIndecomposableSkeleton.fgModule_isIndecomposableModule_iff_indecomposable
        (k := k) (A := P.quotientCategoryAlgebra)
        (P.arrowCokernelFGObj a)).mp
  exact IsUniserialModule.isIndecomposableModule_of_simpleTop
    (P.arrowCokernelFGObj_top_isSimple a)

/-- An arrow-indexed cokernel `V(a)` is not projective.  Otherwise its
canonical quotient would split, decomposing the indecomposable represented
target projective into the nonzero arrow range and a nonzero complement. -/
theorem arrowCokernelFGObj_not_projective
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    ¬ Projective (P.arrowCokernelFGObj a) := by
  intro hprojective
  let R := P.quotientCategoryAlgebraᵐᵒᵖ
  let T := P.representedVertexModule y
  let V := P.arrowCokernelFGObj a
  let q : T →ₗ[R] V := P.arrowCokernelProjection a
  letI : Module.Projective R V :=
    moduleProjective_of_fgProjective V hprojective
  obtain ⟨s, hs⟩ := Module.projective_lifting_property
    q (LinearMap.id (R := R) (M := V))
      (P.arrowCokernelProjection_surjective a)
  have hs_left : Function.LeftInverse q s := by
    intro z
    exact LinearMap.congr_fun hs z
  have hs_injective : Function.Injective s := hs_left.injective
  let e : Module.End R T := s.comp q
  have he : IsIdempotentElem e := by
    rw [IsIdempotentElem]
    apply LinearMap.ext
    intro z
    change s (q (s (q z))) = s (q z)
    rw [hs_left]
  have hker : LinearMap.ker e = P.arrowCokernelSubmodule a := by
    ext z
    change s (q z) = 0 ↔ z ∈ P.arrowCokernelSubmodule a
    constructor
    · intro hz
      have hqz : q z = 0 := hs_injective (by simpa using hz)
      rw [← P.arrowCokernelProjection_ker a]
      exact hqz
    · intro hz
      have hqz : q z = 0 := by
        rw [← LinearMap.mem_ker, P.arrowCokernelProjection_ker a]
        exact hz
      simp [hqz]
  have he_ne_zero : e ≠ 0 := by
    intro hezero
    have hs_zero : s = 0 := by
      apply LinearMap.ext
      intro z
      obtain ⟨t, rfl⟩ := P.arrowCokernelProjection_surjective a z
      change e t = 0
      rw [hezero]
      rfl
    letI : Nontrivial V := P.arrowCokernelFGObj_nontrivial a
    have hsubsingleton : Subsingleton V := by
      constructor
      intro z w
      apply hs_injective
      rw [hs_zero]
      rfl
    exact not_subsingleton_iff_nontrivial.mpr inferInstance hsubsingleton
  have hrange_ne_bot : LinearMap.range e ≠ ⊥ :=
    (not_congr LinearMap.range_eq_bot).mpr he_ne_zero
  have htargetIndecomposable :
      QuotientSubmoduleEquidistribution.Foundation.IsIndecomposableModule
        R T :=
    IsUniserialModule.isIndecomposableModule_of_simpleTop
      (P.representedVertexModule_top_isSimple y)
  rcases htargetIndecomposable.eq_bot_or_eq_bot
      (LinearMap.IsIdempotentElem.isCompl he) with
    hrange | hkerbot
  · exact hrange_ne_bot hrange
  · exact P.arrowCokernelSubmodule_ne_bot a (hker.symm.trans hkerbot)

end StringPresentation

end MagnitudeConjecture.BoundQuiver
