import MagnitudeConjecture.Algebra.StringPathCombinatorics

/-!
# Path bases for arrow-generated ideals

For a monomial special-biserial presentation, composition with one displayed
arrow has a basis indexed by the surviving continuations of that arrow.  The
continuation basis has at most one vector in every path length by
`StringPathCombinatorics`.  These are the pointwise path bases underlying the
uniserial modules `aA` in the string-algebra argument of the frozen manuscript.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory

namespace MagnitudeConjecture.BoundQuiver

universe u

variable {k A Q : Type u} [Field k] [Ring A] [Algebra k A]
variable [Fintype Q] [Quiver.{u} Q]
variable [∀ x y : Q, Fintype (x ⟶ y)]

namespace StringPresentation

/-- Surviving continuations from the endpoint of `a` to a fixed vertex `z`.
They index the `z`-coordinate of the right ideal generated by `a`. -/
abbrev RightContinuationAt
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :=
  {q : Quiver.Path y z //
    pathMap P.toPresentation.relations q ≫
        arrowMap P.toPresentation.relations a ≠ 0}

/-- Postcomposition by the image of `a`, in the reversed categorical
orientation of the bound-quiver category. -/
def rightArrowCompositionLinearMap
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    (obj P.toPresentation.relations z ⟶
        obj P.toPresentation.relations y) →ₗ[k]
      (obj P.toPresentation.relations z ⟶
        obj P.toPresentation.relations x) where
  toFun f := f ≫ arrowMap P.toPresentation.relations a
  map_add' f g := by simp only [Preadditive.add_comp]
  map_smul' r f := by
    simpa only [RingHom.id_apply] using
      (CategoryTheory.Linear.smul_comp _ _ _ r f
        (arrowMap P.toPresentation.relations a))

/-- A continuation indexes its concatenated surviving path. -/
def rightContinuationAtToSurviving
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    P.RightContinuationAt a z →
      SurvivingPath P.toPresentation.relations x z :=
  fun q ↦ ⟨a.toPath.comp q.1, by
    rw [← pathMap_comp]
    exact q.2⟩

/-- Concatenation with a fixed initial arrow is injective. -/
theorem rightContinuationAtToSurviving_injective
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Function.Injective (P.rightContinuationAtToSurviving a z) := by
  intro p q hpq
  apply Subtype.ext
  apply Quiver.Path.comp_injective_right a.toPath
  exact congrArg Subtype.val hpq

/-- A fixed-endpoint continuation is a continuation with varying endpoint. -/
def rightContinuationAtToPath
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    P.RightContinuationAt a z →
      P.toSpecialBiserialPresentation.RightContinuationPath a :=
  fun q ↦ ⟨⟨z, q.1⟩, q.2⟩

/-- Forgetting a fixed endpoint is injective. -/
theorem rightContinuationAtToPath_injective
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Function.Injective (P.rightContinuationAtToPath a z) := by
  intro p q hpq
  apply Subtype.ext
  have hval := congrArg
    (fun t : P.toSpecialBiserialPresentation.RightContinuationPath a ↦ t.1)
    hpq
  injection hval

/-- Fixed-endpoint continuations form a finite type. -/
theorem rightContinuationAt_finite
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Finite (P.RightContinuationAt a z) := by
  letI : Finite
      (P.toSpecialBiserialPresentation.RightContinuationPath a) :=
    P.toSpecialBiserialPresentation.rightContinuationPath_finite a
  exact Finite.of_injective (P.rightContinuationAtToPath a z)
    (P.rightContinuationAtToPath_injective a z)

/-- Path length embeds the fixed-endpoint continuation basis into the natural
numbers. -/
def rightContinuationAtLengthEmbedding
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    P.RightContinuationAt a z ↪ ℕ :=
  (⟨P.rightContinuationAtToPath a z,
      P.rightContinuationAtToPath_injective a z⟩ :
    P.RightContinuationAt a z ↪
      P.toSpecialBiserialPresentation.RightContinuationPath a).trans
    (P.toSpecialBiserialPresentation.rightContinuationLengthEmbedding a)

/-- The concatenated path map is the corresponding arrow-composition image. -/
theorem rightContinuationAt_pathMap
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q)
    (q : P.RightContinuationAt a z) :
    pathMap P.toPresentation.relations
        (P.rightContinuationAtToSurviving a z q).1 =
      P.rightArrowCompositionLinearMap a z
        (pathMap P.toPresentation.relations q.1) := by
  change
    pathMap P.toPresentation.relations (a.toPath.comp q.1) =
      pathMap P.toPresentation.relations q.1 ≫
        arrowMap P.toPresentation.relations a
  simpa only [arrowMap] using
    (pathMap_comp P.toPresentation.relations a.toPath q.1).symm

/-- Concatenated surviving continuations of an arrow are linearly
independent. -/
theorem rightContinuationAt_linearIndependent
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    LinearIndependent k
      (fun q : P.RightContinuationAt a z ↦
        P.rightArrowCompositionLinearMap a z
          (pathMap P.toPresentation.relations q.1)) := by
  have h :=
    (survivingPathMap_linearIndependent P.monomial x z).comp
      (P.rightContinuationAtToSurviving a z)
      (P.rightContinuationAtToSurviving_injective a z)
  have hfamily :
      ((fun p : SurvivingPath P.toPresentation.relations x z ↦
          pathMap P.toPresentation.relations p.1) ∘
          P.rightContinuationAtToSurviving a z) =
        (fun q : P.RightContinuationAt a z ↦
          P.rightArrowCompositionLinearMap a z
            (pathMap P.toPresentation.relations q.1)) := by
    funext q
    exact P.rightContinuationAt_pathMap a z q
  rw [hfamily] at h
  exact h

/-- The surviving continuations span the image of composition with `a`. -/
theorem span_rightContinuationAt_eq_range
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Submodule.span k
        (Set.range fun q : P.RightContinuationAt a z ↦
          P.rightArrowCompositionLinearMap a z
            (pathMap P.toPresentation.relations q.1)) =
      LinearMap.range (P.rightArrowCompositionLinearMap a z) := by
  apply le_antisymm
  · apply Submodule.span_le.2
    rintro f ⟨q, rfl⟩
    exact ⟨pathMap P.toPresentation.relations q.1, rfl⟩
  · rintro f ⟨g, rfl⟩
    have hg :=
      (survivingPathBasis P.toPresentation.relations P.monomial y z).mem_span g
    induction hg using Submodule.span_induction with
    | mem h hh =>
        rcases hh with ⟨q, rfl⟩
        rw [survivingPathBasis_apply]
        by_cases hq :
            pathMap P.toPresentation.relations q.1 ≫
                arrowMap P.toPresentation.relations a = 0
        · change
            P.rightArrowCompositionLinearMap a z
                (pathMap P.toPresentation.relations q.1) ∈ _
          rw [show P.rightArrowCompositionLinearMap a z
              (pathMap P.toPresentation.relations q.1) = 0 from hq]
          exact Submodule.zero_mem _
        · apply Submodule.subset_span
          exact ⟨⟨q.1, hq⟩, rfl⟩
    | zero =>
        change P.rightArrowCompositionLinearMap a z 0 ∈ _
        rw [map_zero]
        exact Submodule.zero_mem _
    | add f g _ _ hf hg =>
        rw [map_add]
        exact Submodule.add_mem _ hf hg
    | smul r f _ hf =>
        rw [map_smul]
        exact Submodule.smul_mem _ r hf

/-- The pointwise arrow-generated subspace has its literal continuation-path
basis. -/
noncomputable def rightArrowCoordinateBasis
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Module.Basis (P.RightContinuationAt a z) k
      (LinearMap.range (P.rightArrowCompositionLinearMap a z)) := by
  let family : P.RightContinuationAt a z →
      LinearMap.range (P.rightArrowCompositionLinearMap a z) := fun q ↦
    ⟨P.rightArrowCompositionLinearMap a z
        (pathMap P.toPresentation.relations q.1),
      ⟨pathMap P.toPresentation.relations q.1, rfl⟩⟩
  have hli : LinearIndependent k family := by
    apply LinearIndependent.of_comp
      (LinearMap.range (P.rightArrowCompositionLinearMap a z)).subtype
    exact P.rightContinuationAt_linearIndependent a z
  apply Module.Basis.mk hli
  have hspan := (Submodule.span_range_subtype_eq_top_iff
    (LinearMap.range (P.rightArrowCompositionLinearMap a z))
    (fun q : P.RightContinuationAt a z ↦
      ⟨pathMap P.toPresentation.relations q.1, rfl⟩)).2
        (P.span_rightContinuationAt_eq_range a z)
  change ⊤ ≤ Submodule.span k (Set.range fun q : P.RightContinuationAt a z ↦
    (⟨P.rightArrowCompositionLinearMap a z
        (pathMap P.toPresentation.relations q.1),
      ⟨pathMap P.toPresentation.relations q.1, rfl⟩⟩ :
        LinearMap.range (P.rightArrowCompositionLinearMap a z)))
  exact hspan.ge

/-- The dimension of one coordinate of the arrow-generated ideal is the
number of surviving paths ending there which begin with the chosen arrow. -/
theorem finrank_rightArrowCompositionRange_eq_natCard
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Module.finrank k
        (LinearMap.range (P.rightArrowCompositionLinearMap a z)) =
      Nat.card (P.RightContinuationAt a z) := by
  letI : Finite (P.RightContinuationAt a z) :=
    P.rightContinuationAt_finite a z
  letI : Fintype (P.RightContinuationAt a z) := Fintype.ofFinite _
  simpa only [Fintype.card_eq_nat_card] using
    Module.finrank_eq_card_basis (P.rightArrowCoordinateBasis a z)

/-- Surviving continuations from a fixed vertex `z` to the source of `a`.
They index the `z`-coordinate of the categorical right ideal represented by
the displayed arrow. -/
abbrev LeftContinuationAt
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :=
  {p : Quiver.Path z x //
    arrowMap P.toPresentation.relations a ≫
        pathMap P.toPresentation.relations p ≠ 0}

/-- Precomposition by the image of `a`, in the reversed categorical
orientation of the bound-quiver category. -/
def leftArrowCompositionLinearMap
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    (obj P.toPresentation.relations x ⟶
        obj P.toPresentation.relations z) →ₗ[k]
      (obj P.toPresentation.relations y ⟶
        obj P.toPresentation.relations z) where
  toFun f := arrowMap P.toPresentation.relations a ≫ f
  map_add' f g := by simp only [Preadditive.comp_add]
  map_smul' r f := by
    simpa only [RingHom.id_apply] using
      (CategoryTheory.Linear.comp_smul _ _ _
        (arrowMap P.toPresentation.relations a) r f)

/-- A left continuation indexes its concatenated surviving path. -/
def leftContinuationAtToSurviving
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    P.LeftContinuationAt a z →
      SurvivingPath P.toPresentation.relations z y :=
  fun p ↦ ⟨p.1.comp a.toPath, by
    rw [← pathMap_comp]
    exact p.2⟩

/-- Concatenation with a fixed final arrow is injective. -/
theorem leftContinuationAtToSurviving_injective
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Function.Injective (P.leftContinuationAtToSurviving a z) := by
  intro p q hpq
  apply Subtype.ext
  apply Quiver.Path.comp_injective_left a.toPath
  exact congrArg Subtype.val hpq

/-- A fixed-startpoint left continuation is a continuation with varying
startpoint. -/
def leftContinuationAtToPath
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    P.LeftContinuationAt a z →
      P.toSpecialBiserialPresentation.LeftContinuationPath a :=
  fun p ↦ ⟨⟨z, p.1⟩, p.2⟩

/-- Forgetting a fixed startpoint is injective. -/
theorem leftContinuationAtToPath_injective
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Function.Injective (P.leftContinuationAtToPath a z) := by
  intro p q hpq
  apply Subtype.ext
  have hval := congrArg
    (fun t : P.toSpecialBiserialPresentation.LeftContinuationPath a ↦ t.1)
    hpq
  injection hval

/-- Fixed-startpoint left continuations form a finite type. -/
theorem leftContinuationAt_finite
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Finite (P.LeftContinuationAt a z) := by
  letI : Finite
      (P.toSpecialBiserialPresentation.LeftContinuationPath a) :=
    P.toSpecialBiserialPresentation.leftContinuationPath_finite a
  exact Finite.of_injective (P.leftContinuationAtToPath a z)
    (P.leftContinuationAtToPath_injective a z)

/-- Path length embeds the fixed-startpoint left continuation basis into the
natural numbers. -/
def leftContinuationAtLengthEmbedding
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    P.LeftContinuationAt a z ↪ ℕ :=
  (⟨P.leftContinuationAtToPath a z,
      P.leftContinuationAtToPath_injective a z⟩ :
    P.LeftContinuationAt a z ↪
      P.toSpecialBiserialPresentation.LeftContinuationPath a).trans
    (P.toSpecialBiserialPresentation.leftContinuationLengthEmbedding a)

/-- The concatenated path map is the corresponding left-composition image. -/
theorem leftContinuationAt_pathMap
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q)
    (p : P.LeftContinuationAt a z) :
    pathMap P.toPresentation.relations
        (P.leftContinuationAtToSurviving a z p).1 =
      P.leftArrowCompositionLinearMap a z
        (pathMap P.toPresentation.relations p.1) := by
  change
    pathMap P.toPresentation.relations (p.1.comp a.toPath) =
      arrowMap P.toPresentation.relations a ≫
        pathMap P.toPresentation.relations p.1
  simpa only [arrowMap] using
    (pathMap_comp P.toPresentation.relations p.1 a.toPath).symm

/-- Concatenated surviving left continuations of an arrow are linearly
independent. -/
theorem leftContinuationAt_linearIndependent
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    LinearIndependent k
      (fun p : P.LeftContinuationAt a z ↦
        P.leftArrowCompositionLinearMap a z
          (pathMap P.toPresentation.relations p.1)) := by
  have h :=
    (survivingPathMap_linearIndependent P.monomial z y).comp
      (P.leftContinuationAtToSurviving a z)
      (P.leftContinuationAtToSurviving_injective a z)
  have hfamily :
      ((fun p : SurvivingPath P.toPresentation.relations z y ↦
          pathMap P.toPresentation.relations p.1) ∘
          P.leftContinuationAtToSurviving a z) =
        (fun p : P.LeftContinuationAt a z ↦
          P.leftArrowCompositionLinearMap a z
            (pathMap P.toPresentation.relations p.1)) := by
    funext p
    exact P.leftContinuationAt_pathMap a z p
  rw [hfamily] at h
  exact h

/-- The surviving left continuations span the image of composition with
`a`. -/
theorem span_leftContinuationAt_eq_range
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Submodule.span k
        (Set.range fun p : P.LeftContinuationAt a z ↦
          P.leftArrowCompositionLinearMap a z
            (pathMap P.toPresentation.relations p.1)) =
      LinearMap.range (P.leftArrowCompositionLinearMap a z) := by
  apply le_antisymm
  · apply Submodule.span_le.2
    rintro f ⟨p, rfl⟩
    exact ⟨pathMap P.toPresentation.relations p.1, rfl⟩
  · rintro f ⟨g, rfl⟩
    have hg :=
      (survivingPathBasis P.toPresentation.relations P.monomial z x).mem_span g
    induction hg using Submodule.span_induction with
    | mem h hh =>
        rcases hh with ⟨p, rfl⟩
        rw [survivingPathBasis_apply]
        by_cases hp :
            arrowMap P.toPresentation.relations a ≫
                pathMap P.toPresentation.relations p.1 = 0
        · change
            P.leftArrowCompositionLinearMap a z
                (pathMap P.toPresentation.relations p.1) ∈ _
          rw [show P.leftArrowCompositionLinearMap a z
              (pathMap P.toPresentation.relations p.1) = 0 from hp]
          exact Submodule.zero_mem _
        · apply Submodule.subset_span
          exact ⟨⟨p.1, hp⟩, rfl⟩
    | zero =>
        change P.leftArrowCompositionLinearMap a z 0 ∈ _
        rw [map_zero]
        exact Submodule.zero_mem _
    | add f g _ _ hf hg =>
        rw [map_add]
        exact Submodule.add_mem _ hf hg
    | smul r f _ hf =>
        rw [map_smul]
        exact Submodule.smul_mem _ r hf

/-- The pointwise categorical arrow-generated subspace has its literal left
continuation-path basis. -/
noncomputable def leftArrowCoordinateBasis
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Module.Basis (P.LeftContinuationAt a z) k
      (LinearMap.range (P.leftArrowCompositionLinearMap a z)) := by
  let family : P.LeftContinuationAt a z →
      LinearMap.range (P.leftArrowCompositionLinearMap a z) := fun p ↦
    ⟨P.leftArrowCompositionLinearMap a z
        (pathMap P.toPresentation.relations p.1),
      ⟨pathMap P.toPresentation.relations p.1, rfl⟩⟩
  have hli : LinearIndependent k family := by
    apply LinearIndependent.of_comp
      (LinearMap.range (P.leftArrowCompositionLinearMap a z)).subtype
    exact P.leftContinuationAt_linearIndependent a z
  apply Module.Basis.mk hli
  have hspan := (Submodule.span_range_subtype_eq_top_iff
    (LinearMap.range (P.leftArrowCompositionLinearMap a z))
    (fun p : P.LeftContinuationAt a z ↦
      ⟨pathMap P.toPresentation.relations p.1, rfl⟩)).2
        (P.span_leftContinuationAt_eq_range a z)
  change ⊤ ≤ Submodule.span k (Set.range fun p : P.LeftContinuationAt a z ↦
    (⟨P.leftArrowCompositionLinearMap a z
        (pathMap P.toPresentation.relations p.1),
      ⟨pathMap P.toPresentation.relations p.1, rfl⟩⟩ :
        LinearMap.range (P.leftArrowCompositionLinearMap a z)))
  exact hspan.ge

@[simp]
theorem leftArrowCoordinateBasis_apply
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q)
    (p : P.LeftContinuationAt a z) :
    P.leftArrowCoordinateBasis a z p =
      ⟨P.leftArrowCompositionLinearMap a z
          (pathMap P.toPresentation.relations p.1),
        ⟨pathMap P.toPresentation.relations p.1, rfl⟩⟩ := by
  simp [leftArrowCoordinateBasis, Module.Basis.mk_apply]

/-- The dimension of one coordinate of the categorical right arrow ideal is
the number of surviving paths starting there which end with the chosen
arrow. -/
theorem finrank_leftArrowCompositionRange_eq_natCard
    (P : StringPresentation k A Q)
    {x y : Q} (a : x ⟶ y) (z : Q) :
    Module.finrank k
        (LinearMap.range (P.leftArrowCompositionLinearMap a z)) =
      Nat.card (P.LeftContinuationAt a z) := by
  letI : Finite (P.LeftContinuationAt a z) :=
    P.leftContinuationAt_finite a z
  letI : Fintype (P.LeftContinuationAt a z) := Fintype.ofFinite _
  simpa only [Fintype.card_eq_nat_card] using
    Module.finrank_eq_card_basis (P.leftArrowCoordinateBasis a z)

end StringPresentation

end MagnitudeConjecture.BoundQuiver
