import MagnitudeConjecture.Algebra.BoundQuiverPresentation
import Mathlib.LinearAlgebra.Basis.Basic

/-!
# String bound-quiver presentations

This file records the string-algebra convention used in the frozen
manuscript.  A relation ideal is monomial when, in every Hom space of the
free linear path category, it is spanned by the individual paths killed by
the quotient.  Thus the nonzero images of paths form a basis of the quotient
Hom space, and products of basis vectors are either zero or another basis
vector.

A string presentation is a special-biserial presentation with this monomial
condition.  The bundled existence predicate retains the literal displayed
quiver, while the transport lemmas show that only the presented algebra up
to algebra equivalence matters.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open QuotientSubmoduleEquidistribution.CategoricalIdeal

namespace MagnitudeConjecture.BoundQuiver

universe u

variable {k Q : Type u} [Field k] [Fintype Q] [Quiver.{u} Q]
variable [∀ x y : Q, Fintype (x ⟶ y)]

/-- A path whose image in the relation quotient is nonzero. -/
abbrev SurvivingPath (R : RelationFamily k Q) (x y : Q) :=
  {p : Quiver.Path x y // pathMap R p ≠ 0}

/-- A relation ideal is monomial when each of its Hom subspaces is the span
of the individual paths killed by the quotient.  This is the directly usable
linear-category form of saying that the ideal is generated by paths. -/
def IsMonomial (R : RelationFamily k Q) : Prop :=
  ∀ x y : Q,
    HomIdeal.generatedHomSubmodule k R
        (LinearPathCategory.obj k Q y)
        (LinearPathCategory.obj k Q x) =
      Submodule.span k
        ((fun p : Quiver.Path x y ↦ LinearPathCategory.pathHom p) ''
          {p : Quiver.Path x y | pathMap R p = 0})

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- A path dies in the quotient exactly when its linearized path belongs to
the generated relation ideal. -/
theorem pathMap_eq_zero_iff_mem_relationIdeal
    (R : RelationFamily k Q) {x y : Q} (p : Quiver.Path x y) :
    pathMap R p = 0 ↔
      LinearPathCategory.pathHom p ∈
        HomIdeal.generatedHomSubmodule k R
          (LinearPathCategory.obj k Q y)
          (LinearPathCategory.obj k Q x) := by
  change
    (LinearPathCategory.HomogeneousQuotient.quotientFunctor R).map
        (LinearPathCategory.pathHom p) = 0 ↔ _
  exact
    (LinearPathCategory.HomogeneousQuotient.relationIdeal R).map_eq_zero_iff _

/-- Admissibility bounds the lengths of all surviving paths, so the path
basis of every quotient Hom space is finite. -/
theorem survivingPathFiniteOfAdmissible
    (R : RelationFamily k Q) (hR : IsAdmissible R) (x y : Q) :
    Finite (SurvivingPath R x y) := by
  obtain ⟨N, _, hlong⟩ := hR.long_paths_mem
  let toBounded : SurvivingPath R x y →
      Quiver.Path.BoundedPaths x y (N - 1) := fun p ↦
    ⟨p.1, Nat.le_sub_one_of_lt (by
      apply Nat.lt_of_not_ge
      intro hp
      exact p.2 ((pathMap_eq_zero_iff_mem_relationIdeal R p.1).2
        (hlong p.1 hp)))⟩
  exact @Finite.of_injective _ _ (boundedPathsFinite (N - 1) x y)
    toBounded (by
      intro p q hpq
      apply Subtype.ext
      exact congrArg
        (fun r : Quiver.Path.BoundedPaths x y (N - 1) ↦ r.1) hpq)

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- In a monomial quotient, distinct surviving paths have linearly independent
images. -/
theorem survivingPathMap_linearIndependent
    {R : RelationFamily k Q} (hR : IsMonomial R) (x y : Q) :
    LinearIndependent k
      (fun p : SurvivingPath R x y ↦ pathMap R p.1) := by
  let v : Quiver.Path x y →
      (LinearPathCategory.obj k Q y ⟶ LinearPathCategory.obj k Q x) :=
    fun p ↦ LinearPathCategory.pathHom p
  let s : Set (Quiver.Path x y) := {p | pathMap R p ≠ 0}
  let t : Set (Quiver.Path x y) := {p | pathMap R p = 0}
  let q := LinearPathCategory.HomogeneousQuotient.quotientHomLinearMap R
    (LinearPathCategory.obj k Q y) (LinearPathCategory.obj k Q x)
  have hv : LinearIndependent k v := by
    exact (LinearPathCategory.homPathBasis
      (LinearPathCategory.obj k Q y)
      (LinearPathCategory.obj k Q x)).linearIndependent
  have hst : Disjoint s t := by
    rw [Set.disjoint_left]
    intro p hps hpt
    exact hps hpt
  have hspan : Submodule.span k (Set.range
      (fun p : SurvivingPath R x y ↦ v p.1)) =
      Submodule.span k (v '' s) := by
    congr 1
    ext f
    constructor
    · rintro ⟨p, rfl⟩
      exact ⟨p.1, p.2, rfl⟩
    · rintro ⟨p, hp, rfl⟩
      exact ⟨⟨p, hp⟩, rfl⟩
  have hker : LinearMap.ker q = Submodule.span k (v '' t) := by
    rw [LinearPathCategory.HomogeneousQuotient.ker_quotientHomLinearMap,
      hR x y]
    rfl
  have hdisjoint : Disjoint
      (Submodule.span k (Set.range
        (fun p : SurvivingPath R x y ↦ v p.1)))
      (LinearMap.ker q) := by
    rw [hspan, hker]
    exact hv.disjoint_span_image hst
  change LinearIndependent k
    (q ∘ fun p : SurvivingPath R x y ↦ v p.1)
  exact (hv.comp (fun p : SurvivingPath R x y ↦ p.1)
      Subtype.val_injective).map hdisjoint

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- The nonzero path images span the corresponding Hom space in every
bound-quiver quotient. -/
theorem span_survivingPathMap_eq_top
    (R : RelationFamily k Q) (x y : Q) :
    Submodule.span k
      (Set.range fun p : SurvivingPath R x y ↦ pathMap R p.1) = ⊤ := by
  apply top_unique
  intro f hf
  clear hf
  obtain ⟨g, rfl⟩ :=
    LinearPathCategory.HomogeneousQuotient.quotientHom_surjective R
      (LinearPathCategory.obj k Q y)
      (LinearPathCategory.obj k Q x) f
  have hg :=
    (LinearPathCategory.homPathBasis
      (LinearPathCategory.obj k Q y)
      (LinearPathCategory.obj k Q x)).mem_span g
  induction hg using Submodule.span_induction with
  | mem g hg =>
      rcases hg with ⟨p, rfl⟩
      rw [LinearPathCategory.homPathBasis_apply]
      by_cases hp : pathMap R p ≠ 0
      · apply Submodule.subset_span
        exact ⟨⟨p, hp⟩, rfl⟩
      · simp only [ne_eq, not_not] at hp
        change pathMap R p ∈ _
        rw [hp]
        exact Submodule.zero_mem _
  | zero => simp
  | add g h _ _ hg hh =>
      simpa using Submodule.add_mem _ hg hh
  | smul c g _ hg =>
      simpa using Submodule.smul_mem _ c hg

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- The surviving paths form the canonical path basis of each Hom space in a
monomial bound-quiver quotient. -/
noncomputable def survivingPathBasis
    (R : RelationFamily k Q) (hR : IsMonomial R) (x y : Q) :
    Module.Basis (SurvivingPath R x y) k (obj R y ⟶ obj R x) :=
  Module.Basis.mk (survivingPathMap_linearIndependent hR x y)
    (span_survivingPathMap_eq_top R x y).ge

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
@[simp]
theorem survivingPathBasis_apply
    (R : RelationFamily k Q) (hR : IsMonomial R) (x y : Q)
    (p : SurvivingPath R x y) :
    survivingPathBasis R hR x y p = pathMap R p.1 := by
  exact Module.Basis.mk_apply _ _ _

/-- In an admissible monomial quotient, the Hom-space dimension counts the
surviving paths with the specified endpoints. -/
theorem finrank_quotientHom_eq_natCard_survivingPath
    (R : RelationFamily k Q) (hadm : IsAdmissible R)
    (hmono : IsMonomial R) (x y : Q) :
    Module.finrank k (obj R y ⟶ obj R x) =
      Nat.card (SurvivingPath R x y) := by
  letI : Finite (SurvivingPath R x y) :=
    survivingPathFiniteOfAdmissible R hadm x y
  letI : Fintype (SurvivingPath R x y) := Fintype.ofFinite _
  simpa only [Fintype.card_eq_nat_card] using
    Module.finrank_eq_card_basis (survivingPathBasis R hmono x y)

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- Products of surviving-path basis vectors are either zero or another
surviving-path basis vector. -/
theorem survivingPathMap_comp_eq_zero_or_eq
    (R : RelationFamily k Q) {x y z : Q}
    (p : SurvivingPath R x y) (q : SurvivingPath R y z) :
    pathMap R q.1 ≫ pathMap R p.1 = 0 ∨
      ∃ r : SurvivingPath R x z,
        pathMap R q.1 ≫ pathMap R p.1 = pathMap R r.1 := by
  rw [pathMap_comp]
  by_cases h : pathMap R (p.1.comp q.1) = 0
  · exact Or.inl h
  · exact Or.inr ⟨⟨p.1.comp q.1, h⟩, rfl⟩

variable {A B : Type u} [Ring A] [Algebra k A]
variable [Ring B] [Algebra k B]

/-- A string presentation is a special-biserial presentation whose relation
ideal is monomial. -/
structure StringPresentation (k A Q : Type u)
    [Field k] [Ring A] [Algebra k A]
    [Fintype Q] [Quiver.{u} Q] [∀ x y : Q, Fintype (x ⟶ y)]
    extends SpecialBiserialPresentation k A Q where
  monomial : IsMonomial toPresentation.relations

namespace StringPresentation

/-- Transport a string presentation across an algebra equivalence. -/
def mapAlgEquiv
    {Q' : Type u} [Fintype Q'] [Quiver.{u} Q']
    [∀ x y : Q', Fintype (x ⟶ y)]
    (P : StringPresentation k A Q') (e : B ≃ₐ[k] A) :
    StringPresentation k B Q' where
  toSpecialBiserialPresentation :=
    P.toSpecialBiserialPresentation.mapAlgEquiv e
  monomial := P.monomial

end StringPresentation

/-- A universe-local finite quiver carrying a string presentation of the
given algebra. -/
structure StringModel (k A : Type u)
    [Field k] [Ring A] [Algebra k A] where
  Vertex : Type u
  vertexFintype : Fintype Vertex
  quiver : Quiver.{u} Vertex
  arrowFintype :
    letI : Quiver.{u} Vertex := quiver
    ∀ x y : Vertex, Fintype (x ⟶ y)
  presentation :
    letI : Fintype Vertex := vertexFintype
    letI : Quiver.{u} Vertex := quiver
    letI (x y : Vertex) : Fintype (x ⟶ y) := arrowFintype x y
    StringPresentation k A Vertex

/-- The algebra admits a literal string bound-quiver presentation. -/
def AdmitsStringPresentation (k A : Type u)
    [Field k] [Ring A] [Algebra k A] : Prop :=
  Nonempty (StringModel k A)

namespace StringModel

/-- Forget the monomial condition from a bundled string model. -/
def toSpecialBiserialModel (M : StringModel k A) :
    SpecialBiserialModel k A where
  Vertex := M.Vertex
  vertexFintype := M.vertexFintype
  quiver := M.quiver
  arrowFintype := M.arrowFintype
  presentation := by
    letI : Fintype M.Vertex := M.vertexFintype
    letI : Quiver.{u} M.Vertex := M.quiver
    letI (x y : M.Vertex) : Fintype (x ⟶ y) := M.arrowFintype x y
    exact M.presentation.toSpecialBiserialPresentation

/-- Transport a bundled string model across an algebra equivalence. -/
def mapAlgEquiv (M : StringModel k A) (e : B ≃ₐ[k] A) :
    StringModel k B where
  Vertex := M.Vertex
  vertexFintype := M.vertexFintype
  quiver := M.quiver
  arrowFintype := M.arrowFintype
  presentation := by
    letI : Fintype M.Vertex := M.vertexFintype
    letI : Quiver.{u} M.Vertex := M.quiver
    letI (x y : M.Vertex) : Fintype (x ⟶ y) := M.arrowFintype x y
    exact M.presentation.mapAlgEquiv e

end StringModel

/-- Every string presentation is, after forgetting monomiality, a
special-biserial presentation. -/
theorem admitsSpecialBiserialPresentation_of_admitsStringPresentation
    (h : AdmitsStringPresentation k A) :
    AdmitsSpecialBiserialPresentation k A := by
  obtain ⟨M⟩ := h
  exact ⟨M.toSpecialBiserialModel⟩

/-- Admitting a string presentation is invariant under algebra
equivalence. -/
theorem admitsStringPresentation_iff_of_algEquiv (e : A ≃ₐ[k] B) :
    AdmitsStringPresentation k A ↔ AdmitsStringPresentation k B := by
  constructor
  · rintro ⟨M⟩
    exact ⟨M.mapAlgEquiv e.symm⟩
  · rintro ⟨M⟩
    exact ⟨M.mapAlgEquiv e⟩

end MagnitudeConjecture.BoundQuiver
