import MagnitudeConjecture.Algebra.StringDetectorEvaluation
import MagnitudeConjecture.Algebra.StringDetectorFiniteIndex

/-!
# Finite-string detector reconstruction map

When the inversion-class index of finite strings is finite, the coherent
evaluations assemble into one map from the biproduct of all detector-generated
string summands.  Applying any matching detector to this total map is an
isomorphism.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits

attribute [local instance] HasFiniteBiproducts.of_hasFiniteProducts

namespace MagnitudeConjecture.BoundQuiver.StringWord.DetectorIndex

universe u

variable {k A Q : Type u} [Field k] [Ring A] [Algebra k A]
variable [Fintype Q] [Quiver.{u} Q]
variable [∀ x y : Q, Fintype (x ⟶ y)]
variable {P : BoundQuiver.StringPresentation k A Q}
variable {S : P.toSpecialBiserialPresentation.ArrowPolarization}

local instance : DecidableEq (DetectorIndex S) := Classical.decEq _

variable [Fintype (DetectorIndex S)]

/-- The string summand generated by the `i`th detector of `N`. -/
def reconstructionSummand
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k)
    (i : DetectorIndex S) :
    MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k :=
  i.finiteStringEmbeddingFunctor.obj (i.finiteDetectorFunctor.obj N)

/-- The finite biproduct of all detector-generated string summands. -/
def reconstructionSource
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k) :
    MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k :=
  ⨁ fun i : DetectorIndex S ↦ reconstructionSummand (S := S) N i

/-- The total coherent evaluation from all detector-generated string
summands to `N`. -/
def reconstructionEvaluation
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k) :
    reconstructionSource (S := S) N ⟶ N :=
  biproduct.desc fun i ↦ i.coherentFiniteDetectorEvaluation N

@[simp]
theorem reconstruction_inclusion_comp_evaluation
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k)
    (i : DetectorIndex S) :
    biproduct.ι (reconstructionSummand (S := S) N) i ≫
        reconstructionEvaluation (S := S) N =
      i.coherentFiniteDetectorEvaluation N := by
  exact biproduct.ι_desc _ _

/-- Every matching detector of the total reconstruction map is surjective:
its matching summand already maps onto the target detector. -/
theorem finiteDetectorFunctor_map_reconstructionEvaluation_surjective
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k)
    (j : DetectorIndex S) :
    Function.Surjective
      (j.finiteDetectorFunctor.map
        (reconstructionEvaluation (S := S) N)).hom.hom := by
  let inclusion := biproduct.ι (reconstructionSummand (S := S) N) j
  let matching := j.coherentFiniteDetectorEvaluation N
  have hmatching : inclusion ≫ reconstructionEvaluation (S := S) N = matching :=
    reconstruction_inclusion_comp_evaluation (S := S) N j
  have hsurjective : Function.Surjective
      (j.finiteDetectorFunctor.map matching).hom.hom :=
    j.endpointWord.finiteDetectorFunctor_map_coherentFiniteDetectorEvaluation_surjective N
  intro q
  obtain ⟨x, hx⟩ := hsurjective q
  refine ⟨(j.finiteDetectorFunctor.map inclusion).hom.hom x, ?_⟩
  have hmap := j.finiteDetectorFunctor.congr_map hmatching
  have happly := congrArg (fun f ↦ f.hom.hom x) hmap
  calc
    _ = ((j.finiteDetectorFunctor.map inclusion ≫
          j.finiteDetectorFunctor.map
            (reconstructionEvaluation (S := S) N)).hom.hom x) := rfl
    _ = (j.finiteDetectorFunctor.map
          (inclusion ≫ reconstructionEvaluation (S := S) N)).hom.hom x := by
      rw [Functor.map_comp]
    _ = (j.finiteDetectorFunctor.map matching).hom.hom x := by
      exact happly
    _ = q := hx

/-- Applying a finite detector to the reconstruction source commutes with its
finite biproduct decomposition. -/
def finiteDetectorFunctorReconstructionSourceIso
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k)
    (j : DetectorIndex S) :
    j.finiteDetectorFunctor.obj (reconstructionSource (S := S) N) ≅
      ⨁ fun i : DetectorIndex S ↦
        (finiteDetectorEmbeddingFunctor j i).obj
          (i.finiteDetectorFunctor.obj N) :=
  by
    letI : PreservesBiproduct (reconstructionSummand (S := S) N)
        j.finiteDetectorFunctor :=
      preservesBiproduct_of_preservesProduct j.finiteDetectorFunctor
    exact j.finiteDetectorFunctor.mapBiproduct
      (reconstructionSummand (S := S) N)

/-- Orthogonality makes the detector of the total reconstruction source have
the same dimension as the corresponding detector of `N`. -/
theorem finrank_finiteDetectorFunctor_reconstructionSource
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k)
    (j : DetectorIndex S) :
    Module.finrank k
        ((j.finiteDetectorFunctor.obj
          (reconstructionSource (S := S) N) : FGModuleCat.{u} k) : Type u) =
      Module.finrank k
        ((j.finiteDetectorFunctor.obj N : FGModuleCat.{u} k) : Type u) := by
  let V := fun i : DetectorIndex S ↦
    (finiteDetectorEmbeddingFunctor j i).obj
      (i.finiteDetectorFunctor.obj N)
  calc
    Module.finrank k
        ((j.finiteDetectorFunctor.obj
          (reconstructionSource (S := S) N) : FGModuleCat.{u} k) : Type u) =
        Module.finrank k ((⨁ V : FGModuleCat.{u} k) : Type u) :=
      (FGModuleCat.isoToLinearEquiv
        (finiteDetectorFunctorReconstructionSourceIso (S := S) N j)).finrank_eq
    _ = ∑ i : DetectorIndex S, Module.finrank k (V i) :=
      MagnitudeConjecture.FiniteVectorSpace.finrank_biproduct_sameUniverse V
    _ = ∑ i : DetectorIndex S,
        if j = i then
          Module.finrank k
            ((i.finiteDetectorFunctor.obj N : FGModuleCat.{u} k) : Type u)
        else 0 := by
      apply Finset.sum_congr rfl
      intro i _
      exact finrank_finiteDetectorEmbeddingFunctor j i
        (i.finiteDetectorFunctor.obj N)
    _ = Module.finrank k
        ((j.finiteDetectorFunctor.obj N : FGModuleCat.{u} k) : Type u) := by
      simp

/-- Every finite-string detector sees the total reconstruction evaluation as
an isomorphism. -/
theorem isIso_finiteDetectorFunctor_map_reconstructionEvaluation
    (N : MagnitudeConjecture.CoveringHom.FiniteDimensionalModuleCategory
      (C := (Category P.toPresentation.relations)ᵒᵖ) k)
    (j : DetectorIndex S) :
    IsIso (j.finiteDetectorFunctor.map
      (reconstructionEvaluation (S := S) N)) := by
  let f := j.finiteDetectorFunctor.map
    (reconstructionEvaluation (S := S) N)
  have hsurjective : Function.Surjective f.hom.hom :=
    finiteDetectorFunctor_map_reconstructionEvaluation_surjective
      (S := S) N j
  have hfinrank := finrank_finiteDetectorFunctor_reconstructionSource
    (S := S) N j
  have hbijective : Function.Bijective f.hom.hom := ⟨
      (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hfinrank).2
        hsurjective,
      hsurjective⟩
  let e := (LinearEquiv.ofBijective f.hom.hom hbijective).toFGModuleCatIso
  have heq : e.hom = f := by
    apply ObjectProperty.hom_ext
    apply ModuleCat.hom_ext
    rfl
  change IsIso f
  rw [← heq]
  infer_instance

end MagnitudeConjecture.BoundQuiver.StringWord.DetectorIndex
