import MagnitudeConjecture.Algebra.StringArrowIdeal
import MagnitudeConjecture.Algebra.RightModulePrimitiveIdempotent
import MagnitudeConjecture.CategoryTheory.FiniteCategoryProjectiveGenerator

/-!
# Literal category-algebra ideals generated by string arrows

The quotient path category is used in reversed orientation by the finite
category-algebra construction.  Consequently, a displayed quiver arrow
induces a map between covariant representables whose pointwise images are
indexed by the left continuations of that arrow.  This file packages that
map, its matrix coordinate in the finite category algebra, and the literal
principal right ideal generated by that coordinate.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits

namespace MagnitudeConjecture.BoundQuiver

universe u

variable {k A Q : Type u} [Field k] [Ring A] [Algebra k A]
variable [Fintype Q] [Quiver.{u} Q]
variable [∀ x y : Q, Fintype (x ⟶ y)]

namespace StringPresentation

/-- The finite category algebra attached to the quotient path category of a
string presentation. -/
abbrev quotientCategoryAlgebra (P : StringPresentation k A Q) :=
  CoveringHom.finiteCategoryProjectiveGenerator.algebra
    (finiteRepresentablesOfAdmissible P.toPresentation.admissible)

abbrev quotientRepresentable
    (P : StringPresentation k A Q)
    (X : Category P.toPresentation.relations) :=
  (CoveringHom.finiteDimensionalLinearCoyonedaFunctor
      (finiteRepresentablesOfAdmissible P.toPresentation.admissible)).obj
    (Opposite.op X)

abbrev representedVertexModule
    (P : StringPresentation k A Q) (x : Q) :=
  (CoveringHom.finiteCategoryProjectiveGenerator.representedFGFunctor
    (finiteRepresentablesOfAdmissible P.toPresentation.admissible)).obj
      (P.quotientRepresentable (obj P.toPresentation.relations x))

/-- The projector onto the representable belonging to a displayed vertex. -/
def vertexProjector (P : StringPresentation k A Q) (x : Q) :
    P.quotientCategoryAlgebra :=
  biproduct.π (P.quotientRepresentable) (obj P.toPresentation.relations x) ≫
    biproduct.ι (P.quotientRepresentable) (obj P.toPresentation.relations x)

/-- The map of covariant representables induced contravariantly by a
displayed arrow of the quotient path category. -/
def arrowRepresentableMap
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.quotientRepresentable (obj P.toPresentation.relations x) ⟶
      P.quotientRepresentable (obj P.toPresentation.relations y) :=
  (CoveringHom.finiteDimensionalLinearCoyonedaFunctor
      (finiteRepresentablesOfAdmissible P.toPresentation.admissible)).map
    (arrowMap P.toPresentation.relations a).op

/-- At a vertex `z`, the representable map belonging to `a` is precisely
left composition by the categorical image of `a`. -/
theorem arrowRepresentableMap_app_hom
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) (z : Q) :
    ((P.arrowRepresentableMap a).hom.hom.app
      (obj P.toPresentation.relations z)).hom =
      P.leftArrowCompositionLinearMap a z := by
  rfl

/-- The pointwise range of the assembled representable map has the literal
left-continuation path basis. -/
noncomputable def arrowRepresentableCoordinateBasis
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) (z : Q) :
    Module.Basis (P.LeftContinuationAt a z) k
      (LinearMap.range
        ((P.arrowRepresentableMap a).hom.hom.app
          (obj P.toPresentation.relations z)).hom) := by
  rw [P.arrowRepresentableMap_app_hom a z]
  exact P.leftArrowCoordinateBasis a z

/-- The pointwise dimension of the assembled representable arrow image is
the number of surviving left continuations at that vertex. -/
theorem finrank_arrowRepresentableMap_range_eq_natCard
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) (z : Q) :
    Module.finrank k
        (LinearMap.range
          ((P.arrowRepresentableMap a).hom.hom.app
            (obj P.toPresentation.relations z)).hom) =
      Nat.card (P.LeftContinuationAt a z) := by
  rw [P.arrowRepresentableMap_app_hom a z]
  exact P.finrank_leftArrowCompositionRange_eq_natCard a z

/-- The matrix coordinate of a displayed arrow in the finite category
algebra. -/
def arrowAlgebraCoordinate
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.quotientCategoryAlgebra :=
  biproduct.π (P.quotientRepresentable)
      (obj P.toPresentation.relations x) ≫
    P.arrowRepresentableMap a ≫
    biproduct.ι (P.quotientRepresentable)
      (obj P.toPresentation.relations y)

/-- The arrow coordinate is fixed on the right by its source projector. -/
theorem arrowAlgebraCoordinate_mul_sourceProjector
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.arrowAlgebraCoordinate a * P.vertexProjector x =
      P.arrowAlgebraCoordinate a := by
  rw [End.mul_def]
  simp [arrowAlgebraCoordinate, vertexProjector, Category.assoc]

/-- The arrow coordinate is fixed on the left by its target projector. -/
theorem targetProjector_mul_arrowAlgebraCoordinate
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    P.vertexProjector y * P.arrowAlgebraCoordinate a =
      P.arrowAlgebraCoordinate a := by
  rw [End.mul_def]
  simp [arrowAlgebraCoordinate, vertexProjector, Category.assoc]

/-- Left multiplication by the arrow coordinate, restricted from the source
vertex projective to the target vertex projective. -/
def arrowProjectiveLinearMap
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    RightModule.rightIdeal (P.vertexProjector x) →ₗ[
        P.quotientCategoryAlgebraᵐᵒᵖ]
      RightModule.rightIdeal (P.vertexProjector y) where
  toFun z :=
    ⟨P.arrowAlgebraCoordinate a * z.1,
      ⟨P.arrowAlgebraCoordinate a * z.1, by
        change
          P.vertexProjector y * (P.arrowAlgebraCoordinate a * z.1) =
            P.arrowAlgebraCoordinate a * z.1
        rw [← mul_assoc, P.targetProjector_mul_arrowAlgebraCoordinate a]⟩⟩
  map_add' z w := by
    apply Subtype.ext
    exact mul_add _ _ _
  map_smul' r z := by
    apply Subtype.ext
    exact (mul_assoc _ _ r.unop).symm

@[simp]
theorem arrowProjectiveLinearMap_apply_val
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y)
    (z : RightModule.rightIdeal (P.vertexProjector x)) :
    (P.arrowProjectiveLinearMap a z).1 =
      P.arrowAlgebraCoordinate a * z.1 :=
  rfl

set_option maxHeartbeats 800000 in
/-- A vertex-projector right ideal is the right module represented by the
matching covariant representable. -/
def vertexRightIdealRepresentedLinearEquiv
    (P : StringPresentation k A Q) (x : Q) :
    RightModule.rightIdeal (P.vertexProjector x) ≃ₗ[
        P.quotientCategoryAlgebraᵐᵒᵖ]
      P.representedVertexModule x where
  toFun q := q.1 ≫
    biproduct.π (P.quotientRepresentable)
      (obj P.toPresentation.relations x)
  invFun f :=
    ⟨f ≫ biproduct.ι (P.quotientRepresentable)
        (obj P.toPresentation.relations x),
      ⟨f ≫ biproduct.ι (P.quotientRepresentable)
          (obj P.toPresentation.relations x), by
        change
          (f ≫ biproduct.ι (P.quotientRepresentable)
              (obj P.toPresentation.relations x)) ≫
              P.vertexProjector x =
            f ≫ biproduct.ι (P.quotientRepresentable)
              (obj P.toPresentation.relations x)
        simp [vertexProjector, Category.assoc]⟩⟩
  map_add' q r := by
    change
      (q.1 + r.1) ≫ biproduct.π (P.quotientRepresentable)
          (obj P.toPresentation.relations x) = _
    exact Preadditive.add_comp _ _ _ q.1 r.1 _
  map_smul' b q := by
    change
      b.unop ≫ q.1 ≫ biproduct.π (P.quotientRepresentable)
          (obj P.toPresentation.relations x) =
        b.unop ≫ (q.1 ≫ biproduct.π (P.quotientRepresentable)
          (obj P.toPresentation.relations x))
    rfl
  left_inv q := by
    apply Subtype.ext
    change (q.1 : P.quotientCategoryAlgebra) ≫ P.vertexProjector x = q.1
    obtain ⟨r, hr⟩ := q.2
    change P.vertexProjector x * r = q.1 at hr
    rw [← hr]
    change (r ≫ P.vertexProjector x) ≫ P.vertexProjector x =
      r ≫ P.vertexProjector x
    simp [vertexProjector, Category.assoc]
  right_inv f := by
    change
      f ≫ biproduct.ι (P.quotientRepresentable)
          (obj P.toPresentation.relations x) ≫
        biproduct.π (P.quotientRepresentable)
          (obj P.toPresentation.relations x) = f
    simp

/-- The represented linear map induced by the arrow transformation. -/
def representedArrowLinearMap
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :=
  ((CoveringHom.finiteCategoryProjectiveGenerator.representedFGFunctor
      (finiteRepresentablesOfAdmissible P.toPresentation.admissible)).map
        (P.arrowRepresentableMap a)).hom.hom

/-- The projective map defined by multiplying with the arrow matrix is the
represented map of the arrow transformation, after the canonical vertex
identifications. -/
theorem vertexRightIdealRepresentedLinearEquiv_arrowProjective
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    (P.vertexRightIdealRepresentedLinearEquiv y).toLinearMap.comp
        (P.arrowProjectiveLinearMap a) =
      (P.representedArrowLinearMap a).comp
        (P.vertexRightIdealRepresentedLinearEquiv x).toLinearMap := by
  apply LinearMap.ext
  intro z
  change
    (P.arrowAlgebraCoordinate a * z.1) ≫
        biproduct.π (P.quotientRepresentable)
          (obj P.toPresentation.relations y) =
      (z.1 ≫ biproduct.π (P.quotientRepresentable)
        (obj P.toPresentation.relations x)) ≫
          P.arrowRepresentableMap a
  change
    (z.1 ≫ P.arrowAlgebraCoordinate a) ≫
        biproduct.π (P.quotientRepresentable)
          (obj P.toPresentation.relations y) = _
  simp [arrowAlgebraCoordinate, Category.assoc]

/-- The range of the projective arrow map is the represented range of the
assembled arrow transformation. -/
def arrowProjectiveRangeRepresentedRangeLinearEquiv
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    LinearMap.range (P.arrowProjectiveLinearMap a) ≃ₗ[
        P.quotientCategoryAlgebraᵐᵒᵖ]
      LinearMap.range (P.representedArrowLinearMap a) := by
  let ex := P.vertexRightIdealRepresentedLinearEquiv x
  let ey := P.vertexRightIdealRepresentedLinearEquiv y
  have hrange :
      (LinearMap.range (P.arrowProjectiveLinearMap a)).map ey.toLinearMap =
        LinearMap.range (P.representedArrowLinearMap a) := by
    rw [← LinearMap.range_comp,
      P.vertexRightIdealRepresentedLinearEquiv_arrowProjective a]
    exact ex.range_comp (P.representedArrowLinearMap a)
  exact ey.ofSubmodules _ _ hrange

/-- The range of the projective map induced by an arrow is the literal
principal right ideal generated by its category-algebra coordinate. -/
def arrowProjectiveRangeRightIdealLinearEquiv
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    LinearMap.range (P.arrowProjectiveLinearMap a) ≃ₗ[
        P.quotientCategoryAlgebraᵐᵒᵖ]
      RightModule.rightIdeal (P.arrowAlgebraCoordinate a) := by
  let c := P.arrowAlgebraCoordinate a
  let e := P.vertexProjector x
  let t := P.arrowProjectiveLinearMap a
  let toFun : LinearMap.range t → RightModule.rightIdeal c := fun z ↦
    ⟨z.1.1, by
      rcases z.2 with ⟨w, hw⟩
      refine ⟨w.1, ?_⟩
      change c * w.1 = z.1.1
      rw [← P.arrowProjectiveLinearMap_apply_val a w]
      exact congrArg Subtype.val hw⟩
  let witness (z : RightModule.rightIdeal c) : P.quotientCategoryAlgebra :=
    Classical.choose z.2
  have witness_spec (z : RightModule.rightIdeal c) :
      c * witness z = z.1 :=
    Classical.choose_spec z.2
  let source (z : RightModule.rightIdeal c) : RightModule.rightIdeal e :=
    ⟨e * witness z, ⟨witness z, rfl⟩⟩
  let invFun : RightModule.rightIdeal c → LinearMap.range t := fun z ↦
    ⟨t (source z), ⟨source z, rfl⟩⟩
  refine
    { toFun := toFun
      invFun := invFun
      left_inv := ?_
      right_inv := ?_
      map_add' := ?_
      map_smul' := ?_ }
  · intro z w
    apply Subtype.ext
    rfl
  · intro r z
    apply Subtype.ext
    rfl
  · intro z
    apply Subtype.ext
    apply Subtype.ext
    change c * (e * witness (toFun z)) = z.1.1
    rw [← mul_assoc, P.arrowAlgebraCoordinate_mul_sourceProjector a,
      witness_spec]
  · intro z
    apply Subtype.ext
    change c * (e * witness z) = z.1
    rw [← mul_assoc, P.arrowAlgebraCoordinate_mul_sourceProjector a,
      witness_spec]

/-- The literal principal right ideal generated by a displayed arrow is
linearly equivalent to the represented range of the assembled arrow
transformation. -/
def arrowRightIdealRepresentedRangeLinearEquiv
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    RightModule.rightIdeal (P.arrowAlgebraCoordinate a) ≃ₗ[
        P.quotientCategoryAlgebraᵐᵒᵖ]
      LinearMap.range (P.representedArrowLinearMap a) :=
  (P.arrowProjectiveRangeRightIdealLinearEquiv a).symm.trans
    (P.arrowProjectiveRangeRepresentedRangeLinearEquiv a)

end StringPresentation

end MagnitudeConjecture.BoundQuiver
