import MagnitudeConjecture.Algebra.StringArrowCokernelBranchSurjective

/-! # Identifying the surviving branch family with the cokernel radical -/

set_option autoImplicit false
noncomputable section

namespace MagnitudeConjecture.BoundQuiver.StringPresentation

universe u

variable {k A Q : Type u} [Field k] [Ring A] [Algebra k A]
variable [Fintype Q] [Quiver.{u} Q]
variable [∀ x y : Q, Fintype (x ⟶ y)]

/-- The radical of `V(a)` is linearly equivalent to the family of all
incoming-arrow ranges other than the range generated by `a`. -/
def otherIncomingFamilyCokernelRadicalLinearEquiv
    (P : StringPresentation k A Q) {x y : Q} (a : x ⟶ y) :
    (∀ b : OtherIncomingArrow (Sigma.mk x a),
        LinearMap.range (P.representedArrowLinearMap b.1.2)) ≃ₗ[
      P.quotientCategoryAlgebraᵐᵒᵖ]
    Module.jacobson P.quotientCategoryAlgebraᵐᵒᵖ
      (P.arrowCokernelFGObj a) :=
  LinearEquiv.ofBijective
    (P.otherIncomingFamilyToCokernelRadical a)
    ⟨P.otherIncomingFamilyToCokernelRadical_injective a,
      P.otherIncomingFamilyToCokernelRadical_surjective a⟩

end MagnitudeConjecture.BoundQuiver.StringPresentation
