#!/usr/bin/env python3
"""Generate the standalone Challenge from the maintained Mathlib-only vocabulary."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
THEOREM = """
universe u
/-- Magnitude is bounded below by the number of simple right-module classes,
with equality exactly for special biserial algebras. -/
theorem MagnitudeConjecture.magnitudeTheorem
    (k A : Type u) [Field k] [IsAlgClosed k] [Ring A] [Algebra k A]
    [FiniteDimensional k A] : MagnitudeConjecture.Statement.MainClaim k A := by
  sorry
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if Challenge.lean is stale")
    args = parser.parse_args()
    source = (ROOT / "MagnitudeConjecture/Statement.lean").read_text()
    imports = [line.split()[1] for line in source.splitlines() if line.startswith("import ")]
    if not imports or any(not name.startswith("Mathlib.") for name in imports):
        raise SystemExit("Statement.lean must import only Mathlib")
    expected = "-- Generated by scripts/generate_challenge.py; edit Statement.lean.\n" + source + THEOREM
    target = ROOT / "Challenge.lean"
    if args.check:
        if not target.exists() or target.read_text() != expected:
            raise SystemExit("Challenge.lean is stale; run scripts/generate_challenge.py")
    else:
        target.write_text(expected)
    print(f"Challenge.lean: {len(expected.splitlines())} lines, {len(expected.encode())} bytes")


if __name__ == "__main__":
    main()
