import QuotientSubmoduleEquidistribution.CategoryTheory.FiniteTauCategory
import QuotientSubmoduleEquidistribution.CategoryTheory.IdealQuotient
import QuotientSubmoduleEquidistribution.CategoryTheory.IdempotentLifting
import QuotientSubmoduleEquidistribution.CategoryTheory.IyamaLadderRadical
import QuotientSubmoduleEquidistribution.CategoryTheory.IyamaKrullSchmidtWeight
import QuotientSubmoduleEquidistribution.CategoryTheory.IyamaNakayamaExtraction
import QuotientSubmoduleEquidistribution.CategoryTheory.RejectiveOpposite
import QuotientSubmoduleEquidistribution.CategoryTheory.SplitMorphismComplement
import QuotientSubmoduleEquidistribution.CategoryTheory.LinearGeneratedHomIdeal
import QuotientSubmoduleEquidistribution.CategoryTheory.LinearMat
import QuotientSubmoduleEquidistribution.CategoryTheory.MatWeakExactness
import QuotientSubmoduleEquidistribution.RepresentationTheory.ContragredientDuality

/-!
# Vendored categorical foundation audit

This module makes the initial vendored dependency cone part of the compiled
magnitude package and checks the stable interfaces needed by later strata.
-/

namespace MagnitudeConjecture.VendoredAudit

#check QuotientSubmoduleEquidistribution.CategoricalIdeal.HomIdeal
#check QuotientSubmoduleEquidistribution.CategoricalRadical.IsRadicalMorphism
#check QuotientSubmoduleEquidistribution.CategoricalRejective.RightRejectiveData
#check QuotientSubmoduleEquidistribution.CategoricalRejective.LeftRejectiveData
#check QuotientSubmoduleEquidistribution.Iyama.RightTauSequence
#check QuotientSubmoduleEquidistribution.Iyama.LeftTauSequence
#check QuotientSubmoduleEquidistribution.Iyama.FiniteTauCategoryData
#check QuotientSubmoduleEquidistribution.Iyama.FiniteTauCategoryData.hasMuMinusNakayamaExtraction
#check QuotientSubmoduleEquidistribution.Iyama.FiniteRightTauCategoryData.additiveObjectWeightOfLabelWeight
#check QuotientSubmoduleEquidistribution.Iyama.AdditiveObjectWeight.morphismWeight_muMinus_eq_muPlus_of_nakayamaPair_offProjectives
#check QuotientSubmoduleEquidistribution.Iyama.FiniteRightTauCategoryData.isRadicalMorphism_iff_not_isSplitMono_from_obj
#check QuotientSubmoduleEquidistribution.splitMonoComplement
#check QuotientSubmoduleEquidistribution.Contragredient.reverseDualityEquivalence
#check QuotientSubmoduleEquidistribution.CategoricalIdeal.HomIdeal.quotientLinear
#check QuotientSubmoduleEquidistribution.CategoryTheory.IdempotentLifting.isIdempotentComplete_of_objectwise_nilpotent_kernel
#check QuotientSubmoduleEquidistribution.CategoryTheory.matLinear
#check QuotientSubmoduleEquidistribution.CategoryTheory.matHomModuleFinite
#check QuotientSubmoduleEquidistribution.Iyama.mat_isWeakKernel_of_exact_embedding
#check QuotientSubmoduleEquidistribution.Iyama.mat_isWeakCokernel_of_exact_embedding

end MagnitudeConjecture.VendoredAudit
