import MagnitudeConjecture.CategoryTheory.MeshIncomingDecomposition
import MagnitudeConjecture.CategoryTheory.MeshPairedRelation
import MagnitudeConjecture.CategoryTheory.MeshRealization

/-!
# Ringel's directed faithfulness induction

This file develops the representation-independent part of the standardness
argument.  A strict order on arrows rules out backward paths.  The ordinary
mesh relation then records, in the quotient, the composite of the paired
source and sink arrow families.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open scoped BigOperators

namespace MagnitudeConjecture.MeshCategory

universe u z

variable {k : Type u} [Field k]
variable {Q : Type} [Quiver.{0} Q]
variable [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)]
variable {C : Type z} [Category C] [Preadditive C] [Linear k C]
variable {T : RightMeshData Q} {F₀ : Q → C}

namespace RightMeshData

omit [Fintype Q] [∀ x y : Q, Fintype (x ⟶ y)] in
/-- If every arrow strictly lowers a chosen order, every nonempty path also
strictly lowers that order. -/
theorem path_lt_of_length_ne_zero [LinearOrder Q]
    (harrow : ∀ {a b : Q}, (a ⟶ b) → b < a)
    {a b : Q} (p : Quiver.Path a b) (hp : p.length ≠ 0) : b < a := by
  induction p with
  | nil => exact (hp rfl).elim
  | @cons b c p e ih =>
      by_cases hplen : p.length = 0
      · have hab : a = b := p.eq_of_length_zero hplen
        subst b
        exact harrow e
      · exact lt_trans (harrow e) (ih hplen)

/-- There are no mesh-category morphisms strictly backwards in an order
lowered by every quiver arrow. -/
theorem hom_eq_zero_of_lt [LinearOrder Q]
    (harrow : ∀ {a b : Q}, (a ⟶ b) → b < a)
    {x y : Q} (hyx : y < x)
    (f : obj (k := k) T x ⟶ obj (k := k) T y) : f = 0 := by
  obtain ⟨g, rfl⟩ := (quotientFunctor (k := k) T).map_surjective f
  have hg : g = 0 := by
    apply (MagnitudeConjecture.LinearPathCategory.homPathLinearEquiv
      (MagnitudeConjecture.LinearPathCategory.obj k Q x)
      (MagnitudeConjecture.LinearPathCategory.obj k Q y)).injective
    ext p
    exfalso
    cases p with
    | nil => exact (lt_irrefl x hyx).elim
    | cons p e =>
        exact (asymm
          (RightMeshData.path_lt_of_length_ne_zero harrow
            (p.cons e) (by simp)) hyx).elim
  rw [hg, (quotientFunctor (k := k) T).map_zero]

end RightMeshData

namespace Realization

open RightMeshData

variable (R : Realization (k := k) T F₀)

/-- The realization of a length-one mesh morphism is its selected arrow
representative. -/
@[simp]
theorem functor_map_incomingArrowHom {z : Q}
    (a : IncomingArrow z) :
    R.functor.map (T.incomingArrowHom (k := k) a) = R.arrowMap a.2 := by
  change R.freeFunctor.map
      (MagnitudeConjecture.LinearPathCategory.pathHom a.2.toPath) =
    R.arrowMap a.2
  rw [MagnitudeConjecture.LinearPathCategory.lift_map_pathHom]
  change MagnitudeConjecture.LinearPathCategory.pathMap F₀ R.arrowMap
      (Quiver.Path.nil.cons a.2) = R.arrowMap a.2
  calc
    MagnitudeConjecture.LinearPathCategory.pathMap F₀ R.arrowMap
          (Quiver.Path.nil.cons a.2) =
        R.arrowMap a.2 ≫
          MagnitudeConjecture.LinearPathCategory.pathMap F₀ R.arrowMap
            (Quiver.Path.nil : Quiver.Path z z) :=
      MagnitudeConjecture.LinearPathCategory.pathMap_cons
        F₀ R.arrowMap Quiver.Path.nil a.2
    _ = R.arrowMap a.2 := by
      rw [MagnitudeConjecture.LinearPathCategory.pathMap_nil,
        Category.comp_id]

/-- Realization carries the incoming-arrow decomposition to the corresponding
sum of composites in the target category. -/
theorem functor_map_incomingSum {x z : Q}
    (h : IncomingCoefficient (k := k) T x z) :
    R.functor.map (T.incomingSum h) =
      ∑ a : IncomingArrow z,
        R.functor.map (h a) ≫ R.arrowMap a.2 := by
  rw [RightMeshData.incomingSum, R.functor.map_sum]
  apply Finset.sum_congr rfl
  intro a _
  rw [R.functor.map_comp, R.functor_map_incomingArrowHom]
  rfl

/-- The local exactness input in Ringel's proof.  At a projective target the
incoming arrow family is jointly monic.  At a nonprojective target its kernel
is generated by the paired outgoing arrow family from the translate. -/
structure DirectedExactData where
  order : LinearOrder Q
  arrow_lt : ∀ {a b : Q} (_e : a ⟶ b), order.lt b a
  target_id_ne_zero :
    ∀ x : Q, 𝟙 (R.functor.obj (obj (k := k) T x)) ≠ 0
  projective_exact :
    ∀ (z : Q), z ∈ T.projective → ∀ (x : Q)
      (h : IncomingCoefficient (k := k) T x z),
      (∑ a : IncomingArrow z,
          R.functor.map (h a) ≫
            R.functor.map (T.incomingArrowHom (k := k) a)) = 0 →
        ∀ a, R.functor.map (h a) = 0
  nonprojective_exact :
    ∀ (z : {z : Q // z ∉ T.projective}) (x : Q)
      (h : IncomingCoefficient (k := k) T x z.1),
      (∑ a : IncomingArrow z.1,
          R.functor.map (h a) ≫
            R.functor.map (T.incomingArrowHom (k := k) a)) = 0 →
        ∃ t : R.functor.obj (obj (k := k) T x) ⟶
            R.functor.obj (obj (k := k) T (T.tau z)),
          ∀ a : IncomingArrow z.1,
            R.functor.map (h a) =
              t ≫ R.functor.map (T.incomingArrowHom (k := k)
                (⟨T.tau z, T.arrowEquiv z a.1 a.2⟩ :
                  IncomingArrow a.1))

namespace DirectedExactData

/-- Ringel's induction on the target vertex: local mesh exactness and
directedness force every morphism killed by the realization to vanish. -/
theorem map_eq_zero (D : R.DirectedExactData) [R.functor.Full] {x z : Q}
    (f : obj (k := k) T x ⟶ obj (k := k) T z)
    (hf : R.functor.map f = 0) : f = 0 := by
  letI : LinearOrder Q := DirectedExactData.order D
  let P : Q → Prop := fun z ↦
    ∀ (x : Q) (f : obj (k := k) T x ⟶ obj (k := k) T z),
      R.functor.map f = 0 → f = 0
  have hP : ∀ z, P z := by
    intro z
    apply (wellFounded_lt).induction z
    intro z ih
    intro x f hf
    obtain ⟨c, h, hdecomp⟩ :=
      T.exists_eq_diagonalScalar_add_incomingSum f
    by_cases hxz : x = z
    · subst x
      have hh : h = 0 := by
        funext a
        exact T.hom_eq_zero_of_lt D.arrow_lt
          (D.arrow_lt a.2) (h a)
      have hfeq : f = c • 𝟙 (obj (k := k) T z) := by
        rw [hdecomp, hh, RightMeshData.diagonalScalar_self]
        simp [RightMeshData.incomingSum]
      have hcmap : c • 𝟙 (R.functor.obj (obj (k := k) T z)) = 0 := by
        have hf' := hf
        rw [hfeq, R.functor.map_smul, R.functor.map_id] at hf'
        exact hf'
      have hc : c = 0 := by
        by_contra hc
        apply D.target_id_ne_zero z
        calc
          𝟙 (R.functor.obj (obj (k := k) T z)) =
              c⁻¹ • (c • 𝟙 (R.functor.obj (obj (k := k) T z))) := by
            simp [hc]
          _ = 0 := by rw [hcmap]; simp
      rw [hdecomp, hh, hc]
      simp [RightMeshData.diagonalScalar,
        RightMeshData.incomingSum]
    · have hdiag : T.diagonalScalar (k := k) x z c = 0 := by
        simp [RightMeshData.diagonalScalar, hxz]
      have hsum :
          (∑ a : IncomingArrow z,
            R.functor.map (h a) ≫
              R.functor.map (T.incomingArrowHom (k := k) a)) = 0 := by
        have hf' := hf
        rw [hdecomp, hdiag, zero_add, RightMeshData.incomingSum,
          R.functor.map_sum] at hf'
        simp_rw [R.functor.map_comp] at hf'
        exact hf'
      by_cases hz : z ∈ T.projective
      · have hmap (a : IncomingArrow z) :
            R.functor.map (h a) = 0 :=
          D.projective_exact z hz x h hsum a
        have hh : h = 0 := by
          funext a
          exact ih a.1 (D.arrow_lt a.2) x (h a) (hmap a)
        rw [hdecomp, hdiag, hh]
        simp [RightMeshData.incomingSum]
      · let znp : {z : Q // z ∉ T.projective} := ⟨z, hz⟩
        obtain ⟨t, ht⟩ := D.nonprojective_exact znp x h hsum
        obtain ⟨q, hq⟩ :
            ∃ q : obj (k := k) T x ⟶ obj (k := k) T (T.tau znp),
              R.functor.map q = t :=
          R.functor.map_surjective t
        let h' : IncomingCoefficient (k := k) T x z :=
          fun a ↦ h a - q ≫ T.incomingArrowHom (k := k)
            (⟨T.tau znp, T.arrowEquiv znp a.1 a.2⟩ :
              IncomingArrow a.1)
        have h'map (a : IncomingArrow z) :
            R.functor.map (h' a) = 0 := by
          dsimp only [h']
          rw [R.functor.map_sub, R.functor.map_comp, ht a, hq, sub_self]
        have h'zero (a : IncomingArrow z) : h' a = 0 :=
          ih a.1 (D.arrow_lt a.2) x (h' a) (h'map a)
        have hh (a : IncomingArrow z) :
            h a = q ≫ T.incomingArrowHom (k := k)
              (⟨T.tau znp, T.arrowEquiv znp a.1 a.2⟩ :
                IncomingArrow a.1) := by
          dsimp only [h'] at h'zero
          exact sub_eq_zero.mp (h'zero a)
        calc
          f = T.incomingSum h := by rw [hdecomp, hdiag, zero_add]
          _ = T.incomingSum
              (fun a : IncomingArrow z ↦
                q ≫ T.incomingArrowHom (k := k)
                  (⟨T.tau znp, T.arrowEquiv znp a.1 a.2⟩ :
                    IncomingArrow a.1)) := by
              apply congrArg T.incomingSum
              funext a
              exact hh a
          _ = 0 := T.paired_incomingSum_eq_zero (k := k) znp q
  exact hP z x f hf

/-- On every displayed pair of mesh vertices, the directed exact realization
is injective.  This vertexwise form is exactly what the strict standard mesh
presentation consumes. -/
theorem map_injective (D : R.DirectedExactData) [R.functor.Full]
    (x z : Q) : Function.Injective
      (fun f : obj (k := k) T x ⟶ obj (k := k) T z ↦ R.functor.map f) := by
  intro f g hfg
  apply sub_eq_zero.mp
  apply map_eq_zero (R := R) D (f - g)
  rw [R.functor.map_sub]
  exact sub_eq_zero.mpr hfg

end DirectedExactData

end Realization

end MagnitudeConjecture.MeshCategory
