import MagnitudeConjecture.CategoryTheory.HomogeneousPathIdeal
import MagnitudeConjecture.Graded.QuotientDecomposition

/-!
# Grading a path-category quotient by homogeneous relations

A family of homogeneous relations generates a homogeneous two-sided ideal.
The categorical quotient therefore inherits the path-length grading by taking
the images of the source components.  Composition adds degrees in the
quotient, and degree zero is unchanged.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory

namespace MagnitudeConjecture.LinearPathCategory.HomogeneousQuotient

open QuotientSubmoduleEquidistribution.CategoricalIdeal

universe u v w

variable {k : Type u} [Field k]
variable {Q : Type v} [Quiver.{w} Q]

/-- The two-sided linear ideal generated by a family of path-category
relations. -/
def relationIdeal
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) :
    HomIdeal (Category k Q) :=
  HomIdeal.linearSpan k R

/-- The raw categorical quotient by the generated relation ideal. -/
abbrev RawCategory
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) :=
  CategoryTheory.Quotient (relationIdeal R).rel

/-- The quotient functor from the free linear path category. -/
abbrev quotientFunctor
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) :=
  CategoryTheory.Quotient.functor (relationIdeal R).rel

instance rawPreadditive
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) :
    Preadditive (RawCategory R) :=
  (relationIdeal R).quotientPreadditive

instance quotientFunctorAdditive
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) :
    (quotientFunctor R).Additive :=
  CategoryTheory.Quotient.functor_additive
    (relationIdeal R).rel
    (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
      (relationIdeal R).add_compatible f₁ f₂ g₁ g₂ hf hg)

instance rawLinear
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) :
    Linear k (RawCategory R) :=
  (relationIdeal R).quotientLinear

instance quotientFunctorLinear
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) :
    (quotientFunctor R).Linear k :=
  (relationIdeal R).quotientFunctorLinear

/-- An original vertex as an object of the quotient category. -/
abbrev obj (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X : Category k Q) : RawCategory R :=
  (quotientFunctor R).obj X

/-- The quotient map on a Hom space as a linear map. -/
def quotientHomLinearMap
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X Y : Category k Q) :
    (X ⟶ Y) →ₗ[k] (obj R X ⟶ obj R Y) :=
  (quotientFunctor R).mapLinearMap k

/-- The quotient map is surjective on every Hom space. -/
theorem quotientHom_surjective
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X Y : Category k Q) :
    Function.Surjective (quotientHomLinearMap R X Y) :=
  (quotientFunctor R).map_surjective

/-- The kernel of the quotient map is exactly the generated relation
submodule. -/
theorem ker_quotientHomLinearMap
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X Y : Category k Q) :
    LinearMap.ker (quotientHomLinearMap R X Y) =
      HomIdeal.generatedHomSubmodule k R X Y := by
  ext f
  change (quotientFunctor R).map f = 0 ↔
    f ∈ HomIdeal.generatedHomSubmodule k R X Y
  exact (relationIdeal R).map_eq_zero_iff f

/-- The degree-`n` part of a quotient Hom space is the image of the
path-length-`n` part upstairs. -/
def lengthComponent
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X Y : Category k Q) (n : ℕ) :
    Submodule k (obj R X ⟶ obj R Y) :=
  (LinearPathCategory.lengthComponent X Y n).map
    (quotientHomLinearMap R X Y)

/-- Homogeneous relations give an internal path-length decomposition of each
quotient Hom space. -/
theorem lengthComponent_isInternal
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (hR : ∀ (A B : Category k Q) (r : A ⟶ B),
      r ∈ R A B → ∃ n, r ∈ LinearPathCategory.lengthComponent A B n)
    (X Y : Category k Q) :
    DirectSum.IsInternal (lengthComponent R X Y) := by
  letI : DirectSum.Decomposition
      (LinearPathCategory.lengthComponent X Y) :=
    (LinearPathCategory.lengthComponent_isInternal X Y).chooseDecomposition
  apply MagnitudeConjecture.Graded.image_isInternal_of_surjective_of_ker_isHomogeneous
    (LinearPathCategory.lengthComponent X Y)
    (quotientHomLinearMap R X Y)
    (quotientHom_surjective R X Y)
  rw [ker_quotientHomLinearMap]
  exact LinearPathCategory.linearSpan_hom_isHomogeneous R hR X Y

/-- Composition in a homogeneous relation quotient adds path length. -/
theorem comp_mem_lengthComponent
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    {X Y Z : Category k Q} {i j : ℕ}
    {f : obj R X ⟶ obj R Y} {g : obj R Y ⟶ obj R Z}
    (hf : f ∈ lengthComponent R X Y i)
    (hg : g ∈ lengthComponent R Y Z j) :
    f ≫ g ∈ lengthComponent R X Z (i + j) := by
  rcases hf with ⟨f, hf, rfl⟩
  rcases hg with ⟨g, hg, rfl⟩
  change (quotientFunctor R).map f ≫ (quotientFunctor R).map g ∈
    lengthComponent R X Z (i + j)
  rw [← (quotientFunctor R).map_comp]
  exact ⟨f ≫ g, LinearPathCategory.comp_mem_lengthComponent hf hg, rfl⟩

@[simp]
theorem id_mem_lengthComponent_zero
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X : Category k Q) :
    𝟙 (obj R X) ∈ lengthComponent R X X 0 := by
  refine ⟨𝟙 X, LinearPathCategory.id_mem_lengthComponent_zero X, ?_⟩
  exact (quotientFunctor R).map_id X

/-- Distinct vertices still have zero degree-zero quotient morphisms. -/
theorem lengthComponent_zero_eq_bot_of_vertex_ne
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    {X Y : Category k Q} (hXY : vertex Y ≠ vertex X) :
    lengthComponent R X Y 0 = ⊥ := by
  rw [lengthComponent,
    LinearPathCategory.lengthComponent_zero_eq_bot_of_vertex_ne hXY]
  exact Submodule.map_bot _

/-- At a vertex, the quotient degree-zero part consists exactly of scalar
multiples of the identity. -/
theorem lengthComponent_zero_self
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X : Category k Q) :
    lengthComponent R X X 0 = k ∙ (𝟙 (obj R X)) := by
  rw [lengthComponent, LinearPathCategory.lengthComponent_zero_self]
  rw [Submodule.map_span]
  rw [Set.image_singleton]
  change k ∙ (quotientFunctor R).map (𝟙 X) = k ∙ (𝟙 (obj R X))
  rw [(quotientFunctor R).map_id]

/-- If every path-basis two-sided composite of a relation has positive
length, then the homogeneous quotient does not kill any vertex identity. -/
theorem id_ne_zero_of_basisCompositeSet_positive
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X : Category k Q)
    (hpositive : ∀ f : X ⟶ X, f ∈ LinearPathCategory.basisCompositeSet R X X →
      ∃ n, n ≠ 0 ∧ f ∈ LinearPathCategory.lengthComponent X X n) :
    𝟙 (obj R X) ≠ 0 := by
  intro hid
  have hsource : quotientHomLinearMap R X X (𝟙 X) = 0 := by
    change (quotientFunctor R).map (𝟙 X) = 0
    simpa using hid
  have hmem : (𝟙 X) ∈ HomIdeal.generatedHomSubmodule k R X X := by
    rw [← ker_quotientHomLinearMap, LinearMap.mem_ker]
    exact hsource
  have hle : HomIdeal.generatedHomSubmodule k R X X ≤
      LinearMap.ker (LinearPathCategory.nilPathCoefficient X) := by
    rw [LinearPathCategory.generatedHomSubmodule_eq_span_basisCompositeSet]
    apply Submodule.span_le.2
    intro f hf
    change LinearPathCategory.nilPathCoefficient X f = 0
    obtain ⟨n, hn, hfn⟩ := hpositive f hf
    exact LinearPathCategory.nilPathCoefficient_eq_zero_of_mem_lengthComponent X hn hfn
  have hone := hle hmem
  change LinearPathCategory.nilPathCoefficient X (𝟙 X) = 0 at hone
  rw [LinearPathCategory.nilPathCoefficient_id] at hone
  exact one_ne_zero hone

end MagnitudeConjecture.LinearPathCategory.HomogeneousQuotient
