import QuotientSubmoduleEquidistribution.CategoryTheory.LinearGeneratedHomIdeal
import MagnitudeConjecture.CategoryTheory.PathLengthGrading
import MagnitudeConjecture.Graded.QuotientDecomposition

/-!
# Homogeneous ideals generated by path-category relations

If the specified relation generators in a free linear path category are
homogeneous for path length, then the two-sided linear Hom ideal that they
generate is homogeneous.  Arbitrary multipliers are expanded in the path
bases on the two sides.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory

namespace MagnitudeConjecture.LinearPathCategory

open QuotientSubmoduleEquidistribution.CategoricalIdeal

universe u v w

variable {k : Type u} [Field k]
variable {Q : Type v} [Quiver.{w} Q]

/-- Two-sided composites of a relation generator with path-basis morphisms on
both sides. -/
def basisCompositeSet
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (X Y : Category k Q) : Set (X ⟶ Y) :=
  {f | ∃ (A B : Category k Q) (r : A ⟶ B), r ∈ R A B ∧
      ∃ (p : Quiver.Path (vertex A) (vertex X))
        (q : Quiver.Path (vertex Y) (vertex B)),
        f = pathHom p ≫ r ≫ pathHom q}

theorem basisCompositeSet_subset_twoSidedCompositeSet
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) (X Y : Category k Q) :
    basisCompositeSet R X Y ⊆
      HomIdeal.twoSidedCompositeSet R X Y := by
  rintro f ⟨A, B, r, hr, p, q, rfl⟩
  exact ⟨A, B, r, hr, pathHom p, pathHom q, rfl⟩

/-- Every composite with arbitrary morphisms on the two sides is in the span
of composites whose side factors are path-basis morphisms. -/
theorem twoSidedComposite_mem_span_basisCompositeSet
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    {X Y A B : Category k Q} {r : A ⟶ B} (hr : r ∈ R A B)
    (a : X ⟶ A) (b : B ⟶ Y) :
    a ≫ r ≫ b ∈ Submodule.span k (basisCompositeSet R X Y) := by
  have ha := (homPathBasis X A).mem_span a
  induction ha using Submodule.span_induction with
  | mem a ha =>
      rcases ha with ⟨p, rfl⟩
      rw [homPathBasis_apply]
      have hb := (homPathBasis B Y).mem_span b
      induction hb using Submodule.span_induction with
      | mem b hb =>
          rcases hb with ⟨q, rfl⟩
          rw [homPathBasis_apply]
          apply Submodule.subset_span
          exact ⟨A, B, r, hr, p, q, rfl⟩
      | zero => simp
      | add b c _ _ hb hc => simpa using Submodule.add_mem _ hb hc
      | smul c b _ hb => simpa using Submodule.smul_mem _ c hb
  | zero => simp
  | add a c _ _ ha hc => simpa using Submodule.add_mem _ ha hc
  | smul c a _ ha => simpa using Submodule.smul_mem _ c ha

/-- The usual generated Hom submodule can be presented using path-basis
multipliers only. -/
theorem generatedHomSubmodule_eq_span_basisCompositeSet
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y)) (X Y : Category k Q) :
    HomIdeal.generatedHomSubmodule k R X Y =
      Submodule.span k (basisCompositeSet R X Y) := by
  apply le_antisymm
  · apply Submodule.span_le.2
    intro f hf
    rcases hf with ⟨A, B, r, hr, a, b, rfl⟩
    exact twoSidedComposite_mem_span_basisCompositeSet R hr a b
  · apply Submodule.span_le.2
    intro f hf
    apply Submodule.subset_span
    exact basisCompositeSet_subset_twoSidedCompositeSet R X Y hf

theorem basisCompositeSet_isHomogeneous
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (hR : ∀ (A B : Category k Q) (r : A ⟶ B),
      r ∈ R A B → ∃ n, r ∈ lengthComponent A B n)
    {X Y : Category k Q} {f : X ⟶ Y}
    (hf : f ∈ basisCompositeSet R X Y) :
    ∃ n, f ∈ lengthComponent X Y n := by
  rcases hf with ⟨A, B, r, hr, p, q, rfl⟩
  obtain ⟨n, hn⟩ := hR A B r hr
  have hp : pathHom p ∈ lengthComponent X A p.length :=
    (pathHom_mem_lengthComponent_iff p p.length).2 rfl
  have hq : pathHom q ∈ lengthComponent B Y q.length :=
    (pathHom_mem_lengthComponent_iff q q.length).2 rfl
  refine ⟨p.length + n + q.length, ?_⟩
  exact MagnitudeConjecture.CategoricalGrading.comp_comp_mem
    (fun X Y ↦ lengthComponent X Y)
    (fun ha hb ↦ comp_mem_lengthComponent ha hb) hp hn hq

noncomputable local instance lengthDecomposition (X Y : Category k Q) :
    DirectSum.Decomposition (lengthComponent X Y) :=
  (lengthComponent_isInternal X Y).chooseDecomposition

/-- A two-sided Hom ideal generated by path-length-homogeneous relations is
homogeneous in every Hom space. -/
theorem linearSpan_hom_isHomogeneous
    (R : ∀ X Y : Category k Q, Set (X ⟶ Y))
    (hR : ∀ (A B : Category k Q) (r : A ⟶ B),
      r ∈ R A B → ∃ n, r ∈ lengthComponent A B n)
    (X Y : Category k Q) :
    DirectSum.SetLike.IsHomogeneous (lengthComponent X Y)
      ((HomIdeal.linearSpan k R).hom X Y) := by
  change DirectSum.SetLike.IsHomogeneous (lengthComponent X Y)
    (HomIdeal.generatedHomSubmodule k R X Y)
  rw [generatedHomSubmodule_eq_span_basisCompositeSet]
  exact MagnitudeConjecture.Graded.span_isHomogeneous_of_forall_mem_component
    (lengthComponent X Y) (basisCompositeSet R X Y)
    (fun _ hf ↦ basisCompositeSet_isHomogeneous R hR hf)

end MagnitudeConjecture.LinearPathCategory
