import MagnitudeConjecture.CategoryTheory.LinearIdealQuotientLift
import MagnitudeConjecture.CategoryTheory.LinearPathLift
import MagnitudeConjecture.CategoryTheory.MeshCategory

/-!
# Linear realizations of mesh categories

An assignment of objects and reversed arrow representatives determines a
linear functor from the free path category.  If the displayed mesh relations
evaluate to zero, that functor descends to the mesh quotient.  This file also
isolates the exact kernel statement which makes the descended realization
faithful.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory

namespace MagnitudeConjecture.MeshCategory

open QuotientSubmoduleEquidistribution.CategoricalIdeal

universe u v w z

variable {k : Type u} [Field k]
variable {Q : Type v} [Quiver.{w} Q]
variable [∀ x : Q, Fintype (Σ y : Q, x ⟶ y)]
variable {C : Type z} [Category C] [Preadditive C] [Linear k C]

/-- A realization of the arrows of a right translation quiver in a linear
category for which every ordinary mesh relation evaluates to zero. -/
structure Realization (T : RightMeshData Q) (F₀ : Q → C) where
  arrowMap : ∀ {i j : Q}, (i ⟶ j) → (F₀ j ⟶ F₀ i)
  map_meshRelation :
    ∀ x : {x : Q // x ∉ T.projective},
      (MagnitudeConjecture.LinearPathCategory.lift
        (k := k) F₀ arrowMap).map (T.meshRelation (k := k) x) = 0

namespace Realization

variable {T : RightMeshData Q} {F₀ : Q → C}
variable (R : Realization (k := k) T F₀)

/-- The free linear path realization determined by the arrow assignment. -/
abbrev freeFunctor :
    MagnitudeConjecture.LinearPathCategory.Category k Q ⥤ C :=
  MagnitudeConjecture.LinearPathCategory.lift (k := k) F₀ R.arrowMap

/-- The Hom ideal generated by the ordinary mesh relations. -/
abbrev meshIdeal (_R : Realization (k := k) T F₀) :
    HomIdeal (MagnitudeConjecture.LinearPathCategory.Category k Q) :=
  MagnitudeConjecture.LinearPathCategory.HomogeneousQuotient.relationIdeal
    (T.meshGeneratorSet (k := k))

/-- Vanishing of the mesh generators implies vanishing of their whole
two-sided linear Hom ideal. -/
theorem meshIdeal_isKilledBy :
    R.meshIdeal.IsKilledBy R.freeFunctor := by
  intro X Y f hf
  have hk : f ∈
      (HomIdeal.functorKernel (k := k) R.freeFunctor).hom X Y := by
    apply HomIdeal.linearSpan_le
      (T.meshGeneratorSet (k := k))
      (HomIdeal.functorKernel (k := k) R.freeFunctor)
      ?_ hf
    intro U V r hr
    change R.freeFunctor.map r = 0
    rcases hr with ⟨x, rfl, rfl, rfl⟩
    simpa using R.map_meshRelation x
  exact (HomIdeal.mem_functorKernel_iff
    (k := k) R.freeFunctor f).1 hk

/-- The induced realization of the ordinary mesh quotient. -/
def functor : RawCategory (k := k) T ⥤ C :=
  R.meshIdeal.quotientLift R.freeFunctor R.meshIdeal_isKilledBy

noncomputable instance functor_additive : R.functor.Additive :=
  HomIdeal.quotientLift_additive R.meshIdeal R.freeFunctor
    R.meshIdeal_isKilledBy

noncomputable instance functor_linear : R.functor.Linear k :=
  HomIdeal.quotientLift_linear R.meshIdeal R.freeFunctor
    R.meshIdeal_isKilledBy

noncomputable instance functor_full [R.freeFunctor.Full] :
    R.functor.Full :=
  HomIdeal.quotientLift_full R.meshIdeal R.freeFunctor
    R.meshIdeal_isKilledBy

@[simp]
theorem functor_map_quotient_map
    {X Y : MagnitudeConjecture.LinearPathCategory.Category k Q}
    (f : X ⟶ Y) :
    R.functor.map ((quotientFunctor (k := k) T).map f) =
      R.freeFunctor.map f :=
  rfl

/-- The residual standardness statement upstairs: every relation killed by
the free-path realization lies in the ideal generated by the meshes. -/
def KernelGeneratedByMesh : Prop :=
  ∀ {X Y : MagnitudeConjecture.LinearPathCategory.Category k Q}
      {f : X ⟶ Y},
    R.freeFunctor.map f = 0 → f ∈ R.meshIdeal.hom X Y

/-- Kernel generation by meshes makes the quotient realization faithful. -/
theorem functor_faithful
    (hker : R.KernelGeneratedByMesh) : R.functor.Faithful :=
  R.meshIdeal.quotientLift_faithful R.freeFunctor
    R.meshIdeal_isKilledBy hker

/-- A full mesh realization which is injective on one displayed Hom space
gives a linear equivalence on that Hom space. -/
def homLinearEquivOfInjective [R.functor.Full]
    (x y : Q)
    (hinjective : Function.Injective
      (fun f : obj (k := k) T x ⟶ obj (k := k) T y ↦ R.functor.map f)) :
    (obj (k := k) T x ⟶ obj (k := k) T y) ≃ₗ[k]
      (F₀ x ⟶ F₀ y) :=
  LinearEquiv.ofBijective (R.functor.mapLinearMap k)
    ⟨hinjective, R.functor.map_surjective⟩

/-- A full and faithful mesh realization gives a linear equivalence on each
Hom space. -/
def homLinearEquiv [R.functor.Full] [R.functor.Faithful]
    (x y : Q) :
    (obj (k := k) T x ⟶ obj (k := k) T y) ≃ₗ[k]
      (F₀ x ⟶ F₀ y) :=
  R.homLinearEquivOfInjective x y R.functor.map_injective

@[simp]
theorem homLinearEquivOfInjective_apply [R.functor.Full]
    (x y : Q)
    (hinjective : Function.Injective
      (fun f : obj (k := k) T x ⟶ obj (k := k) T y ↦ R.functor.map f))
    (f : obj (k := k) T x ⟶ obj (k := k) T y) :
    R.homLinearEquivOfInjective x y hinjective f = R.functor.map f :=
  rfl

@[simp]
theorem homLinearEquiv_apply [R.functor.Full] [R.functor.Faithful]
    (x y : Q) (f : obj (k := k) T x ⟶ obj (k := k) T y) :
    R.homLinearEquiv x y f = R.functor.map f :=
  rfl

end Realization

end MagnitudeConjecture.MeshCategory
