import MagnitudeConjecture.CategoryTheory.FiniteDimensionalModuleLocalRepresentationFinite
import MagnitudeConjecture.CategoryTheory.ObjectDeletionModuleExtension
import Mathlib.CategoryTheory.Abelian.SerreClass.Basic

/-!
# Module-theoretic inheritance under object deletion

Extension by zero embeds finite-dimensional modules on an object-deletion
category fully faithfully into the ambient finite-dimensional module
category.  Its essential image consists exactly of the ambient modules which
vanish on the deleted objects, and that vanishing subcategory is a Serre
class.  This file also formalizes the manuscript's first inheritance
consequence: local representation-finiteness passes to every object-deletion
category.

For a surviving base object, start from a finite ambient family covering all
indecomposables nonzero there.  Keep exactly those finitely many indices whose
ambient representative occurs in the essential image of extension by zero,
and choose one deletion-stage preimage at each retained index.  Full
faithfulness then reflects the ambient isomorphisms back to the deletion
stage.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits
open scoped ZeroObject

namespace MagnitudeConjecture.ObjectDeletion

open MagnitudeConjecture.CoveringHom

universe u v

variable {k : Type v} [Field k]
variable (C : Type u) [Category.{v} C] [Preadditive C] [Linear k C]
variable (S : Set C)

/-- An ambient module vanishes on all objects removed by the deletion. -/
def ModuleVanishesOnDeleted
    (M : C ⥤ ModuleCat.{v} k) : Prop :=
  ∀ X : C, X ∈ S → IsZero (M.obj X)

/-- A module which vanishes on the deleted objects kills the Hom ideal
generated by those objects. -/
theorem module_isKilledBy_of_vanishesOnDeleted
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M) :
    (ideal (k := k) C S).IsKilledBy M := by
  intro X Y f hf
  have hk : f ∈
      (QuotientSubmoduleEquidistribution.CategoricalIdeal.HomIdeal.functorKernel
        (k := k) M).hom X Y := by
    apply QuotientSubmoduleEquidistribution.CategoricalIdeal.HomIdeal.linearSpan_le
      (endomorphismRelations C S)
      (QuotientSubmoduleEquidistribution.CategoricalIdeal.HomIdeal.functorKernel
        (k := k) M)
      ?_ hf
    intro U V r hr
    rcases hr with ⟨rfl, hU⟩
    change M.map r = 0
    exact (hM U hU).eq_of_src _ _
  exact
    (QuotientSubmoduleEquidistribution.CategoricalIdeal.HomIdeal.mem_functorKernel_iff
      (k := k) M f).1 hk

/-- Descend an ambient module which vanishes on the deleted objects to the
object-deletion category. -/
def moduleRestrictionToDeletion
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M) :
    DeletionCategory (k := k) C S ⥤ ModuleCat.{v} k :=
  (IsSurvivingRaw (k := k) C S).ι ⋙
    (ideal (k := k) C S).quotientLift M
      (module_isKilledBy_of_vanishesOnDeleted (k := k) C S M hM)

noncomputable instance moduleRestrictionToDeletion_additive
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M) :
    (moduleRestrictionToDeletion (k := k) C S M hM).Additive := by
  dsimp [moduleRestrictionToDeletion]
  infer_instance

noncomputable instance moduleRestrictionToDeletion_linear
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M) :
    (moduleRestrictionToDeletion (k := k) C S M hM).Linear k := by
  dsimp [moduleRestrictionToDeletion]
  infer_instance

set_option backward.isDefEq.respectTransparency false in
/-- An isomorphism of ambient vanishing modules descends to an isomorphism
of their restrictions to the object-deletion category. -/
noncomputable def moduleRestrictionToDeletionIso
    (M N : C ⥤ ModuleCat.{v} k)
    [M.Additive] [M.Linear k] [N.Additive] [N.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M)
    (hN : ModuleVanishesOnDeleted (k := k) C S N)
    (e : M ≅ N) :
    moduleRestrictionToDeletion (k := k) C S M hM ≅
      moduleRestrictionToDeletion (k := k) C S N hN :=
  NatIso.ofComponents (fun X ↦ e.app X.obj.as) (by
    intro X Y f
    rcases X with ⟨⟨X⟩, hX⟩
    rcases Y with ⟨⟨Y⟩, hY⟩
    obtain ⟨g, hg⟩ := (rawFunctor (k := k) C S).map_surjective f.hom
    change
      ((ideal (k := k) C S).quotientLift M
          (module_isKilledBy_of_vanishesOnDeleted (k := k) C S M hM)).map
            f.hom ≫ e.hom.app Y =
        e.hom.app X ≫
          ((ideal (k := k) C S).quotientLift N
            (module_isKilledBy_of_vanishesOnDeleted (k := k) C S N hN)).map
              f.hom
    rw [← hg]
    exact e.hom.naturality g)

@[simp]
theorem moduleRestrictionToDeletion_map_survivingMap
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M)
    {X Y : C} (hX : X ∉ S) (hY : Y ∉ S) (f : X ⟶ Y) :
    (moduleRestrictionToDeletion (k := k) C S M hM).map
        (survivingMap (k := k) C S hX hY f) =
      M.map f := by
  rfl

/-- The extension of the descended module is pointwise isomorphic to the
original ambient module. -/
def moduleRestrictionExtensionIsoApp
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M)
    (X : C) :
    (moduleExtensionByZero (k := k) C S
        (moduleRestrictionToDeletion (k := k) C S M hM)).obj X ≅
      M.obj X := by
  by_cases hX : X ∈ S
  · exact
      (moduleExtensionByZero_obj_isZero_of_mem (k := k) C S
        (moduleRestrictionToDeletion (k := k) C S M hM) hX).iso
          (hM X hX)
  · exact moduleExtensionByZeroObjIso (k := k) C S
      (moduleRestrictionToDeletion (k := k) C S M hM) hX

@[simp]
theorem moduleRestrictionExtensionIsoApp_of_not_mem
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M)
    {X : C} (hX : X ∉ S) :
    moduleRestrictionExtensionIsoApp (k := k) C S M hM X =
      moduleExtensionByZeroObjIso (k := k) C S
        (moduleRestrictionToDeletion (k := k) C S M hM) hX := by
  unfold moduleRestrictionExtensionIsoApp
  split
  · rename_i h
    exact (hX h).elim
  · rfl

/-- Extension by zero after descent recovers an ambient module which vanishes
on the deleted objects. -/
def moduleRestrictionExtensionIso
    (M : C ⥤ ModuleCat.{v} k) [M.Additive] [M.Linear k]
    (hM : ModuleVanishesOnDeleted (k := k) C S M) :
    moduleExtensionByZero (k := k) C S
        (moduleRestrictionToDeletion (k := k) C S M hM) ≅
      M :=
  NatIso.ofComponents
    (fun X ↦ moduleRestrictionExtensionIsoApp (k := k) C S M hM X)
    (by
      intro X Y f
      by_cases hX : X ∈ S
      · exact
          (moduleExtensionByZero_obj_isZero_of_mem (k := k) C S
            (moduleRestrictionToDeletion (k := k) C S M hM) hX).eq_of_src _ _
      · by_cases hY : Y ∈ S
        · exact (hM Y hY).eq_of_tgt _ _
        · rw [moduleRestrictionExtensionIsoApp_of_not_mem
              (k := k) C S M hM hX,
            moduleRestrictionExtensionIsoApp_of_not_mem
              (k := k) C S M hM hY]
          change
            moduleExtensionByZeroMap (k := k) C S
                (moduleRestrictionToDeletion (k := k) C S M hM) f ≫
                (moduleExtensionByZeroObjIso (k := k) C S
                  (moduleRestrictionToDeletion (k := k) C S M hM) hY).hom =
              (moduleExtensionByZeroObjIso (k := k) C S
                (moduleRestrictionToDeletion (k := k) C S M hM) hX).hom ≫
                M.map f
          have hmap :
              moduleExtensionByZeroMap (k := k) C S
                    (moduleRestrictionToDeletion (k := k) C S M hM) f ≫
                  (moduleExtensionByZeroObjIso (k := k) C S
                    (moduleRestrictionToDeletion (k := k) C S M hM) hY).hom =
                (moduleExtensionByZeroObjIso (k := k) C S
                    (moduleRestrictionToDeletion (k := k) C S M hM) hX).hom ≫
                  (moduleRestrictionToDeletion (k := k) C S M hM).map
                    (survivingMap (k := k) C S hX hY f) := by
            simpa only [moduleExtensionByZero] using
              moduleExtensionByZeroObjIso_map (k := k) C S
                (moduleRestrictionToDeletion (k := k) C S M hM)
                  hX hY f
          calc
            _ = (moduleExtensionByZeroObjIso (k := k) C S
                    (moduleRestrictionToDeletion (k := k) C S M hM) hX).hom ≫
                  (moduleRestrictionToDeletion (k := k) C S M hM).map
                    (survivingMap (k := k) C S hX hY f) := hmap
            _ = _ := congrArg (fun q ↦
              (moduleExtensionByZeroObjIso (k := k) C S
                (moduleRestrictionToDeletion (k := k) C S M hM) hX).hom ≫ q)
                  (moduleRestrictionToDeletion_map_survivingMap
                    (k := k) C S M hM hX hY f))

/-- Descend a linear ambient module which vanishes on the deleted objects. -/
def linearModuleRestrictionToDeletion
    (M : LinearModuleCategory.{u, v, v, v} (C := C) k)
    (hM : ModuleVanishesOnDeleted (k := k) C S M.obj) :
    LinearModuleCategory.{u, v, v, v}
      (C := DeletionCategory (k := k) C S) k :=
  ⟨moduleRestrictionToDeletion (k := k) C S M.obj hM,
    ⟨inferInstance, inferInstance⟩⟩

/-- Restricting a vanishing linear module successively along `S` and `T`
agrees with restricting it once along `S ∪ T`, after the canonical
equivalence between the two deletion categories. -/
noncomputable def iteratedLinearModuleRestrictionIso
    (T : Set C)
    (M : LinearModuleCategory.{u, v, v, v} (C := C) k)
    (hUnion : ModuleVanishesOnDeleted (k := k) C (S ∪ T) M.obj)
    (hS : ModuleVanishesOnDeleted (k := k) C S M.obj)
    (hT : ModuleVanishesOnDeleted (k := k)
      (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)
      (linearModuleRestrictionToDeletion (k := k) C S M hS).obj) :
    iteratedToUnionFunctor (k := k) C S T ⋙
        (linearModuleRestrictionToDeletion
          (k := k) C (S ∪ T) M hUnion).obj ≅
      (linearModuleRestrictionToDeletion (k := k)
        (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)
        (linearModuleRestrictionToDeletion (k := k) C S M hS) hT).obj := by
  refine NatIso.ofComponents (fun _ ↦ Iso.refl _) ?_
  intro X Y f
  change
    ((ideal (k := k) C (S ∪ T)).quotientLift M.obj
      (module_isKilledBy_of_vanishesOnDeleted
        (k := k) C (S ∪ T) M.obj hUnion)).map
        ((iteratedRawToRawUnion (k := k) C S T).map f.hom) =
      ((ideal (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)).quotientLift
          (linearModuleRestrictionToDeletion (k := k) C S M hS).obj
          (module_isKilledBy_of_vanishesOnDeleted (k := k)
            (DeletionCategory (k := k) C S)
            (AdditionalDeleted (k := k) C S T)
            (linearModuleRestrictionToDeletion (k := k) C S M hS).obj hT)).map
        f.hom
  obtain ⟨g, hg⟩ :=
    (rawFunctor (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)).map_surjective f.hom
  rw [← hg]
  change
    ((ideal (k := k) C (S ∪ T)).quotientLift M.obj
      (module_isKilledBy_of_vanishesOnDeleted
        (k := k) C (S ∪ T) M.obj hUnion)).map
        ((firstDeletionToRawUnion (k := k) C S T).map g) =
      (linearModuleRestrictionToDeletion (k := k) C S M hS).obj.map g
  obtain ⟨q, hq⟩ :=
    (rawFunctor (k := k) C S).map_surjective g.hom
  change
    ((ideal (k := k) C (S ∪ T)).quotientLift M.obj
      (module_isKilledBy_of_vanishesOnDeleted
        (k := k) C (S ∪ T) M.obj hUnion)).map
        ((rawFunctorOfLE (k := k) C Set.subset_union_left).map g.hom) =
      ((ideal (k := k) C S).quotientLift M.obj
        (module_isKilledBy_of_vanishesOnDeleted
          (k := k) C S M.obj hS)).map g.hom
  rw [← hq]
  rfl

/-- Restriction is unchanged when the deleted-object set is replaced by an
equal set and the deletion category is transported by that equality. -/
noncomputable def deletionEquivalenceOfEq_linearModuleRestrictionIso
    {T : Set C} (hST : S = T)
    (M : LinearModuleCategory.{u, v, v, v} (C := C) k)
    (hS : ModuleVanishesOnDeleted (k := k) C S M.obj)
    (hT : ModuleVanishesOnDeleted (k := k) C T M.obj) :
    (deletionEquivalenceOfEq (k := k) C hST).functor ⋙
        (linearModuleRestrictionToDeletion (k := k) C T M hT).obj ≅
      (linearModuleRestrictionToDeletion (k := k) C S M hS).obj := by
  subst T
  exact Iso.refl _

/-- If `S ⊆ T`, successive restriction along `S` and the surviving part of
`T` agrees with direct restriction along `T`. -/
noncomputable def iteratedLinearModuleRestrictionIsoOfSubset
    (T : Set C) (hST : S ⊆ T)
    (M : LinearModuleCategory.{u, v, v, v} (C := C) k)
    (hFull : ModuleVanishesOnDeleted (k := k) C T M.obj)
    (hS : ModuleVanishesOnDeleted (k := k) C S M.obj)
    (hAdditional : ModuleVanishesOnDeleted (k := k)
      (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)
      (linearModuleRestrictionToDeletion (k := k) C S M hS).obj) :
    let hEq : S ∪ T = T := Set.union_eq_right.mpr hST
    let e := (iteratedDeletionEquivalence (k := k) C S T).trans
      (deletionEquivalenceOfEq (k := k) C hEq)
    e.functor ⋙ (linearModuleRestrictionToDeletion
        (k := k) C T M hFull).obj ≅
      (linearModuleRestrictionToDeletion (k := k)
        (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)
        (linearModuleRestrictionToDeletion (k := k) C S M hS)
        hAdditional).obj := by
  let hEq : S ∪ T = T := Set.union_eq_right.mpr hST
  let hUnion : ModuleVanishesOnDeleted (k := k) C (S ∪ T) M.obj :=
    fun X hX ↦ hFull X (hEq ▸ hX)
  let e₁ := iteratedDeletionEquivalence (k := k) C S T
  let e₂ := deletionEquivalenceOfEq (k := k) C hEq
  let a := deletionEquivalenceOfEq_linearModuleRestrictionIso
    (k := k) C (S ∪ T) hEq M hUnion hFull
  let b := iteratedLinearModuleRestrictionIso
    (k := k) C S T M hUnion hS hAdditional
  change (e₁.functor ⋙ e₂.functor) ⋙
      (linearModuleRestrictionToDeletion (k := k) C T M hFull).obj ≅ _
  exact (Functor.isoWhiskerLeft e₁.functor a).trans b

/-- At the linear-module level, extension by zero after descent is
isomorphic to the original vanishing module. -/
def linearModuleRestrictionExtensionIso
    (M : LinearModuleCategory.{u, v, v, v} (C := C) k)
    (hM : ModuleVanishesOnDeleted (k := k) C S M.obj) :
    (linearModuleExtensionByZero (k := k) C S).obj
        (linearModuleRestrictionToDeletion (k := k) C S M hM) ≅
      M :=
  ObjectProperty.isoMk _
    (moduleRestrictionExtensionIso (k := k) C S M.obj hM)

/-- Restricting the extension by zero of a linear deletion module recovers
the original module. -/
noncomputable def linearModuleExtensionRestrictionIso
    (M : LinearModuleCategory.{u, v, v, v}
      (C := DeletionCategory (k := k) C S) k) :
    let F := linearModuleExtensionByZero (k := k) C S
    let hvanish : ModuleVanishesOnDeleted (k := k) C S
        (F.obj M).obj := fun _X hX ↦
      moduleExtensionByZero_obj_isZero_of_mem (k := k) C S M.obj hX
    linearModuleRestrictionToDeletion (k := k) C S (F.obj M) hvanish ≅ M := by
  let F := linearModuleExtensionByZero (k := k) C S
  let hvanish : ModuleVanishesOnDeleted (k := k) C S
      (F.obj M).obj := fun _X hX ↦
    moduleExtensionByZero_obj_isZero_of_mem (k := k) C S M.obj hX
  apply F.preimageIso
  exact linearModuleRestrictionExtensionIso
    (k := k) C S (F.obj M) hvanish

/-- The essential image of extension by zero consists exactly of the ambient
linear modules which vanish on the deleted objects. -/
theorem linearModuleExtensionByZero_essImage_iff
    (M : LinearModuleCategory.{u, v, v, v} (C := C) k) :
    (linearModuleExtensionByZero (k := k) C S).essImage M ↔
      ModuleVanishesOnDeleted (k := k) C S M.obj := by
  constructor
  · rintro ⟨N, ⟨e⟩⟩ X hX
    let J := (IsLinearModule.{u, v, v, v} (C := C) k).ι
    let eX : ((linearModuleExtensionByZero (k := k) C S).obj N).obj.obj X ≅
        M.obj.obj X :=
      (J.mapIso e).app X
    exact (eX.isZero_iff).1
      (moduleExtensionByZero_obj_isZero_of_mem (k := k) C S N.obj hX)
  · intro hM
    exact ⟨linearModuleRestrictionToDeletion (k := k) C S M hM,
      ⟨linearModuleRestrictionExtensionIso (k := k) C S M hM⟩⟩

/-- Restriction of a vanishing module preserves pointwise finite dimension
and finite object support. -/
theorem linearModuleRestrictionToDeletion_isFiniteDimensional
    (M : LinearModuleCategory.{u, v, v, v} (C := C) k)
    (hvanish : ModuleVanishesOnDeleted (k := k) C S M.obj)
    (hfinite : IsFiniteDimensionalModule (C := C) k M) :
    IsFiniteDimensionalModule
      (C := DeletionCategory (k := k) C S) k
      (linearModuleRestrictionToDeletion (k := k) C S M hvanish) := by
  constructor
  · intro X
    exact hfinite.1 X.obj.as
  · change Set.Finite
      ((fun X : DeletionCategory (k := k) C S ↦ X.obj.as) ⁻¹'
        moduleSupport k M.obj)
    have hinjective :
        Function.Injective
          (fun X : DeletionCategory (k := k) C S ↦ X.obj.as) := by
      intro X Y hXY
      apply ObjectProperty.FullSubcategory.ext
      apply CategoryTheory.Quotient.ext
      exact hXY
    exact hfinite.2.preimage hinjective.injOn

/-- Descend a finite-dimensional ambient module which vanishes on the
deleted objects. -/
def finiteDimensionalModuleRestrictionToDeletion
    (M : FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k)
    (hM : ModuleVanishesOnDeleted (k := k) C S M.obj.obj) :
    FiniteDimensionalModuleCategory.{u, v, v, v}
      (C := DeletionCategory (k := k) C S) k :=
  ⟨linearModuleRestrictionToDeletion (k := k) C S M.obj hM,
    linearModuleRestrictionToDeletion_isFiniteDimensional
      (k := k) C S M.obj hM M.property⟩

/-- At the finite-dimensional-module level, extension by zero after descent
is isomorphic to the original vanishing module. -/
def finiteDimensionalModuleRestrictionExtensionIso
    (M : FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k)
    (hM : ModuleVanishesOnDeleted (k := k) C S M.obj.obj) :
    (finiteDimensionalModuleExtensionByZero (k := k) C S).obj
        (finiteDimensionalModuleRestrictionToDeletion (k := k) C S M hM) ≅
      M :=
  ObjectProperty.isoMk _
    (linearModuleRestrictionExtensionIso (k := k) C S M.obj hM)

/-- Restriction to the deletion category preserves indecomposability for an
ambient finite module which vanishes on the deleted objects. -/
theorem finiteDimensionalModuleRestrictionToDeletion_indec
    (M : FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k)
    (hM : Indecomposable M)
    (hvanish : ModuleVanishesOnDeleted (k := k) C S M.obj.obj) :
    Indecomposable
      (finiteDimensionalModuleRestrictionToDeletion
        (k := k) C S M hvanish) := by
  let R := finiteDimensionalModuleRestrictionToDeletion
    (k := k) C S M hvanish
  let e := finiteDimensionalModuleRestrictionExtensionIso
    (k := k) C S M hvanish
  have hFR : Indecomposable
      ((finiteDimensionalModuleExtensionByZero (k := k) C S).obj R) :=
    (MagnitudeConjecture.CategoryTheory.indecomposable_iff_of_iso e).2 hM
  exact (finiteDimensionalModuleExtensionByZero_indec_iff
    (k := k) C S R).1 hFR

/-- The essential image of extension by zero consists exactly of the ambient
finite-dimensional modules which vanish on the deleted objects. -/
theorem finiteDimensionalModuleExtensionByZero_essImage_iff
    (M : FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k) :
    (finiteDimensionalModuleExtensionByZero (k := k) C S).essImage M ↔
      ModuleVanishesOnDeleted (k := k) C S M.obj.obj := by
  constructor
  · rintro ⟨N, ⟨e⟩⟩ X hX
    let J := (IsFiniteDimensionalModule.{u, v, v, v} (C := C) k).ι
    let K := (IsLinearModule.{u, v, v, v} (C := C) k).ι
    let eX :
        ((finiteDimensionalModuleExtensionByZero (k := k) C S).obj
            N).obj.obj.obj X ≅ M.obj.obj.obj X :=
      (K.mapIso (J.mapIso e)).app X
    exact (eX.isZero_iff).1
      (moduleExtensionByZero_obj_isZero_of_mem (k := k) C S N.obj.obj hX)
  · intro hM
    exact ⟨finiteDimensionalModuleRestrictionToDeletion
        (k := k) C S M hM,
      ⟨finiteDimensionalModuleRestrictionExtensionIso
        (k := k) C S M hM⟩⟩

/-- Evaluation of a finite-dimensional linear module at an object of the
base category. -/
def finiteDimensionalModuleEvaluation (X : C) :
    FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k ⥤
      ModuleCat.{v} k :=
  (IsFiniteDimensionalModule (C := C) k).ι ⋙
    (IsLinearModule (C := C) k).ι ⋙
      (evaluation C (ModuleCat.{v} k)).obj X

section ExactEvaluation

private abbrev finiteModuleInclusion :=
  (IsFiniteDimensionalModule.{u, v, v, v} (C := C) k).ι

private abbrev linearModuleInclusion :=
  (IsLinearModule.{u, v, v, v} (C := C) k).ι

local instance {M N :
    FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k}
    (f : M ⟶ N) :
    PreservesLimit (parallelPair f 0)
      (finiteModuleInclusion (k := k) C) :=
  (IsFiniteDimensionalModule (C := C) k).preservesKernels_ι f

local instance {M N :
    FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k}
    (f : M ⟶ N) :
    PreservesColimit (parallelPair f 0)
      (finiteModuleInclusion (k := k) C) :=
  (IsFiniteDimensionalModule (C := C) k).preservesCokernels_ι f

local instance {M N : LinearModuleCategory.{u, v, v, v} (C := C) k}
    (f : M ⟶ N) :
    PreservesLimit (parallelPair f 0)
      (linearModuleInclusion (k := k) C) :=
  (IsLinearModule (C := C) k).preservesKernels_ι f

local instance {M N : LinearModuleCategory.{u, v, v, v} (C := C) k}
    (f : M ⟶ N) :
    PreservesColimit (parallelPair f 0)
      (linearModuleInclusion (k := k) C) :=
  (IsLinearModule (C := C) k).preservesCokernels_ι f

local instance : PreservesFiniteLimits
    (finiteModuleInclusion (k := k) C) :=
  (finiteModuleInclusion (k := k) C).preservesFiniteLimits_of_preservesKernels

local instance : PreservesFiniteColimits
    (finiteModuleInclusion (k := k) C) :=
  (finiteModuleInclusion (k := k) C).preservesFiniteColimits_of_preservesCokernels

local instance : PreservesFiniteLimits
    (linearModuleInclusion (k := k) C) :=
  (linearModuleInclusion (k := k) C).preservesFiniteLimits_of_preservesKernels

local instance : PreservesFiniteColimits
    (linearModuleInclusion (k := k) C) :=
  (linearModuleInclusion (k := k) C).preservesFiniteColimits_of_preservesCokernels

local instance : PreservesFiniteLimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C) :=
  comp_preservesFiniteLimits
    (finiteModuleInclusion (k := k) C)
    (linearModuleInclusion (k := k) C)

local instance : PreservesFiniteColimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C) :=
  comp_preservesFiniteColimits
    (finiteModuleInclusion (k := k) C)
    (linearModuleInclusion (k := k) C)

local instance (X : C) : PreservesFiniteLimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C ⋙
        (evaluation C (ModuleCat.{v} k)).obj X) :=
  comp_preservesFiniteLimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C)
    ((evaluation C (ModuleCat.{v} k)).obj X)

local instance (X : C) : PreservesFiniteColimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C ⋙
        (evaluation C (ModuleCat.{v} k)).obj X) :=
  comp_preservesFiniteColimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C)
    ((evaluation C (ModuleCat.{v} k)).obj X)

noncomputable instance finiteDimensionalModuleEvaluation_preservesFiniteLimits
    (X : C) :
    PreservesFiniteLimits
      (finiteDimensionalModuleEvaluation (k := k) C X) := by
  change PreservesFiniteLimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C ⋙
        (evaluation C (ModuleCat.{v} k)).obj X)
  infer_instance

noncomputable instance finiteDimensionalModuleEvaluation_preservesFiniteColimits
    (X : C) :
    PreservesFiniteColimits
      (finiteDimensionalModuleEvaluation (k := k) C X) := by
  change PreservesFiniteColimits
    (finiteModuleInclusion (k := k) C ⋙
      linearModuleInclusion (k := k) C ⋙
        (evaluation C (ModuleCat.{v} k)).obj X)
  infer_instance

end ExactEvaluation

/-- The ambient finite-dimensional modules which vanish on every deleted
object. -/
def finiteModuleVanishesOnDeleted :
    ObjectProperty
      (FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k) :=
  fun M ↦ ModuleVanishesOnDeleted (k := k) C S M.obj.obj

/-- Modules vanishing on the deleted objects are closed under subobjects,
quotients, and extensions inside the ambient finite-dimensional module
category. -/
instance finiteModuleVanishesOnDeleted_isSerreClass :
    (finiteModuleVanishesOnDeleted (k := k) C S).IsSerreClass where
  exists_zero := by
    refine ⟨0, isZero_zero _, ?_⟩
    intro X _
    exact (finiteDimensionalModuleEvaluation (k := k) C X).map_isZero
      (isZero_zero _)
  prop_of_mono f _ hN := by
    intro X hX
    let P : ObjectProperty
        (FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k) :=
      (show ObjectProperty (ModuleCat.{v} k) from IsZero).inverseImage
        (finiteDimensionalModuleEvaluation (k := k) C X)
    exact P.prop_of_mono f (hN X hX)
  prop_of_epi f _ hM := by
    intro X hX
    let P : ObjectProperty
        (FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k) :=
      (show ObjectProperty (ModuleCat.{v} k) from IsZero).inverseImage
        (finiteDimensionalModuleEvaluation (k := k) C X)
    exact P.prop_of_epi f (hM X hX)
  prop_X₂_of_shortExact hT h₁ h₃ := by
    intro X hX
    let P : ObjectProperty
        (FiniteDimensionalModuleCategory.{u, v, v, v} (C := C) k) :=
      (show ObjectProperty (ModuleCat.{v} k) from IsZero).inverseImage
        (finiteDimensionalModuleEvaluation (k := k) C X)
    exact P.prop_X₂_of_shortExact hT (h₁ X hX) (h₃ X hX)

/-- The essential image of finite-dimensional extension by zero is the
vanishing Serre class, as an equality of object properties. -/
theorem finiteDimensionalModuleExtensionByZero_essImage_eq :
    (finiteDimensionalModuleExtensionByZero (k := k) C S).essImage =
      finiteModuleVanishesOnDeleted (k := k) C S := by
  ext M
  exact finiteDimensionalModuleExtensionByZero_essImage_iff
    (k := k) C S M

/-- The essential image of finite-dimensional extension by zero is closed
under subobjects, quotients, and extensions. -/
instance finiteDimensionalModuleExtensionByZero_essImage_isSerreClass :
    (finiteDimensionalModuleExtensionByZero.{u, v, v, v}
      (k := k) C S).essImage.IsSerreClass := by
  simpa only [finiteDimensionalModuleExtensionByZero_essImage_eq
    (k := k) C S] using
      (inferInstance :
        (finiteModuleVanishesOnDeleted (k := k) C S).IsSerreClass)

/-- Local representation-finiteness of finite-support modules passes from an
ambient category to any object-deletion category. -/
theorem isLocallyRepresentationFinite_deletion
    (hlocal : IsLocallyRepresentationFinite (k := k) (C := C)) :
    IsLocallyRepresentationFinite
      (k := k) (C := DeletionCategory (k := k) C S) := by
  classical
  intro X
  let F := finiteDimensionalModuleExtensionByZero (k := k) C S
  obtain ⟨H⟩ := hlocal X.obj.as
  let Occurs (j : Fin H.n) : Prop :=
    ∃ M : FiniteDimensionalModuleCategory.{u, v, v, v}
        (C := DeletionCategory (k := k) C S) k,
      Nonempty (F.obj M ≅ H.obj j)
  let I := {j : Fin H.n // Occurs j}
  let n := Fintype.card I
  let e : Fin n ≃ I := (Fintype.equivFin I).symm
  let chosen (t : Fin n) :
      FiniteDimensionalModuleCategory.{u, v, v, v}
        (C := DeletionCategory (k := k) C S) k :=
    Classical.choose (e t).property
  let chosenIso (t : Fin n) :
      F.obj (chosen t) ≅ H.obj (e t).1 :=
    Classical.choice (Classical.choose_spec (e t).property)
  refine ⟨
    { n := n
      obj := chosen
      indecomposable := ?_
      covers := ?_ }⟩
  · intro t
    have hF : Indecomposable (F.obj (chosen t)) :=
      (MagnitudeConjecture.CategoryTheory.indecomposable_iff_of_iso
        (chosenIso t)).2 (H.indecomposable (e t).1)
    exact
      (finiteDimensionalModuleExtensionByZero_indec_iff
        (k := k) C S (chosen t)).1 hF
  · intro Y hY hYX
    have hFY : Indecomposable (F.obj Y) :=
      finiteDimensionalModuleExtensionByZero_indec (k := k) C S Y hY
    have hFnontrivial :
        Nontrivial ((F.obj Y).obj.obj.obj X.obj.as) := by
      change Nontrivial
        (moduleExtensionByZeroObj (k := k) C S Y.obj.obj X.obj.as)
      let iX := moduleExtensionByZeroObjIsoAt (k := k) C S Y.obj.obj X
      have hinjective : Function.Injective iX.inv.hom :=
        (ModuleCat.mono_iff_injective iX.inv).mp inferInstance
      exact hinjective.nontrivial
    obtain ⟨j, ⟨eY⟩⟩ := H.covers hFY hFnontrivial
    have hj : Occurs j := ⟨Y, ⟨eY.symm⟩⟩
    let q : I := ⟨j, hj⟩
    let t : Fin n := e.symm q
    have hchosen :
        F.obj (chosen t) ≅ H.obj j := by
      simpa [t, q] using chosenIso t
    exact ⟨t, ⟨F.preimageIso (hchosen ≪≫ eY)⟩⟩

end MagnitudeConjecture.ObjectDeletion
