import MagnitudeConjecture.CategoryTheory.ObjectDeletionQuotient
import MagnitudeConjecture.CategoryTheory.LinearIdealQuotientLift

/-!
# Comparing successive and union object deletions

For sets of objects `S` and `T`, the manuscript freely identifies deleting
`S` and then the surviving objects represented by `T` with deleting `S ∪ T`
at once.  This file constructs the canonical linear functor between those
categories.  Its faithfulness is the substantive point: modulo the first
deletion ideal, the extra kernel is generated exactly by the still-surviving
objects in `T`.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open QuotientSubmoduleEquidistribution.CategoricalIdeal

namespace MagnitudeConjecture.ObjectDeletion

universe u v w

variable {k : Type w} [Ring k]
variable (C : Type u) [Category.{v} C] [Preadditive C] [Linear k C]

/-- The ideal generated by the empty set of objects contains only the zero
morphism. -/
theorem mem_ideal_empty_iff {X Y : C} (f : X ⟶ Y) :
    f ∈ (ideal (k := k) C ∅).hom X Y ↔ f = 0 := by
  constructor
  · intro hf
    change f ∈ HomIdeal.generatedHomSubmodule k
      (endomorphismRelations C ∅) X Y at hf
    induction hf using Submodule.span_induction with
    | mem q hq =>
        rcases hq with ⟨A, B, r, hr, a, b, rfl⟩
        exact False.elim hr.2
    | zero => rfl
    | add p q hp hq ihp ihq => simp [ihp, ihq]
    | smul c q hq ihq => simp [ihq]
  · rintro rfl
    exact (ideal (k := k) C ∅).hom X Y |>.zero_mem

/-- Deleting no objects gives a category equivalent to the original one. -/
def emptyDeletionFunctor : C ⥤ DeletionCategory (k := k) C ∅ where
  obj X := ⟨(rawFunctor (k := k) C ∅).obj X, by
    change X ∉ (∅ : Set C)
    exact fun h ↦ h⟩
  map f := ObjectProperty.homMk ((rawFunctor (k := k) C ∅).map f)

noncomputable instance emptyDeletionFunctor_additive :
    (emptyDeletionFunctor (k := k) C).Additive where
  map_add := by
    intro X Y f g
    apply ObjectProperty.hom_ext
    exact (rawFunctor (k := k) C ∅).map_add

noncomputable instance emptyDeletionFunctor_linear :
    (emptyDeletionFunctor (k := k) C).Linear k where
  map_smul := by
    intro X Y f r
    apply ObjectProperty.hom_ext
    exact (rawFunctor (k := k) C ∅).map_smul r f

noncomputable instance emptyDeletionFunctor_full :
    (emptyDeletionFunctor (k := k) C).Full where
  map_surjective {X Y} f := by
    obtain ⟨g, hg⟩ := (rawFunctor (k := k) C ∅).map_surjective f.hom
    refine ⟨g, ?_⟩
    apply ObjectProperty.hom_ext
    exact hg

noncomputable instance emptyDeletionFunctor_faithful :
    (emptyDeletionFunctor (k := k) C).Faithful where
  map_injective {X Y} := by
    intro f g hfg
    have hfg' : (rawFunctor (k := k) C ∅).map f =
        (rawFunctor (k := k) C ∅).map g := by
      exact congrArg (fun q ↦ q.hom) hfg
    have hzero : (rawFunctor (k := k) C ∅).map (f - g) = 0 := by
      rw [(rawFunctor (k := k) C ∅).map_sub, hfg', sub_self]
    have hmem := ((ideal (k := k) C ∅).map_eq_zero_iff (f - g)).1 hzero
    exact sub_eq_zero.mp ((mem_ideal_empty_iff (k := k) C (f - g)).1 hmem)

noncomputable instance emptyDeletionFunctor_essSurj :
    (emptyDeletionFunctor (k := k) C).EssSurj where
  mem_essImage Y := by
    refine ⟨Y.obj.as, ⟨ObjectProperty.isoMk _ (eqToIso ?_)⟩⟩
    apply CategoryTheory.Quotient.ext
    rfl

/-- Canonical equivalence between the ambient category and deletion by the
empty object set. -/
noncomputable def emptyDeletionEquivalence :
    C ≌ DeletionCategory (k := k) C ∅ := by
  letI : (emptyDeletionFunctor (k := k) C).IsEquivalence := {}
  exact (emptyDeletionFunctor (k := k) C).asEquivalence

/-- Equal deleted-object sets give definitionally the same deletion category,
after transporting along the equality. -/
noncomputable def deletionEquivalenceOfEq {S T : Set C} (h : S = T) :
    DeletionCategory (k := k) C S ≌ DeletionCategory (k := k) C T := by
  subst T
  exact CategoryTheory.Equivalence.refl

noncomputable instance deletionEquivalenceOfEq_functor_additive
    {S T : Set C} (h : S = T) :
    (deletionEquivalenceOfEq (k := k) C h).functor.Additive := by
  subst T
  change (𝟭 (DeletionCategory (k := k) C S)).Additive
  infer_instance

noncomputable instance deletionEquivalenceOfEq_functor_linear
    {S T : Set C} (h : S = T) :
    (deletionEquivalenceOfEq (k := k) C h).functor.Linear k := by
  subst T
  change (𝟭 (DeletionCategory (k := k) C S)).Linear k
  infer_instance

/-- The equivalence attached to equality of deleted sets is literally
bijective on objects. -/
theorem deletionEquivalenceOfEq_functor_obj_bijective {S T : Set C}
    (h : S = T) :
    Function.Bijective
      (deletionEquivalenceOfEq (k := k) C h).functor.obj := by
  subst T
  exact Function.bijective_id

@[simp]
theorem deletionEquivalenceOfEq_functor_obj_as {S T : Set C}
    (h : S = T) (X : DeletionCategory (k := k) C S) :
    ((deletionEquivalenceOfEq (k := k) C h).functor.obj X).obj.as =
      X.obj.as := by
  subst T
  rfl

/-- Inclusion of deleted object sets induces inclusion of deletion ideals. -/
theorem ideal_mono {S T : Set C} (hST : S ⊆ T)
    {X Y : C} {f : X ⟶ Y}
    (hf : f ∈ (ideal (k := k) C S).hom X Y) :
    f ∈ (ideal (k := k) C T).hom X Y := by
  apply HomIdeal.linearSpan_le
    (endomorphismRelations C S) (ideal (k := k) C T) ?_ hf
  intro U V r hr
  rcases hr with ⟨rfl, hU⟩
  exact endomorphism_mem_ideal (k := k) C T (hST hU) r

/-- The larger raw quotient kills the smaller deletion ideal. -/
theorem rawFunctorOfLE_isKilledBy {S T : Set C} (hST : S ⊆ T) :
    (ideal (k := k) C S).IsKilledBy (rawFunctor (k := k) C T) := by
  intro X Y f hf
  exact ((ideal (k := k) C T).map_eq_zero_iff f).2
    (ideal_mono (k := k) C hST hf)

/-- The canonical functor from a smaller raw deletion quotient to a larger
one. -/
def rawFunctorOfLE {S T : Set C} (hST : S ⊆ T) :
    RawCategory (k := k) C S ⥤ RawCategory (k := k) C T :=
  (ideal (k := k) C S).quotientLift (rawFunctor (k := k) C T)
    (rawFunctorOfLE_isKilledBy (k := k) C hST)

noncomputable instance rawFunctorOfLE_additive {S T : Set C}
    (hST : S ⊆ T) : (rawFunctorOfLE (k := k) C hST).Additive :=
  HomIdeal.quotientLift_additive (ideal (k := k) C S)
    (rawFunctor (k := k) C T)
    (rawFunctorOfLE_isKilledBy (k := k) C hST)

noncomputable instance rawFunctorOfLE_linear {S T : Set C}
    (hST : S ⊆ T) : (rawFunctorOfLE (k := k) C hST).Linear k :=
  HomIdeal.quotientLift_linear (ideal (k := k) C S)
    (rawFunctor (k := k) C T)
    (rawFunctorOfLE_isKilledBy (k := k) C hST)

noncomputable instance rawFunctorOfLE_full {S T : Set C}
    (hST : S ⊆ T) : (rawFunctorOfLE (k := k) C hST).Full :=
  HomIdeal.quotientLift_full (ideal (k := k) C S)
    (rawFunctor (k := k) C T)
    (rawFunctorOfLE_isKilledBy (k := k) C hST)

@[simp]
theorem rawFunctorOfLE_map_rawFunctor {S T : Set C} (hST : S ⊆ T)
    {X Y : C} (f : X ⟶ Y) :
    (rawFunctorOfLE (k := k) C hST).map
      ((rawFunctor (k := k) C S).map f) =
        (rawFunctor (k := k) C T).map f :=
  rfl

/-- After deleting `S`, these are the surviving objects represented by `T`.
Objects lying in `S ∩ T` are already absent. -/
def AdditionalDeleted (S T : Set C) :
    Set (DeletionCategory (k := k) C S) :=
  fun X ↦ X.obj.as ∈ T

/-- The result of deleting `S` and then the surviving representatives of
`T`. -/
abbrev IteratedDeletionCategory (S T : Set C) :=
  DeletionCategory (k := k) (DeletionCategory (k := k) C S)
    (AdditionalDeleted (k := k) C S T)

/-- A surviving ambient object, regarded as an object of `C/(S)`. -/
def survivingObj (S : Set C) {X : C} (hX : X ∉ S) :
    DeletionCategory (k := k) C S :=
  ⟨(rawFunctor (k := k) C S).obj X, hX⟩

/-- The image in `C/(S)` of an ambient map between surviving objects. -/
def survivingMap (S : Set C) {X Y : C}
    (hX : X ∉ S) (hY : Y ∉ S) (f : X ⟶ Y) :
    survivingObj (k := k) C S hX ⟶ survivingObj (k := k) C S hY :=
  ObjectProperty.homMk ((rawFunctor (k := k) C S).map f)

@[simp]
theorem survivingMap_zero (S : Set C) {X Y : C}
    (hX : X ∉ S) (hY : Y ∉ S) :
    survivingMap (k := k) C S hX hY (0 : X ⟶ Y) = 0 := by
  apply ObjectProperty.hom_ext
  change (rawFunctor (k := k) C S).map (0 : X ⟶ Y) = 0
  exact (rawFunctor (k := k) C S).map_zero X Y

@[simp]
theorem survivingMap_add (S : Set C) {X Y : C}
    (hX : X ∉ S) (hY : Y ∉ S) (f g : X ⟶ Y) :
    survivingMap (k := k) C S hX hY (f + g) =
      survivingMap (k := k) C S hX hY f +
        survivingMap (k := k) C S hX hY g := by
  apply ObjectProperty.hom_ext
  exact (rawFunctor (k := k) C S).map_add

@[simp]
theorem survivingMap_smul (S : Set C) {X Y : C}
    (hX : X ∉ S) (hY : Y ∉ S) (c : k) (f : X ⟶ Y) :
    survivingMap (k := k) C S hX hY (c • f) =
      c • survivingMap (k := k) C S hX hY f := by
  apply ObjectProperty.hom_ext
  exact (rawFunctor (k := k) C S).map_smul c f

@[simp]
theorem survivingMap_comp (S : Set C) {X Y Z : C}
    (hX : X ∉ S) (hY : Y ∉ S) (hZ : Z ∉ S)
    (f : X ⟶ Y) (g : Y ⟶ Z) :
    survivingMap (k := k) C S hX hZ (f ≫ g) =
      survivingMap (k := k) C S hX hY f ≫
        survivingMap (k := k) C S hY hZ g := by
  apply ObjectProperty.hom_ext
  exact (rawFunctor (k := k) C S).map_comp f g

/-- If an ambient map belongs to the union deletion ideal, its image after
deleting `S` belongs to the ideal generated by the still-surviving objects
represented by `T`. -/
theorem survivingMap_mem_additionalIdeal_of_mem_unionIdeal
    (S T : Set C) {X Y : C} (hX : X ∉ S) (hY : Y ∉ S)
    {f : X ⟶ Y} (hf : f ∈ (ideal (k := k) C (S ∪ T)).hom X Y) :
    survivingMap (k := k) C S hX hY f ∈
      (ideal (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)).hom
          (survivingObj (k := k) C S hX)
          (survivingObj (k := k) C S hY) := by
  change f ∈ HomIdeal.generatedHomSubmodule k
    (endomorphismRelations C (S ∪ T)) X Y at hf
  induction hf using Submodule.span_induction with
  | mem q hq =>
      rcases hq with ⟨A, B, r, hr, a, b, rfl⟩
      rcases hr with ⟨rfl, hA⟩
      by_cases hAS : A ∈ S
      · have hz : survivingMap (k := k) C S hX hY
            (a ≫ r ≫ b) = 0 := by
          apply ObjectProperty.hom_ext
          change (rawFunctor (k := k) C S).map (a ≫ r ≫ b) = 0
          rw [Functor.map_comp, Functor.map_comp]
          have hrzero : (rawFunctor (k := k) C S).map r = 0 :=
            ((ideal (k := k) C S).map_eq_zero_iff r).2
              (endomorphism_mem_ideal (k := k) C S hAS r)
          rw [hrzero]
          simp
        rw [hz]
        exact (ideal (k := k) (DeletionCategory (k := k) C S)
          (AdditionalDeleted (k := k) C S T)).hom _ _ |>.zero_mem
      · have hAT : A ∈ T := hA.resolve_left hAS
        have hmem : survivingObj (k := k) C S hAS ∈
            AdditionalDeleted (k := k) C S T := hAT
        have hcomp := comp_mem_ideal (k := k)
          (DeletionCategory (k := k) C S)
          (AdditionalDeleted (k := k) C S T) hmem
          (survivingMap (k := k) C S hX hAS a)
          (survivingMap (k := k) C S hAS hY (r ≫ b))
        rw [survivingMap_comp]
        exact hcomp
  | zero =>
      rw [survivingMap_zero]
      exact (ideal (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)).hom
          (survivingObj (k := k) C S hX)
          (survivingObj (k := k) C S hY) |>.zero_mem
  | add p q hp hq ihp ihq =>
      rw [survivingMap_add]
      exact (ideal (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)).hom
          (survivingObj (k := k) C S hX)
          (survivingObj (k := k) C S hY) |>.add_mem ihp ihq
  | smul c q hq ihq =>
      rw [survivingMap_smul]
      exact (ideal (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)).smul_mem c ihq

/-- The first deletion category maps canonically to the raw quotient by
`S ∪ T`. -/
abbrev firstDeletionToRawUnion (S T : Set C) :
    DeletionCategory (k := k) C S ⥤ RawCategory (k := k) C (S ∪ T) :=
  (IsSurvivingRaw (k := k) C S).ι ⋙
    rawFunctorOfLE (k := k) C Set.subset_union_left

/-- The canonical map to the union quotient kills the objects represented by
`T` after the first deletion. -/
theorem firstDeletionToRawUnion_isKilledBy (S T : Set C) :
    (ideal (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)).IsKilledBy
        (firstDeletionToRawUnion (k := k) C S T) := by
  intro X Y f hf
  have hk : f ∈
      (HomIdeal.functorKernel (k := k)
        (firstDeletionToRawUnion (k := k) C S T)).hom X Y := by
    apply HomIdeal.linearSpan_le
      (endomorphismRelations (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T))
      (HomIdeal.functorKernel (k := k)
        (firstDeletionToRawUnion (k := k) C S T))
      ?_ hf
    intro U V r hr
    rcases hr with ⟨rfl, hU⟩
    change (rawFunctorOfLE (k := k) C Set.subset_union_left).map r.hom = 0
    obtain ⟨q, hq⟩ :=
      (rawFunctor (k := k) C S).map_surjective r.hom
    rw [← hq]
    change (rawFunctor (k := k) C (S ∪ T)).map q = 0
    apply ((ideal (k := k) C (S ∪ T)).map_eq_zero_iff q).2
    exact endomorphism_mem_ideal (k := k) C (S ∪ T)
      (Or.inr hU) q
  exact (HomIdeal.mem_functorKernel_iff
    (k := k) (firstDeletionToRawUnion (k := k) C S T) f).1 hk

/-- No additional morphisms vanish in the union quotient: the kernel after
the first deletion is contained in the ideal generated by surviving
representatives of `T`. -/
theorem firstDeletionToRawUnion_kernel_le (S T : Set C)
    {X Y : DeletionCategory (k := k) C S} {f : X ⟶ Y}
    (hf : (firstDeletionToRawUnion (k := k) C S T).map f = 0) :
    f ∈ (ideal (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)).hom X Y := by
  obtain ⟨q, hq⟩ :=
    (rawFunctor (k := k) C S).map_surjective f.hom
  have hqzero : (rawFunctor (k := k) C (S ∪ T)).map q = 0 := by
    change (rawFunctorOfLE (k := k) C Set.subset_union_left).map f.hom = 0 at hf
    rw [← hq] at hf
    exact hf
  have hqmem : q ∈ (ideal (k := k) C (S ∪ T)).hom X.obj.as Y.obj.as :=
    ((ideal (k := k) C (S ∪ T)).map_eq_zero_iff q).1 hqzero
  have hmapped := survivingMap_mem_additionalIdeal_of_mem_unionIdeal
    (k := k) C S T X.property Y.property hqmem
  have hEq : survivingMap (k := k) C S X.property Y.property q = f := by
    apply ObjectProperty.hom_ext
    exact hq
  rw [← hEq]
  exact hmapped

/-- The canonical functor from the raw iterated quotient to the raw quotient
by the union. -/
def iteratedRawToRawUnion (S T : Set C) :
    RawCategory (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T) ⥤
      RawCategory (k := k) C (S ∪ T) :=
  (ideal (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)).quotientLift
    (firstDeletionToRawUnion (k := k) C S T)
    (firstDeletionToRawUnion_isKilledBy (k := k) C S T)

noncomputable instance iteratedRawToRawUnion_additive (S T : Set C) :
    (iteratedRawToRawUnion (k := k) C S T).Additive :=
  HomIdeal.quotientLift_additive
    (ideal (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T))
    (firstDeletionToRawUnion (k := k) C S T)
    (firstDeletionToRawUnion_isKilledBy (k := k) C S T)

noncomputable instance iteratedRawToRawUnion_linear (S T : Set C) :
    (iteratedRawToRawUnion (k := k) C S T).Linear k :=
  HomIdeal.quotientLift_linear
    (ideal (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T))
    (firstDeletionToRawUnion (k := k) C S T)
    (firstDeletionToRawUnion_isKilledBy (k := k) C S T)

noncomputable instance iteratedRawToRawUnion_full (S T : Set C) :
    (iteratedRawToRawUnion (k := k) C S T).Full :=
  HomIdeal.quotientLift_full
    (ideal (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T))
    (firstDeletionToRawUnion (k := k) C S T)
    (firstDeletionToRawUnion_isKilledBy (k := k) C S T)

noncomputable instance iteratedRawToRawUnion_faithful (S T : Set C) :
    (iteratedRawToRawUnion (k := k) C S T).Faithful :=
  (ideal (k := k) (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)).quotientLift_faithful
    (firstDeletionToRawUnion (k := k) C S T)
    (firstDeletionToRawUnion_isKilledBy (k := k) C S T)
    (firstDeletionToRawUnion_kernel_le (k := k) C S T)

/-- The canonical linear functor from successive deletion to deletion by the
union. -/
def iteratedToUnionFunctor (S T : Set C) :
    IteratedDeletionCategory (k := k) C S T ⥤
      DeletionCategory (k := k) C (S ∪ T) :=
  (IsSurvivingRaw (k := k) C (S ∪ T)).lift
    ((IsSurvivingRaw (k := k)
      (DeletionCategory (k := k) C S)
      (AdditionalDeleted (k := k) C S T)).ι ⋙
        iteratedRawToRawUnion (k := k) C S T)
    (fun X ↦ by
      change X.obj.as.obj.as ∉ S ∪ T
      rintro (hS | hT)
      · exact X.obj.as.property hS
      · exact X.property hT)

noncomputable instance iteratedToUnionFunctor_additive (S T : Set C) :
    (iteratedToUnionFunctor (k := k) C S T).Additive where
  map_add := by
    intro X Y f g
    apply ObjectProperty.hom_ext
    exact (iteratedRawToRawUnion (k := k) C S T).map_add

noncomputable instance iteratedToUnionFunctor_linear (S T : Set C) :
    (iteratedToUnionFunctor (k := k) C S T).Linear k where
  map_smul := by
    intro X Y f r
    apply ObjectProperty.hom_ext
    exact (iteratedRawToRawUnion (k := k) C S T).map_smul r f.hom

noncomputable instance iteratedToUnionFunctor_full (S T : Set C) :
    (iteratedToUnionFunctor (k := k) C S T).Full := by
  dsimp only [iteratedToUnionFunctor]
  infer_instance

noncomputable instance iteratedToUnionFunctor_faithful (S T : Set C) :
    (iteratedToUnionFunctor (k := k) C S T).Faithful := by
  dsimp only [iteratedToUnionFunctor]
  infer_instance

@[simp]
theorem iteratedToUnionFunctor_obj_as (S T : Set C)
    (X : IteratedDeletionCategory (k := k) C S T) :
    ((iteratedToUnionFunctor (k := k) C S T).obj X).obj.as =
      X.obj.as.obj.as :=
  rfl

noncomputable instance iteratedToUnionFunctor_essSurj (S T : Set C) :
    (iteratedToUnionFunctor (k := k) C S T).EssSurj where
  mem_essImage Y := by
    have hS : Y.obj.as ∉ S := fun h ↦ Y.property (Or.inl h)
    have hT : Y.obj.as ∉ T := fun h ↦ Y.property (Or.inr h)
    let X₁ := survivingObj (k := k) C S hS
    have hX₁ : X₁ ∉ AdditionalDeleted (k := k) C S T := hT
    let X₂ : IteratedDeletionCategory (k := k) C S T :=
      ⟨(rawFunctor (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)).obj X₁, hX₁⟩
    refine ⟨X₂, ⟨ObjectProperty.isoMk _ (eqToIso ?_)⟩⟩
    apply CategoryTheory.Quotient.ext
    rfl

/-- Successive object deletion is canonically equivalent to deletion by the
union. -/
noncomputable def iteratedDeletionEquivalence (S T : Set C) :
    IteratedDeletionCategory (k := k) C S T ≌
      DeletionCategory (k := k) C (S ∪ T) := by
  letI : (iteratedToUnionFunctor (k := k) C S T).IsEquivalence := {}
  exact (iteratedToUnionFunctor (k := k) C S T).asEquivalence

noncomputable instance iteratedDeletionEquivalence_functor_additive
    (S T : Set C) :
    (iteratedDeletionEquivalence (k := k) C S T).functor.Additive := by
  change (iteratedToUnionFunctor (k := k) C S T).Additive
  infer_instance

noncomputable instance iteratedDeletionEquivalence_functor_linear
    (S T : Set C) :
    (iteratedDeletionEquivalence (k := k) C S T).functor.Linear k := by
  change (iteratedToUnionFunctor (k := k) C S T).Linear k
  infer_instance

/-- The canonical equivalence from successive deletion to union deletion is
literally bijective on objects, not merely essentially surjective. -/
theorem iteratedDeletionEquivalence_functor_obj_bijective (S T : Set C) :
    Function.Bijective
      (iteratedDeletionEquivalence (k := k) C S T).functor.obj := by
  constructor
  · intro X Y hXY
    apply ObjectProperty.FullSubcategory.ext
    apply CategoryTheory.Quotient.ext
    apply ObjectProperty.FullSubcategory.ext
    apply CategoryTheory.Quotient.ext
    exact congrArg (fun Z ↦ Z.obj.as) hXY
  · intro Y
    have hS : Y.obj.as ∉ S := fun h ↦ Y.property (Or.inl h)
    have hT : Y.obj.as ∉ T := fun h ↦ Y.property (Or.inr h)
    let X₁ := survivingObj (k := k) C S hS
    have hX₁ : X₁ ∉ AdditionalDeleted (k := k) C S T := hT
    let X₂ : IteratedDeletionCategory (k := k) C S T :=
      ⟨(rawFunctor (k := k) (DeletionCategory (k := k) C S)
        (AdditionalDeleted (k := k) C S T)).obj X₁, hX₁⟩
    refine ⟨X₂, ?_⟩
    apply ObjectProperty.FullSubcategory.ext
    apply CategoryTheory.Quotient.ext
    rfl

/-- The literal object bijection underlying successive deletion. -/
noncomputable def iteratedDeletionObjectEquiv (S T : Set C) :
    IteratedDeletionCategory (k := k) C S T ≃
      DeletionCategory (k := k) C (S ∪ T) :=
  Equiv.ofBijective
    (iteratedDeletionEquivalence (k := k) C S T).functor.obj
    (iteratedDeletionEquivalence_functor_obj_bijective (k := k) C S T)

@[simp]
theorem iteratedDeletionObjectEquiv_apply (S T : Set C)
    (X : IteratedDeletionCategory (k := k) C S T) :
    iteratedDeletionObjectEquiv (k := k) C S T X =
      (iteratedDeletionEquivalence (k := k) C S T).functor.obj X :=
  rfl

section SingletonChangeOfBase

universe u₂ v₂

variable {D : Type u₂} [Category.{v₂} D] [Preadditive D] [Linear k D]

/-- A linear equivalence carries the ideal generated by one object into the
ideal generated by its image. -/
theorem map_mem_singleton_ideal
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) {X Y : C} {f : X ⟶ Y}
    (hf : f ∈ (ideal (k := k) C ({q} : Set C)).hom X Y) :
    e.functor.map f ∈
      (ideal (k := k) D ({e.functor.obj q} : Set D)).hom
        (e.functor.obj X) (e.functor.obj Y) := by
  change f ∈ HomIdeal.generatedHomSubmodule k
    (endomorphismRelations C ({q} : Set C)) X Y at hf
  induction hf using Submodule.span_induction with
  | mem g hg =>
      rcases hg with ⟨A, B, r, ⟨rfl, hA⟩, a, b, rfl⟩
      have hAq : A = q := Set.mem_singleton_iff.mp hA
      subst A
      rw [e.functor.map_comp, e.functor.map_comp]
      exact comp_mem_ideal (k := k) D ({e.functor.obj q} : Set D)
        (Set.mem_singleton _) _ _
  | zero =>
      rw [e.functor.map_zero]
      exact (ideal (k := k) D ({e.functor.obj q} : Set D)).hom
        (e.functor.obj X) (e.functor.obj Y) |>.zero_mem
  | add g h _ _ hg hh =>
      rw [e.functor.map_add]
      exact (ideal (k := k) D ({e.functor.obj q} : Set D)).hom
        (e.functor.obj X) (e.functor.obj Y) |>.add_mem hg hh
  | smul r g _ hg =>
      rw [e.functor.map_smul]
      exact HomIdeal.smul_mem
        (ideal (k := k) D ({e.functor.obj q} : Set D)) r hg

/-- For an equivalence, membership in a singleton-generated deletion ideal
is also reflected from the image category. -/
theorem mem_singleton_ideal_of_map
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) {X Y : C} {f : X ⟶ Y}
    (hf : e.functor.map f ∈
      (ideal (k := k) D ({e.functor.obj q} : Set D)).hom
        (e.functor.obj X) (e.functor.obj Y)) :
    f ∈ (ideal (k := k) C ({q} : Set C)).hom X Y := by
  change e.functor.map f ∈
    HomIdeal.generatedHomSubmodule k
      (endomorphismRelations D ({e.functor.obj q} : Set D))
      (e.functor.obj X) (e.functor.obj Y) at hf
  have hpre (g : e.functor.obj X ⟶ e.functor.obj Y)
      (hg : g ∈ HomIdeal.generatedHomSubmodule k
        (endomorphismRelations D ({e.functor.obj q} : Set D))
        (e.functor.obj X) (e.functor.obj Y)) :
      e.functor.preimage g ∈
        (ideal (k := k) C ({q} : Set C)).hom X Y := by
    induction hg using Submodule.span_induction with
    | mem g hg =>
        rcases hg with ⟨A, B, r, ⟨rfl, hA⟩, a, b, rfl⟩
        have hAq : A = e.functor.obj q := Set.mem_singleton_iff.mp hA
        subst A
        rw [show e.functor.preimage (a ≫ r ≫ b) =
            e.functor.preimage a ≫ e.functor.preimage r ≫
              e.functor.preimage b by
          apply e.functor.map_injective
          simp]
        exact comp_mem_ideal (k := k) C ({q} : Set C)
          (Set.mem_singleton q) _ _
    | zero =>
        rw [show e.functor.preimage 0 = 0 by
          apply e.functor.map_injective
          simp]
        exact (ideal (k := k) C ({q} : Set C)).hom X Y |>.zero_mem
    | add g h _ _ hg hh =>
        rw [show e.functor.preimage (g + h) =
            e.functor.preimage g + e.functor.preimage h by
          apply e.functor.map_injective
          simp only [Functor.map_preimage, Functor.map_add]]
        exact (ideal (k := k) C ({q} : Set C)).hom X Y |>.add_mem hg hh
    | smul r g _ hg =>
        rw [show e.functor.preimage (r • g) =
            r • e.functor.preimage g by
          apply e.functor.map_injective
          simp only [Functor.map_preimage, Functor.map_smul]]
        exact HomIdeal.smul_mem
          (ideal (k := k) C ({q} : Set C)) r hg
  simpa using hpre (e.functor.map f) hf

/-- The composite from the source category to the raw quotient by the image
object kills the source singleton deletion ideal. -/
theorem singletonIdeal_isKilledBy
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) :
    (ideal (k := k) C ({q} : Set C)).IsKilledBy
      (e.functor ⋙ rawFunctor (k := k) D ({e.functor.obj q} : Set D)) := by
  intro X Y f hf
  exact ((ideal (k := k) D ({e.functor.obj q} : Set D)).map_eq_zero_iff
    (e.functor.map f)).2
      (map_mem_singleton_ideal (k := k) (C := C) e q hf)

/-- The induced functor between the two raw singleton-deletion quotients. -/
def rawSingletonDeletionMapFunctor
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) :
    RawCategory (k := k) C ({q} : Set C) ⥤
      RawCategory (k := k) D ({e.functor.obj q} : Set D) :=
  (ideal (k := k) C ({q} : Set C)).quotientLift
    (e.functor ⋙ rawFunctor (k := k) D ({e.functor.obj q} : Set D))
    (singletonIdeal_isKilledBy (k := k) (C := C) e q)

noncomputable instance rawSingletonDeletionMapFunctor_additive
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) :
    (rawSingletonDeletionMapFunctor (k := k) (C := C) e q).Additive := by
  unfold rawSingletonDeletionMapFunctor
  infer_instance

noncomputable instance rawSingletonDeletionMapFunctor_linear
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) :
    (rawSingletonDeletionMapFunctor (k := k) (C := C) e q).Linear k := by
  unfold rawSingletonDeletionMapFunctor
  infer_instance

noncomputable instance rawSingletonDeletionMapFunctor_full
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) :
    (rawSingletonDeletionMapFunctor (k := k) (C := C) e q).Full := by
  unfold rawSingletonDeletionMapFunctor
  infer_instance

noncomputable instance rawSingletonDeletionMapFunctor_faithful
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (q : C) :
    (rawSingletonDeletionMapFunctor (k := k) (C := C) e q).Faithful := by
  apply HomIdeal.quotientLift_faithful
  intro X Y f hf
  apply mem_singleton_ideal_of_map (k := k) (C := C) e q
  exact ((ideal (k := k) D ({e.functor.obj q} : Set D)).map_eq_zero_iff
    (e.functor.map f)).1 hf

/-- Restrict singleton-deletion change of base to the surviving objects. -/
def singletonDeletionMapFunctor
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    DeletionCategory (k := k) C ({q} : Set C) ⥤
      DeletionCategory (k := k) D ({e.functor.obj q} : Set D) where
  obj X := ⟨(rawSingletonDeletionMapFunctor
      (k := k) (C := C) e q).obj X.obj, by
    intro h
    have heq : e.functor.obj X.obj.as = e.functor.obj q :=
      Set.mem_singleton_iff.mp h
    have hXq : X.obj.as = q := hobj.1 heq
    exact X.property (Set.mem_singleton_iff.mpr hXq)⟩
  map f := ObjectProperty.homMk
    ((rawSingletonDeletionMapFunctor (k := k) (C := C) e q).map f.hom)

noncomputable instance singletonDeletionMapFunctor_additive
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    (singletonDeletionMapFunctor (k := k) (C := C) e hobj q).Additive where
  map_add := by
    intro X Y f g
    apply ObjectProperty.hom_ext
    exact (rawSingletonDeletionMapFunctor
      (k := k) (C := C) e q).map_add

noncomputable instance singletonDeletionMapFunctor_linear
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    (singletonDeletionMapFunctor (k := k) (C := C) e hobj q).Linear k where
  map_smul := by
    intro X Y f r
    apply ObjectProperty.hom_ext
    exact (rawSingletonDeletionMapFunctor
      (k := k) (C := C) e q).map_smul r f.hom

noncomputable instance singletonDeletionMapFunctor_full
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    (singletonDeletionMapFunctor (k := k) (C := C) e hobj q).Full where
  map_surjective {X Y} f := by
    obtain ⟨g, hg⟩ :=
      (rawSingletonDeletionMapFunctor
        (k := k) (C := C) e q).map_surjective f.hom
    refine ⟨ObjectProperty.homMk g, ?_⟩
    apply ObjectProperty.hom_ext
    exact hg

noncomputable instance singletonDeletionMapFunctor_faithful
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    (singletonDeletionMapFunctor (k := k) (C := C) e hobj q).Faithful where
  map_injective {X Y} f g hfg := by
    apply ObjectProperty.hom_ext
    apply (rawSingletonDeletionMapFunctor
      (k := k) (C := C) e q).map_injective
    exact congrArg (fun h ↦ h.hom) hfg

/-- Every target survivor is represented by an inverse image survivor. -/
theorem singletonDeletionMapFunctor_essSurj
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    (singletonDeletionMapFunctor
      (k := k) (C := C) e hobj q).EssSurj where
  mem_essImage Y := by
    obtain ⟨X₀, hX₀eq⟩ := hobj.2 Y.obj.as
    have hX₀ : X₀ ∉ ({q} : Set C) := by
      intro h
      have hXq : X₀ = q := Set.mem_singleton_iff.mp h
      have heq : e.functor.obj q = Y.obj.as := hXq ▸ hX₀eq
      exact Y.property (Set.mem_singleton_iff.mpr heq.symm)
    let X : DeletionCategory (k := k) C ({q} : Set C) :=
      ⟨(rawFunctor (k := k) C ({q} : Set C)).obj X₀, hX₀⟩
    refine ⟨X, ⟨ObjectProperty.isoMk _ ?_⟩⟩
    exact eqToIso (by
      apply CategoryTheory.Quotient.ext
      exact hX₀eq)

/-- Deleting one object commutes with an additive linear equivalence whose
forward object map is a literal bijection. -/
noncomputable def singletonDeletionEquivalence
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    DeletionCategory (k := k) C ({q} : Set C) ≌
      DeletionCategory (k := k) D ({e.functor.obj q} : Set D) := by
  letI : (singletonDeletionMapFunctor
      (k := k) (C := C) e hobj q).EssSurj :=
    singletonDeletionMapFunctor_essSurj
      (k := k) (C := C) e hobj q
  letI : (singletonDeletionMapFunctor
      (k := k) (C := C) e hobj q).IsEquivalence := {}
  exact (singletonDeletionMapFunctor
    (k := k) (C := C) e hobj q).asEquivalence

noncomputable instance singletonDeletionEquivalence_functor_additive
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    (singletonDeletionEquivalence
      (k := k) (C := C) e hobj q).functor.Additive := by
  change (singletonDeletionMapFunctor
    (k := k) (C := C) e hobj q).Additive
  infer_instance

noncomputable instance singletonDeletionEquivalence_functor_linear
    (e : C ≌ D) [e.functor.Additive] [e.functor.Linear k]
    (hobj : Function.Bijective e.functor.obj) (q : C) :
    (singletonDeletionEquivalence
      (k := k) (C := C) e hobj q).functor.Linear k := by
  change (singletonDeletionMapFunctor
    (k := k) (C := C) e hobj q).Linear k
  infer_instance

end SingletonChangeOfBase

end MagnitudeConjecture.ObjectDeletion
