import QuotientSubmoduleEquidistribution.CategoryTheory.LinearGeneratedHomIdeal
import Mathlib.CategoryTheory.ObjectProperty.FullSubcategory
import Mathlib.CategoryTheory.Limits.Shapes.ZeroObjects

/-!
# Quotienting a linear category by deleted objects

For a set `S` of objects of a linear category `C`, the manuscript writes
`C/(S)` for the category whose objects are those outside `S` and whose Hom
spaces are quotiented by the ideal of maps factoring through finite direct
sums of objects of `S`.

The ideal below is generated by all endomorphisms of objects in `S`.
Equivalently it is generated by their identity morphisms, so its elements are
finite linear combinations of maps factoring through deleted objects.  We
first form the raw Hom-ideal quotient and then take the full subcategory on
the surviving objects; deleted objects therefore do not remain as a family of
isomorphic zero objects.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory CategoryTheory.Limits
open QuotientSubmoduleEquidistribution.CategoricalIdeal

namespace MagnitudeConjecture.ObjectDeletion

universe u v w

variable {k : Type w} [Ring k]
variable (C : Type u) [Category.{v} C] [Preadditive C] [Linear k C]

/-- Relation generators supported at a deleted object.  Taking all
endomorphisms rather than only the identity gives the same generated ideal
and avoids transporting identities across object equalities. -/
def endomorphismRelations (S : Set C) (X Y : C) : Set (X ⟶ Y) :=
  fun _ ↦ X = Y ∧ X ∈ S

/-- The two-sided linear Hom ideal generated by the deleted objects. -/
def ideal (S : Set C) : HomIdeal C :=
  HomIdeal.linearSpan k (endomorphismRelations C S)

/-- Every endomorphism of a deleted object belongs to the deletion ideal. -/
theorem endomorphism_mem_ideal (S : Set C) {X : C} (hX : X ∈ S)
    (f : X ⟶ X) :
    f ∈ (ideal (k := k) C S).hom X X :=
  HomIdeal.relation_mem_linearSpan (endomorphismRelations C S) ⟨rfl, hX⟩

/-- In particular, the identity of a deleted object belongs to the deletion
ideal. -/
theorem id_mem_ideal (S : Set C) {X : C} (hX : X ∈ S) :
    𝟙 X ∈ (ideal (k := k) C S).hom X X :=
  endomorphism_mem_ideal (k := k) C S hX (𝟙 X)

/-- Every map which factors through one deleted object belongs to the
deletion ideal. -/
theorem comp_mem_ideal (S : Set C) {X Y Z : C} (hZ : Z ∈ S)
    (a : X ⟶ Z) (b : Z ⟶ Y) :
    a ≫ b ∈ (ideal (k := k) C S).hom X Y := by
  have hid := id_mem_ideal (k := k) C S hZ
  have hpre := (ideal (k := k) C S).precomp a hid
  have hpost := (ideal (k := k) C S).postcomp b hpre
  simpa only [Category.comp_id] using hpost

/-- The raw quotient in which deleted objects are still present as zero
objects. -/
abbrev RawCategory (S : Set C) :=
  CategoryTheory.Quotient (ideal (k := k) C S).rel

noncomputable instance rawPreadditive (S : Set C) :
    Preadditive (RawCategory (k := k) C S) :=
  (ideal (k := k) C S).quotientPreadditive

/-- The raw quotient functor. -/
abbrev rawFunctor (S : Set C) : C ⥤ RawCategory (k := k) C S :=
  CategoryTheory.Quotient.functor (ideal (k := k) C S).rel

noncomputable instance rawFunctor_additive (S : Set C) :
    (rawFunctor (k := k) C S).Additive :=
  CategoryTheory.Quotient.functor_additive
    (ideal (k := k) C S).rel
      (fun {_ _} f₁ f₂ g₁ g₂ hf hg ↦
        (ideal (k := k) C S).add_compatible f₁ f₂ g₁ g₂ hf hg)

noncomputable instance rawLinear (S : Set C) :
    Linear k (RawCategory (k := k) C S) :=
  (ideal (k := k) C S).quotientLinear

noncomputable instance rawFunctor_linear (S : Set C) :
    (rawFunctor (k := k) C S).Linear k :=
  (ideal (k := k) C S).quotientFunctorLinear

/-- The full subcategory of original objects which survive the deletion. -/
def IsSurviving (S : Set C) : ObjectProperty C :=
  fun X ↦ X ∉ S

/-- The full subcategory of raw quotient objects represented by surviving
objects. -/
def IsSurvivingRaw (S : Set C) :
    ObjectProperty (RawCategory (k := k) C S) :=
  fun X ↦ X.as ∉ S

/-- The manuscript's category `C/(S)`: surviving objects with Hom spaces
modulo maps factoring through deleted objects. -/
abbrev DeletionCategory (S : Set C) :=
  (IsSurvivingRaw (k := k) C S).FullSubcategory

/-- The ambient full subcategory on the surviving objects. -/
abbrev SurvivingCategory (S : Set C) :=
  (IsSurviving C S).FullSubcategory

/-- The quotient functor on surviving objects. -/
def functor (S : Set C) :
    SurvivingCategory C S ⥤ DeletionCategory (k := k) C S where
  obj X := ⟨(rawFunctor (k := k) C S).obj X.obj, X.property⟩
  map f := ObjectProperty.homMk ((rawFunctor (k := k) C S).map f.hom)

noncomputable instance functor_additive (S : Set C) :
    (functor (k := k) C S).Additive where
  map_add := by
    intro X Y f g
    apply ObjectProperty.hom_ext
    exact (rawFunctor (k := k) C S).map_add

noncomputable instance functor_linear (S : Set C) :
    (functor (k := k) C S).Linear k where
  map_smul := by
    intro X Y f r
    apply ObjectProperty.hom_ext
    exact (rawFunctor (k := k) C S).map_smul r f.hom

noncomputable instance functor_full (S : Set C) :
    (functor (k := k) C S).Full where
  map_surjective {X Y} f := by
    obtain ⟨g, hg⟩ := (rawFunctor (k := k) C S).map_surjective f.hom
    refine ⟨ObjectProperty.homMk g, ?_⟩
    apply ObjectProperty.hom_ext
    exact hg

/-- A surviving morphism maps to zero exactly when its ambient representative
belongs to the ideal generated by the deleted objects. -/
theorem functor_map_eq_zero_iff (S : Set C)
    {X Y : SurvivingCategory C S} (f : X ⟶ Y) :
    (functor (k := k) C S).map f = 0 ↔
      f.hom ∈ (ideal (k := k) C S).hom X.obj Y.obj := by
  constructor
  · intro h
    apply ((ideal (k := k) C S).map_eq_zero_iff f.hom).1
    let P := IsSurvivingRaw (k := k) C S
    have h' := congrArg (fun g ↦ P.ι.map g) h
    change (rawFunctor (k := k) C S).map f.hom = 0 at h'
    exact h'
  · intro h
    let P := IsSurvivingRaw (k := k) C S
    apply P.ι.map_injective
    change (rawFunctor (k := k) C S).map f.hom = 0
    exact ((ideal (k := k) C S).map_eq_zero_iff f.hom).2 h

/-- Every deleted object becomes a zero object in the raw quotient. -/
theorem rawFunctor_obj_isZero (S : Set C) {X : C} (hX : X ∈ S) :
    IsZero ((rawFunctor (k := k) C S).obj X) := by
  rw [IsZero.iff_id_eq_zero]
  rw [← (rawFunctor (k := k) C S).map_id]
  exact ((ideal (k := k) C S).map_eq_zero_iff (𝟙 X)).2
    (id_mem_ideal (k := k) C S hX)

end MagnitudeConjecture.ObjectDeletion
