import Mathlib.CategoryTheory.Groupoid.FreeGroupoid
import Mathlib.GroupTheory.FreeGroup.NielsenSchreier

/-!
# Vertex groups of free quiver groupoids

The free groupoid generated by a quiver satisfies Mathlib's
`IsFreeGroupoid` universal property.  Consequently the vertex group at any
base vertex of a connected quiver is a free group.  This is the combinatorial
form of the classical fact that the fundamental group of a graph is free.
-/

set_option autoImplicit false
noncomputable section
set_option backward.isDefEq.respectTransparency.types false

open CategoryTheory

namespace MagnitudeConjecture.QuiverFreeGroupoid

universe u

variable {V : Type u} [Quiver.{u} V]

private theorem map_eqToHom_singleObj
    {X : Type u} [Group X]
    (F : Quiver.FreeGroupoid V ⥤ CategoryTheory.SingleObj.{u} X)
    {A B : Quiver.FreeGroupoid V} (h : A = B) :
    F.map (eqToHom h) = 1 := by
  subst B
  rw [eqToHom_refl, F.map_id]
  rfl

/-- A generating quiver arrow, with its endpoints transported from the
underlying representatives to the corresponding quotient objects. -/
def generatorOf {X Y : Quiver.FreeGroupoid V}
    (e : @Quiver.Hom V _ X.as Y.as) : X ⟶ Y :=
  eqToHom (by apply CategoryTheory.Quotient.ext; rfl) ≫
    (Quiver.FreeGroupoid.of V).map e ≫
      eqToHom (by apply CategoryTheory.Quotient.ext; rfl)

/-- The free groupoid generated by a quiver satisfies Mathlib's abstract
free-groupoid universal property. -/
instance freeGroupoidIsFreeGroupoid :
    IsFreeGroupoid (Quiver.FreeGroupoid V) where
  quiverGenerators :=
    { Hom := fun X Y ↦ @Quiver.Hom V _ X.as Y.as }
  of := fun {X Y} e ↦
    generatorOf (X := (show Quiver.FreeGroupoid V from X))
      (Y := (show Quiver.FreeGroupoid V from Y)) e
  unique_lift := by
    intro X _ f
    let phi : V ⥤q CategoryTheory.SingleObj X :=
      { obj := fun _ ↦ ()
        map := fun {a b} e ↦
          f (a := (⟨a⟩ : IsFreeGroupoid.Generators
            (Quiver.FreeGroupoid V)))
            (b := (⟨b⟩ : IsFreeGroupoid.Generators
              (Quiver.FreeGroupoid V))) e }
    let F := Quiver.FreeGroupoid.lift phi
    refine ⟨F, ?_, ?_⟩
    · intro a b e
      rcases a with ⟨a⟩
      rcases b with ⟨b⟩
      change F.map (generatorOf e) = f e
      have hspec := congrArg
        (fun q : V ⥤q CategoryTheory.SingleObj.{u} X ↦ q.map e)
        (Quiver.FreeGroupoid.lift_spec phi)
      simpa [F, generatorOf, phi, map_eqToHom_singleObj,
        CategoryTheory.SingleObj.comp_as_mul] using hspec
    · intro E hE
      apply Quiver.FreeGroupoid.lift_unique phi E
      fapply Prefunctor.ext
      · intro a
        rfl
      · intro a b e
        have h := hE
          (⟨a⟩ : IsFreeGroupoid.Generators (Quiver.FreeGroupoid V))
          (⟨b⟩ : IsFreeGroupoid.Generators (Quiver.FreeGroupoid V)) e
        simpa [generatorOf, phi, map_eqToHom_singleObj,
          CategoryTheory.SingleObj.comp_as_mul] using h

/-- The vertex group of the free groupoid on a connected quiver is free. -/
theorem end_isFreeGroup
    (root : V)
    (hconnected : ∀ x y : V, Nonempty
      (@Quiver.Path (Quiver.Symmetrify V)
        (Quiver.symmetrifyQuiver V) x y)) :
    IsFreeGroup (End ((Quiver.FreeGroupoid.of V).obj root)) := by
  letI : Nonempty (Quiver.FreeGroupoid V) :=
    ⟨(Quiver.FreeGroupoid.of V).obj root⟩
  letI : IsConnected (Quiver.FreeGroupoid V) :=
    CategoryTheory.zigzag_isConnected fun X Y ↦ by
      rcases X with ⟨X⟩
      rcases Y with ⟨Y⟩
      obtain ⟨p⟩ := hconnected X Y
      exact CategoryTheory.Zigzag.of_hom (Quot.mk _ p)
  infer_instance

end MagnitudeConjecture.QuiverFreeGroupoid

namespace MagnitudeConjecture.ConnectedGroupoid

universe u

open CategoryTheory

variable {G : Type u} [Groupoid.{u} G]

/-- Generators for a connected groupoid based at `r`: free generators of the
vertex group at `r`, together with one spoke from `r` to every other object. -/
def BasedGenerator (r : G) [IsFreeGroup (End r)] (a b : G) :=
  {_g : IsFreeGroup.Generators (End r) // a = r ∧ b = r} ⊕
    PLift (a = r ∧ b ≠ r)

/-- A chosen morphism from the root to every object of a connected groupoid,
normalized to the identity at the root. -/
noncomputable def connector (r : G)
    (hconnected : ∀ x : G, Nonempty (r ⟶ x)) (x : G) : r ⟶ x := by
  classical
  exact if hx : x = r then eqToHom hx.symm else Classical.choice (hconnected x)

@[simp]
theorem connector_root (r : G)
    (hconnected : ∀ x : G, Nonempty (r ⟶ x)) :
    connector r hconnected r = 𝟙 r := by
  simp [connector]

/-- Interpret a based generator as a morphism of the original groupoid. -/
noncomputable def basedGeneratorMorphism (r : G)
    [IsFreeGroup (End r)]
    (hconnected : ∀ x : G, Nonempty (r ⟶ x))
    {a b : G} : BasedGenerator r a b → (a ⟶ b)
  | Sum.inl ⟨g, ha, hb⟩ =>
      eqToHom ha ≫ (show End r from IsFreeGroup.of g) ≫
        eqToHom hb.symm
  | Sum.inr ⟨⟨ha, _⟩⟩ =>
      eqToHom ha ≫ connector r hconnected b

/-- Conjugate a groupoid morphism to a loop at the chosen root. -/
noncomputable def loopAtRoot (r : G)
    (hconnected : ∀ x : G, Nonempty (r ⟶ x))
    {a b : G} (p : a ⟶ b) : End r :=
  connector r hconnected a ≫ p ≫
    Groupoid.inv (connector r hconnected b)

@[simp]
theorem loopAtRoot_id (r : G)
    (hconnected : ∀ x : G, Nonempty (r ⟶ x)) (a : G) :
    loopAtRoot r hconnected (𝟙 a) = 1 := by
  simp [loopAtRoot]

theorem loopAtRoot_comp (r : G)
    (hconnected : ∀ x : G, Nonempty (r ⟶ x))
    {a b c : G} (p : a ⟶ b) (q : b ⟶ c) :
    loopAtRoot r hconnected (p ≫ q) =
      loopAtRoot r hconnected q * loopAtRoot r hconnected p := by
  simp [loopAtRoot, End.mul_def, Category.assoc]

@[simp]
theorem loopAtRoot_connector (r : G)
    (hconnected : ∀ x : G, Nonempty (r ⟶ x)) (x : G) :
    loopAtRoot r hconnected (connector r hconnected x) = 1 := by
  simp [loopAtRoot]

/-- A connected groupoid with free vertex group at one root is itself a free
groupoid.  A free loop basis and one spoke to every other object give an
explicit generating quiver. -/
@[reducible] noncomputable def isFreeGroupoidOfEndIsFree
    (r : G) (hconnected : ∀ x : G, Nonempty (r ⟶ x))
    [IsFreeGroup (End r)] : IsFreeGroupoid G := by
  classical
  let generators : Quiver (IsFreeGroupoid.Generators G) :=
    ⟨fun a b ↦ BasedGenerator r (show G from a) (show G from b)⟩
  let ofGenerator : ∀ {a b : IsFreeGroupoid.Generators G},
      @Quiver.Hom _ generators a b →
        ((show G from a) ⟶ (show G from b)) :=
    fun {_ _} g ↦ basedGeneratorMorphism r hconnected g
  refine {
    quiverGenerators := generators
    of := ofGenerator
    unique_lift := ?_ }
  intro X _ f
  let vertexLabel : G → X := fun x ↦
    if hx : x = r then 1
    else f (a := show IsFreeGroupoid.Generators G from r)
      (b := show IsFreeGroupoid.Generators G from x) (Sum.inr ⟨⟨rfl, hx⟩⟩)
  let loopLabel : IsFreeGroup.Generators (End r) → X := fun g ↦
    f (a := show IsFreeGroupoid.Generators G from r)
      (b := show IsFreeGroupoid.Generators G from r) (Sum.inl ⟨g, rfl, rfl⟩)
  let basisLoop : IsFreeGroup.Generators (End r) → End r :=
    fun g ↦ IsFreeGroup.of g
  let loopHom : End r →* X := IsFreeGroup.lift loopLabel
  let F : G ⥤ CategoryTheory.SingleObj X :=
    { obj := fun _ ↦ ()
      map := fun {a b} p ↦
        vertexLabel b * loopHom (loopAtRoot r hconnected p) *
          (vertexLabel a)⁻¹
      map_id := by
        intro a
        rw [loopAtRoot_id, loopHom.map_one]
        simp only [mul_one, mul_inv_cancel,
          CategoryTheory.SingleObj.id_as_one]
      map_comp := by
        intro a b c p q
        rw [CategoryTheory.SingleObj.comp_as_mul]
        rw [loopAtRoot_comp, loopHom.map_mul]
        simp only [mul_assoc, inv_mul_cancel_left] }
  refine ⟨F, ?_, ?_⟩
  · intro a b g
    change G at a b
    rcases g with ⟨g, ha, hb⟩ | ⟨⟨ha, hb⟩⟩
    · change a = r at ha
      change b = r at hb
      subst a
      subst b
      simp only [ofGenerator, basedGeneratorMorphism,
        eqToHom_refl, Category.id_comp, Category.comp_id]
      change vertexLabel r * loopHom (loopAtRoot r hconnected
        (show End r from IsFreeGroup.of g)) * (vertexLabel r)⁻¹ = loopLabel g
      simp only [vertexLabel, dif_pos rfl, one_mul, inv_one, mul_one]
      rw [show loopAtRoot r hconnected
          (show End r from IsFreeGroup.of g) = IsFreeGroup.of g by
            simp [loopAtRoot], IsFreeGroup.lift_of]
    · change a = r at ha
      change b ≠ r at hb
      subst a
      simp only [ofGenerator, basedGeneratorMorphism, eqToHom_refl,
        Category.id_comp]
      change vertexLabel b * loopHom
        (loopAtRoot r hconnected (connector r hconnected b)) *
          (vertexLabel r)⁻¹ = _
      have hloop : loopAtRoot r hconnected (connector r hconnected b) =
          1 := loopAtRoot_connector r hconnected b
      rw [hloop, loopHom.map_one]
      simp only [vertexLabel, dif_neg hb, dif_pos rfl, inv_one,
        mul_one]
  · intro E hE
    fapply CategoryTheory.Functor.hext
    · intro x
      exact Subsingleton.elim _ _
    intro a b p
    apply heq_of_eq
    have hconnector : ∀ x : G,
        E.map (connector r hconnected x) = vertexLabel x := by
      intro x
      by_cases hx : x = r
      · subst x
        rw [connector_root, E.map_id]
        simp [vertexLabel, CategoryTheory.SingleObj.id_as_one]
      · simpa only [vertexLabel, dif_neg hx, ofGenerator,
          basedGeneratorMorphism, eqToHom_refl, Category.id_comp] using
          hE (show IsFreeGroupoid.Generators G from r)
            (show IsFreeGroupoid.Generators G from x) (Sum.inr ⟨⟨rfl, hx⟩⟩)
    have hloopHom : E.mapEnd r = loopHom := by
      apply IsFreeGroup.ext_hom
      intro g
      change E.map (basisLoop g) = loopHom (basisLoop g)
      rw [show basisLoop g = IsFreeGroup.of g by rfl,
        IsFreeGroup.lift_of]
      simpa only [loopLabel, ofGenerator, basedGeneratorMorphism,
        eqToHom_refl, Category.id_comp, Category.comp_id] using
        hE (show IsFreeGroupoid.Generators G from r)
          (show IsFreeGroupoid.Generators G from r)
          (Sum.inl ⟨g, rfl, rfl⟩)
    have hdecomp : p = Groupoid.inv (connector r hconnected a) ≫
        loopAtRoot r hconnected p ≫ connector r hconnected b := by
      simp [loopAtRoot]
    have hmapLoop : E.map (loopAtRoot r hconnected p) =
        loopHom (loopAtRoot r hconnected p) := by
      exact DFunLike.congr_fun hloopHom (loopAtRoot r hconnected p)
    have hmapInvConnector :
        E.map (Groupoid.inv (connector r hconnected a)) =
          (vertexLabel a)⁻¹ := by
      rw [Groupoid.inv_eq_inv, E.map_inv,
        CategoryTheory.SingleObj.inv_as_inv, hconnector]
    change E.map p = vertexLabel b *
      loopHom (loopAtRoot r hconnected p) * (vertexLabel a)⁻¹
    calc
      E.map p = E.map (Groupoid.inv (connector r hconnected a) ≫
          loopAtRoot r hconnected p ≫ connector r hconnected b) :=
        congrArg E.map hdecomp
      _ = vertexLabel b * E.map (loopAtRoot r hconnected p) *
          (vertexLabel a)⁻¹ := by
        simp only [E.map_comp,
          CategoryTheory.SingleObj.comp_as_mul,
          hconnector, mul_assoc]
        rw [hmapInvConnector]
      _ = _ := by rw [hmapLoop]

end MagnitudeConjecture.ConnectedGroupoid

namespace MagnitudeConjecture.CategoryTheory.Functor

universe u v

variable {C : Type u} {D : Type v} [Category C] [Category D]

/-- A fully faithful functor identifies the endomorphism monoids of an object
and its image. -/
def endMulEquivOfFullyFaithful (F : C ⥤ D) (hF : F.FullyFaithful)
    (X : C) : End X ≃* End (F.obj X) where
  toEquiv := hF.homEquiv
  map_mul' f g := by
    exact F.map_comp g f

end MagnitudeConjecture.CategoryTheory.Functor
