import MagnitudeConjecture.CategoryTheory.MeshCategory
import Mathlib.Logic.Equiv.Set
import Mathlib.Logic.Equiv.Fintype
import Mathlib.Data.Sym.Sym2
import Mathlib.GroupTheory.Perm.Cycle.Basic

/-!
# Translation and arrow orbit graphs

An injective right translation is a partial bijection on vertices.  Polarization
promotes it to a partial bijection on ordinary arrows.  This file constructs
the resulting tau-orbits, sigma-orbits, and the arrow-orbit graph used in the
Bongartz--Gabriel deformation.
-/

set_option autoImplicit false
noncomputable section

open CategoryTheory
open scoped Sym2

namespace MagnitudeConjecture.MeshCategory.RightMeshData

universe u

variable {Q : Type u} [Quiver.{u} Q]

/-- The right translation is injective on its nonprojective domain.  Equivalently,
it is a partial bijection from nonprojective to noninjective vertices once its
range is declared to be the noninjective locus. -/
def IsTauInjective (T : RightMeshData Q) : Prop :=
  Function.Injective T.tau

namespace IsTauInjective

variable (T : RightMeshData Q) (hT : T.IsTauInjective)

/-- The vertices reached by the partial translation. -/
def tauRange : Set Q := Set.range T.tau

/-- An injective right translation is an equivalence onto its range. -/
def tauRangeEquiv :
    {x : Q // x ∉ T.projective} ≃ {y : Q // y ∈ tauRange T} :=
  Equiv.ofInjective T.tau hT

/-- Ordinary arrows whose source lies in the domain of the translation. -/
abbrev SourceArrow :=
  Σ s : {x : Q // x ∉ T.projective}, Σ y : Q, s.1 ⟶ y

/-- Ordinary arrows whose target lies in the range of the translation. -/
abbrev TargetArrow :=
  Σ t : {y : Q // y ∈ tauRange T}, Σ x : Q, x ⟶ t.1

/-- Polarization promotes the vertex partial translation to an equivalence
between arrows with nonprojective source and arrows with noninjective target. -/
def arrowTranslationEquiv :
    SourceArrow T ≃ TargetArrow T :=
  Equiv.sigmaCongr (tauRangeEquiv T hT) fun s ↦
    Equiv.sigmaCongr (Equiv.refl Q) fun y ↦ T.arrowEquiv s y

/-- The total type of ordinary arrows, retaining both endpoints. -/
abbrev Arrow (_T : RightMeshData Q) := Σ x : Q, Σ y : Q, x ⟶ y

/-- Forget that an ordinary arrow starts in the translation domain. -/
def SourceArrow.forget : SourceArrow T → Arrow T
  | ⟨s, y, a⟩ => ⟨s.1, y, a⟩

/-- Forget that an ordinary arrow ends in the translation range. -/
def TargetArrow.forget : TargetArrow T → Arrow T
  | ⟨t, x, a⟩ => ⟨x, t.1, a⟩

/-- One forward polarization step on ordinary arrows. -/
def ArrowTranslationStep (a b : Arrow T) : Prop :=
  ∃ c : SourceArrow T,
    c.forget = a ∧ (arrowTranslationEquiv T hT c).forget = b

/-- The sigma-orbit relation on ordinary arrows, generated by polarization. -/
def arrowOrbitSetoid : Setoid (Arrow T) :=
  Relation.EqvGen.setoid (ArrowTranslationStep T hT)

/-- Sigma-orbits of ordinary arrows. -/
def ArrowOrbit := Quotient (arrowOrbitSetoid T hT)

/-- One forward translation step lies in a single sigma-orbit. -/
theorem arrowTranslation_related (c : SourceArrow T) :
    (arrowOrbitSetoid T hT) c.forget
      (arrowTranslationEquiv T hT c).forget :=
  Relation.EqvGen.rel _ _ ⟨c, rfl, rfl⟩

/-- The vertex relation generated by one partial-translation step. -/
def TauStep (x y : Q) : Prop :=
  ∃ s : {x : Q // x ∉ T.projective}, s.1 = x ∧ T.tau s = y

/-- The tau-orbit relation on vertices. -/
def tauOrbitSetoid : Setoid Q :=
  Relation.EqvGen.setoid (TauStep T)

/-- Tau-orbits of vertices. -/
def TauOrbit := Quotient (tauOrbitSetoid T)

/-- A vertex and its translate lie in the same tau-orbit. -/
theorem tau_related (s : {x : Q // x ∉ T.projective}) :
    (tauOrbitSetoid T) s.1 (T.tau s) :=
  Relation.EqvGen.rel _ _ ⟨s, rfl, rfl⟩

/-- The tau-orbit containing a vertex. -/
def tauClass (x : Q) : TauOrbit T :=
  Quotient.mk _ x

/-- The unordered tau-orbit endpoints of an ordinary arrow. -/
def arrowEnds : Arrow T → Sym2 (TauOrbit T)
  | ⟨x, y, _⟩ => s(tauClass T x, tauClass T y)

private theorem arrowEnds_eq_of_step {a b : Arrow T}
    (h : ArrowTranslationStep T hT a b) :
    arrowEnds T a = arrowEnds T b := by
  rcases h with ⟨⟨s, y, a⟩, rfl, rfl⟩
  change s(tauClass T s.1, tauClass T y) =
    s(tauClass T y, tauClass T (T.tau s))
  rw [show tauClass T (T.tau s) = tauClass T s.1 by
    apply Quotient.sound
    exact Relation.EqvGen.symm _ _ (tau_related T s)]
  exact Sym2.eq_swap

private theorem arrowEnds_eq_of_orbit {a b : Arrow T}
    (h : Relation.EqvGen (ArrowTranslationStep T hT) a b) :
    arrowEnds T a = arrowEnds T b := by
  induction h with
  | rel a b h => exact arrowEnds_eq_of_step T hT h
  | refl => rfl
  | symm a b _ ih => exact ih.symm
  | trans a b c _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- A sigma-orbit of arrows has a well-defined unordered pair of tau-orbit
endpoints. -/
def arrowOrbitEnds : ArrowOrbit T hT → Sym2 (TauOrbit T) :=
  Quotient.lift (arrowEnds T) fun _ _ h ↦
    arrowEnds_eq_of_orbit T hT h

@[simp]
theorem arrowOrbitEnds_mk (a : Arrow T) :
    arrowOrbitEnds T hT (Quotient.mk _ a) = arrowEnds T a :=
  rfl

/-- A chosen ordinary-arrow representative of a sigma-orbit. -/
def arrowOrbitRepresentative (e : ArrowOrbit T hT) : Arrow T :=
  Quotient.out e

/-- Source tau-orbit of the chosen orientation of a sigma-orbit. -/
def arrowOrbitSource (e : ArrowOrbit T hT) : TauOrbit T :=
  tauClass T (arrowOrbitRepresentative T hT e).1

/-- Target tau-orbit of the chosen orientation of a sigma-orbit. -/
def arrowOrbitTarget (e : ArrowOrbit T hT) : TauOrbit T :=
  tauClass T (arrowOrbitRepresentative T hT e).2.1

/-- The unordered endpoints of a sigma-orbit agree with the endpoints of its
chosen representative. -/
theorem arrowOrbitEnds_eq_mk_source_target (e : ArrowOrbit T hT) :
    arrowOrbitEnds T hT e =
      s(arrowOrbitSource T hT e, arrowOrbitTarget T hT e) := by
  calc
    arrowOrbitEnds T hT e =
        arrowOrbitEnds T hT (Quotient.mk _ (Quotient.out e)) :=
      congrArg (arrowOrbitEnds T hT) (Quotient.out_eq e).symm
    _ = arrowEnds T (Quotient.out e) := rfl
    _ = s(arrowOrbitSource T hT e, arrowOrbitTarget T hT e) := by
      change arrowEnds T (Quotient.out e) =
        s(tauClass T (Quotient.out e).1,
          tauClass T (Quotient.out e).2.1)
      rcases Quotient.out e with ⟨x, y, a⟩
      rfl

/-- The arrow-orbit graph has tau-orbits as vertices and one arbitrarily
oriented edge for each sigma-orbit of ordinary arrows. -/
def OrbitGraphVertex (_hT : T.IsTauInjective) := TauOrbit T

/-- Edges of the arrow-orbit graph with their chosen endpoints exposed. -/
def OrbitGraphArrow (X Y : OrbitGraphVertex T hT) :=
  {e : ArrowOrbit T hT //
    arrowOrbitSource T hT e = X ∧ arrowOrbitTarget T hT e = Y}

instance orbitGraphQuiver : Quiver (OrbitGraphVertex T hT) where
  Hom := OrbitGraphArrow T hT

/-- Every sigma-orbit supplies its chosen oriented edge in the orbit graph. -/
def arrowOrbitEdge (e : ArrowOrbit T hT) :
    @Quiver.Hom (OrbitGraphVertex T hT) (orbitGraphQuiver T hT)
      (arrowOrbitSource T hT e) (arrowOrbitTarget T hT e) :=
  ⟨e, rfl, rfl⟩

@[simp]
theorem tauRangeEquiv_apply
    (s : {x : Q // x ∉ T.projective}) :
    (tauRangeEquiv T hT s).1 = T.tau s :=
  rfl

@[simp]
theorem arrowTranslationEquiv_apply
    (s : {x : Q // x ∉ T.projective}) (y : Q) (a : s.1 ⟶ y) :
    arrowTranslationEquiv T hT ⟨s, y, a⟩ =
      ⟨tauRangeEquiv T hT s, y, T.arrowEquiv s y a⟩ :=
  rfl

/-- A finite extension of the partial translation to a permutation of all
vertices.  Its values at projective vertices are auxiliary and will not enter
the intrinsic periodicity predicate below. -/
noncomputable def tauPermutation [Finite Q] : Equiv.Perm Q :=
  by
    classical
    exact (tauRangeEquiv T hT).extendSubtype

@[simp]
theorem tauPermutation_apply_of_nonprojective [Finite Q]
    (x : Q) (hx : x ∉ T.projective) :
    tauPermutation T hT x = T.tau ⟨x, hx⟩ := by
  classical
  simpa [tauPermutation] using
    Equiv.extendSubtype_apply_of_mem (tauRangeEquiv T hT) x hx

theorem tauPermutation_apply_projective_not_mem_range [Finite Q]
    (x : Q) (hx : x ∈ T.projective) :
    tauPermutation T hT x ∉ tauRange T := by
  classical
  exact Equiv.extendSubtype_not_mem (tauRangeEquiv T hT) x (by simpa using hx)

/-- A vertex is periodic when its intrinsic tau-orbit contains no projective
boundary vertex. -/
def IsPeriodicVertex (x : Q) : Prop :=
  ∀ y : Q, (tauOrbitSetoid T) x y → y ∉ T.projective

theorem isPeriodicVertex_iff_class_has_no_projective (x : Q) :
    IsPeriodicVertex T x ↔
      ∀ y : Q, tauClass T y = tauClass T x → y ∉ T.projective := by
  constructor
  · intro hx y hy
    apply hx y
    exact (tauOrbitSetoid T).symm (Quotient.exact hy)
  · intro hx y hy
    apply hx y
    exact Quotient.sound ((tauOrbitSetoid T).symm hy)

theorem isPeriodicVertex_of_related {x y : Q}
    (hx : IsPeriodicVertex T x) (hxy : (tauOrbitSetoid T) x y) :
    IsPeriodicVertex T y := by
  intro z hyz
  exact hx z ((tauOrbitSetoid T).trans hxy hyz)

theorem isPeriodicVertex_iff_of_related {x y : Q}
    (hxy : (tauOrbitSetoid T) x y) :
    IsPeriodicVertex T x ↔ IsPeriodicVertex T y := by
  constructor
  · exact fun hx => isPeriodicVertex_of_related T hx hxy
  · exact fun hy => isPeriodicVertex_of_related T hy ((tauOrbitSetoid T).symm hxy)

private theorem tauStep_sameCycle [Finite Q] {x y : Q}
    (hxy : TauStep T x y) :
    (tauPermutation T hT).SameCycle x y := by
  rcases hxy with ⟨s, rfl, rfl⟩
  refine ⟨1, ?_⟩
  simp [tauPermutation_apply_of_nonprojective T hT s.1 s.2]

theorem related_sameCycle [Finite Q] {x y : Q}
    (hxy : (tauOrbitSetoid T) x y) :
    (tauPermutation T hT).SameCycle x y := by
  induction hxy with
  | rel x y h => exact tauStep_sameCycle T hT h
  | refl => exact Equiv.Perm.SameCycle.rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih₁ ih₂ => exact ih₁.trans ih₂

private theorem pow_related_of_periodic [Finite Q]
    {x : Q} (hx : IsPeriodicVertex T x) :
    ∀ n : ℕ, (tauOrbitSetoid T) x ((tauPermutation T hT ^ n) x) := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      have hn : (tauPermutation T hT ^ n) x ∉ T.projective :=
        hx _ ih
      rw [pow_succ', Equiv.Perm.mul_apply,
        tauPermutation_apply_of_nonprojective T hT _ hn]
      exact (tauOrbitSetoid T).trans ih (tau_related T ⟨_, hn⟩)

/-- On a periodic component, intrinsic tau-connectedness agrees with belonging
to the cycle of the finite permutation extending tau. -/
theorem periodic_related_iff_sameCycle [Finite Q]
    {x : Q} (hx : IsPeriodicVertex T x) (y : Q) :
    (tauOrbitSetoid T) x y ↔ (tauPermutation T hT).SameCycle x y := by
  constructor
  · exact related_sameCycle T hT
  · intro hxy
    obtain ⟨n, hn⟩ := hxy.exists_nat_pow_eq
    rw [← hn]
    exact pow_related_of_periodic T hT hx n

/-- Equivalently, periodicity says that the entire finite permutation cycle
extending tau avoids the projective boundary. -/
theorem isPeriodicVertex_iff_sameCycle_has_no_projective [Finite Q] (x : Q) :
    IsPeriodicVertex T x ↔
      ∀ y : Q, (tauPermutation T hT).SameCycle x y → y ∉ T.projective := by
  constructor
  · intro hx y hxy
    exact hx y ((periodic_related_iff_sameCycle T hT hx y).2 hxy)
  · intro hx y hxy
    exact hx y (related_sameCycle T hT hxy)

/-- A nonperiodic tau-component contains a projective endpoint. -/
theorem not_isPeriodicVertex_iff_exists_projective_related (x : Q) :
    ¬ IsPeriodicVertex T x ↔
      ∃ y : Q, y ∈ T.projective ∧ (tauOrbitSetoid T) x y := by
  simp only [IsPeriodicVertex, not_forall, not_not]
  constructor
  · rintro ⟨y, hxy, hy⟩
    exact ⟨y, hy, hxy⟩
  · rintro ⟨y, hy, hxy⟩
    exact ⟨y, hxy, hy⟩

/-- Periodicity descends from vertices to intrinsic tau-orbits. -/
def IsPeriodicTauOrbit : TauOrbit T → Prop :=
  Quotient.lift (IsPeriodicVertex T) fun _ _ hxy ↦
    propext (isPeriodicVertex_iff_of_related T hxy)

@[simp]
theorem isPeriodicTauOrbit_tauClass (x : Q) :
    IsPeriodicTauOrbit T (tauClass T x) ↔ IsPeriodicVertex T x :=
  Iff.rfl

/-- Periodic tau-orbits, which are cyclic components of the partial
translation. -/
abbrev PeriodicTauOrbit := {o : TauOrbit T // IsPeriodicTauOrbit T o}

/-- Nonperiodic tau-orbits, each of which meets the projective boundary. -/
abbrev NonperiodicTauOrbit := {o : TauOrbit T // ¬ IsPeriodicTauOrbit T o}

theorem not_isPeriodicTauOrbit_iff_exists_projective (o : TauOrbit T) :
    ¬ IsPeriodicTauOrbit T o ↔
      ∃ y : Q, y ∈ T.projective ∧ tauClass T y = o := by
  induction o using Quotient.inductionOn with
  | _ x =>
      change ¬ IsPeriodicVertex T x ↔
        ∃ y : Q, y ∈ T.projective ∧
          Quotient.mk (tauOrbitSetoid T) y =
            Quotient.mk (tauOrbitSetoid T) x
      rw [not_isPeriodicVertex_iff_exists_projective_related]
      constructor
      · rintro ⟨y, hy, hxy⟩
        exact ⟨y, hy, Quotient.sound ((tauOrbitSetoid T).symm hxy)⟩
      · rintro ⟨y, hy, hxy⟩
        exact ⟨y, hy,
          (tauOrbitSetoid T).symm (Quotient.exact hxy)⟩

end IsTauInjective

end MagnitudeConjecture.MeshCategory.RightMeshData
